import os

keys = [
    "home_nearby_title",
    "home_nearby_subtitle",
    "home_nearby_refresh_status",
    "home_network_wifi",
    "home_network_hotspot",
    "home_network_local",
    "home_network_none",
    "home_network_ready_desc",
    "home_network_none_desc",
    "home_nearby_optional_title",
    "home_nearby_optional_desc",
    "home_nearby_refresh",
    "home_nearby_open_title",
    "home_nearby_open_desc",
    "home_nearby_action_open_session",
    "home_nearby_action_open",
    "home_nearby_device_available",
    "home_nearby_device_pin"
]

translations = {
    "values": ["Nearby &amp; network", "Make sure your local network is ready, then look for another DirectServe device if you want to open it in the app.", "Refresh status", "Wi-Fi connected", "Hotspot active", "Local network ready", "Network needed", "Nearby devices can open the link on this network.", "Connect both devices to the same Wi-Fi or hotspot.", "DirectServe app is optional", "If the other device also has DirectServe, it can appear here. Everyone else can still scan the QR code or open the browser link.", "Refresh nearby", "Open in the DirectServe app", "This is only for devices with DirectServe installed. The browser link and QR code still work for everyone else.", "Open nearby session", "Open", "Available", "PIN needed"],
    "values-ar": ["الشبكة والأجهزة القريبة", "تأكد من جاهزية شبكتك المحلية، ثم ابحث عن جهاز DirectServe آخر إذا كنت تريد فتحه في التطبيق.", "تحديث الحالة", "متصل بـ Wi-Fi", "نقطة الاتصال نشطة", "الشبكة المحلية جاهزة", "الشبكة مطلوبة", "يمكن للأجهزة القريبة فتح الرابط على هذه الشبكة.", "قم بتوصيل كلا الجهازين بنفس شبكة Wi-Fi أو نقطة الاتصال.", "تطبيق DirectServe اختياري", "إذا كان الجهاز الآخر يحتوي أيضاً على DirectServe، فقد يظهر هنا. يمكن للآخرين الاستمرار في مسح رمز QR أو فتح رابط المتصفح.", "تحديث الأجهزة القريبة", "الفتح في تطبيق DirectServe", "هذا مخصص فقط للأجهزة المثبت عليها DirectServe. رابط المتصفح ورمز QR لا يزالان يعملان للجميع.", "فتح الجلسة القريبة", "فتح", "متاح", "مطلوب رقم تعريف (PIN)"],
    "values-de": ["In der Nähe &amp; Netzwerk", "Stellen Sie sicher, dass Ihr lokales Netzwerk bereit ist, dann suchen Sie nach einem anderen DirectServe-Gerät, wenn Sie es in der App öffnen möchten.", "Status aktualisieren", "WLAN verbunden", "Hotspot aktiv", "Lokales Netzwerk bereit", "Netzwerk erforderlich", "Geräte in der Nähe können den Link in diesem Netzwerk öffnen.", "Verbinden Sie beide Geräte mit demselben WLAN oder Hotspot.", "DirectServe-App ist optional", "Wenn das andere Gerät ebenfalls DirectServe hat, kann es hier erscheinen. Alle anderen können weiterhin den QR-Code scannen oder den Browser-Link öffnen.", "Geräte in der Nähe aktualisieren", "In der DirectServe-App öffnen", "Dies gilt nur für Geräte, auf denen DirectServe installiert ist. Der Browser-Link und der QR-Code funktionieren weiterhin für alle anderen.", "Nahegelegene Sitzung öffnen", "Öffnen", "Verfügbar", "PIN erforderlich"],
    "values-es": ["Cercanos y red", "Asegúrate de que tu red local esté lista, luego busca otro dispositivo DirectServe si quieres abrirlo en la aplicación.", "Actualizar estado", "Wi-Fi conectado", "Punto de acceso activo", "Red local lista", "Se necesita red", "Los dispositivos cercanos pueden abrir el enlace en esta red.", "Conecta ambos dispositivos al mismo Wi-Fi o punto de acceso.", "La aplicación DirectServe es opcional", "Si el otro dispositivo también tiene DirectServe, puede aparecer aquí. Todos los demás aún pueden escanear el código QR o abrir el enlace del navegador.", "Actualizar cercanos", "Abrir en la aplicación DirectServe", "Esto es solo para dispositivos que tienen DirectServe instalado. El enlace del navegador y el código QR aún funcionan para todos los demás.", "Abrir sesión cercana", "Abrir", "Disponible", "Se necesita PIN"],
    "values-fr": ["À proximité et réseau", "Assurez-vous que votre réseau local est prêt, puis recherchez un autre appareil DirectServe si vous souhaitez l\'ouvrir dans l\'application.", "Actualiser le statut", "Wi-Fi connecté", "Point d\'accès actif", "Réseau local prêt", "Réseau nécessaire", "Les appareils à proximité peuvent ouvrir le lien sur ce réseau.", "Connectez les deux appareils au même Wi-Fi ou point d\'accès.", "L\'application DirectServe est facultative", "Si l\'autre appareil a également DirectServe, il peut apparaître ici. Tous les autres peuvent toujours scanner le code QR ou ouvrir le lien du navigateur.", "Actualiser à proximité", "Ouvrir dans l\'application DirectServe", "Ceci est uniquement pour les appareils avec DirectServe installé. Le lien du navigateur et le code QR fonctionnent toujours pour tous les autres.", "Ouvrir une session à proximité", "Ouvrir", "Disponible", "Code PIN requis"],
    "values-hi": ["आस-पास और नेटवर्क", "सुनिश्चित करें कि आपका स्थानीय नेटवर्क तैयार है, फिर यदि आप इसे ऐप में खोलना चाहते हैं तो किसी अन्य DirectServe डिवाइस की खोज करें।", "स्थिति ताज़ा करें", "Wi-Fi कनेक्टेड", "हॉटस्पॉट सक्रिय", "स्थानीय नेटवर्क तैयार", "नेटवर्क आवश्यक", "आस-पास के डिवाइस इस नेटवर्क पर लिंक खोल सकते हैं।", "दोनों डिवाइस को एक ही Wi-Fi या हॉटस्पॉट से कनेक्ट करें।", "DirectServe ऐप वैकल्पिक है", "अगर दूसरे डिवाइस में भी DirectServe है, तो वह यहाँ दिखाई दे सकता है। बाक़ी सभी लोग QR कोड स्कैन कर सकते हैं या ब्राउज़र लिंक खोल सकते हैं।", "आस-पास ताज़ा करें", "DirectServe ऐप में खोलें", "यह केवल DirectServe इंस्टॉल किए गए डिवाइसों के लिए है। ब्राउज़र लिंक और QR कोड बाक़ी सभी के लिए काम करते रहेंगे।", "आस-पास का सत्र खोलें", "खोलें", "उपलब्ध", "पिन आवश्यक"],
    "values-id": ["Di sekitar &amp; jaringan", "Pastikan jaringan lokal Anda siap, lalu cari perangkat DirectServe lain jika Anda ingin membukanya di aplikasi.", "Perbarui status", "Wi-Fi terhubung", "Hotspot aktif", "Jaringan lokal siap", "Dibutuhkan jaringan", "Perangkat di sekitar dapat membuka tautan di jaringan ini.", "Hubungkan kedua perangkat ke Wi-Fi atau hotspot yang sama.", "Aplikasi DirectServe opsional", "Jika perangkat lain juga memiliki DirectServe, ia dapat muncul di sini. Semua orang masih dapat memindai kode QR atau membuka tautan browser.", "Perbarui di sekitar", "Buka di aplikasi DirectServe", "Ini hanya untuk perangkat yang menginstal DirectServe. Tautan browser dan kode QR masih berfungsi untuk semua orang.", "Buka sesi di sekitar", "Buka", "Tersedia", "Diperlukan PIN"],
    "values-it": ["Nelle vicinanze e rete", "Assicurati che la tua rete locale sia pronta, quindi cerca un altro dispositivo DirectServe se vuoi aprirlo nell\'app.", "Aggiorna stato", "Wi-Fi connesso", "Hotspot attivo", "Rete locale pronta", "Rete necessaria", "I dispositivi vicini possono aprire il link su questa rete.", "Collega entrambi i dispositivi allo stesso Wi-Fi o hotspot.", "L\'app DirectServe è facoltativa", "Se l\'altro dispositivo ha anche DirectServe, può apparire qui. Tutti gli altri possono comunque scansionare il codice QR o aprire il link nel browser.", "Aggiorna nelle vicinanze", "Apri nell\'app DirectServe", "Questo vale solo per i dispositivi su cui è installato DirectServe. Il link nel browser e il codice QR continuano a funzionare per tutti gli altri.", "Apri sessione vicina", "Apri", "Disponibile", "PIN richiesto"],
    "values-ja": ["付近とネットワーク", "ローカルネットワークの準備ができていることを確認してから、アプリで開きたい場合は別のDirectServeデバイスを探してください。", "ステータスを更新", "Wi-Fiに接続済み", "ホットスポットが有効", "ローカルネットワーク準備完了", "ネットワークが必要です", "付近のデバイスはこのネットワーク上のリンクを開くことができます。", "両方のデバイスを同じWi-Fiまたはホットスポットに接続してください。", "DirectServeアプリはオプションです", "もう一方のデバイスにもDirectServeがある場合、ここに表示されることがあります。それ以外の人は、引き続きQRコードをスキャンするか、ブラウザのリンクを開くことができます。", "付近を更新", "DirectServeアプリで開く", "これはDirectServeがインストールされているデバイスのみ対象です。ブラウザのリンクとQRコードは引き続き全員に有効です。", "付近のセッションを開く", "開く", "利用可能", "PINが必要です"],
    "values-ko": ["주변 및 네트워크", "로컬 네트워크가 준비되었는지 확인한 다음 앱에서 열려면 다른 DirectServe 기기를 찾으세요.", "상태 새로고침", "Wi-Fi 연결됨", "핫스팟 활성화됨", "로컬 네트워크 준비됨", "네트워크 필요", "주변 기기가 이 네트워크의 링크를 열 수 있습니다.", "두 기기를 동일한 Wi-Fi 또는 핫스팟에 연결하세요.", "DirectServe 앱은 선택사항입니다", "다른 기기에도 DirectServe가 있으면 여기에 나타날 수 있습니다. 다른 모든 사용자는 계속해서 QR 코드를 스캔하거나 브라우저 링크를 열 수 있습니다.", "주변 새로고침", "DirectServe 앱에서 열기", "DirectServe가 설치된 기기에만 해당됩니다. 브라우저 링크 및 QR 코드는 다른 모든 사용자를 위해 계속 작동합니다.", "주변 세션 열기", "열기", "사용 가능", "PIN 필요"],
    "values-ml": ["സമീപമുള്ളവയും നെറ്റ്‌വർക്കും", "നിങ്ങളുടെ ലോക്കൽ നെറ്റ്‌വർക്ക് തയ്യാറാണെന്ന് ഉറപ്പുവരുത്തുക, തുടർന്ന് ആപ്പിൾതുറക്കാൻ താൽപ്പര്യമുള്ള മറ്റൊരു DirectServe ഉപകരണം തെരയുക.", "സ്റ്റാറ്റസ് റിഫ്രഷ് ചെയ്യുക", "Wi-Fi കണക്‌റ്റ് ചെയ്തു", "ഹോട്ട്‌സ്പോട്ട് സജീവം", "ലോക്കൽ നെറ്റ്‌വർക്ക് തയ്യാർ", "നെറ്റ്‌വർക്ക് ആവശ്യമാണ്", "ഈ നെറ്റ്‌വർക്കിലെ ലിങ്ക് സമീപമുള്ള ഉപകരണങ്ങൾക്ക് തുറക്കാനാകും.", "രണ്ട് ഉപകരണങ്ങളും ഒരേ Wi-Fi അല്ലെങ്കിൽ ഹോട്ട്‌സ്പോട്ടിലേക്ക് കണക്‌റ്റ് ചെയ്യുക.", "DirectServe ആപ്പ് ഓപ്ഷണലാണ്", "മറ്റേ ഉപകരണത്തിലും DirectServe ഉണ്ടെങ്കിൽ, അവ ഇവിടെ കാണാം. മറ്റുള്ളവർക്ക് ഇപ്പോഴും QR കോഡ് സ്കാൻ ചെയ്യാനോ ബ്രൗസർ ലിങ്ക് തുറക്കാനോ കഴിയും.", "സമീപമുള്ളവ റിഫ്രഷ് ചെയ്യുക", "DirectServe ആപ്പിൽ തുറക്കുക", "DirectServe ഇൻസ്റ്റാൾ ചെയ്തിട്ടുള്ള ഉപകരണങ്ങൾക്ക് മാത്രമാണിത്. ബ്രൗസർ ലിങ്കും QR കോഡും മറ്റുള്ളവർക്ക് തുടർന്നും പ്രവർത്തിക്കും.", "സമീപത്തെ സെഷൻ തുറക്കുക", "തുറക്കുക", "ലഭ്യമാണ്", "PIN ആവശ്യമാണ്"],
    "values-nl": ["Dichtbij &amp; netwerk", "Zorg ervoor dat uw lokale netwerk gereed is en zoek vervolgens een ander DirectServe-apparaat als u het in de app wilt openen.", "Status vernieuwen", "Wi-Fi verbonden", "Hotspot actief", "Lokaal netwerk gereed", "Netwerk vereist", "Apparaten in de buurt kunnen de link op dit netwerk openen.", "Verbind beide apparaten met dezelfde Wi-Fi of hotspot.", "DirectServe-app is optioneel", "Als het andere apparaat ook DirectServe heeft, kan dit hier verschijnen. Anderen kunnen nog steeds de QR-code scannen of de browserlink openen.", "Dichtbij vernieuwen", "Openen in de DirectServe-app", "Dit is alleen voor apparaten waarop DirectServe is geïnstalleerd. De browserlink en QR-code werken nog steeds voor alle anderen.", "Sessie in de buurt openen", "Openen", "Beschikbaar", "PIN vereist"],
    "values-pt": ["Na proximidade e rede", "Certifique-se de que a sua rede local está pronta e, em seguida, procure outro dispositivo DirectServe se pretender abri-lo na aplicação.", "Atualizar estado", "Wi-Fi ligado", "Hotspot ativo", "Rede local pronta", "Rede necessária", "Os dispositivos próximos podem abrir a ligação nesta rede.", "Ligue ambos os dispositivos ao mesmo Wi-Fi ou hotspot.", "A aplicação DirectServe é opcional", "Se o outro dispositivo também tiver o DirectServe, pode aparecer aqui. Todos os outros podem continuar a ler o código QR ou abrir a ligação do navegador.", "Atualizar próximos", "Abrir na aplicação DirectServe", "Isto é apenas para dispositivos com o DirectServe instalado. A ligação do navegador e o código QR continuam a funcionar para todos os outros.", "Abrir sessão próxima", "Abrir", "Disponível", "PIN necessário"],
    "values-ru": ["Рядом и сеть", "Убедитесь, что ваша локальная сеть готова, затем найдите другое устройство DirectServe, если хотите открыть его в приложении.", "Обновить статус", "Wi-Fi подключен", "Точка доступа активна", "Локальная сеть готова", "Требуется сеть", "Устройства поблизости могут открыть ссылку в этой сети.", "Подключите оба устройства к одной Wi-Fi или точке доступа.", "Приложение DirectServe необязательно", "Если на другом устройстве тоже установлен DirectServe, оно может появиться здесь. Все остальные по-прежнему могут отсканировать QR-код или открыть ссылку в браузере.", "Обновить устройства рядом", "Открыть в приложении DirectServe", "Это касается только устройств с установленным DirectServe. Ссылка в браузере и QR-код все еще работают для всех остальных.", "Открыть сеанс поблизости", "Открыть", "Доступно", "Требуется PIN"],
    "values-ta": ["அருக்கில் மற்றும் நெட்வொர்க்", "உங்கள் உள்ளூர் நெட்வொர்க் தயார்நிலையில் உள்ளதா என்பதை உறுதிசெய்து, பயன்பாட்டில் அதனைத் திறக்க விரும்பினால், மற்றொரு DirectServe சாதனத்தைத் தேடவும்.", "நிலையைப் புதுப்பி", "Wi-Fi இணைக்கப்பட்டது", "ஹாட்ஸ்பாட் செயலில் உள்ளது", "உள்ளூர் நெட்வொர்க் தயார்", "நெட்வொர்க் தேவை", "அருக்கிலுள்ள சாதனங்களால் இந்த நெட்வொர்க்கில் இணைப்பைத் திறக்க முடியும்.", "இரண்டு சாதனங்களையும் ஒரே Wi-Fi அல்லது ஹாட்ஸ்பாட்டுடன் இணைக்கவும்.", "DirectServe ஆப்ஸ் விருப்பத்தேர்வானது", "மற்றொரு சாதனத்திலும் DirectServe இருந்தால், அது இங்கு தோன்றலாம். மற்றவர்கள் QR குறியீட்டை ஸ்கேன் செய்யலாம் அல்லது உலாவி இணைப்பைத் திறக்கலாம்.", "அருக்கில் எனப் புதுப்பி", "DirectServe ஆப்ஸில் திற", "இது DirectServe நிறுவப்பட்ட சாதனங்களுக்கு மட்டுமே. உலாவி இணைப்பும் QR குறியீடும் மற்ற அனைவருக்கும் தொடர்ந்து செயல்படும்.", "அருக்கிலுள்ள அமர்வைத் திற", "திற", "கிடைக்கிறது", "PIN தேவை"],
    "values-te": ["సమీపంగా &amp; నెట్‌వర్క్", "మీ స్థానిక నెట్‌వర్క్ సిద్ధంగా ఉందని నిర్ధారించుకోండి, ఆపై మీరు యాప్‌లో తెరవాలనుకుంటే మరొక DirectServe పరికరం కోసం వెతకండి.", "స్థితిని రిఫ్రెష్ చేయండి", "Wi-Fi కనెక్ట్ చేయబడింది", "హాట్‌స్పాట్ సక్రియంగా ఉంది", "స్థానిక నెట్‌వర్క్ సిద్ధంగా ఉంది", "నెట్‌వర్క్ అవసరం", "సమీపంలోని పరికరాలు ఈ నెట్‌వర్క్‌లోని లింక్‌ను తెరవగలవు.", "రెండు పరికరాలను ఒకే Wi-Fi లేదా హాట్‌స్పాట్‌కి కనెక్ట్ చేయండి.", "DirectServe యాప్ ఐచ్ఛికం", "మరొక పరికరం కూడా DirectServeని కలిగి ఉంటే, అది ఇక్కడ కనిపించవచ్చు. అందరు క్యూఆర్ కోడ్‌ని స్కాన్ చేయవచ్చు లేదా బ్రౌజర్ లింక్‌ను తెరవవచ్చు.", "సమీపగా ఉన్నవి రిఫ్రెష్ చేయండి", "DirectServe యాప్‌లో తెరవండి", "ఇది DirectServe ఇన్‌స్టాల్ చేసిన పరికరాల కోసం మాత్రమే. బ్రౌజర్ లింక్ మరియు క్యూఆర్ కోడ్ మిగిలిన వారందరికీ పని చేస్తాయి.", "సమీప సెషన్‌ను తెరవండి", "తెరువు", "అందుబాటులో ఉంది", "PIN అవసరం"],
    "values-th": ["ใกล้เคียง &amp; เครือข่าย", "ตรวจสอบให้แน่ใจว่าเครือข่ายท้องถิ่นของคุณพร้อมแล้ว จากนั้นมองหาอุปกรณ์ DirectServe อื่น หากคุณต้องการเปิดในแอป", "รีเฟรชสถานะ", "เชื่อมต่อ Wi-Fi แล้ว", "ฮอตสปอตกำลังใช้งาน", "เครือข่ายท้องถิ่นพร้อม", "จำเป็นต้องใช้เครือข่าย", "อุปกรณ์ใกล้เคียงสามารถเปิดลิงก์บนเครือข่ายนี้ได้", "เชื่อมต่ออุปกรณ์ทั้งสองเข้ากับ Wi-Fi หรือฮอตสปอตเดียวกัน", "แอป DirectServe เป็นทางเลือก", "หากอุปกรณ์เครื่องอื่นมี DirectServe ด้วย อาจปรากฏขึ้นที่นี่ ทุกคนยังคงสามารถสแกนคิวอาร์โค้ดหรือเปิดลิงก์เบราว์เซอร์ได้", "รีเฟรชที่อยู่ใกล้เคียง", "เปิดในแอป DirectServe", "สำหรับอุปกรณ์ที่ติดตั้ง DirectServe เท่านั้น ลิงก์เบราว์เซอร์และคิวอาร์โค้ดยังคงใช้งานได้สำหรับทุกคน", "เปิดเซสชันใกล้เคียง", "เปิด", "พร้อมใช้งาน", "ต้องใช้ PIN"],
    "values-tr": ["Yakındakiler ve ağ", "Yerel ağınızın hazır olduğundan emin olun, ardından uygulama içinde açmak istiyorsanız başka bir DirectServe cihazı arayın.", "Durumu yenile", "Wi-Fi bağlı", "Etkin nokta aktif", "Yerel ağ hazır", "Ağ gerekli", "Yakındaki cihazlar bağlantıyı bu ağ üzerinde açabilir.", "Her iki cihazı da aynı Wi-Fi veya etkin noktaya bağlayın.", "DirectServe uygulaması isteğe bağlıdır", "Diğer cihazda da DirectServe varsa, burada görünebilir. Diğer herkes QR kodunu tarayabilir veya tarayıcı bağlantısını açabilir.", "Yakındakileri yenile", "DirectServe uygulamasında aç", "Bu sadece DirectServe yüklü cihazlar içindir. Tarayıcı bağlantısı ve QR kodu herkes için çalışmaya devam edecektir.", "Yakındaki oturumu aç", "Aç", "Kullanılabilir", "PIN gereklidir"],
    "values-vi": ["Lân cận &amp; mạng", "Đảm bảo mạng cục bộ của bạn đã sẵn sàng, sau đó tìm kiếm một thiết bị DirectServe khác nếu bạn muốn mở nó trong ứng dụng.", "Làm mới trạng thái", "Đã kết nối Wi-Fi", "Điểm phát sóng đang hoạt động", "Mạng cục bộ đã sẵn sàng", "Cần có mạng", "Các thiết bị lân cận có thể mở liên kết trên mạng này.", "Kết nối cả hai thiết bị với cùng một Wi-Fi hoặc điểm phát sóng.", "Ứng dụng DirectServe là tùy chọn", "Nếu thiết bị kia cũng có DirectServe, nó có thể xuất hiện tại đây. Những người khác vẫn có thể quét mã QR hoặc mở liên kết trình duyệt.", "Làm mới lân cận", "Mở trong ứng dụng DirectServe", "Điều này chỉ dành cho các thiết bị đã cài đặt DirectServe. Liên kết trình duyệt và mã QR vẫn hoạt động cho mọi người khác.", "Mở phiên lân cận", "Mở", "Có sẵn", "Cần mã PIN"],
    "values-zh-rCN": ["附近与网络", "确保您的本地网络已准备就绪，如果您想在应用中打开，请寻找另一个 DirectServe 设备。", "刷新状态", "已连接 Wi-Fi", "热点已启用", "本地网络就绪", "需要网络", "附近的设备可以在此网络上打开链接。", "将两台设备连接到同一个 Wi-Fi 或热点。", "DirectServe 应用是可选的", "如果另一台设备也有 DirectServe，它可能会出现在这里。其他人仍然可以扫码或打开浏览器链接。", "刷新附近设备", "在 DirectServe 应用中打开", "这仅适用于安装了 DirectServe 的设备。浏览器链接和二维码仍然适用其他人。", "打开附近会话", "打开", "可用", "需要 PIN 码"],
    "values-zh-rTW": ["附近與網路", "確保您的區域網路已準備就緒，如果您想在應用程式中開啟，請尋找另一個 DirectServe 裝置。", "重新整理狀態", "已連線 Wi-Fi", "熱點已啟用", "區域網路備妥", "需要網路", "附近的裝置可以在此網路上開啟連結。", "將兩部裝置連線到同一個 Wi-Fi 或熱點。", "DirectServe 應用程式是選用的", "如果另一部裝置也有 DirectServe，它可能會出現在此處。其他人仍然可以掃描條碼或開啟瀏覽器連結。", "重新整理附近裝置", "在 DirectServe 應用程式中開啟", "這僅適用於安裝了 DirectServe 的裝置。瀏覽器連結和 QR 碼仍然適用於其他人。", "開啟附近工作階段", "開啟", "可用", "需要 PIN 碼"]
}

base_dir = r"C:\Users\sudhi\.gemini\antigravity\scratch\GhostStream\core\resources\src\main\res"

for folder, strings_list in translations.items():
    file_path = os.path.join(base_dir, folder, "strings.xml")
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
        
        # Check if already added
        if keys[0] in content:
            print(f"Skipping {folder}, already contains {keys[0]}")
            continue

        insert_text = "\n    <!-- Support Panel (Nearby & network) -->\n"
        for i, key in enumerate(keys):
            val = strings_list[i].replace("'", "\\'") # escape apostrophes
            insert_text += f'    <string name="{key}">{val}</string>\n'
        
        insert_text += "</resources>"
        
        new_content = content.replace("</resources>", insert_text)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        
        print(f"Updated {folder}/strings.xml")
    else:
        print(f"Warning: {file_path} does not exist.")

print("Chunk 2 translation complete.")
