import os
import xml.etree.ElementTree as ET
from xml.dom import minidom
import loc_sync

TRANSLATIONS = {
    'es': {
        'library_selection_step_2': 'Paso 2: Crear el recurso compartido guardado a partir de los %1$d archivos seleccionados%2$s.',
        'home_feature_live_screen': 'Pantalla en vivo',
        'home_feature_live_screen_desc': 'Duplica la pantalla de tu teléfono en un navegador de la red local.',
        'home_feature_quick_text': 'Texto rápido',
        'home_feature_quick_text_desc': 'Envía texto o enlaces a dispositivos de navegador cercanos.',
        'web_live_title': 'Pantalla en vivo',
        'web_live_waiting': 'Esperando transmisión',
        'web_live_status_live': 'En vivo',
        'web_live_status_starting': 'Iniciando',
        'web_live_status_stopped': 'Detenido',
        'web_live_status_connecting': 'Conectando',
        'web_live_status_waiting_viewer': 'Esperando',
        'web_live_status_reconnecting': 'Reconectando',
        'web_live_audio_live': 'Audio en vivo',
        'web_live_audio_unavailable': 'Audio no disponible',
        'web_live_audio_blocked_or_silent': 'Audio bloqueado o silenciado',
        'web_live_audio_limit': 'Es posible que el audio no esté disponible para algunas aplicaciones debido a las restricciones del sistema.',
        'web_live_capture_notice': 'Algunas aplicaciones bloquean la captura de pantalla, por lo que los videos protegidos o las pantallas seguras pueden aparecer vacíos o incompletos.',
        'web_live_browser_tip': 'Para mejores resultados, usa Chrome para ver la Pantalla en vivo.',
        'web_live_unmute_hint': 'Toca Activar sonido para escuchar el audio. Los navegadores inician las transmisiones en vivo silenciadas hasta que permitas el sonido.',
        'web_live_stream_ended': 'Transmisión finalizada',
        'web_live_fullscreen': 'Pantalla completa',
        'web_live_refresh': 'Actualizar',
        'web_live_fit': 'Ajustar',
        'web_live_fill': 'Llenar',
        'web_live_mute': 'Silenciar',
        'web_live_unmute': 'Activar sonido',
        'web_live_unsupported': 'WebRTC no es compatible con este navegador.',
        'web_live_busy': 'Otro navegador ya está viendo esta pantalla en vivo.',
        'web_live_pin_required': 'Se requiere un PIN de sesión para ver.',
        'sharing_blocked_by_live_screen': 'Detén la pantalla en vivo antes de iniciar una sesión de uso compartido normal.',
        'live_screen_blocked_by_sharing': 'Detén la sesión de uso compartido actual antes de iniciar la pantalla en vivo.',
        'live_screen_pin_label': 'PIN para unirse: %1$s',
        'live_screen_pin_hint': 'Se les pedirá este PIN a los espectadores antes de que puedan ver.',
        'quick_text_blocked_by_live_screen': 'Detén la pantalla en vivo antes de usar Texto rápido.',
        'web_live_pin_entry_title': 'Introduce el PIN de directo',
        'web_live_pin_entry_desc': 'Introduce el PIN que aparece en el teléfono anfitrión para empezar a ver.',
        'web_live_pin_entry_submit': 'Empezar a ver',
        'web_live_pin_entry_invalid': 'Ese PIN no coincide. Inténtalo de nuevo.'
    },
    'ar': {
        'library_selection_step_2': 'الخطوة 2: إنشاء المشاركة المحفوظة من %1$d ملفات مختارة%2$s.',
        'home_feature_live_screen': 'البث المباشر للشاشة',
        'home_feature_live_screen_desc': 'بث شاشة هاتفك إلى متصفح على الشبكة المحلية.',
        'home_feature_quick_text': 'النص السريع',
        'home_feature_quick_text_desc': 'إرسال نصوص أو روابط إلى أجهزة المتصفح القريبة.',
        'web_live_title': 'البث المباشر للشاشة',
        'web_live_waiting': 'في انتظار البث',
        'web_live_status_live': 'مباشر',
        'web_live_status_starting': 'جاري البدء',
        'web_live_status_stopped': 'متوقف',
        'web_live_status_connecting': 'جاري الاتصال',
        'web_live_status_waiting_viewer': 'في الانتظار',
        'web_live_status_reconnecting': 'إعادة الاتصال',
        'web_live_audio_live': 'الصوت مباشر',
        'web_live_audio_unavailable': 'الصوت غير متوفر',
        'web_live_audio_blocked_or_silent': 'الصوت محجوب أو صامت',
        'web_live_audio_limit': 'قد لا يكون الصوت متاحاً لبعض التطبيقات بسبب قيود النظام.',
        'web_live_capture_notice': 'تقوم بعض التطبيقات بحظر تسجيل الشاشة، لذا قد تظهر مقاطع الفيديو المحمية أو الشاشات الآمنة فارغة أو غير مكتملة.',
        'web_live_browser_tip': 'للحصول على أفضل النتائج، استخدم متصفح Chrome لمشاهدة البث المباشر للشاشة.',
        'web_live_unmute_hint': 'اضغط على إلغاء كتم الصوت لسماع الصوت. تبدأ المتصفحات البث المباشر مكتومة الصوت حتى تسمح بالصوت.',
        'web_live_stream_ended': 'انتهى البث',
        'web_live_fullscreen': 'ملء الشاشة',
        'web_live_refresh': 'تحديث',
        'web_live_fit': 'ملاءمة',
        'web_live_fill': 'تعبئة',
        'web_live_mute': 'كتم الصوت',
        'web_live_unmute': 'إلغاء كتم الصوت',
        'web_live_unsupported': 'WebRTC غير مدعوم في هذا المتصفح.',
        'web_live_busy': 'هناك متصفح آخر يشاهد هذا البث المباشر للشاشة بالفعل.',
        'web_live_pin_required': 'مطلوب رمز PIN للجلسة للمشاهدة.',
        'sharing_blocked_by_live_screen': 'أوقف البث المباشر للشاشة قبل بدء جلسة مشاركة عادية.',
        'live_screen_blocked_by_sharing': 'أوقف جلسة المشاركة الحالية قبل بدء البث المباشر للشاشة.',
        'live_screen_pin_label': 'رمز PIN للانضمام: %1$s',
        'live_screen_pin_hint': 'سيُطلب من المشاهدين إدخال رمز PIN هذا قبل أن يتمكنوا من المشاهدة.',
        'quick_text_blocked_by_live_screen': 'أوقف البث المباشر للشاشة قبل استخدام النص السريع.',
        'web_live_pin_entry_title': 'أدخل رمز PIN للبث المباشر',
        'web_live_pin_entry_desc': 'أدخل رمز PIN المعروض على الهاتف المضيف لبدء المشاهدة.',
        'web_live_pin_entry_submit': 'بدء المشاهدة',
        'web_live_pin_entry_invalid': 'رمز PIN هذا غير مطابق. حاول مرة أخرى.'
    },
    'hi': {
        'library_selection_step_2': 'चरण 2: %1$d चयनित फ़ाइलों%2$s से सहेजी गई शेयरिंग बनाएं।',
        'home_feature_live_screen': 'लाइव स्क्रीन',
        'home_feature_live_screen_desc': 'स्थानीय नेटवर्क पर ब्राउज़र पर अपने फ़ोन की स्क्रीन मिरर करें।',
        'home_feature_quick_text': 'त्वरित टेक्स्ट',
        'home_feature_quick_text_desc': 'आस-पास के ब्राउज़र डिवाइस पर टेक्स्ट या लिंक भेजें।',
        'web_live_title': 'लाइव स्क्रीन',
        'web_live_waiting': 'स्ट्रीम का इंतज़ार है',
        'web_live_status_live': 'लाइव',
        'web_live_status_starting': 'शुरू हो रहा है',
        'web_live_status_stopped': 'रुका हुआ',
        'web_live_status_connecting': 'जुड़ रहा है',
        'web_live_status_waiting_viewer': 'प्रतीक्षा में',
        'web_live_status_reconnecting': 'पुनः जुड़ रहा है',
        'web_live_audio_live': 'ऑडियो लाइव',
        'web_live_audio_unavailable': 'ऑडियो उपलब्ध नहीं है',
        'web_live_audio_blocked_or_silent': 'ऑडियो अवरुद्ध या मौन है',
        'web_live_audio_limit': 'सिस्टम प्रतिबंधों के कारण कुछ ऐप्स के लिए ऑडियो उपलब्ध नहीं हो सकता है।',
        'web_live_capture_notice': 'कुछ ऐप्स स्क्रीन कैप्चर को ब्लॉक करते हैं, इसलिए संरक्षित वीडियो या सुरक्षित स्क्रीन खाली या अधूरी दिखाई दे सकती हैं।',
        'web_live_browser_tip': 'सर्वोत्तम परिणामों के लिए, लाइव स्क्रीन देखने के लिए Chrome का उपयोग करें।',
        'web_live_unmute_hint': 'ऑडियो सुनने के लिए अनम्यूट पर टैप करें। ब्राउज़र लाइव स्ट्रीम को तब तक म्यूट रखते हैं जब तक आप ऑडियो की अनुमति नहीं देते।',
        'web_live_stream_ended': 'स्ट्रीम समाप्त',
        'web_live_fullscreen': 'फुल स्क्रीन',
        'web_live_refresh': 'ताज़ा करें',
        'web_live_fit': 'फ़िट',
        'web_live_fill': 'भरें',
        'web_live_mute': 'म्यूट',
        'web_live_unmute': 'अनम्यूट',
        'web_live_unsupported': 'इस ब्राउज़र में WebRTC समर्थित नहीं है।',
        'web_live_busy': 'कोई अन्य ब्राउज़र पहले से ही इस लाइव स्क्रीन को देख रहा है।',
        'web_live_pin_required': 'देखने के लिए सत्र पिन आवश्यक है।',
        'sharing_blocked_by_live_screen': 'सामान्य शेयरिंग सत्र शुरू करने से पहले लाइव स्क्रीन को रोकें।',
        'live_screen_blocked_by_sharing': 'लाइव स्क्रीन शुरू करने से पहले वर्तमान शेयरिंग सत्र को रोकें।',
        'live_screen_pin_label': 'शामिल होने के लिए पिन: %1$s',
        'live_screen_pin_hint': 'दर्शकों को देखने से पहले यह पिन दर्ज करने के लिए कहा जाएगा।',
        'quick_text_blocked_by_live_screen': 'त्वरित टेक्स्ट का उपयोग करने से पहले लाइव स्क्रीन को रोकें।',
        'web_live_pin_entry_title': 'लाइव पिन दर्ज करें',
        'web_live_pin_entry_desc': 'देखना शुरू करने के लिए होस्ट फोन पर दिखाया गया पिन दर्ज करें।',
        'web_live_pin_entry_submit': 'देखना शुरू करें',
        'web_live_pin_entry_invalid': 'वह पिन मेल नहीं खाता। फिर से प्रयास करें।'
    },
    'ru': {
        'library_selection_step_2': 'Шаг 2: Создайте сохраненный общий ресурс из %1$d выбранных файлов%2$s.',
        'home_feature_live_screen': 'Прямой эфир экрана',
        'home_feature_live_screen_desc': 'Транслируйте экран телефона в браузер в локальной сети.',
        'home_feature_quick_text': 'Быстрый текст',
        'home_feature_quick_text_desc': 'Отправляйте текст или ссылки на ближайшие устройства с браузером.',
        'web_live_title': 'Прямой эфир экрана',
        'web_live_waiting': 'Ожидание потока',
        'web_live_status_live': 'В эфире',
        'web_live_status_starting': 'Запуск',
        'web_live_status_stopped': 'Остановлено',
        'web_live_status_connecting': 'Подключение',
        'web_live_status_waiting_viewer': 'В ожидании',
        'web_live_status_reconnecting': 'Переподключение',
        'web_live_audio_live': 'Аудио в эфире',
        'web_live_audio_unavailable': 'Аудио недоступно',
        'web_live_audio_blocked_or_silent': 'Аудио заблокировано или выключено',
        'web_live_audio_limit': 'Аудио может быть недоступно для некоторых приложений из-за системных ограничений.',
        'web_live_capture_notice': 'Некоторые приложения блокируют захват экрана, поэтому защищенные видео или защищенные экраны могут отображаться пустыми или неполными.',
        'web_live_browser_tip': 'Для достижения наилучших результатов используйте Chrome для просмотра экрана в прямом эфире.',
        'web_live_unmute_hint': 'Нажмите «Включить звук», чтобы услышать аудио. Браузеры запускают прямые трансляции без звука, пока вы не разрешите его.',
        'web_live_stream_ended': 'Трансляция окончена',
        'web_live_fullscreen': 'Полный экран',
        'web_live_refresh': 'Обновить',
        'web_live_fit': 'По размеру',
        'web_live_fill': 'Заполнить',
        'web_live_mute': 'Выключить звук',
        'web_live_unmute': 'Включить звук',
        'web_live_unsupported': 'WebRTC не поддерживается в этом браузере.',
        'web_live_busy': 'Другой браузер уже просматривает этот экран в прямом эфире.',
        'web_live_pin_required': 'Для просмотра требуется PIN-код сессии.',
        'sharing_blocked_by_live_screen': 'Остановите прямой эфир экрана перед запуском обычной сессии обмена.',
        'live_screen_blocked_by_sharing': 'Остановите текущую сессию обмена перед запуском прямого эфира экрана.',
        'live_screen_pin_label': 'PIN для подключения: %1$s',
        'live_screen_pin_hint': 'Зрителям потребуется ввести этот PIN-код перед просмотром.',
        'quick_text_blocked_by_live_screen': 'Остановите прямой эфир экрана перед использованием быстрого текста.',
        'web_live_pin_entry_title': 'Введите PIN-код эфира',
        'web_live_pin_entry_desc': 'Введите PIN-код, отображаемый на телефоне-хосте, чтобы начать просмотр.',
        'web_live_pin_entry_submit': 'Начать просмотр',
        'web_live_pin_entry_invalid': 'Этот PIN-код не совпадает. Попробуйте еще раз.'
    },
    'ja': {
        'library_selection_step_2': 'ステップ 2: 選択された %1$d 個のファイル%2$sから保存済み共有を作成します。',
        'home_feature_live_screen': 'ライブスクリーン',
        'home_feature_live_screen_desc': 'ローカルネットワーク上のブラウザにスマホの画面をミラーリングします。',
        'home_feature_quick_text': 'クイックテキスト',
        'home_feature_quick_text_desc': '近くのブラウザデバイスにテキストやリンクを送信します。',
        'web_live_title': 'ライブスクリーン',
        'web_live_waiting': '配信を待機中',
        'web_live_status_live': 'ライブ',
        'web_live_status_starting': '開始中',
        'web_live_status_stopped': '停止中',
        'web_live_status_connecting': '接続中',
        'web_live_status_waiting_viewer': '待機中',
        'web_live_status_reconnecting': '再接続中',
        'web_live_audio_live': '音声ライブ',
        'web_live_audio_unavailable': '音声利用不可',
        'web_live_audio_blocked_or_silent': '音声ブロックまたはミュート',
        'web_live_audio_limit': 'システムの制限により、一部のアプリで音声が利用できない場合があります。',
        'web_live_capture_notice': '一部のアプリは画面キャプチャをブロックするため、保護された動画や安全な画面は空白または不完全に表示される場合があります。',
        'web_live_browser_tip': '最高の体験を得るには、ライブスクリーンの視聴に Chrome を使用してください。',
        'web_live_unmute_hint': '音声を聴くには「ミュート解除」をタップしてください。ブラウザは音声を許可するまでライブ配信をミュート状態で開始します。',
        'web_live_stream_ended': '配信終了',
        'web_live_fullscreen': '全画面',
        'web_live_refresh': '更新',
        'web_live_fit': 'フィット',
        'web_live_fill': '塗りつぶし',
        'web_live_mute': 'ミュート',
        'web_live_unmute': 'ミュート解除',
        'web_live_unsupported': 'このブラウザは WebRTC をサポートしていません。',
        'web_live_busy': '別のブラウザがすでにこのライブスクリーンを視聴しています。',
        'web_live_pin_required': '視聴にはセッションPINが必要です。',
        'sharing_blocked_by_live_screen': '通常の共有セッションを開始する前にライブスクリーンを停止してください。',
        'live_screen_blocked_by_sharing': 'ライブスクリーンを開始する前に現在の共有セッションを停止してください。',
        'live_screen_pin_label': '参加用PIN: %1$s',
        'live_screen_pin_hint': '視聴者は、視聴を開始する前にこのPINの入力を求められます。',
        'quick_text_blocked_by_live_screen': 'クイックテキストを使用する前にライブスクリーンを停止してください。',
        'web_live_pin_entry_title': 'ライブPINを入力',
        'web_live_pin_entry_desc': '視聴を開始するには、ホストの電話に表示されているPINを入力してください。',
        'web_live_pin_entry_submit': '視聴を開始',
        'web_live_pin_entry_invalid': 'PINが一致しません。もう一度お試しください。'
    },
    'zh-rCN': {
        'library_selection_step_2': '第 2 步：从选定的 %1$d 个文件%2$s创建已保存共享。',
        'home_feature_live_screen': '实时屏幕',
        'home_feature_live_screen_desc': '将手机屏幕镜像到本地网络上的浏览器。',
        'home_feature_quick_text': '快捷文本',
        'home_feature_quick_text_desc': '向附近的浏览器设备发送文本或链接。',
        'web_live_title': '实时屏幕',
        'web_live_waiting': '等待流传输',
        'web_live_status_live': '直播中',
        'web_live_status_starting': '正在启动',
        'web_live_status_stopped': '已停止',
        'web_live_status_connecting': '正在连接',
        'web_live_status_waiting_viewer': '等待中',
        'web_live_status_reconnecting': '正在重新连接',
        'web_live_audio_live': '音频直播中',
        'web_live_audio_unavailable': '音频不可用',
        'web_live_audio_blocked_or_silent': '音频已屏蔽或静音',
        'web_live_audio_limit': '由于系统限制，某些应用可能无法使用音频。',
        'web_live_capture_notice': '某些应用会阻止屏幕截取，因此受保护的视频或安全屏幕可能会显示为空白或不完整。',
        'web_live_browser_tip': '为了获得最佳效果，请使用 Chrome 查看实时屏幕。',
        'web_live_unmute_hint': '点击取消静音以收听音频。在您允许音频之前，浏览器会以静音方式开始直播。',
        'web_live_stream_ended': '流传输已结束',
        'web_live_fullscreen': '全屏',
        'web_live_refresh': '刷新',
        'web_live_fit': '适应',
        'web_live_fill': '填充',
        'web_live_mute': '静音',
        'web_live_unmute': '取消静音',
        'web_live_unsupported': '此浏览器不支持 WebRTC。',
        'web_live_busy': '另一个浏览器已在查看此实时屏幕。',
        'web_live_pin_required': '需要会话 PIN 才能查看。',
        'sharing_blocked_by_live_screen': '在开始普通共享会话之前，请先停止实时屏幕。',
        'live_screen_blocked_by_sharing': '在开始实时屏幕之前，请先停止当前的共享会话。',
        'live_screen_pin_label': '加入 PIN： %1$s',
        'live_screen_pin_hint': '观众在观看前将被要求输入此 PIN。',
        'quick_text_blocked_by_live_screen': '在使用快捷文本之前，请先停止实时屏幕。',
        'web_live_pin_entry_title': '输入直播 PIN',
        'web_live_pin_entry_desc': '输入主机手机上显示的 PIN 以开始观看。',
        'web_live_pin_entry_submit': '开始观看',
        'web_live_pin_entry_invalid': '该 PIN 不匹配。请重试。'
    },
    'zh-rTW': {
        'library_selection_step_2': '第 2 步：從選定的 %1$d 個檔案%2$s建立已儲存共享。',
        'home_feature_live_screen': '即時螢幕',
        'home_feature_live_screen_desc': '將手機螢幕映射到本地網絡上的瀏覽器。',
        'home_feature_quick_text': '快捷文字',
        'home_feature_quick_text_desc': '向附近的瀏覽器裝置傳送文字或連結。',
        'web_live_title': '即時螢幕',
        'web_live_waiting': '等待串流',
        'web_live_status_live': '直播中',
        'web_live_status_starting': '正在啟動',
        'web_live_status_stopped': '已停止',
        'web_live_status_connecting': '正在連接',
        'web_live_status_waiting_viewer': '等待中',
        'web_live_status_reconnecting': '正在重新連接',
        'web_live_audio_live': '音訊直播中',
        'web_live_audio_unavailable': '音訊不可用',
        'web_live_audio_blocked_or_silent': '音訊已屏蔽或靜音',
        'web_live_audio_limit': '由於系統限制，某些應用程式可能無法使用音訊。',
        'web_live_capture_notice': '某些應用程式會阻止螢幕截取，因此受保護的影片或安全螢幕可能會顯示為空白或不完整。',
        'web_live_browser_tip': '為了獲得最佳效果，請使用 Chrome 查看即時螢幕。',
        'web_live_unmute_hint': '點擊取消靜音以收聽音訊。在您允許音訊之前，瀏覽器會以靜音方式開始直播。',
        'web_live_stream_ended': '串流已結束',
        'web_live_fullscreen': '全螢幕',
        'web_live_refresh': '重新整理',
        'web_live_fit': '適應',
        'web_live_fill': '填充',
        'web_live_mute': '靜音',
        'web_live_unmute': '取消靜音',
        'web_live_unsupported': '此瀏覽器不支援 WebRTC。',
        'web_live_busy': '另一個瀏覽器已在查看此即時螢幕。',
        'web_live_pin_required': '需要會話 PIN 才能查看。',
        'sharing_blocked_by_live_screen': '在開始普通共享會話之前，請先停止即時螢幕。',
        'live_screen_blocked_by_sharing': '在開始即時螢幕之前，請先停止當前的共享會話。',
        'live_screen_pin_label': '加入 PIN： %1$s',
        'live_screen_pin_hint': '觀眾在觀看前將被要求輸入此 PIN。',
        'quick_text_blocked_by_live_screen': '在使用快捷文字之前，請先停止即時螢幕。',
        'web_live_pin_entry_title': '輸入直播 PIN',
        'web_live_pin_entry_desc': '輸入主機手機上顯示的 PIN 以開始觀看。',
        'web_live_pin_entry_submit': '開始觀看',
        'web_live_pin_entry_invalid': '該 PIN 不匹配。請重試。'
    },
    'ko': {
        'library_selection_step_2': '2단계: 선택한 %1$d개의 파일%2$s로 저장된 공유를 생성합니다.',
        'home_feature_live_screen': '라이브 스크린',
        'home_feature_live_screen_desc': '로컬 네트워크의 브라우저에 휴대폰 화면을 미러링합니다.',
        'home_feature_quick_text': '퀵 텍스트',
        'home_feature_quick_text_desc': '근처의 브라우저 장치로 텍스트나 링크를 보냅니다.',
        'web_live_title': '라이브 스크린',
        'web_live_waiting': '스트림 대기 중',
        'web_live_status_live': '라이브',
        'web_live_status_starting': '시작 중',
        'web_live_status_stopped': '정지됨',
        'web_live_status_connecting': '연결 중',
        'web_live_status_waiting_viewer': '대기 중',
        'web_live_status_reconnecting': '재연결 중',
        'web_live_audio_live': '오디오 라이브',
        'web_live_audio_unavailable': '오디오 사용 불가',
        'web_live_audio_blocked_or_silent': '오디오 차단 또는 음소거',
        'web_live_audio_limit': '시스템 제한으로 인해 일부 앱에서는 오디오를 사용할 수 없을 수 있습니다.',
        'web_live_capture_notice': '일부 앱은 화면 캡처를 차단하므로 보호된 비디오나 보안 화면은 공백으로 표시되거나 불완전하게 표시될 수 있습니다.',
        'web_live_browser_tip': '최상의 결과를 얻으려면 Chrome을 사용하여 라이브 스크린을 시청하세요.',
        'web_live_unmute_hint': '오디오를 들으려면 음소거 해제를 누르세요. 브라우저는 오디오를 허용할 때까지 라이브 스트림을 음소거 상태로 시작합니다.',
        'web_live_stream_ended': '스트림 종료됨',
        'web_live_fullscreen': '전체 화면',
        'web_live_refresh': '새로고침',
        'web_live_fit': '맞춤',
        'web_live_fill': '채우기',
        'web_live_mute': '음소거',
        'web_live_unmute': '음소거 해제',
        'web_live_unsupported': '이 브라우저는 WebRTC를 지원하지 않습니다.',
        'web_live_busy': '다른 브라우저에서 이미 이 라이브 스크린을 시청하고 있습니다.',
        'web_live_pin_required': '시청하려면 세션 PIN이 필요합니다.',
        'sharing_blocked_by_live_screen': '일반 공유 세션을 시작하기 전에 라이브 스크린을 중지하세요.',
        'live_screen_blocked_by_sharing': '라이브 스크린을 시작하기 전에 현재 공유 세션을 중지하세요.',
        'live_screen_pin_label': '참여 PIN: %1$s',
        'live_screen_pin_hint': '시청자는 시청을 시작하기 전에 이 PIN을 입력해야 합니다.',
        'quick_text_blocked_by_live_screen': '퀵 텍스트를 사용하기 전에 라이브 스크린을 중지하세요.',
        'web_live_pin_entry_title': '라이브 PIN 입력',
        'web_live_pin_entry_desc': '시청을 시작하려면 호스트 전화에 표시된 PIN을 입력하세요.',
        'web_live_pin_entry_submit': '시청 시작',
        'web_live_pin_entry_invalid': 'PIN이 일치하지 않습니다. 다시 시도하세요.'
    },
    'nl': {
        'library_selection_step_2': 'Stap 2: Maak de opgeslagen share van de %1$d geselecteerde bestanden%2$s.',
        'home_feature_live_screen': 'Live-scherm',
        'home_feature_live_screen_desc': 'Spiegel uw telefoonscherm naar een browser op het lokale netwerk.',
        'home_feature_quick_text': 'Snelle tekst',
        'home_feature_quick_text_desc': 'Stuur tekst of links naar browserapparaten in de buurt.',
        'web_live_title': 'Live-scherm',
        'web_live_waiting': 'Wachten op stream',
        'web_live_status_live': 'Live',
        'web_live_status_starting': 'Opstarten',
        'web_live_status_stopped': 'Gestopt',
        'web_live_status_connecting': 'Verbinden',
        'web_live_status_waiting_viewer': 'Wachten',
        'web_live_status_reconnecting': 'Opnieuw verbinden',
        'web_live_audio_live': 'Audio live',
        'web_live_audio_unavailable': 'Audio niet beschikbaar',
        'web_live_audio_blocked_or_silent': 'Audio geblokkeerd of gedempt',
        'web_live_audio_limit': 'Audio is mogelijk niet beschikbaar voor sommige apps vanwege systeembeperkingen.',
        'web_live_capture_notice': 'Sommige apps blokkeren schermopname, dus beveiligde video\'s of beveiligde schermen kunnen leeg of onvolledig verschijnen.',
        'web_live_browser_tip': 'Gebruik Chrome voor de beste resultaten om het live-scherm te bekijken.',
        'web_live_unmute_hint': 'Tik op Dempen opheffen om audio te horen. Browsers starten live-streams gedempt totdat u audio toestaat.',
        'web_live_stream_ended': 'Stream beëindigd',
        'web_live_fullscreen': 'Volledig scherm',
        'web_live_refresh': 'Vernieuwen',
        'web_live_fit': 'Passend maken',
        'web_live_fill': 'Vullen',
        'web_live_mute': 'Dempen',
        'web_live_unmute': 'Dempen opheffen',
        'web_live_unsupported': 'WebRTC wordt niet ondersteund in deze browser.',
        'web_live_busy': 'Een andere browser bekijkt dit live-scherm al.',
        'web_live_pin_required': 'Een sessie-PIN is vereist om te bekijken.',
        'sharing_blocked_by_live_screen': 'Stop Live-scherm voordat u een normale deelsessie start.',
        'live_screen_blocked_by_sharing': 'Stop de huidige deelsessie voordat u Live-scherm start.',
        'live_screen_pin_label': 'PIN om deel te nemen: %1$s',
        'live_screen_pin_hint': 'Kijkers wordt om deze PIN gevraagd voordat ze kunnen kijken.',
        'quick_text_blocked_by_live_screen': 'Stop Live-scherm voordat u Snelle tekst gebruikt.',
        'web_live_pin_entry_title': 'Voer live PIN in',
        'web_live_pin_entry_desc': 'Voer de PIN in die op de host-telefoon wordt weergegeven om te beginnen met kijken.',
        'web_live_pin_entry_submit': 'Begin met kijken',
        'web_live_pin_entry_invalid': 'Die PIN kwam niet overeen. Probeer het opnieuw.'
    },
    'sv': {
        'library_selection_step_2': 'Steg 2: Skapa den sparade delningen från de %1$d valda filerna%2$s.',
        'home_feature_live_screen': 'Liveskärm',
        'home_feature_live_screen_desc': 'Spegla din telefonskärm till en webbläsare på det lokala nätverket.',
        'home_feature_quick_text': 'Snabbtext',
        'home_feature_quick_text_desc': 'Skicka text eller länkar till webbläsarenheter i närheten.',
        'web_live_title': 'Liveskärm',
        'web_live_waiting': 'Väntar på ström',
        'web_live_status_live': 'Live',
        'web_live_status_starting': 'Startar',
        'web_live_status_stopped': 'Stoppad',
        'web_live_status_connecting': 'Ansluter',
        'web_live_status_waiting_viewer': 'Väntar',
        'web_live_status_reconnecting': 'Ansluter igen',
        'web_live_audio_live': 'Ljud live',
        'web_live_audio_unavailable': 'Ljud ej tillgängligt',
        'web_live_audio_blocked_or_silent': 'Ljud blockerat eller tyst',
        'web_live_audio_limit': 'Ljud kanske inte är tillgängligt för vissa appar på grund av systembegränsningar.',
        'web_live_capture_notice': 'Vissa appar blockerar skärminspelning, så skyddade videor eller säkra skärmar kan visas tomma eller ofullständiga.',
        'web_live_browser_tip': 'För bästa resultat, använd Chrome för att titta på liveskärmen.',
        'web_live_unmute_hint': 'Tryck på Slå på ljud för att höra ljudet. Webbläsare startar liveströmmar med ljudet avstängt tills du tillåter ljud.',
        'web_live_stream_ended': 'Strömmen avslutades',
        'web_live_fullscreen': 'Helskärm',
        'web_live_refresh': 'Uppdatera',
        'web_live_fit': 'Anpassa',
        'web_live_fill': 'Fyll',
        'web_live_mute': 'Ljud av',
        'web_live_unmute': 'Ljud på',
        'web_live_unsupported': 'WebRTC stöds inte i den här webbläsaren.',
        'web_live_busy': 'En annan webbläsare tittar redan på den här liveskärmen.',
        'web_live_pin_required': 'En sessions-PIN krävs för att titta.',
        'sharing_blocked_by_live_screen': 'Stoppa Liveskärm innan du startar en vanlig delningssession.',
        'live_screen_blocked_by_sharing': 'Stoppa den aktuella delningssessionen innan du startar Liveskärm.',
        'live_screen_pin_label': 'PIN för att gå med: %1$s',
        'live_screen_pin_hint': 'Tittare kommer att tillfrågas om denna PIN innan de kan titta.',
        'quick_text_blocked_by_live_screen': 'Stoppa Liveskärm innan du använder Snabbtext.',
        'web_live_pin_entry_title': 'Ange live-PIN',
        'web_live_pin_entry_desc': 'Ange PIN-koden som visas på värdtelefonen för att börja titta.',
        'web_live_pin_entry_submit': 'Börja titta',
        'web_live_pin_entry_invalid': 'Den PIN-koden stämde inte. Försök igen.'
    },
    'el': {
        'library_selection_step_2': 'Βήμα 2: Δημιουργήστε την αποθηκευμένη κοινή χρήση από τα %1$d επιλεγμένα αρχεία%2$s.',
        'home_feature_live_screen': 'Ζωντανή οθόνη',
        'home_feature_live_screen_desc': 'Αντικατοπτρίστε την οθόνη του τηλεφώνου σας σε ένα πρόγραμμα περιήγησης στο τοπικό δίκτυο.',
        'home_feature_quick_text': 'Γρήγορο κείμενο',
        'home_feature_quick_text_desc': 'Στείλτε κείμενο ή συνδέσμους σε κοντινές συσκευές με πρόγραμμα περιήγησης.',
        'web_live_title': 'Ζωντανή οθόνη',
        'web_live_waiting': 'Αναμονή για ροή',
        'web_live_status_live': 'Ζωντανά',
        'web_live_status_starting': 'Έναρξη',
        'web_live_status_stopped': 'Διακόπηκε',
        'web_live_status_connecting': 'Σύνδεση',
        'web_live_status_waiting_viewer': 'Σε αναμονή',
        'web_live_status_reconnecting': 'Επανασύνδεση',
        'web_live_audio_live': 'Ήχος ζωντανά',
        'web_live_audio_unavailable': 'Ήχος μη διαθέσιμος',
        'web_live_audio_blocked_or_silent': 'Ήχος αποκλεισμένος ή σε σίγαση',
        'web_live_audio_limit': 'Ο ήχος ενδέχεται να μην είναι διαθέσιμος για ορισμένες εφαρμογές λόγω περιορισμών του συστήματος.',
        'web_live_capture_notice': 'Ορισμένες εφαρμογές αποκλείουν την καταγραφή οθόνης, επομένως προστατευμένα βίντεο ή ασφαλείς οθόνες ενδέχεται να εμφανίζονται κενές ή ελλιπείς.',
        'web_live_browser_tip': 'Για καλύτερα αποτελέσματα, χρησιμοποιήστε το Chrome για να παρακολουθήσετε τη ζωντανή οθόνη.',
        'web_live_unmute_hint': 'Πατήστε Κατάργηση σίγασης για να ακούσετε ήχο. Τα προγράμματα περιήγησης ξεκινούν τις ζωντανές ροές με σίγαση μέχρι να επιτρέψετε τον ήχο.',
        'web_live_stream_ended': 'Η ροή έληξε',
        'web_live_fullscreen': 'Πλήρης οθόνη',
        'web_live_refresh': 'Ανανέωση',
        'web_live_fit': 'Προσαρμογή',
        'web_live_fill': 'Γέμισμα',
        'web_live_mute': 'Σίγαση',
        'web_live_unmute': 'Κατάργηση σίγασης',
        'web_live_unsupported': 'Το WebRTC δεν υποστηρίζεται σε αυτό το πρόγραμμα περιήγησης.',
        'web_live_busy': 'Ένα άλλο πρόγραμμα περιήγησης παρακολουθεί ήδη αυτήν τη ζωντανή οθόνη.',
        'web_live_pin_required': 'Απαιτείται PIN συνεδρίας για την παρακολούθηση.',
        'sharing_blocked_by_live_screen': 'Διακόψτε τη Ζωντανή οθόνη πριν ξεκινήσετε μια κανονική συνεδρία κοινής χρήσης.',
        'live_screen_blocked_by_sharing': 'Διακόψτε την τρέχουσα συνεδρία κοινής χρήσης πριν ξεκινήσετε τη Ζωντανή οθόνη.',
        'live_screen_pin_label': 'PIN για συμμετοχή: %1$s',
        'live_screen_pin_hint': 'Θα ζητηθεί από τους θεατές αυτό το PIN πριν μπορέσουν να παρακολουθήσουν.',
        'quick_text_blocked_by_live_screen': 'Διακόψτε τη Ζωντανή οθόνη πριν χρησιμοποιήσετε το Γρήγορο κείμενο.',
        'web_live_pin_entry_title': 'Εισαγάγετε το PIN',
        'web_live_pin_entry_desc': 'Εισαγάγετε το PIN που εμφανίζεται στο τηλέφωνο του κεντρικού υπολογιστή για να ξεκινήσετε την παρακολούθηση.',
        'web_live_pin_entry_submit': 'Έναρξη παρακολούθησης',
        'web_live_pin_entry_invalid': 'Αυτό το PIN δεν ταιριάζει. Δοκιμάστε ξανά.'
    },
    'tr': {
        'library_selection_step_2': 'Adım 2: Seçilen %1$d dosyadan%2$s kaydedilmiş paylaşımı oluşturun.',
        'home_feature_live_screen': 'Canlı Ekran',
        'home_feature_live_screen_desc': 'Telefonunuzun ekranını yerel ağdaki bir tarayıcıya yansıtın.',
        'home_feature_quick_text': 'Hızlı Metin',
        'home_feature_quick_text_desc': 'Yakındaki tarayıcı cihazlarına metin veya bağlantı gönderin.',
        'web_live_title': 'Canlı Ekran',
        'web_live_waiting': 'Yayın bekleniyor',
        'web_live_status_live': 'Canlı',
        'web_live_status_starting': 'Başlatılıyor',
        'web_live_status_stopped': 'Durduruldu',
        'web_live_status_connecting': 'Bağlanıyor',
        'web_live_status_waiting_viewer': 'Beklemede',
        'web_live_status_reconnecting': 'Yeniden bağlanıyor',
        'web_live_audio_live': 'Ses canlı',
        'web_live_audio_unavailable': 'Ses kullanılamıyor',
        'web_live_audio_blocked_or_silent': 'Ses engellendi veya sessiz',
        'web_live_audio_limit': 'Sistem kısıtlamaları nedeniyle bazı uygulamalar için ses kullanılamayabilir.',
        'web_live_capture_notice': 'Bazı uygulamalar ekran yakalamayı engeller, bu nedenle korumalı videolar veya güvenli ekranlar boş veya eksik görünebilir.',
        'web_live_browser_tip': 'En iyi sonuçlar için canlı ekranı izlemek üzere Chrome kullanın.',
        'web_live_unmute_hint': 'Sesi duymak için Sesi Aç\'a dokunun. Tarayıcılar, siz sese izin verene kadar canlı yayınları sessiz başlatır.',
        'web_live_stream_ended': 'Yayın sona erdi',
        'web_live_fullscreen': 'Tam ekran',
        'web_live_refresh': 'Yenile',
        'web_live_fit': 'Sığdır',
        'web_live_fill': 'Doldur',
        'web_live_mute': 'Sesi Kapat',
        'web_live_unmute': 'Sesi Aç',
        'web_live_unsupported': 'WebRTC bu tarayıcıda desteklenmiyor.',
        'web_live_busy': 'Başka bir tarayıcı zaten bu canlı ekranı izliyor.',
        'web_live_pin_required': 'İzlemek için oturum PIN\'i gereklidir.',
        'sharing_blocked_by_live_screen': 'Normal bir paylaşım oturumu başlatmadan önce Canlı Ekranı durdurun.',
        'live_screen_blocked_by_sharing': 'Canlı Ekranı başlatmadan önce mevcut paylaşım oturumunu durdurun.',
        'live_screen_pin_label': 'Katılmak için PIN: %1$s',
        'live_screen_pin_hint': 'İzleyicilerin izleyebilmesi için bu PIN\'i girmeleri istenecektir.',
        'quick_text_blocked_by_live_screen': 'Hızlı Metni kullanmadan önce Canlı Ekranı durdurun.',
        'web_live_pin_entry_title': 'Canlı PIN girin',
        'web_live_pin_entry_desc': 'İzlemeye başlamak için ana telefonda gösterilen PIN\'i girin.',
        'web_live_pin_entry_submit': 'İzlemeye başla',
        'web_live_pin_entry_invalid': 'Bu PIN eşleşmedi. Tekrar deneyin.'
    },
    'id': {
        'library_selection_step_2': 'Langkah 2: Buat berbagi tersimpan dari %1$d berkas terpilih%2$s.',
        'home_feature_live_screen': 'Layar Langsung',
        'home_feature_live_screen_desc': 'Mirror layar ponsel Anda ke browser di jaringan lokal.',
        'home_feature_quick_text': 'Teks Cepat',
        'home_feature_quick_text_desc': 'Kirim teks atau tautan ke perangkat browser terdekat.',
        'web_live_title': 'Layar Langsung',
        'web_live_waiting': 'Menunggu aliran',
        'web_live_status_live': 'Langsung',
        'web_live_status_starting': 'Memulai',
        'web_live_status_stopped': 'Berhenti',
        'web_live_status_connecting': 'Menghubungkan',
        'web_live_status_waiting_viewer': 'Menunggu',
        'web_live_status_reconnecting': 'Menghubungkan kembali',
        'web_live_audio_live': 'Audio langsung',
        'web_live_audio_unavailable': 'Audio tidak tersedia',
        'web_live_audio_blocked_or_silent': 'Audio diblokir atau bisu',
        'web_live_audio_limit': 'Audio mungkin tidak tersedia untuk beberapa aplikasi karena batasan sistem.',
        'web_live_capture_notice': 'Beberapa aplikasi memblokir tangkapan layar, sehingga video yang dilindungi atau layar aman mungkin tampak kosong atau tidak lengkap.',
        'web_live_browser_tip': 'Untuk hasil terbaik, gunakan Chrome untuk menonton layar langsung.',
        'web_live_unmute_hint': 'Ketuk Bunyikan untuk mendengar audio. Browser memulai aliran langsung dalam keadaan bisu sampai Anda mengizinkan audio.',
        'web_live_stream_ended': 'Aliran berakhir',
        'web_live_fullscreen': 'Layar penuh',
        'web_live_refresh': 'Segarkan',
        'web_live_fit': 'Pas',
        'web_live_fill': 'Isi',
        'web_live_mute': 'Bisu',
        'web_live_unmute': 'Bunyikan',
        'web_live_unsupported': 'WebRTC tidak didukung di browser ini.',
        'web_live_busy': 'Browser lain sudah menonton layar langsung ini.',
        'web_live_pin_required': 'PIN sesi diperlukan untuk menonton.',
        'sharing_blocked_by_live_screen': 'Hentikan Layar Langsung sebelum memulai sesi berbagi normal.',
        'live_screen_blocked_by_sharing': 'Hentikan sesi berbagi saat ini sebelum memulai Layar Langsung.',
        'live_screen_pin_label': 'PIN untuk bergabung: %1$s',
        'live_screen_pin_hint': 'Penonton akan dimintai PIN ini sebelum mereka dapat menonton.',
        'quick_text_blocked_by_live_screen': 'Hentikan Layar Langsung sebelum menggunakan Teks Cepat.',
        'web_live_pin_entry_title': 'Masukkan PIN langsung',
        'web_live_pin_entry_desc': 'Masukkan PIN yang ditampilkan di ponsel host untuk mulai menonton.',
        'web_live_pin_entry_submit': 'Mulai menonton',
        'web_live_pin_entry_invalid': 'PIN itu tidak cocok. Coba lagi.'
    },
    'in': {
        'library_selection_step_2': 'Langkah 2: Buat berbagi tersimpan dari %1$d berkas terpilih%2$s.',
        'home_feature_live_screen': 'Layar Langsung',
        'home_feature_live_screen_desc': 'Mirror layar ponsel Anda ke browser di jaringan lokal.',
        'home_feature_quick_text': 'Teks Cepat',
        'home_feature_quick_text_desc': 'Kirim teks atau tautan ke perangkat browser terdekat.',
        'web_live_title': 'Layar Langsung',
        'web_live_waiting': 'Menunggu aliran',
        'web_live_status_live': 'Langsung',
        'web_live_status_starting': 'Memulai',
        'web_live_status_stopped': 'Berhenti',
        'web_live_status_connecting': 'Menghubungkan',
        'web_live_status_waiting_viewer': 'Menunggu',
        'web_live_status_reconnecting': 'Menghubungkan kembali',
        'web_live_audio_live': 'Audio langsung',
        'web_live_audio_unavailable': 'Audio tidak tersedia',
        'web_live_audio_blocked_or_silent': 'Audio diblokir atau bisu',
        'web_live_audio_limit': 'Audio mungkin tidak tersedia untuk beberapa aplikasi karena batasan sistem.',
        'web_live_capture_notice': 'Beberapa aplikasi memblokir tangkapan layar, sehingga video yang dilindungi atau layar aman mungkin tampak kosong or tidak lengkap.',
        'web_live_browser_tip': 'Untuk hasil terbaik, gunakan Chrome untuk menonton layar langsung.',
        'web_live_unmute_hint': 'Ketuk Bunyikan untuk mendengar audio. Browser memulai aliran langsung dalam keadaan bisu sampai Anda mengizinkan audio.',
        'web_live_stream_ended': 'Aliran berakhir',
        'web_live_fullscreen': 'Layar penuh',
        'web_live_refresh': 'Segarkan',
        'web_live_fit': 'Pas',
        'web_live_fill': 'Isi',
        'web_live_mute': 'Bisu',
        'web_live_unmute': 'Bunyikan',
        'web_live_unsupported': 'WebRTC tidak didukung di browser ini.',
        'web_live_busy': 'Browser lain sudah menonton layar langsung ini.',
        'web_live_pin_required': 'PIN sesi diperlukan untuk menonton.',
        'sharing_blocked_by_live_screen': 'Hentikan Layar Langsung sebelum memulai sesi berbagi normal.',
        'live_screen_blocked_by_sharing': 'Hentikan sesi berbagi saat ini sebelum memulai Layar Langsung.',
        'live_screen_pin_label': 'PIN untuk bergabung: %1$s',
        'live_screen_pin_hint': 'Penonton akan dimintai PIN ini sebelum mereka dapat menonton.',
        'quick_text_blocked_by_live_screen': 'Hentikan Layar Langsung sebelum menggunakan Teks Cepat.',
        'web_live_pin_entry_title': 'Masukkan PIN langsung',
        'web_live_pin_entry_desc': 'Masukkan PIN yang ditampilkan di ponsel host untuk mulai menonton.',
        'web_live_pin_entry_submit': 'Mulai menonton',
        'web_live_pin_entry_invalid': 'PIN itu tidak cocok. Coba lagi.'
    },
    'vi': {
        'library_selection_step_2': 'Bước 2: Tạo chia sẻ đã lưu từ %1$d tệp đã chọn%2$s.',
        'home_feature_live_screen': 'Màn hình trực tiếp',
        'home_feature_live_screen_desc': 'Phản chiếu màn hình điện thoại của bạn lên trình duyệt trên mạng nội bộ.',
        'home_feature_quick_text': 'Văn bản nhanh',
        'home_feature_quick_text_desc': 'Gửi văn bản hoặc liên kết đến các thiết bị trình duyệt gần đó.',
        'web_live_title': 'Màn hình trực tiếp',
        'web_live_waiting': 'Đang chờ luồng',
        'web_live_status_live': 'Trực tiếp',
        'web_live_status_starting': 'Đang khởi động',
        'web_live_status_stopped': 'Đã dừng',
        'web_live_status_connecting': 'Đang kết nối',
        'web_live_status_waiting_viewer': 'Đang chờ',
        'web_live_status_reconnecting': 'Đang kết nối lại',
        'web_live_audio_live': 'Âm thanh trực tiếp',
        'web_live_audio_unavailable': 'Âm thanh không khả dụng',
        'web_live_audio_blocked_or_silent': 'Âm thanh bị chặn hoặc tắt tiếng',
        'web_live_audio_limit': 'Âm thanh có thể không khả dụng cho một số ứng dụng do các hạn chế của hệ thống.',
        'web_live_capture_notice': 'Một số ứng dụng chặn chụp màn hình, vì vậy các video được bảo vệ hoặc màn hình an toàn có thể xuất hiện trống hoặc không đầy đủ.',
        'web_live_browser_tip': 'Để có kết quả tốt nhất, hãy sử dụng Chrome để xem màn hình trực tiếp.',
        'web_live_unmute_hint': 'Nhấn Bật tiếng để nghe âm thanh. Các trình duyệt bắt đầu luồng trực tiếp ở chế độ tắt tiếng cho đến khi bạn cho phép âm thanh.',
        'web_live_stream_ended': 'Luồng đã kết thúc',
        'web_live_fullscreen': 'Toàn màn hình',
        'web_live_refresh': 'Làm mới',
        'web_live_fit': 'Vừa khít',
        'web_live_fill': 'Lấp đầy',
        'web_live_mute': 'Tắt tiếng',
        'web_live_unmute': 'Bật tiếng',
        'web_live_unsupported': 'WebRTC không được hỗ trợ trong trình duyệt này.',
        'web_live_busy': 'Một trình duyệt khác đã đang xem màn hình trực tiếp này.',
        'web_live_pin_required': 'Cần có mã PIN phiên để xem.',
        'sharing_blocked_by_live_screen': 'Dừng Màn hình trực tiếp trước khi bắt đầu phiên chia sẻ bình thường.',
        'live_screen_blocked_by_sharing': 'Dừng phiên chia sẻ hiện tại trước khi bắt đầu Màn hình trực tiếp.',
        'live_screen_pin_label': 'Mã PIN để tham gia: %1$s',
        'live_screen_pin_hint': 'Người xem sẽ được yêu cầu nhập mã PIN này trước khi họ có thể xem.',
        'quick_text_blocked_by_live_screen': 'Dừng Màn hình trực tiếp trước khi sử dụng Văn bản nhanh.',
        'web_live_pin_entry_title': 'Nhập mã PIN trực tiếp',
        'web_live_pin_entry_desc': 'Nhập mã PIN hiển thị trên điện thoại chủ để bắt đầu xem.',
        'web_live_pin_entry_submit': 'Bắt đầu xem',
        'web_live_pin_entry_invalid': 'Mã PIN đó không khớp. Thử lại.'
    },
    'th': {
        'library_selection_step_2': 'ขั้นตอนที่ 2: สร้างการแชร์ที่บันทึกไว้จากไฟล์ที่เลือก %1$d ไฟล์%2$s',
        'home_feature_live_screen': 'หน้าจอสด',
        'home_feature_live_screen_desc': 'สะท้อนหน้าจอโทรศัพท์ของคุณไปยังเบราว์เซอร์ในเครือข่ายท้องถิ่น',
        'home_feature_quick_text': 'ข้อความด่วน',
        'home_feature_quick_text_desc': 'ส่งข้อความหรือลิงก์ไปยังอุปกรณ์เบราว์เซอร์ที่อยู่ใกล้เคียง',
        'web_live_title': 'หน้าจอสด',
        'web_live_waiting': 'รอสตรีม',
        'web_live_status_live': 'สด',
        'web_live_status_starting': 'กำลังเริ่ม',
        'web_live_status_stopped': 'หยุดแล้ว',
        'web_live_status_connecting': 'กำลังเชื่อมต่อ',
        'web_live_status_waiting_viewer': 'กำลังรอ',
        'web_live_status_reconnecting': 'กำลังเชื่อมต่อใหม่',
        'web_live_audio_live': 'เสียงสด',
        'web_live_audio_unavailable': 'ไม่มีเสียง',
        'web_live_audio_blocked_or_silent': 'เสียงถูกบล็อกหรือปิดเสียง',
        'web_live_audio_limit': 'เสียงอาจไม่สามารถใช้ได้ในบางแอปเนื่องจากข้อจำกัดของระบบ',
        'web_live_capture_notice': 'บางแอปบล็อกการจับภาพหน้าจอ ดังนั้นวิดีโอที่ได้รับการป้องกันหรือหน้าจอที่ปลอดภัยอาจปรากฏเป็นว่างเปล่าหรือไม่สมบูรณ์',
        'web_live_browser_tip': 'เพื่อผลลัพธ์ที่ดีที่สุด ให้ใช้ Chrome เพื่อดูหน้าจอสด',
        'web_live_unmute_hint': 'แตะ "เปิดเสียง" เพื่อฟังเสียง เบราว์เซอร์จะเริ่มสตรีมสดแบบปิดเสียงไว้จนกว่าคุณจะอนุญาตให้ใช้เสียง',
        'web_live_stream_ended': 'สตรีมสิ้นสุดลงแล้ว',
        'web_live_fullscreen': 'เต็มหน้าจอ',
        'web_live_refresh': 'รีเฟรッシュ',
        'web_live_fit': 'พอดี',
        'web_live_fill': 'เต็ม',
        'web_live_mute': 'ปิดเสียง',
        'web_live_unmute': 'เปิดเสียง',
        'web_live_unsupported': 'เบราว์เซอร์นี้ไม่รองรับ WebRTC',
        'web_live_busy': 'มีเบราว์เซอร์อื่นกำลังดูหน้าจอสดนี้อยู่แล้ว',
        'web_live_pin_required': 'ต้องใช้ PIN เซสชันเพื่อเข้าชม',
        'sharing_blocked_by_live_screen': 'หยุดหน้าจอสดก่อนเริ่มเซสชันการแชร์ปกติ',
        'live_screen_blocked_by_sharing': 'หยุดเซสชันการแชร์ปัจจุบันก่อนเริ่มหน้าจอสด',
        'live_screen_pin_label': 'PIN เพื่อเข้าร่วม: %1$s',
        'live_screen_pin_hint': 'ผู้ชมจะถูกถามถึง PIN นี้ก่อนที่จะสามารถรับชมได้',
        'quick_text_blocked_by_live_screen': 'หยุดหน้าจอสดก่อนใช้ข้อความด่วน',
        'web_live_pin_entry_title': 'ใส่ PIN สด',
        'web_live_pin_entry_desc': 'ป้อน PIN ที่แสดงบนโทรศัพท์โฮสต์เพื่อเริ่มรับชม',
        'web_live_pin_entry_submit': 'เริ่มรับชม',
        'web_live_pin_entry_invalid': 'PIN นั้นไม่ตรงกัน ลองอีกครั้ง',
        'message_saved_share_ready': 'การแชร์ที่บันทึกไว้พร้อมแล้วพร้อม %1$d รายการ',
        'message_preparing_browser_playback': 'กำลังเตรียม %1$s เพื่อการเล่นเบราว์เซอร์ที่ราบรื่นยิ่งขึ้น'
    },
    'af': {
        'library_selection_step_2': 'Stap 2: Skep die gestoorde deel vanaf die %1$d geselekteerde lêers%2$s.',
        'home_feature_live_screen': 'Regstreekse skerm',
        'home_feature_live_screen_desc': 'Spieël jou foon se skerm na \'n blaaier op die plaaslike netwerk.',
        'home_feature_quick_text': 'Vinnige teks',
        'home_feature_quick_text_desc': 'Stuur teks of skakels na blaaiertoestelle naby.',
        'web_live_title': 'Regstreekse skerm',
        'web_live_waiting': 'Wag vir stroom',
        'web_live_status_live': 'Regstreeks',
        'web_live_status_starting': 'Begin tans',
        'web_live_status_stopped': 'Gestop',
        'web_live_status_connecting': 'Verbind tans',
        'web_live_status_waiting_viewer': 'Wag tans',
        'web_live_status_reconnecting': 'Verbind weer',
        'web_live_audio_live': 'Oudio regstreeks',
        'web_live_audio_unavailable': 'Oudio nie beskikbaar nie',
        'web_live_audio_blocked_or_silent': 'Oudio geblokkeer of stil',
        'web_live_audio_limit': 'Oudio is dalk nie beskikbaar vir sommige toepassings nie as gevolg van stelselbeperkings.',
        'web_live_capture_notice': 'Sommige toepassings blokkeer skermvaslegging, so beskermde video\'s of veilige skerms kan leeg of onvolledig verskyn.',
        'web_live_browser_tip': 'Vir die beste resultate, gebruik Chrome om die regstreekse skerm te kyk.',
        'web_live_unmute_hint': 'Tik op Ontdem om oudio te hoor. Blaaiers begin regstreekse strome gedemp totdat jy oudio toelaat.',
        'web_live_stream_ended': 'Stroom beëindig',
        'web_live_fullscreen': 'Volskerm',
        'web_live_refresh': 'Verfris',
        'web_live_fit': 'Pas',
        'web_live_fill': 'Vul',
        'web_live_mute': 'Demp',
        'web_live_unmute': 'Ontdem',
        'web_live_unsupported': 'WebRTC word nie in hierdie blaaier ondersteun nie.',
        'web_live_busy': '\'n Ander blaaier kyk reeds na hierdie regstreekse skerm.',
        'web_live_pin_required': '\'n Sessie-PIN word vereis om te kyk.',
        'sharing_blocked_by_live_screen': 'Stop Regstreekse skerm voordat u \'n normale deelsessie begin.',
        'live_screen_blocked_by_sharing': 'Stop die huidige deelsessie voordat u Regstreekse skerm begin.',
        'live_screen_pin_label': 'PIN om aan te sluit: %1$s',
        'live_screen_pin_hint': 'Kykers sal vir hierdie PIN gevra word voordat hulle kan kyk.',
        'quick_text_blocked_by_live_screen': 'Stop Regstreekse skerm voordat u Vinnige teks gebruik.',
        'web_live_pin_entry_title': 'Voer regstreekse PIN in',
        'web_live_pin_entry_desc': 'Voer die PIN in wat op die gasheerfoon gewys word om te begin kyk.',
        'web_live_pin_entry_submit': 'Begin kyk',
        'web_live_pin_entry_invalid': 'Daardie PIN het nie ooreengestem nie. Probeer weer.'
    },
    'ta': {
        'library_selection_step_2': 'படி 2: தேர்ந்தெடுக்கப்பட்ட %1$d கோப்புகளிலிருந்து%2$s சேமிக்கப்பட்ட பகிர்வை உருவாக்கவும்.',
        'home_feature_live_screen': 'நேரடி திரை',
        'home_feature_live_screen_desc': 'உங்கள் தொலைபேசி திரையை உள்ளூர் பிணையத்தில் உள்ள உலாவியில் பிரதிபலிக்கவும்.',
        'home_feature_quick_text': 'விரைவான உரை',
        'home_feature_quick_text_desc': 'அருகிலுள்ள உலாவி சாதனங்களுக்கு உரை அல்லது இணைப்புகளை அனுப்பவும்.',
        'web_live_title': 'நேரடி திரை',
        'web_live_waiting': 'ஸ்ட்ரீமிற்காக காத்திருக்கிறது',
        'web_live_status_live': 'நேரலை',
        'web_live_status_starting': 'தொடங்குகிறது',
        'web_live_status_stopped': 'நிறுத்தப்பட்டது',
        'web_live_status_connecting': 'இணைக்கிறது',
        'web_live_status_waiting_viewer': 'காத்திருக்கிறது',
        'web_live_status_reconnecting': 'மீண்டும் இணைக்கிறது',
        'web_live_audio_live': 'ஆடியோ நேரலை',
        'web_live_audio_unavailable': 'ஆடியோ கிடைக்கவில்லை',
        'web_live_audio_blocked_or_silent': 'ஆடியோ தடுக்கப்பட்டது அல்லது மவுனம்',
        'web_live_audio_limit': 'கணினி கட்டுப்பாடுகள் காரணமாக சில பயன்பாடுகளுக்கு ஆடியோ கிடைக்காமல் போகலாம்.',
        'web_live_capture_notice': 'சில பயன்பாடுகள் ஸ்கிரீன் கேப்சரைத் தடுக்கின்றன, எனவே பாதுகாக்கப்பட்ட வீடியோக்கள் அல்லது பாதுகாப்பான திரைகள் காலியாகவோ அல்லது முழுமையற்றதாகவோ தோன்றலாம்.',
        'web_live_browser_tip': 'சிறந்த முடிவுகளுக்கு, நேரடித் திரையைப் பார்க்க Chrome ஐப் பயன்படுத்தவும்.',
        'web_live_unmute_hint': 'ஆடியோவைக் கேட்க ஒலிநீக்கத்தைத் தட்டவும். நீங்கள் ஆடியோவை அனுமதிக்கும் வரை உலாவிகள் நேரலை ஸ்ட்ரீம்களை ஒலியடக்கத் தொடங்கும்.',
        'web_live_stream_ended': 'ஸ்ட்ரீம் முடிந்தது',
        'web_live_fullscreen': 'முழுத்திரை',
        'web_live_refresh': 'புதுப்பி',
        'web_live_fit': 'பொருத்து',
        'web_live_fill': 'நிரப்பு',
        'web_live_mute': 'ஒலியடக்கு',
        'web_live_unmute': 'ஒலிநீக்கு',
        'web_live_unsupported': 'இந்த உலாவியில் WebRTC ஆதரிக்கப்படவில்லை.',
        'web_live_busy': 'மற்றொரு உலாவி ஏற்கனவே இந்த நேரடித் திரையைப் பார்க்கிறது.',
        'web_live_pin_required': 'பார்க்க செஷன் பின் தேவை.',
        'sharing_blocked_by_live_screen': 'சாதாரண பகிர்வு அமர்வைத் தொடங்கும் முன் நேரடித் திரையை நிறுத்தவும்.',
        'live_screen_blocked_by_sharing': 'நேரடித் திரையைத் தொடங்கும் முன் தற்போதைய பகிர்வு அமர்வை நிறுத்தவும்.',
        'live_screen_pin_label': 'சேருவதற்கான PIN: %1$s',
        'live_screen_pin_hint': 'பார்வையாளர்கள் பார்ப்பதற்கு முன் இந்த PIN கேட்கப்படும்.',
        'quick_text_blocked_by_live_screen': 'விரைவான உரையைப் பயன்படுத்துவதற்கு முன் நேரடித் திரையை நிறுத்தவும்.',
        'web_live_pin_entry_title': 'நேரடி PIN ஐ உள்ளிடவும்',
        'web_live_pin_entry_desc': 'பார்க்கத் தொடங்க ஹோஸ்ட் போனில் காட்டப்படும் PIN ஐ உள்ளிடவும்.',
        'web_live_pin_entry_submit': 'பார்க்கத் தொடங்கு',
        'web_live_pin_entry_invalid': 'அந்த PIN பொருந்தவில்லை. மீண்டும் முயற்சிக்கவும்.'
    },
    'te': {
        'library_selection_step_2': 'దశ 2: ఎంచుకున్న %1$d ఫైల్‌ల%2$s నుండి సేవ్ చేసిన షేర్‌ను సృష్టించండి.',
        'home_feature_live_screen': 'లైవ్ స్క్రీన్',
        'home_feature_live_screen_desc': 'స్థానిక నెట్‌వర్క్‌లోని బ్రౌజర్‌కు మీ ఫోన్ స్క్రీన్‌ను మిర్రర్ చేయండి.',
        'home_feature_quick_text': 'త్వరిత వచనం',
        'home_feature_quick_text_desc': 'సమీపంలోని బ్రౌజర్ పరికరాలకు వచనం లేదా లింక్‌లను పంపండి.',
        'web_live_title': 'లైవ్ స్క్రీన్',
        'web_live_waiting': 'స్ట్రీమ్ కోసం వేచి ఉంది',
        'web_live_status_live': 'లైవ్',
        'web_live_status_starting': 'ప్రారంభమవుతోంది',
        'web_live_status_stopped': 'ఆగిపోయింది',
        'web_live_status_connecting': 'కనెక్ట్ అవుతోంది',
        'web_live_status_waiting_viewer': 'వేచి ఉంది',
        'web_live_status_reconnecting': 'మళ్ళీ కనెక్ట్ అవుతోంది',
        'web_live_audio_live': 'ఆడియో లైవ్',
        'web_live_audio_unavailable': 'ఆడియో అందుబాటులో లేదు',
        'web_live_audio_blocked_or_silent': 'ఆడియో బ్లాక్ చేయబడింది లేదా నిశ్శబ్దంగా ఉంది',
        'web_live_audio_limit': 'సిస్టమ్ పరిమితుల కారణంగా కొన్ని యాప్‌లకు ఆడియో అందుబాటులో ఉండకపోవచ్చు.',
        'web_live_capture_notice': 'కొన్ని యాప్‌లు స్క్రీన్ క్యాప్చర్‌ని బ్లాక్ చేస్తాయి, కాబట్టి రక్షిత వీడియోలు లేదా సురక్షిత స్క్రీన్‌లు ఖాళీగా లేదా అసంపూర్తిగా కనిపించవచ్చు.',
        'web_live_browser_tip': 'ఉత్తమ ఫలితాల కోసం, లైవ్ స్క్రీన్‌ని చూడటానికి Chromeని ఉపయోగించండి.',
        'web_live_unmute_hint': 'ఆడియో వినడానికి అన్‌మ్యూట్ నొక్కండి. మీరు ఆడియోను అనుమతించే వరకు బ్రౌజర్‌లు లైవ్ స్ట్రీమ్‌లను మ్యూట్ మోడ్‌లో ప్రారంభిస్తాయి.',
        'web_live_stream_ended': 'స్ట్రీమ్ ముగిసింది',
        'web_live_fullscreen': 'పూర్తి స్క్రీన్',
        'web_live_refresh': 'రిఫ్రెష్',
        'web_live_fit': 'ఫిట్',
        'web_live_fill': 'ఫిల్',
        'web_live_mute': 'మ్యూట్',
        'web_live_unmute': 'అన్‌మ్యూట్',
        'web_live_unsupported': 'ఈ బ్రౌజర్‌లో WebRTC సపోర్ట్ చేయబడదు.',
        'web_live_busy': 'మరో బ్రౌజర్ ఇప్పటికే ఈ లైవ్ స్క్రీన్‌ని చూస్తోంది.',
        'web_live_pin_required': 'చూడటానికి సెషన్ పిన్ అవసరం.',
        'sharing_blocked_by_live_screen': 'సాధారణ భాగస్వామ్య సెషన్‌ను ప్రారంభించే ముందు లైవ్ స్క్రీన్‌ను ఆపివేయండి.',
        'live_screen_blocked_by_sharing': 'లైవ్ స్క్రీన్‌ను ప్రారంభించే ముందు ప్రస్తుత భాగస్వామ్య సెషన్‌ను ఆపివేయండి.',
        'live_screen_pin_label': 'చేరడానికి PIN: %1$s',
        'live_screen_pin_hint': 'వీక్షకులు చూడటానికి ముందు ఈ PIN అడగబడుతుంది.',
        'quick_text_blocked_by_live_screen': 'త్వరిత వచనాన్ని ఉపయోగించే ముందు లైవ్ స్క్రీన్‌ను ఆపివేయండి.',
        'web_live_pin_entry_title': 'లైవ్ PIN నమోదు చేయండి',
        'web_live_pin_entry_desc': 'చూడటం ప్రారంభించడానికి హోస్ట్ ఫోన్‌లో చూపిన PINని నమోదు చేయండి.',
        'web_live_pin_entry_submit': 'చూడటం ప్రారంభించండి',
        'web_live_pin_entry_invalid': 'ఆ PIN సరిపోలలేదు. మళ్ళీ ప్రయత్నించండి.'
    },
    'ml': {
        'library_selection_step_2': 'ഘട്ടം 2: തിരഞ്ഞെടുത്ത %1$d ഫയലുകളിൽ%2$s നിന്ന് സംരക്ഷിച്ച ഷെയർ സൃഷ്ടിക്കുക.',
        'home_feature_live_screen': 'ലൈവ് സ്ക്രീൻ',
        'home_feature_live_screen_desc': 'ലോക്കൽ നെറ്റ്‌വർക്കിലെ ബ്രൗസറിലേക്ക് നിങ്ങളുടെ ഫോൺ സ്ക്രീൻ മിറർ ചെയ്യുക.',
        'home_feature_quick_text': 'ക്വിക്ക് ടെക്സ്റ്റ്',
        'home_feature_quick_text_desc': 'സമീപത്തുള്ള ബ്രൗസർ ഉപകരണങ്ങളിലേക്ക് ടെക്സ്റ്റ് അല്ലെങ്കിൽ ലിങ്കുകൾ അയയ്ക്കുക.',
        'web_live_title': 'ലൈവ് സ്ക്രീൻ',
        'web_live_waiting': 'സ്ട്രീമിനായി കാത്തിരിക്കുന്നു',
        'web_live_status_live': 'ലൈവ്',
        'web_live_status_starting': 'ആരംഭിക്കുന്നു',
        'web_live_status_stopped': 'നിർത്തിയിരിക്കുന്നു',
        'web_live_status_connecting': 'ബന്ധിപ്പിക്കുന്നു',
        'web_live_status_waiting_viewer': 'കാത്തിരിക്കുന്നു',
        'web_live_status_reconnecting': 'വീണ്ടും ബന്ധിപ്പിക്കുന്നു',
        'web_live_audio_live': 'ഓഡിയോ ലൈവ്',
        'web_live_audio_unavailable': 'ഓഡിയോ ലഭ്യമല്ല',
        'web_live_audio_blocked_or_silent': 'ഓഡിയോ തടയപ്പെട്ടു അല്ലെങ്കിൽ നിശബ്ദമാണ്',
        'web_live_audio_limit': 'സിസ്റ്റം നിയന്ത്രണങ്ങൾ കാരണം ചില ആപ്പുകൾക്ക് ഓഡിയോ ലഭ്യമായേക്കില്ല.',
        'web_live_capture_notice': 'ചില ആപ്പുകൾ സ്ക്രീൻ ക്യാപ്‌ചർ ബ്ലോക്ക് ചെയ്യുന്നു, അതിനാൽ സംരക്ഷിത വീഡിയോകളോ സുരക്ഷിത സ്ക്രീനുകളോ ശൂന്യമായോ അപൂർണ്ണമായോ ദൃശ്യമായേക്കാം.',
        'web_live_browser_tip': 'മികച്ച ഫലങ്ങൾക്കായി, ലൈവ് സ്ക്രീൻ കാണുന്നതിന് Chrome ഉപയോഗിക്കുക.',
        'web_live_unmute_hint': 'ഓഡിയോ കേൾക്കുന്നതിന് അൺമ്യൂട്ട് ടാപ്പ് ചെയ്യുക. നിങ്ങൾ ഓഡിയോ അനുവദിക്കുന്നത് വരെ ബ്രൗസറുകൾ ലൈവ് സ്ട്രീമുകൾ മ്യൂട്ട് ചെയ്തായിരിക്കും ആരംഭിക്കുന്നത്.',
        'web_live_stream_ended': 'സ്ട്രീം അവസാനിച്ചു',
        'web_live_fullscreen': 'ഫുൾ സ്ക്രീൻ',
        'web_live_refresh': 'പുതുക്കുക',
        'web_live_fit': 'ഫിറ്റ്',
        'web_live_fill': 'ഫിൽ',
        'web_live_mute': 'മ്യൂട്ട്',
        'web_live_unmute': 'അൺമ്യൂട്ട്',
        'web_live_unsupported': 'ഈ ബ്രൗസറിൽ WebRTC പിന്തുണയ്ക്കുന്നില്ല.',
        'web_live_busy': 'മറ്റൊരു ബ്രൗസർ ഇതിനകം ഈ ലൈവ് സ്ക്ρίൻ കാണുന്നുണ്ട്.',
        'web_live_pin_required': 'കാണുന്നതിന് സെഷൻ പിൻ ആവശ്യമാണ്.',
        'sharing_blocked_by_live_screen': 'സാധാരണ പങ്കിടൽ സെഷൻ ആരംഭിക്കുന്നതിന് മുമ്പ് ലൈവ് സ്ക്രീൻ നിർത്തുക.',
        'live_screen_blocked_by_sharing': 'ലൈവ് സ്ക്രീൻ ആരംഭിക്കുന്നതിന് മുമ്പ് നിലവിലെ പങ്കിടൽ സെഷൻ നിർത്തുക.',
        'live_screen_pin_label': 'ചേരാനുള്ള PIN: %1$s',
        'live_screen_pin_hint': 'കാണുന്നതിന് മുമ്പ് കാഴ്ചക്കാരോട് ഈ PIN ആവശ്യപ്പെടും.',
        'quick_text_blocked_by_live_screen': 'ക്വിക്ക് ടെക്സ്റ്റ് ഉപയോഗിക്കുന്നതിന് മുമ്പ് ലൈവ് സ്ക്രീൻ നിർത്തുക.',
        'web_live_pin_entry_title': 'ലൈവ് PIN നൽകുക',
        'web_live_pin_entry_desc': 'കാണാൻ തുടങ്ങുന്നതിന് ഹോസ്റ്റ് ഫോണിൽ കാണിച്ചിരിക്കുന്ന PIN നൽകുക.',
        'web_live_pin_entry_submit': 'കാണാൻ തുടങ്ങുക',
        'web_live_pin_entry_invalid': 'ആ PIN പൊരുത്തപ്പെടുന്നില്ല. വീണ്ടും ശ്രമിക്കുക.'
    },
    'fr': {
        'library_selection_step_2': 'Étape 2 : Créer le partage enregistré à partir des %1$d fichiers sélectionnés%2$s.',
        'home_feature_live_screen': 'Écran en direct',
        'home_feature_live_screen_desc': 'Diffusez l\'écran de votre téléphone sur un navigateur du réseau local.',
        'home_feature_quick_text': 'Texte rapide',
        'home_feature_quick_text_desc': 'Envoyez du texte ou des liens vers des navigateurs à proximité.',
        'web_live_title': 'Écran en direct',
        'web_live_waiting': 'En attente du flux',
        'web_live_status_live': 'En direct',
        'web_live_status_starting': 'Démarrage',
        'web_live_status_stopped': 'Arrêté',
        'web_live_status_connecting': 'Connexion',
        'web_live_status_waiting_viewer': 'En attente',
        'web_live_status_reconnecting': 'Reconnexion',
        'web_live_audio_live': 'Audio en vivo',
        'web_live_audio_unavailable': 'Audio indisponible',
        'web_live_audio_blocked_or_silent': 'Audio bloqué ou muet',
        'web_live_audio_limit': 'L\'audio peut ne pas être disponible pour certaines applications en raison des restrictions du système.',
        'web_live_capture_notice': 'Certaines applications bloquent la capture d\'écran, les vidéos protégées ou les écrans sécurisés peuvent donc apparaître vides ou incomplets.',
        'web_live_browser_tip': 'Pour de meilleurs résultats, utilisez Chrome pour voir l\'écran en direct.',
        'web_live_unmute_hint': 'Appuyez sur Réactiver le son pour entendre l\'audio. Les navigateurs démarrent les flux en sourdine jusqu\'à ce que vous autorisiez le son.',
        'web_live_stream_ended': 'Flux terminé',
        'web_live_fullscreen': 'Plein écran',
        'web_live_refresh': 'Actualiser',
        'web_live_fit': 'Ajuster',
        'web_live_fill': 'Remplir',
        'web_live_mute': 'Sourdine',
        'web_live_unmute': 'Réactiver le son',
        'web_live_unsupported': 'WebRTC n\'est pas supporté par ce navigateur.',
        'web_live_busy': 'Un autre navigateur consulte déjà cet écran en direct.',
        'web_live_pin_required': 'Un code PIN de session est requis avant de visionner.',
        'sharing_blocked_by_live_screen': 'Arrêtez l\'écran en direct avant de démarrer une session de partage normale.',
        'live_screen_blocked_by_sharing': 'Arrêtez la session de partage actuelle avant de démarrer l\'écran en direct.',
        'live_screen_pin_label': 'Code PIN pour rejoindre : %1$s',
        'live_screen_pin_hint': 'Les spectateurs devront saisir ce code PIN avant de pouvoir regarder.',
        'quick_text_blocked_by_live_screen': 'Arrêtez l\'écran en direct avant d\'utiliser le texte rapide.',
        'web_live_pin_entry_title': 'Saisissez le code PIN',
        'web_live_pin_entry_desc': 'Saisissez le code PIN affiché sur le téléphone hôte pour commencer à regarder.',
        'web_live_pin_entry_submit': 'Commencer à regarder',
        'web_live_pin_entry_invalid': 'Ce code PIN ne correspond pas. Réessayez.'
    },
    'de': {
        'library_selection_step_2': 'Schritt 2: Erstellen Sie die gespeicherte Freigabe aus den %1$d ausgewählten Dateien%2$s.',
        'home_feature_live_screen': 'Live-Bildschirm',
        'home_feature_live_screen_desc': 'Spiegeln Sie Ihren Telefonbildschirm in einem Browser über Ihr lokales Netzwerk.',
        'home_feature_quick_text': 'Schnelltext',
        'home_feature_quick_text_desc': 'Senden Sie Text oder Links an Browsergeräte in der Nähe.',
        'web_live_title': 'Live-Bildschirm',
        'web_live_waiting': 'Warten auf Stream',
        'web_live_status_live': 'Live',
        'web_live_status_starting': 'Startet',
        'web_live_status_stopped': 'Gestoppt',
        'web_live_status_connecting': 'Verbinden',
        'web_live_status_waiting_viewer': 'Warten',
        'web_live_status_reconnecting': 'Wiederverbinden',
        'web_live_audio_live': 'Audio live',
        'web_live_audio_unavailable': 'Audio nicht verfügbar',
        'web_live_audio_blocked_or_silent': 'Audio blockiert oder stumm',
        'web_live_audio_limit': 'Audio ist für einige Apps aufgrund von Systemeinschränkungen möglicherweise nicht verfügbar.',
        'web_live_capture_notice': 'Einige Apps blockieren die Bildschirmaufnahme, daher können geschützte Videos oder sichere Bildschirme leer oder unvollständig erscheinen.',
        'web_live_browser_tip': 'Für beste Ergebnisse verwenden Sie Chrome zum Ansehen des Live-Bildschirms.',
        'web_live_unmute_hint': 'Tippen Sie auf Ton einschalten, um Audio zu hören. Browser starten Live-Streams stummgeschaltet, bis Sie Ton zulassen.',
        'web_live_stream_ended': 'Stream beendet',
        'web_live_fullscreen': 'Vollbild',
        'web_live_refresh': 'Aktualisieren',
        'web_live_fit': 'Anpassen',
        'web_live_fill': 'Füllen',
        'web_live_mute': 'Stumm',
        'web_live_unmute': 'Ton einschalten',
        'web_live_unsupported': 'WebRTC wird in diesem Browser nicht unterstützt.',
        'web_live_busy': 'Ein anderer Browser zeigt diesen Live-Bildschirm bereits an.',
        'web_live_pin_required': 'Ein Sitzungs-PIN ist zum Ansehen erforderlich.',
        'sharing_blocked_by_live_screen': 'Stoppen Sie den Live-Bildschirm, bevor Sie eine normale Freigabesitzung starten.',
        'live_screen_blocked_by_sharing': 'Stoppen Sie die aktuelle Freigabesitzung, bevor Sie den Live-Bildschirm starten.',
        'live_screen_pin_label': 'PIN zum Beitritt: %1$s',
        'live_screen_pin_hint': 'Zuschauer werden nach dieser PIN gefragt, bevor sie zusehen können.',
        'quick_text_blocked_by_live_screen': 'Stoppen Sie den Live-Bildschirm, bevor Sie Schnelltext verwenden.',
        'web_live_pin_entry_title': 'Live-PIN eingeben',
        'web_live_pin_entry_desc': 'Geben Sie die auf dem Host-Telefon angezeigte PIN ein, um mit dem Zuschauen zu beginnen.',
        'web_live_pin_entry_submit': 'Zuschauen starten',
        'web_live_pin_entry_invalid': 'Diese PIN stimmte nicht überein. Versuchen Sie es erneut.'
    },
    'it': {
        'library_selection_step_2': 'Passaggio 2: Crea la condivisione salvata dai %1$d file selezionati%2$s.',
        'home_feature_live_screen': 'Schermo dal vivo',
        'home_feature_live_screen_desc': 'Duplica lo schermo del tuo telefono su un browser della rete locale.',
        'home_feature_quick_text': 'Testo rapido',
        'home_feature_quick_text_desc': 'Invia testo o link ai dispositivi browser nelle vicinanze.',
        'web_live_title': 'Schermo dal vivo',
        'web_live_waiting': 'In attesa del flusso',
        'web_live_status_live': 'Dal vivo',
        'web_live_status_starting': 'Avvio',
        'web_live_status_stopped': 'Interrotto',
        'web_live_status_connecting': 'Connessione',
        'web_live_status_waiting_viewer': 'In attesa',
        'web_live_status_reconnecting': 'Riconnessione',
        'web_live_audio_live': 'Audio dal vivo',
        'web_live_audio_unavailable': 'Audio non disponibile',
        'web_live_audio_blocked_or_silent': 'Audio bloccato o muto',
        'web_live_audio_limit': 'L\'audio potrebbe non essere disponibile per alcune app a causa delle restrizioni di sistema.',
        'web_live_capture_notice': 'Alcune app bloccano la cattura dello schermo, quindi i video protetti o le schermate sicure potrebbero apparire vuoti o incompleti.',
        'web_live_browser_tip': 'Per risultati migliori, usa Chrome per vedere lo schermo dal vivo.',
        'web_live_unmute_hint': 'Tocca Riattiva audio per ascoltare l\'audio. I browser avviano i flussi dal vivo silenziati finché non consenti l\'audio.',
        'web_live_stream_ended': 'Flusso terminato',
        'web_live_fullscreen': 'Schermo intero',
        'web_live_refresh': 'Aggiorna',
        'web_live_fit': 'Adatta',
        'web_live_fill': 'Riempi',
        'web_live_mute': 'Muto',
        'web_live_unmute': 'Riattiva audio',
        'web_live_unsupported': 'WebRTC non è supportato da questo browser.',
        'web_live_busy': 'Un altro browser sta già visualizzando questo schermo dal vivo.',
        'web_live_pin_required': 'È richiesto un PIN di sessione per la visualizzazione.',
        'sharing_blocked_by_live_screen': 'Interrompi lo schermo dal vivo prima di avviare una normale sessione di condivisione.',
        'live_screen_blocked_by_sharing': 'Interrompi la sessione di condivisione corrente prima di avviare lo schermo dal vivo.',
        'live_screen_pin_label': 'PIN per partecipare: %1$s',
        'live_screen_pin_hint': 'Agli spettatori verrà chiesto questo PIN prima di poter guardare.',
        'quick_text_blocked_by_live_screen': 'Interrompi lo schermo dal vivo prima di utilizzare Testo rapido.',
        'web_live_pin_entry_title': 'Inserisci il PIN',
        'web_live_pin_entry_desc': 'Inserisci il PIN mostrato sul telefono host per iniziare a guardare.',
        'web_live_pin_entry_submit': 'Inizia a guardare',
        'web_live_pin_entry_invalid': 'Il PIN non corrisponde. Riprova.'
    },
    'pt': {
        'library_selection_step_2': 'Passo 2: Criar a partilha guardada a partir dos %1$d ficheiros selecionados%2$s.',
        'home_feature_live_screen': 'Ecrã em tempo real',
        'home_feature_live_screen_desc': 'Espelhe o ecrã do seu telemóvel num navegador da rede local.',
        'home_feature_quick_text': 'Texto rápido',
        'home_feature_quick_text_desc': 'Envie texto ou hiperligações para dispositivos com navegador próximos.',
        'web_live_title': 'Ecrã em tempo real',
        'web_live_waiting': 'A aguardar transmissão',
        'web_live_status_live': 'Em direto',
        'web_live_status_starting': 'A iniciar',
        'web_live_status_stopped': 'Parado',
        'web_live_status_connecting': 'A ligar',
        'web_live_status_waiting_viewer': 'A aguardar',
        'web_live_status_reconnecting': 'A religar',
        'web_live_audio_live': 'Áudio em direto',
        'web_live_audio_unavailable': 'Áudio indisponível',
        'web_live_audio_blocked_or_silent': 'Áudio bloqueado ou silenciado',
        'web_live_audio_limit': 'O áudio pode não estar disponível para algumas aplicações devido a restrições do sistema.',
        'web_live_capture_notice': 'Algumas aplicações bloqueiam a captura de ecrã, pelo que vídeos protegidos ou ecrãs seguros podem aparecer vazios ou incompletos.',
        'web_live_browser_tip': 'Para melhores resultados, use o Chrome para ver o Ecrã em tempo real.',
        'web_live_unmute_hint': 'Toque em Ativar som para ouvir o áudio. Os navegadores iniciam as transmissões em direto silenciadas até permitir o som.',
        'web_live_stream_ended': 'Transmissão terminada',
        'web_live_fullscreen': 'Ecrã inteiro',
        'web_live_refresh': 'Atualizar',
        'web_live_fit': 'Ajustar',
        'web_live_fill': 'Preencher',
        'web_live_mute': 'Silenciar',
        'web_live_unmute': 'Ativar som',
        'web_live_unsupported': 'WebRTC não é suportado por este navegador.',
        'web_live_busy': 'Outro navegador já está a ver este ecrã em tempo real.',
        'web_live_pin_required': 'É necessário um PIN de sessão para ver.',
        'sharing_blocked_by_live_screen': 'Interrompa o Ecrã em Tempo Real antes de iniciar uma sessão de partilha normal.',
        'live_screen_blocked_by_sharing': 'Interrompa a sessão de partilha atual antes de iniciar o Ecrã em Tempo Real.',
        'live_screen_pin_label': 'PIN para aderir: %1$s',
        'live_screen_pin_hint': 'Será pedido este PIN aos espectadores antes de poderem assistir.',
        'quick_text_blocked_by_live_screen': 'Interrompa o Ecrã em Tempo Real antes de utilizar o Texto Rápido.',
        'web_live_pin_entry_title': 'Introduza o PIN em direto',
        'web_live_pin_entry_desc': 'Introduza o PIN apresentado no telemóvel anfitrião para começar a assistir.',
        'web_live_pin_entry_submit': 'Começar a assistir',
        'web_live_pin_entry_invalid': 'O PIN não coincide. Tente novamente.'
    },
    'pt-rBR': {
        'library_selection_step_2': 'Passo 2: Criar o compartilhamento salvo a partir dos %1$d arquivos selecionados%2$s.',
        'home_feature_live_screen': 'Tela ao vivo',
        'home_feature_live_screen_desc': 'Espelhe a tela do seu celular em um navegador da rede local.',
        'home_feature_quick_text': 'Texto rápido',
        'home_feature_quick_text_desc': 'Envie texto ou links para dispositivos com navegador próximos.',
        'web_live_title': 'Tela ao vivo',
        'web_live_waiting': 'Aguardando transmissão',
        'web_live_status_live': 'Ao vivo',
        'web_live_status_starting': 'Iniciando',
        'web_live_status_stopped': 'Parado',
        'web_live_status_connecting': 'Conectando',
        'web_live_status_waiting_viewer': 'Aguardando',
        'web_live_status_reconnecting': 'Reconectando',
        'web_live_audio_live': 'Áudio ao vivo',
        'web_live_audio_unavailable': 'Áudio indisponível',
        'web_live_audio_blocked_or_silent': 'Áudio bloqueado ou silencioso',
        'web_live_audio_limit': 'O áudio pode não estar disponível para alguns aplicativos devido a restrições do sistema.',
        'web_live_capture_notice': 'Alguns aplicativos bloqueiam a captura de tela, portanto vídeos protegidos ou telas seguras podem aparecer vazios ou incompletos.',
        'web_live_browser_tip': 'Para melhores resultados, use o Chrome para ver a Tela ao vivo.',
        'web_live_unmute_hint': 'Toque em Ativar som para ouvir o áudio. Os navegadores iniciam as transmissões ao vivo silenciadas até permitir o som.',
        'web_live_stream_ended': 'Transmissão terminada',
        'web_live_fullscreen': 'Tela cheia',
        'web_live_refresh': 'Atualizar',
        'web_live_fit': 'Ajustar',
        'web_live_fill': 'Preencher',
        'web_live_mute': 'Silenciar',
        'web_live_unmute': 'Ativar som',
        'web_live_unsupported': 'WebRTC não é suportado por este navegador.',
        'web_live_busy': 'Outro navegador já está vendo esta tela ao vivo.',
        'web_live_pin_required': 'Um PIN de sessão é necessário para ver.',
        'sharing_blocked_by_live_screen': 'Interrompa a tela ao vivo antes de iniciar uma sessão de compartilhamento normal.',
        'live_screen_blocked_by_sharing': 'Interrompa a sessão de compartilhamento atual antes de iniciar a tela ao vivo.',
        'live_screen_pin_label': 'PIN para participar: %1$s',
        'live_screen_pin_hint': 'Os espectadores deverão inserir este PIN antes de poderem assistir.',
        'quick_text_blocked_by_live_screen': 'Interrompa a tela ao vivo antes de usar o Texto Rápido.',
        'web_live_pin_entry_title': 'Digite o PIN ao vivo',
        'web_live_pin_entry_desc': 'Digite o PIN exibido no telefone host para começar a assistir.',
        'web_live_pin_entry_submit': 'Começar a assistir',
        'web_live_pin_entry_invalid': 'Esse PIN não coincide. Tente novamente.'
    },
}

def fix_locale(locale_name, base_res_path):
    # 1. Sync structure first (this also handles escaping)
    loc_sync.sync_locale(locale_name, base_res_path)
    
    locale_path = os.path.join(base_res_path, f'values-{locale_name}', 'strings.xml')
    if not os.path.exists(locale_path):
        return

    # 2. Parse English for order
    en_path = os.path.join(base_res_path, 'values', 'strings.xml')
    tree_en = ET.parse(en_path)
    root_en = tree_en.getroot()
    
    # 3. Parse current Locale (after sync)
    tree_loc = ET.parse(locale_path)
    root_loc = tree_loc.getroot()
    loc_data = {}
    for child in root_loc:
        name = child.get('name')
        if child.tag == 'string':
            loc_data[name] = child.text
        elif child.tag == 'plurals':
            items = {}
            for item in child:
                items[item.get('quantity')] = item.text
            loc_data[name] = items

    # 4. Create new root to preserve order and inject fixes
    new_root = ET.Element('resources')
    data = TRANSLATIONS.get(locale_name, {})
    
    for child_en in root_en:
        name = child_en.get('name')
        tag = child_en.tag
        
        # Determine value (Fix > Existing > English)
        if name in data:
            val = data[name]
        elif name in loc_data:
            val = loc_data[name]
        else:
            # English fallback
            if tag == 'string':
                val = child_en.text
            else:
                val = {item.get('quantity'): item.text for item in child_en}

        # Create element
        if tag == 'string':
            el = ET.SubElement(new_root, 'string', name=name)
            el.text = loc_sync.escape_android_string(val) if isinstance(val, str) else val
        else:
            el = ET.SubElement(new_root, 'plurals', name=name)
            if isinstance(val, dict):
                for q, t in val.items():
                    item = ET.SubElement(el, 'item', quantity=q)
                    item.text = loc_sync.escape_android_string(t)
            else:
                # Fallback if somehow it wasn't a dict
                for item_en in child_en:
                    item = ET.SubElement(el, 'item', quantity=item_en.get('quantity'))
                    item.text = loc_sync.escape_android_string(item_en.text)

    # 5. Save with pretty print
    xml_str = ET.tostring(new_root, encoding='utf-8')
    pretty_xml = minidom.parseString(xml_str).toprettyxml(indent="    ")
    
    with open(locale_path, "w", encoding="utf-8") as f:
        f.write(pretty_xml)
    print(f"Fixed {locale_name}")

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    res_path = os.path.join(base_dir, 'core', 'resources', 'src', 'main', 'res')
    for loc in ['es', 'fr', 'de', 'it', 'pt', 'pt-rBR', 'ar', 'hi', 'ru', 'ja', 'zh-rCN', 'zh-rTW', 'ko', 'nl', 'sv', 'el', 'tr', 'id', 'in', 'vi', 'th', 'af', 'ta', 'te', 'ml']:
        fix_locale(loc, res_path)
