import os
import xml.etree.ElementTree as ET

def rebuild_locale(res_dir, locale_name, translation_dict):
    base_path = os.path.join(res_dir, "values", "strings.xml")
    target_dir = os.path.join(res_dir, f"values-{locale_name}")
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)
        
    target_path = os.path.join(target_dir, "strings.xml")
    tree = ET.parse(base_path)
    root = tree.getroot()
    new_root = ET.Element('resources')
    
    for child in root:
        if child.tag == 'string':
            name = child.get('name')
            translatable = child.get('translatable', 'true')
            new_node = ET.SubElement(new_root, 'string', {'name': name})
            if translatable == 'false':
                new_node.set('translatable', 'false')
                new_node.text = child.text
            else:
                val = translation_dict.get(name)
                new_node.text = val if val else child.text
        elif child.tag == 'plurals':
            name = child.get('name')
            new_node = ET.SubElement(new_root, 'plurals', {'name': name})
            plural_data = translation_dict.get(f"plural:{name}", {})
            for item in child:
                qty = item.get('quantity')
                new_item = ET.SubElement(new_node, 'item', {'quantity': qty})
                val = plural_data.get(qty)
                new_item.text = val if val else item.text
        elif child.tag == 'string-array':
            name = child.get('name')
            new_node = ET.SubElement(new_root, 'string-array', {'name': name})
            array_data = translation_dict.get(f"array:{name}", [])
            for i, item in enumerate(child):
                new_item = ET.SubElement(new_node, 'item')
                if i < len(array_data):
                    new_item.text = array_data[i]
                else:
                    new_item.text = item.text

    ET.indent(new_root, space="    ", level=0)
    rough_string = ET.tostring(new_root, encoding='utf-8').decode('utf-8')
    with open(target_path, 'w', encoding='utf-8') as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n')
        f.write(rough_string)

# INDONESIAN (id)
id_data = {
    "common_back": "Kembali", "common_cancel": "Batal", "common_save": "Simpan", "common_delete": "Hapus",
    "common_open": "Buka", "common_refresh": "Segarkan", "common_continue": "Lanjut", "common_accept": "Terima",
    "common_decline": "Tolak", "common_dismiss": "Tutup", "common_remove": "Hapus", "common_search": "Cari",
    "common_separator_pipe": " | ", "common_separator_dot": " • ", "onboarding_skip": "Lewati",
    "onboarding_title": "DirectServe",
    "onboarding_subtitle": "Ubah ponsel Anda menjadi hub lokal untuk TV dan PC.",
    "onboarding_page_1_title": "Tonton di layar mana saja",
    "onboarding_page_1_description": "Buka video dan foto di TV tanpa mengunggah ke cloud.",
    "onboarding_page_2_title": "Berfungsi di semua layar",
    "onboarding_page_2_description": "Akses dari browser perangkat apa pun.",
    "onboarding_page_3_title": "Akses dari Browser",
    "onboarding_page_3_description": "Gunakan tautan lokal atau kode QR.",
    "onboarding_page_4_title": "Berbagi dua arah",
    "onboarding_page_4_description": "Kirim dan terima file dengan mudah.",
    "onboarding_page_5_title": "Tanpa internet",
    "onboarding_page_5_description": "Berfungsi melalui Wi-Fi atau hotspot Anda.",
    "onboarding_page_6_title": "Privasi terjaga",
    "onboarding_page_6_description": "File tetap di ponsel Anda.",
    "onboarding_page_counter": "%1$d / %2$d", "onboarding_next": "Berikutnya", "onboarding_get_started": "Mulai",
    "settings_title": "Pengaturan", "settings_subtitle": "Sesuaikan DirectServe.",
    "settings_group_general": "Umum", "settings_group_notifications": "Notifikasi", "settings_group_privacy": "Privasi",
    "settings_group_browser": "Browser", "settings_group_advanced": "Lanjutan", "settings_group_network": "Jaringan",
    "settings_group_help": "Bantuan", "settings_group_debug": "Debug", "settings_language": "Bahasa",
    "settings_theme": "Tema", "settings_theme_subtitle": "Pilih tampilan", "settings_theme_system": "Sistem",
    "settings_theme_dark": "Gelap", "settings_theme_light": "Terang", "settings_keep_screen_awake": "Biarkan layar menyala",
    "settings_keep_screen_awake_desc": "Mencegah layar mati saat berbagi.",
    "settings_vibrate_on_connect": "Getar saat terhubung", "settings_vibrate_on_connect_desc": "Getar saat ada yang bergabung.",
    "settings_show_speed": "Tampilkan kecepatan", "settings_show_speed_desc": "Kecepatan transfer langsung.",
    "settings_show_recent_shares": "Tampilkan riwayat", "settings_show_recent_shares_desc": "Simpan riwayat berbagi.",
    "settings_auto_stop": "Berhenti Otomatis", "settings_auto_stop_never": "Tidak pernah", "settings_auto_stop_15m": "15 menit",
    "settings_auto_stop_30m": "30 menit", "settings_auto_stop_1h": "1 jam", "settings_connection_alerts": "Peringatan koneksi",
    "settings_connection_alerts_desc": "Beri tahu saat perangkat terhubung.",
    "settings_download_alerts": "Peringatan unduhan", "settings_download_alerts_desc": "Beri tahu saat file diunduh.",
    "settings_upload_requests": "Permintaan unggahan", "settings_upload_requests_desc": "Tanyakan sebelum menerima file.",
    "settings_quick_text_enabled": "Teks Cepat", "settings_quick_text_enabled_desc": "Bagikan pesan teks.",
    "settings_quick_text_alerts": "Peringatan pesan", "settings_quick_text_alerts_desc": "Beri tahu saat ada pesan.",
    "settings_use_pin": "Gunakan PIN", "settings_use_pin_desc": "Minta PIN untuk akses.",
    "settings_new_pin_each_time": "PIN baru setiap saat", "settings_new_pin_each_time_desc": "PIN acak untuk keamanan.",
    "settings_pin_label": "PIN", "settings_pin_placeholder": "4-6 angka", "settings_approve_file_uploads": "Setujui unggahan",
    "settings_approve_file_uploads_desc": "Minta izin sebelum file diunggah.",
    "settings_approve_per_device": "Setujui per perangkat", "settings_approve_per_device_desc": "Setujui sekali saja per perangkat.",
    "settings_received_files_location": "Folder unduhan", "settings_received_files_location_value": "Unduhan",
    "settings_show_thumbnails": "Tampilkan thumbnail", "settings_show_thumbnails_desc": "Pratinjau untuk media.",
    "settings_large_tv_layout": "Tata Letak TV", "settings_large_tv_layout_desc": "Tombol lebih besar.",
    "settings_highlight_downloads": "Sorot unduhan", "settings_highlight_downloads_desc": "Tombol unduh lebih jelas.",
    "settings_sign_out_on_stop": "Keluar saat berhenti", "settings_sign_out_on_stop_desc": "Hapus akses saat sesi berakhir.",
    "settings_clear_temporary_files": "Hapus file sementara", "settings_clear_temporary_files_desc": "Bersihkan video yang dioptimalkan.",
    "settings_prevent_downloads": "Cegah unduhan", "settings_prevent_downloads_desc": "Hanya izinkan menonton.",
    "settings_auto_optimize_library": "Optimasi latar belakang", "settings_auto_optimize_library_desc": "Menguras baterai.",
    "settings_sharing_port": "Port", "settings_sharing_port_placeholder": "43183",
    "settings_sharing_port_help": "Jangan diubah jika tidak yakin.",
    "settings_wifi_settings": "Pengaturan Wi-Fi", "settings_wifi_settings_desc": "Gunakan jaringan yang sama.",
    "settings_hotspot_settings": "Pengaturan Hotspot", "settings_hotspot_settings_desc": "Buat jaringan lokal sendiri.",
    "settings_view_onboarding": "Lihat Tutorial", "settings_view_onboarding_desc": "Ulangi panduan awal.",
    "settings_privacy_policy": "Kebijakan Privasi", "settings_privacy_policy_desc": "Privasi lokal.",
    "settings_privacy_promise": "Janji Kami", "settings_privacy_promise_desc": "File tidak pernah pergi ke cloud.",
    "settings_how_it_works": "Cara Kerja", "settings_how_it_works_desc": "Bantuan.",
    "settings_app_version": "Versi", "settings_recent_shares_count": "Koleksi: %1$d",
    "settings_share_debug_log": "Kirim Log", "settings_share_debug_log_desc": "Laporkan masalah.",
    "settings_clear_debug_log": "Hapus Log",
    "help_title": "Bantuan", "help_about_title": "Tentang",
    "help_about_1": "Buka file di browser.",
    "help_about_2": "Tanpa instal aplikasi lain.",
    "help_about_3": "Tanpa internet atau cloud.",
    "help_section_what_you_can_do": "Apa yang bisa dilakukan", "help_section_video_playback": "Putar Video",
    "help_section_browser_preparation": "Optimasi Web", "help_section_receiving_files": "Terima File",
    "help_section_drop_zone": "Kirim File", "help_section_multiple_devices": "Banyak Perangkat",
    "help_section_privacy_controls": "Privasi", "help_section_good_to_know": "Info Penting",
    "help_section_quick_flow": "Mulai Cepat", "help_line_share_files": "Bagikan file dan folder.",
    "help_line_open_session": "Buka dari browser.",
    "help_line_same_network": "Gunakan Wi-Fi yang sama.",
    "help_line_multiple_browse": "Semua orang bisa akses.",
    "help_line_video_direct": "Video langsung diputar.",
    "help_line_video_temporary": "Terkadang perlu diubah formatnya.",
    "help_line_video_original": "File asli tetap aman.",
    "help_line_prep_optional": "Optimasi bersifat opsional.",
    "help_line_prep_control": "Bisa dihentikan kapan saja.",
    "help_line_prep_batch": "Ponsel bisa menjadi panas.",
    "help_line_receive_upload": "Orang lain bisa mengirim file.",
    "help_line_receive_approval": "Setujui file masuk.",
    "help_line_receive_history": "Disimpan di folder Unduhan.",
    "help_line_drop_zone": "Seret dan lepas file.",
    "help_line_drop_zone_pick": "Atau pilih manual.", "help_line_drop_zone_local": "100% lokal.",
    "help_line_multi_connect": "Banyak perangkat sekaligus.",
    "help_line_multi_live": "Semua terlihat di layar.",
    "help_line_multi_controls": "Blokir perangkat jika perlu.",
    "help_line_privacy_local": "Tanpa akun.",
    "help_line_privacy_session": "Hanya yang dipilih yang dibagikan.",
    "help_line_privacy_controls": "Kontrol penuh di tangan Anda.",
    "help_line_wifi_hotspot": "Gunakan Wi-Fi atau Hotspot.",
    "help_line_public_wifi": "Hotspot lebih stabil.",
    "help_line_downloads_disabled": "Unduhan bisa dimatikan.",
    "help_line_flow_1": "1. Pilih file.", "help_line_flow_2": "2. Mulai sesi.",
    "help_line_flow_3": "3. Pindai QR.", "help_line_flow_4": "4. Tonton.",
    "home_brand_title": "DirectServe", "home_brand_subtitle": "Berbagi Privat",
    "home_chip_local_session": "Lokal", "home_chip_sharing": "Membagikan", "home_chip_ready": "Siap",
    "home_chip_setup_needed": "Butuh Jaringan", "home_live_banner": "Sesi Langsung",
    "home_title_live": "Berbagi Aktif", "home_title_start": "Berbagi Saat Ini",
    "home_body_live": "Perangkat lain bisa terhubung.", "home_body_start": "Tambahkan file untuk dibagikan.",
    "home_body_start_secondary": "Gunakan pustaka Anda.",
    "home_button_start_session": "Mulai", "home_button_open_session": "Buka",
    "home_button_starting": "Memulai...", "home_button_add_media": "Tambah", "home_button_add_more": "Tambah Lagi",
    "home_summary_current_share": "Total", "home_summary_media": "Media", "home_summary_files": "File",
    "home_content_filter_title": "Apa yang dibagikan", "home_content_filter_subtitle": "Terlihat di browser",
    "home_content_filter_videos": "Video", "home_content_filter_music": "Musik", "home_content_filter_photos": "Foto",
    "home_content_filter_files": "File", "home_no_network": "Tidak ada Wi-Fi",
    "network_setup_title": "Butuh Jaringan", "network_setup_body": "Harus berada di jaringan yang sama.",
    "network_setup_trouble_title": "Ada masalah?",
    "network_setup_trouble_body": "Gunakan Hotspot Anda sendiri.",
    "network_setup_open_wifi": "Wi-Fi", "network_setup_switch_hotspot": "Hotspot",
    "network_setup_retry": "Coba Lagi", "network_setup_footer": "Lebih cepat dan stabil.",
    "session_title": "Sesi Langsung", "session_stop_sharing": "Hentikan", "session_live_now": "LANGSUNG",
    "session_live_now_subtitle": "Anda terlihat di jaringan.", "session_share_live": "Sesi Aktif",
    "session_share_preparing": "Menyiapkan...", "session_share_live_body": "Pindai kode QR.",
    "session_qr_title": "Pindai", "session_qr_body": "Untuk perangkat apa pun.",
    "session_qr_preparing": "Membuat", "session_browser_prep_title": "Optimasi Web",
    "session_browser_prep_active": "%1$d%% • Siap %2$d / %3$d", "session_browser_prep_queued": "Antrean %1$d",
    "session_browser_prep_ready": "%1$d siap", "session_browser_prep_message_active": "Memproses...",
    "session_browser_prep_message_queued": "Menunggu", "session_browser_prep_message_ready": "Siap",
    "session_browser_prep_message_manual": "Perlu Tindakan",
    "session_browser_prep_manual_note": "Mungkin tidak diputar dengan baik di browser.",
    "session_prepare_browser_files": "Siapkan", "session_stop_browser_files": "Hentikan",
    "session_library_refresh_title": "Segarkan",
    "session_library_refresh_pending": "%1$d file siap ditambahkan.",
    "session_library_refresh_up_to_date": "Sudah terbaru.", "session_refresh_library": "Segarkan Sekarang",
    "message_live_library_refreshed_updates": "%1$d ditambahkan.",
    "message_live_library_refreshed_current": "Sudah diperbarui.",
    "message_browser_playback_queued_all": "Masuk antrean.",
    "message_browser_playback_already_ready": "Sudah siap.", "message_browser_playback_stopped": "Dihentikan.",
    "library_importing_title": "Mengimpor", "library_importing_body": "Mohon tunggu...",
    "session_waiting_local_link": "Jaringan...", "session_qr_content_desc": "Kode QR",
    "session_share_link": "Tautan", "session_share_link_body": "Buka di jaringan yang sama.", "session_network": "Jaringan",
    "session_access_pin": "PIN Akses", "session_pin_off": "Mati", "session_new_pin": "Baru",
    "session_turn_pin_on": "Aktifkan PIN", "session_turn_pin_off": "Matikan PIN", "session_nearby_name": "Nama",
    "session_what_happens_now": "Status", "session_waiting_ready": "Menunggu...",
    "session_waiting_first_device": "Menunggu perangkat...", "session_devices_connected_now": "%1$d terhubung.",
    "session_friendly_local_name": "Nama Lokal", "session_copy_link": "Salin", "session_share": "Bagikan",
    "session_metric_devices": "Perangkat", "session_metric_sent": "Terkirim", "session_metric_speed": "Kecepatan",
    "session_metric_elapsed": "Waktu", "session_metric_remaining": "Sisa", "session_connected_waiting": "Menunggu...",
    "session_connected_title": "Terhubung", "session_connected_waiting_body": "Akan muncul di sini.",
    "session_connected_count": "%1$d aktif.", "session_disconnect_all": "Putuskan Semua",
    "session_no_devices": "Belum ada.", "session_block_device": "Blokir",
    "session_block": "Blokir", "session_blocked_title": "Diblokir", "session_unblock_device": "Buka Blokir",
    "session_unblock": "Buka", "session_state_sharing_now": "Aktif", "session_state_preparing": "Siap-siap",
    "session_state_network_needed": "Butuh Jaringan", "session_network_hotspot": "Hotspot", "session_network_wifi": "Wi-Fi",
    "session_network_local": "Lokal", "session_network_offline": "Luring", "history_title": "Riwayat",
    "history_tab_all": "Semua", "history_tab_received": "Diterima", "history_empty_all": "Kosong.",
    "history_empty_received": "Kosong.", "history_sent": "Terkirim", "history_received": "Diterima",
    "history_open": "Buka", "history_delete": "Hapus", "history_delete_desc": "Hapus Riwayat",
    "history_date_time_format": "%1$s pada %2$s", "splash_title": "DirectServe", "splash_subtitle": "Berbagi Privat",
    "privacy_policy_title": "Privasi", "privacy_policy_intro": "File Anda aman di ponsel Anda.",
    "privacy_policy_line_1": "Tanpa pendaftaran.", "privacy_policy_line_2": "Tanpa cloud.",
    "privacy_policy_line_3": "Jaringan lokal saja.", "privacy_policy_line_4": "Anda memegang kendali.",
    "main_service_background_protection_failed": "Gagal memulai latar belakang.",
    "main_notification_permission_warning": "Butuh izin notifikasi.",
    "main_batch_media_access_needed": "Butuh izin media.", "main_debug_log_subject": "Log Debug",
    "main_debug_log_body": "Terkirim.", "main_debug_log_chooser": "Kirim via...",
    "main_no_email_app": "Tidak ada aplikasi email.", "main_no_browser_app": "Tidak ada browser.",
    "main_no_file_app": "Tidak ada aplikasi file.", "main_link_copied": "Disalin.",
    "main_link_preparing": "Tunggu...", "main_share_link_chooser": "Bagikan...",
    "main_link_not_ready": "Belum siap.", "main_not_sharing": "Mati", "service_start_failed": "Gagal.",
    "service_auto_stop_message": "Waktu habis.", "service_upload_request_title": "File Masuk",
    "service_upload_request_text": "%1$s dari %3$s ke %2$s", "service_upload_progress_title": "Menerima %1$s",
    "service_upload_progress_text": "%1$d%% (%2$s)", "service_upload_progress_text_unknown": "Dari %1$s",
    "service_upload_success_title": "Tersimpan: %1$s", "service_upload_success_text": "Dari %1$s",
    "service_upload_success_subtext": "Di Unduhan", "service_file_count": "%1$d file",
    "plural:service_new_devices_connected": {"one": "Perangkat bergabung", "other": "%1$d perangkat bergabung"},
    "plural:service_devices_joined": {"one": "%1$s bergabung.", "other": "%1$s bergabung (%2$d)."},
    "service_waiting_for_devices": "Menunggu...", "plural:service_devices_connected": {"one": "1 perangkat", "other": "%1$d perangkat"},
    "service_preparing_browser_access": "Menyiapkan web...", "service_channel_requests_name": "Transfer",
    "service_channel_requests_desc": "Unduhan", "service_channel_connections_name": "Koneksi",
    "service_channel_connections_desc": "Perangkat", "service_channel_quick_text_name": "Teks",
    "service_channel_quick_text_desc": "Pesan", "service_quick_text_title": "Pesan dari %1$s",
    "library_title": "Pustaka", "library_header_title": "File",
    "library_header_body": "Yang dibagikan.", "library_header_subtitles": "Tambahkan subtitle.",
    "library_info_items": "Item", "library_info_folders": "Folder", "library_info_size": "Ukuran",
    "library_empty_title": "Kosong", "library_empty_body": "Tambahkan sesuatu.", "library_section_folders": "Folder",
    "library_section_folders_body": "Folder yang dibagikan.", "library_empty_filter_title": "Tidak Ada",
    "library_empty_filter_body": "Ubah filter.", "library_section_files": "File", "library_single_file_name": "File",
    "library_selected_files_name": "Dipilih", "library_save_selected_title": "Simpan",
    "library_save_selected_body": "Untuk nanti.", "library_share_name": "Nama", "library_manage_title": "Kelola",
    "library_manage_body": "Atur file.", "library_selection_title": "Pilihan Baru",
    "library_selection_step_1": "1. Pilih file.", "library_selection_step_2": "2. Selesai.",
    "library_search_label": "Cari...", "library_show_title": "Tampilkan", "library_show_body": "Filter",
    "library_category_all": "Semua", "library_category_videos": "Video", "library_category_photos": "Foto",
    "library_category_music": "Musik", "library_category_files": "File", "library_add_title": "Tambah",
    "library_add_body": "Dari ponsel.", "library_add_files": "File", "library_add_whole_folder": "Folder",
    "library_add_from_suggestions": "Galeri", "library_organize_title": "Urutkan",
    "library_organize_body": "Pilih urutan.", "library_sort_prefix": "Urutan: %1$s",
    "library_clear_all_action": "Hapus Semua", "plural:library_items_in_view": {"one": "1", "other": "%1$d"},
    "library_clear_all_title": "Hapus Semua?", "library_clear_all_body": "Daftar akan kosong.",
    "library_sort_newest": "Terbaru", "library_sort_name": "Nama", "library_sort_size": "Ukuran",
    "library_cancel_selection": "Batal", "library_create_saved_share": "Selesai", "library_start_saved_share_selection": "Pilih",
    "library_browser_prep_title": "Salinan Web", "library_browser_prep_body": "File ringan untuk browser.",
    "library_folder_summary": "%1$d | %2$s", "library_unavailable": "Tidak tersedia", "library_direct_play": "Putar Langsung",
    "library_subtitle": "Subtitle", "library_selected": "Dipilih", "library_tap_to_select": "Ketuk",
    "library_select_this_file": "Ya", "library_preparing": "Menyiapkan", "library_preparing_for_browser": "Di antrean",
    "library_ready": "Siap", "library_ready_for_browser": "Web Siap", "library_try_again": "Lagi",
    "library_try_browser_prep_again": "Coba Lagi", "library_prepare": "Siapkan", "library_prepare_for_browser": "Selesai",
    "library_type_video": "Video", "library_type_photo": "Foto", "library_type_music": "Musik", "library_type_file": "File",
    "library_compat_ready_to_play": "Siap | %1$s", "library_compat_not_prepared": "Belum siap", "library_compat_queued": "Di antrean",
    "library_compat_preparing": "Memproses...", "library_compat_ready": "Siap", "library_compat_unavailable": "Tidak didukung",
    "library_compat_message": "%1$s | %2$s", "selection_add_files_title": "Pilih", "selection_add_files_body": "Apa yang dibagikan?",
    "selection_add_selected": "Tambah", "selection_pick_files_again": "Ubah", "selection_nothing_selected_title": "Kosong",
    "selection_nothing_selected_body": "Pilih sesuatu.", "selection_add_folder_title": "Folder",
    "selection_add_folder_body": "Pilih folder.", "selection_add_folder": "Selesai",
    "selection_choose_another_folder": "Ubah", "selection_no_folder_title": "Salah",
    "selection_no_folder_body": "Pilih folder.", "selection_selected_folder": "Folder", "selection_selected_item": "1",
    "selection_smart_picks_title": "Tanggal", "selection_smart_picks_body": "Siap dibagikan.",
    "selection_media_access_title": "Izin", "selection_media_access_body": "Beri izin.",
    "selection_grant_access": "Ya", "selection_loading_groups_title": "Mencari...", "selection_loading_groups_body": "Mengatur...",
    "selection_no_groups_title": "Tidak Ada", "selection_no_groups_body": "Tambah manual.", "selection_refresh_groups": "Segarkan",
    "selection_add_group": "Plus", "home_upload_request_title": "File Baru", "home_upload_request_single": "file",
    "home_upload_request_files": "%1$d file", "home_upload_request_body": "%1$s mengirim %2$s:",
    "home_upload_request_total_size": "Ukuran: %1$s", "home_history_content_desc": "Riwayat",
    "home_settings_content_desc": "Pengaturan", "home_network_required_title": "Jaringan",
    "home_network_required_body": "Wi-Fi atau Hotspot.", "message_unable_add_folder": "Error.",
    "message_saved_share_named": "Disimpan: '%1$s'", "message_unable_save_share": "Gagal.",
    "message_saved_share_ready": "Siap.", "home_all_files_access_title": "Dokumen?",
    "home_all_files_access_body": "Izinkan.", "home_all_files_access_grant": "Ya",
    "home_all_files_access_media_only": "Hanya Media", "home_all_files_nudge_text": "File apa pun!",
    "message_unable_open_saved_share": "Error.", "message_saved_share_removed": "Dihapus.",
    "message_something_went_wrong": "Ada yang salah.", "message_pin_on": "PIN Nyala.", "message_pin_off": "PIN Mati.",
    "message_debug_log_prepare_failed": "Log Error.", "message_debug_log_cleared": "Selesai.",
    "message_debug_log_clear_failed": "Error.", "message_file_no_longer_available": "Hilang.",
    "message_preparing_browser_playback": "Web %1$s.", "nearby_helper_tap_session": "Ketuk.",
    "nearby_helper_open_on_other_device": "Buka.", "share_preset_enter_name": "Nama:",
    "share_preset_add_content_first": "Isi dulu.", "share_preset_select_file_first": "Pilih.",
    "share_preset_files_unavailable": "File tidak ada.", "share_preset_collection_unavailable": "Tidak ada.",
    "share_preset_restore_failed": "Error.", "sharing_preflight_failed": "Error: %1$s",
    "sharing_add_content_first": "Masukkan file.", "sharing_same_wifi_needed": "Satu Wi-Fi.",
    "sharing_connect_before_start": "Terhubung dulu.", "sharing_server_start_failed": "Error: %1$s",
    "sharing_blocked_by_live_screen": "Matikan berbagi layar.", "sharing_stopped": "Berhenti.",
    "sharing_device_android": "Android", "network_helper_wifi_ready": "Wi-Fi Oke.",
    "network_helper_local_ready": "Lokal Oke.", "network_helper_wifi_found": "IP Ada.",
    "network_helper_hotspot_ready": "Hotspot Oke.", "network_helper_mobile_only": "Hanya Data.",
    "network_helper_local_address_ready": "IP Oke.", "network_helper_connect_both": "Hubungkan bersama.",
    "discovery_unavailable_device": "Mati.", "discovery_nsd_unavailable": "Mati.",
    "discovery_searching": "Mencari...", "discovery_unavailable_now": "Hanya QR.",
    "discovery_start_failed": "Error (%1$d)", "discovery_ready_to_open": "Selesai.",
    "browser_title": "DirectServe", "browser_subtitle": "File", "browser_file_unavailable": "Hilang.",
    "browser_debug_unavailable": "Mati.", "browser_debug_missing_payload": "Kosong.", "browser_pin_mismatch": "PIN Salah.",
    "browser_device_blocked": "Diblokir.", "browser_enter_pin": "PIN:",
    "browser_optimized_unavailable": "Bukan Web.", "browser_video_part_preparing": "Membuat...",
    "browser_video_part_unavailable": "Kosong.", "browser_hls_not_needed": "Tidak Perlu.",
    "browser_hls_not_ready": "Belum Siap.", "home_action_add_to_share_title": "Tambah",
    "home_action_add_to_share_subtitle": "File", "home_action_files": "File", "home_action_files_desc": "Ya",
    "home_action_folder": "Folder", "home_action_folder_desc": "Ya", "home_action_library": "Pustaka",
    "home_action_library_desc": "Cari", "home_button_share_all_media": "Semua", "home_button_adding_all": "Menambah...",
    "home_media_server_active": "Semua Nyala", "home_btn_stop_media_server": "Stop", "web_folders_title": "Folder",
    "web_folder_items": "%1$d", "web_btn_back_to_folders": "Kembali", "web_all_media": "Media",
    "home_nearby_title": "Sekitar", "home_nearby_subtitle": "Perangkat.",
    "home_nearby_refresh_status": "Segarkan", "home_network_wifi": "Wi-Fi Oke", "home_network_hotspot": "Hotspot Oke",
    "home_network_local": "Lokal Oke", "home_network_none": "Kosong", "home_network_ready_desc": "Siap.",
    "home_network_none_desc": "Butuh koneksi.", "home_nearby_optional_title": "App Opsional",
    "home_nearby_optional_desc": "Bisa lewat web.", "home_nearby_refresh": "Cari",
    "home_nearby_open_title": "Di App", "home_nearby_open_desc": "Jika ada.",
    "home_nearby_action_open_session": "Ayo", "home_nearby_action_open": "Ya", "home_nearby_device_available": "Selesai",
    "home_nearby_device_pin": "PIN", "web_hero_eyebrow": "DirectServe", "web_hero_title": "Media Anda",
    "web_hero_desc1": "Video, foto.", "web_hero_desc2": "File.", "web_hero_desc3": "Privat.",
    "web_hero_stat_shared": "Berjalan", "web_items": "item", "web_hero_stat_ready": "Siap", "web_hero_stat_access": "Izin",
    "web_access_pin": "Terkunci", "web_access_instant": "Terbuka", "web_access_pin_desc": "Butuh PIN",
    "web_access_instant_desc": "Siap", "web_pin_entry_kicker": "PIN", "web_pin_entry_title": "Masukkan PIN",
    "web_pin_entry_desc": "Di layar.", "web_pin_entry_placeholder": "PIN", "web_btn_videos": "Video",
    "web_btn_download_all_files": "Unduh Semua", "web_cat_videos": "Video", "web_cat_photos": "Foto",
    "web_cat_music": "Musik", "web_cat_files": "File", "web_recent_title": "Baru", "web_recent_meta": "siap",
    "web_nav_home": "Home", "web_nav_drop_zone": "Drop", "web_nav_logout": "Keluar", "web_nav_media": "Media",
    "web_nav_files": "File", "web_nav_send": "Kirim", "web_strip_session": "Sesi", "web_strip_device": "Kita",
    "web_strip_link": "Tautan", "web_security_pin": "PIN", "web_security_open": "Mati", "web_status_unknown": "?",
    "home_connected_devices": "Terhubung", "home_rename_device": "Nama", "home_rename_device_subtitle": "%1$s • %2$s",
    "home_rename_custom_name": "Baru", "home_rename_save": "Selesai", "home_rename_cancel": "Batal", "home_quick_filters": "Filter",
    "home_quick_filter_today": "Hari ini", "home_quick_filter_today_desc": "24 Jam", "home_quick_filter_week": "Minggu",
    "home_quick_filter_week_desc": "7 Hari", "home_quick_filter_month": "Bulan", "home_quick_filter_month_desc": "30 Hari",
    "home_quick_filter_custom": "Waktu", "home_quick_filter_custom_desc": "Pilih", "home_date_range_title": "Hari",
    "home_date_range_from": "Dari", "home_date_range_start": "Mulai", "home_date_range_to": "Ke",
    "home_date_range_end": "Akhir", "home_date_range_tip": "Bagus.", "home_date_range_apply": "Oke",
    "home_date_range_cancel": "Batal", "home_recent_shares": "Lama", "home_section_library": "File",
    "home_section_live_tools": "Alat", "home_section_network_tv": "TV", "home_section_sharing": "Aksi",
    "home_section_live_features": "Ekstra", "home_feature_library": "Pustaka", "home_feature_library_desc": "Set.",
    "home_feature_transfers": "Transfer", "home_feature_transfers_desc": "Unduh.", "home_feature_share_files": "Bagi",
    "home_feature_share_files_desc": "Semua.", "home_feature_receive_files": "Terima",
    "home_feature_receive_files_desc": "Ya.", "home_feature_play_media": "Putar",
    "home_feature_play_media_desc": "Web.", "home_feature_play_media_live": "Ya.", "home_feature_dlna": "DLNA",
    "home_feature_dlna_desc": "TV.", "home_feature_dlna_enabled": "Nyala.", "home_feature_live_screen": "Layar",
    "home_feature_live_screen_desc": "Mirror.", "home_feature_quick_text": "Teks", "home_feature_quick_text_desc": "Ya.",
    "home_saved_shares": "Koleksi", "home_saved_shares_save_now": "Simpan", "home_saved_shares_open": "Buka",
    "home_saved_shares_delete": "Hapus", "plural:home_saved_shares_items_count": {"one": "1", "other": "%1$d"},
    "library_date_group_label": "%1$s", "web_upload_title": "Unggah", "web_upload_subtitle": "Ke ponsel.",
    "web_upload_prompt_title": "Beri File", "web_upload_prompt_desktop": "Seret.",
    "web_upload_prompt_mobile": "Ketuk.", "web_upload_button_browse": "Cari",
    "web_upload_button_photos": "Foto", "web_upload_button_any_file": "File", "web_upload_target_kicker": "Ponsel",
    "web_upload_target_status": "Selesai.", "web_upload_how_kicker": "Ya", "web_upload_how_title": "Izin",
    "web_upload_how_body": "Perlu setuju.", "web_action_download": "Unduh", "web_action_view": "Lihat",
    "web_photo_view": "Lihat", "web_btn_download_all": "Unduh Semua", "web_btn_download_selected": "Unduh",
    "web_btn_download_original": "Asli", "web_btn_fullscreen": "Penuh", "web_error_streaming_codec": "Tidak Jalan. Unduh.",
    "web_error_downloads_disabled": "Mati.", "web_error_video_decode": "Error. Unduh.",
    "web_error_video_start": "Error. Unduh.", "web_error_video_start_no_dl": "Diperbaiki...",
    "web_error_load_failed": "Error.", "web_btn_select_files": "Pilih", "web_status_selection_on": "Nyala",
    "web_btn_select_all": "Semua", "web_btn_clear_selection": "Batal", "web_player_slow_start_hint": "Tunggu...",
    "web_selection_count": "%1$d", "web_library_desc_download": "Lihat atau ambil.", "web_library_desc_browse": "Semua di sini.",
    "web_btn_load_more": "Lagi", "web_btn_show_all": "Semua", "web_btn_showing_all": "Mengambil...",
    "web_show_all_confirm": "Semua %1$d?", "web_library_showing_count": "%1$d / %2$d",
    "web_search_placeholder": "Nama...", "web_library_empty": "Kosong.", "web_upload_selection_empty": "Tidak Ada.",
    "web_upload_selection_single": "%1$s", "web_upload_selection_multiple": "%1$d", "web_upload_button_send": "Kirim",
    "common_quick_filters": "Filter", "common_edit_nickname": "Nama", "home_quick_filters_desc": "Hari.",
    "home_date_range_body": "Hari.", "web_upload_requesting": "Meminta...", "web_upload_waiting": "Menunggu...",
    "web_upload_denied": "Ditolak.", "web_upload_failed_status": "Error (%1$d)",
    "web_upload_network_error": "Jaringan.", "web_upload_cancelled": "Batal.", "web_upload_success_title": "Masuk",
    "web_upload_success_detail_single": "Selesai.", "web_upload_success_detail_multiple": "Selesai.",
    "web_upload_failed_title": "Tidak", "web_upload_failed_detail": "Error.", "web_player_error_open": "Gagal",
    "web_player_opening": "Mulai...", "web_player_ready": "Siap", "web_player_analyzing": "Mengecek...",
    "web_player_finalizing": "Selesai...", "web_player_stalled": "Berhenti", "web_player_starting": "Ayo...",
    "web_player_wait_desc": "Sebentar...", "web_player_ready_desc": "Main.", "web_player_analyzing_desc": "Cari...",
    "web_player_finalizing_desc": "Hampir...", "web_player_stalled_desc": "Berat.",
    "web_player_needs_prepare": "Butuh Web", "web_player_needs_prepare_desc": "Di HP.",
    "web_player_starting_desc": "Mulai...", "web_player_try_again": "Lagi", "web_player_status_opening": "Mulai",
    "web_player_status_ready": "Oke", "web_player_status_analyzing": "Cek", "web_player_status_finalizing": "Akhir",
    "web_player_status_stalled": "Macet", "web_player_status_playing": "Main", "web_player_progress_preparing": "Tunggu",
    "web_player_progress_converting": "Nulis", "web_player_status_failed": "Gagal", "web_player_status_stopped": "Stop",
    "web_prepare_video": "Web", "web_progress_percent": "%1$d%%", "web_media_quick_title": "Media",
    "web_media_quick_subtitle": "Masuk.", "web_media_open_category": "%1$s", "web_media_empty": "Kosong.",
    "web_send_files_to_device": "Kirim", "web_upload_in_progress": "Jalan...", "web_upload_complete": "Selesai",
    "web_upload_failed": "Gagal", "web_cancel": "Batal", "web_upload_preparing_transfer": "Siap...",
    "web_upload_connecting": "Menyambung...", "web_btn_back": "Kembali", "web_status_subtitles_available": "Subtitle",
    "web_now_playing": "Playing", "common_resume": "Lanjut", "web_status_init_progress": "0%",
    "common_play": "Play", "common_pause": "Pause", "common_unit_b": "B", "common_unit_kb": "KB",
    "common_unit_mb": "MB", "common_unit_gb": "GB", "common_unit_tb": "TB", "common_unit_s": "d",
    "common_unit_m": "m", "common_unit_h": "j", "common_byte_format_decimal": "%1$.1f %2$s",
    "common_byte_format_integer": "%1$d %2$s", "common_duration_format_m_s": "%1$dm %2$dd",
    "common_duration_format_h_m": "%1$dj %2$dm", "common_duration_format_s": "%1$dd",
    "common_duration_timestamp_m_s": "%1$d:%2$02d", "common_duration_timestamp_h_m_s": "%1$d:%2$02d:%3$02d",
    "service_file_index_pattern": "%1$s (%2$d/%3$d)", "service_upload_progress_subtext_pattern": "%1$s / %2$s",
    "help_section_media_server": "Server", "help_line_media_server_1": "Hub.",
    "help_line_media_server_2": "Diatur.", "help_section_folders_nav": "Folder",
    "help_line_folders_1": "Seperti asli.", "help_line_folders_2": "Bersih.", "help_section_dlna_tv": "TV",
    "help_line_dlna_1": "Pintar.", "help_line_dlna_2": "DirectServe.", "help_line_dlna_3": "Jaringan.",
    "help_line_dlna_4": "VLC Oke.", "help_section_search_sticky": "Cari", "help_line_search_1": "Cepat.",
    "help_line_search_2": "Atas.", "settings_dlna": "DLNA TV", "settings_dlna_desc": "TV/VLC.",
    "dlna_server_name": "DirectServe", "dlna_server_name_template": "DirectServe (%1$s)",
    "web_action_download_zip": "ZIP", "web_btn_download_all_zip": "Semua ZIP",
    "web_btn_download_selected_zip": "Ambil ZIP", "web_error_no_items_selected": "Kosong.",
    "web_download_started_hint": "Bungkus...", "playback_mode_direct": "Direct Play",
    "playback_mode_repackaging": "Kotak", "playback_mode_transcoding": "Berat",
    "playback_mode_analyzing": "Cek", "compatibility_message_cached_ready": "Sudah siap.",
    "compatibility_message_stopped": "Stop.", "compatibility_message_validation_failed": "Error: %1$s",
    "compatibility_message_adjusted": "Selesai.", "compatibility_message_optimizing": "Siap...",
    "compatibility_message_almost_ready": "Segera...", "compatibility_message_ready": "Selesai.",
    "compatibility_message_analyzing": "Lihat...", "compatibility_message_finalizing_optimized": "Akhir...",
    "compatibility_message_finalizing_compatible": "Akhir...", "compatibility_message_optimizing_web": "Web...",
    "compatibility_message_repackaging_web": "Bungkus...", "compatibility_message_converting_web": "Ubah...",
}

# JAPANESE (ja)
ja_data = {
    "common_back": "戻る", "common_cancel": "キャンセル", "common_save": "保存", "common_delete": "削除",
    "common_open": "開く", "common_refresh": "更新", "common_continue": "続行", "common_accept": "承諾",
    "common_decline": "拒否", "common_dismiss": "閉じる", "common_remove": "削除", "common_search": "検索",
    "common_separator_pipe": " | ", "common_separator_dot": " • ", "onboarding_skip": "スキップ",
    "onboarding_title": "DirectServe",
    "onboarding_subtitle": "スマホをTVやPCのローカルハブに。",
    "onboarding_page_1_title": "どの画面でも視聴",
    "onboarding_page_1_description": "クラウド不要でビデオや写真を大画面で。",
    "onboarding_page_2_title": "あらゆるデバイスで動作",
    "onboarding_page_2_description": "TV、PC、スマホ、ブラウザがあればOK。",
    "onboarding_page_3_title": "ブラウザからアクセス",
    "onboarding_page_3_description": "アプリ不要。リンクかQRコードだけ。",
    "onboarding_page_4_title": "双方向の共有",
    "onboarding_page_4_description": "ファイルの送受信が簡単。",
    "onboarding_page_5_title": "インターネット不要",
    "onboarding_page_5_description": "Wi-Fiまたはアクセスポイントで動作。",
    "onboarding_page_6_title": "プライバシー",
    "onboarding_page_6_description": "ファイルはスマホ内に残ります。",
    "onboarding_page_counter": "%1$d / %2$d", "onboarding_next": "次へ", "onboarding_get_started": "始める",
    "settings_title": "設定", "settings_subtitle": "DirectServeのカスタマイズ",
    "settings_group_general": "一般", "settings_group_notifications": "通知", "settings_group_privacy": "プライバシー",
    "settings_group_browser": "ブラウザ", "settings_group_advanced": "詳細設定", "settings_group_network": "ネットワーク",
    "settings_group_help": "ヘルプ", "settings_group_debug": "デバッグ", "settings_language": "言語",
    "settings_theme": "テーマ", "settings_theme_subtitle": "外観を変更", "settings_theme_system": "システム",
    "settings_theme_dark": "ダーク", "settings_theme_light": "ライト", "settings_keep_screen_awake": "画面をオンに保つ",
    "settings_keep_screen_awake_desc": "共有中は画面をオフにしない。",
    "settings_vibrate_on_connect": "接続時にバイブ", "settings_vibrate_on_connect_desc": "誰かが参加した時。",
    "settings_show_speed": "速度を表示", "settings_show_speed_desc": "リアルタイムの転送速度。",
    "settings_show_recent_shares": "履歴を表示", "settings_show_recent_shares_desc": "ローカル履歴を保存。",
    "settings_auto_stop": "自動停止", "settings_auto_stop_never": "しない", "settings_auto_stop_15m": "15分",
    "settings_auto_stop_30m": "30分", "settings_auto_stop_1h": "1時間", "settings_connection_alerts": "接続通知",
    "settings_connection_alerts_desc": "デバイスが接続した時。",
    "settings_download_alerts": "ダウンロード通知", "settings_download_alerts_desc": "ファイルがダウンロードされた時。",
    "settings_upload_requests": "アップロード要求", "settings_upload_requests_desc": "ファイルの受信前に確認。",
    "settings_quick_text_enabled": "クイックテキスト", "settings_quick_text_enabled_desc": "テキストメッセージを共有。",
    "settings_quick_text_alerts": "メッセージ通知", "settings_quick_text_alerts_desc": "メッセージ受信時。",
    "settings_use_pin": "PINを使用", "settings_use_pin_desc": "安全のためのパスワード。",
    "settings_new_pin_each_time": "毎回新しいPIN", "settings_new_pin_each_time_desc": "セキュリティ強化。",
    "settings_pin_label": "PIN", "settings_pin_placeholder": "4-6桁", "settings_approve_file_uploads": "アップロードを承認",
    "settings_approve_file_uploads_desc": "受信前に確認。",
    "settings_approve_per_device": "デバイス毎に承認", "settings_approve_per_device_desc": "1度だけ承認。",
    "settings_received_files_location": "保存先", "settings_received_files_location_value": "ダウンロード",
    "settings_show_thumbnails": "サムネイルを表示", "settings_show_thumbnails_desc": "メディアのプレビュー。",
    "settings_large_tv_layout": "TVレイアウト", "settings_large_tv_layout_desc": "大きなボタン。",
    "settings_highlight_downloads": "ダウンロードを強調", "settings_highlight_downloads_desc": "見やすくする。",
    "settings_sign_out_on_stop": "停止時にサインアウト", "settings_sign_out_on_stop_desc": "アクセスを切断。",
    "settings_clear_temporary_files": "一時ファイルを削除", "settings_clear_temporary_files_desc": "ビデオの最適化ファイルを消す。",
    "settings_prevent_downloads": "ダウンロードを防止", "settings_prevent_downloads_desc": "視聴のみを許可。",
    "settings_auto_optimize_library": "バックグラウンド最適化", "settings_auto_optimize_library_desc": "バッテリーを消費します。",
    "settings_sharing_port": "ポート", "settings_sharing_port_placeholder": "43183",
    "settings_sharing_port_help": "変更しないでください。",
    "settings_wifi_settings": "Wi-Fi設定", "settings_wifi_settings_desc": "同じネットワークが必要です。",
    "settings_hotspot_settings": "ホットスポット設定", "settings_hotspot_settings_desc": "ローカルネットワークを作成。",
    "settings_view_onboarding": "チュートリアル", "settings_view_onboarding_desc": "最初のガイドを再表示。",
    "settings_privacy_policy": "プライバシーポリシー", "settings_privacy_policy_desc": "ローカルプライバシー。",
    "settings_privacy_promise": "約束", "settings_privacy_promise_desc": "ファイルは安全です。",
    "settings_how_it_works": "仕組み", "settings_how_it_works_desc": "ヘルプ。",
    "settings_app_version": "バージョン", "settings_recent_shares_count": "コレクション: %1$d",
    "settings_share_debug_log": "ログを送信", "settings_share_debug_log_desc": "問題を報告。",
    "settings_clear_debug_log": "ログをクリア",
    "help_title": "ヘルプ", "help_about_title": "概要",
    "help_about_1": "ブラウザでファイルを開きます。",
    "help_about_2": "アプリのインストールは不要です。",
    "help_about_3": "インターネットもクラウドも不要。",
    "help_section_what_you_can_do": "できること", "help_section_video_playback": "動画再生",
    "help_section_browser_preparation": "Web最適化", "help_section_receiving_files": "ファイルの受信",
    "help_section_drop_zone": "ファイルの送信", "help_section_multiple_devices": "複数デバイス",
    "help_section_privacy_controls": "プライバシー", "help_section_good_to_know": "知っておくべきこと",
    "help_section_quick_flow": "クイックスタート", "help_line_share_files": "ファイルやフォルダを共有。",
    "help_line_open_session": "ブラウザから開く。",
    "help_line_same_network": "同じWi-Fiを使用。",
    "help_line_multiple_browse": "皆で同時にアクセス。",
    "help_line_video_direct": "動画を直接再生。",
    "help_line_video_temporary": "フォーマット変換が必要な場合も。",
    "help_line_video_original": "元のファイルは安全です。",
    "help_line_prep_optional": "最適化は任意です。",
    "help_line_prep_control": "いつでも停止できます。",
    "help_line_prep_batch": "スマホが熱くなることがあります。",
    "help_line_receive_upload": "他の人がファイルを送れます。",
    "help_line_receive_approval": "受信を承認します。",
    "help_line_receive_history": "ダウンロードフォルダに保存。",
    "help_line_drop_zone": "ドラッグ＆ドロップ。",
    "help_line_drop_zone_pick": "または手動で選択。", "help_line_drop_zone_local": "100%ローカル。",
    "help_line_multi_connect": "多くのデバイスが同時に。",
    "help_line_multi_live": "画面に全員が表示されます。",
    "help_line_multi_controls": "必要ならブロック。",
    "help_line_privacy_local": "アカウント不要。",
    "help_line_privacy_session": "選択したものだけを共有。",
    "help_line_privacy_controls": "完全にコントロール。",
    "help_line_wifi_hotspot": "Wi-Fiまたはホットスポット。",
    "help_line_public_wifi": "ホットスポットが安定しています。",
    "help_line_downloads_disabled": "ダウンロードをオフにできます。",
    "help_line_flow_1": "1. ファイルを選択。", "help_line_flow_2": "2. セッション開始。",
    "help_line_flow_3": "3. QRをスキャン。", "help_line_flow_4": "4. 視聴する。",
    "home_brand_title": "DirectServe", "home_brand_subtitle": "プライベート共有",
    "home_chip_local_session": "ローカル", "home_chip_sharing": "共有中", "home_chip_ready": "準備完了",
    "home_chip_setup_needed": "ネットワークが必要", "home_live_banner": "ライブセッション",
    "home_title_live": "共有アクティブ", "home_title_start": "現在の共有",
    "home_body_live": "他のデバイスが接続できます。", "home_body_start": "ファイルを追加してください。",
    "home_body_start_secondary": "ライブラリを使用します。",
    "home_button_start_session": "開始", "home_button_open_session": "開く",
    "home_button_starting": "開始中...", "home_button_add_media": "追加", "home_button_add_more": "さらに追加",
    "home_summary_current_share": "合計", "home_summary_media": "メディア", "home_summary_files": "ファイル",
    "home_content_filter_title": "共有するもの", "home_content_filter_subtitle": "ブラウザで表示",
    "home_content_filter_videos": "動画", "home_content_filter_music": "音楽", "home_content_filter_photos": "写真",
    "home_content_filter_files": "ファイル", "home_no_network": "Wi-Fiがありません",
    "network_setup_title": "ネットワークが必要", "network_setup_body": "同じネットワークが必要です。",
    "network_setup_trouble_title": "問題がありますか？",
    "network_setup_trouble_body": "独自のホットスポットを使用。",
    "network_setup_open_wifi": "Wi-Fi", "network_setup_switch_hotspot": "ホットスポット",
    "network_setup_retry": "再試行", "network_setup_footer": "より速く安定しています。",
    "session_title": "ライブセッション", "session_stop_sharing": "停止", "session_live_now": "ライブ",
    "session_live_now_subtitle": "ネットワーク上で表示されています。", "session_share_live": "セッションアクティブ",
    "session_share_preparing": "準備中...", "session_share_live_body": "QRコードをスキャン。",
    "session_qr_title": "スキャン", "session_qr_body": "どのデバイスでも。",
    "session_qr_preparing": "作成中", "session_browser_prep_title": "Web最適化",
    "session_browser_prep_active": "%1$d%% • 完了 %2$d / %3$d", "session_browser_prep_queued": "待機中 %1$d",
    "session_browser_prep_ready": "%1$d 完了", "session_browser_prep_message_active": "処理中...",
    "session_browser_prep_message_queued": "待機中", "session_browser_prep_message_ready": "完了",
    "session_browser_prep_message_manual": "アクションが必要",
    "session_browser_prep_manual_note": "ブラウザでうまく再生されないかも。",
    "session_prepare_browser_files": "準備", "session_stop_browser_files": "停止",
    "session_library_refresh_title": "更新",
    "session_library_refresh_pending": "%1$d ファイル待機中。",
    "session_library_refresh_up_to_date": "最新です。", "session_refresh_library": "今すぐ更新",
    "message_live_library_refreshed_updates": "%1$d 追加されました。",
    "message_live_library_refreshed_current": "すでに更新済み。",
    "message_browser_playback_queued_all": "キューに追加。",
    "message_browser_playback_already_ready": "すでに完了。", "message_browser_playback_stopped": "停止しました。",
    "library_importing_title": "インポート中", "library_importing_body": "お待ちください...",
    "session_waiting_local_link": "ネットワーク...", "session_qr_content_desc": "QRコード",
    "session_share_link": "リンク", "session_share_link_body": "同じネットワークで開く。", "session_network": "ネットワーク",
    "session_access_pin": "アクセスPIN", "session_pin_off": "オフ", "session_new_pin": "新規",
    "session_turn_pin_on": "PINをオン", "session_turn_pin_off": "PINをオフ", "session_nearby_name": "名前",
    "session_what_happens_now": "ステータス", "session_waiting_ready": "待機中...",
    "session_waiting_first_device": "デバイスを待っています...", "session_devices_connected_now": "%1$d 接続中。",
    "session_friendly_local_name": "ローカル名", "session_copy_link": "コピー", "session_share": "共有",
    "session_metric_devices": "デバイス", "session_metric_sent": "送信済", "session_metric_speed": "速度",
    "session_metric_elapsed": "時間", "session_metric_remaining": "残り", "session_connected_waiting": "待機中...",
    "session_connected_title": "接続済み", "session_connected_waiting_body": "ここに表示されます。",
    "session_connected_count": "%1$d アクティブ。", "session_disconnect_all": "すべて切断",
    "session_no_devices": "まだいません。", "session_block_device": "ブロック",
    "session_block": "ブロック", "session_blocked_title": "ブロック中", "session_unblock_device": "ブロック解除",
    "session_unblock": "解除", "session_state_sharing_now": "アクティブ", "session_state_preparing": "準備中",
    "session_state_network_needed": "ネットワークが必要", "session_network_hotspot": "ホットスポット", "session_network_wifi": "Wi-Fi",
    "session_network_local": "ローカル", "session_network_offline": "オフライン", "history_title": "履歴",
    "history_tab_all": "すべて", "history_tab_received": "受信済", "history_empty_all": "空です。",
    "history_empty_received": "空です。", "history_sent": "送信", "history_received": "受信",
    "history_open": "開く", "history_delete": "削除", "history_delete_desc": "履歴から削除",
    "history_date_time_format": "%1$s %2$s", "splash_title": "DirectServe", "splash_subtitle": "プライベート共有",
    "privacy_policy_title": "プライバシー", "privacy_policy_intro": "ファイルはスマホ内で安全です。",
    "privacy_policy_line_1": "登録不要。", "privacy_policy_line_2": "クラウドなし。",
    "privacy_policy_line_3": "ローカルネットワークのみ。", "privacy_policy_line_4": "あなたがコントロール。",
    "main_service_background_protection_failed": "バックグラウンド起動失敗。",
    "main_notification_permission_warning": "通知の許可が必要です。",
    "main_batch_media_access_needed": "メディアの許可が必要です。", "main_debug_log_subject": "デバッグログ",
    "main_debug_log_body": "送信されました。", "main_debug_log_chooser": "送信方法...",
    "main_no_email_app": "メールアプリがありません。", "main_no_browser_app": "ブラウザがありません。",
    "main_no_file_app": "ファイルアプリがありません。", "main_link_copied": "コピーしました。",
    "main_link_preparing": "お待ちください...", "main_share_link_chooser": "共有...",
    "main_link_not_ready": "準備ができていません。", "main_not_sharing": "オフ", "service_start_failed": "失敗しました。",
    "service_auto_stop_message": "時間切れ。", "service_upload_request_title": "受信ファイル",
    "service_upload_request_text": "%1$s （%3$s -> %2$s）", "service_upload_progress_title": "受信中 %1$s",
    "service_upload_progress_text": "%1$d%% (%2$s)", "service_upload_progress_text_unknown": "送信元 %1$s",
    "service_upload_success_title": "保存済: %1$s", "service_upload_success_text": "送信元 %1$s",
    "service_upload_success_subtext": "ダウンロード内", "service_file_count": "%1$d ファイル",
    "plural:service_new_devices_connected": {"one": "デバイスが参加", "other": "%1$d デバイスが参加"},
    "plural:service_devices_joined": {"one": "%1$s が参加。", "other": "%1$s が参加 (%2$d)。"},
    "service_waiting_for_devices": "待機中...", "plural:service_devices_connected": {"one": "1 デバイス", "other": "%1$d デバイス"},
    "service_preparing_browser_access": "Webの準備中...", "service_channel_requests_name": "転送",
    "service_channel_requests_desc": "ダウンロード", "service_channel_connections_name": "接続",
    "service_channel_connections_desc": "デバイス", "service_channel_quick_text_name": "テキスト",
    "service_channel_quick_text_desc": "メッセージ", "service_quick_text_title": "%1$sからのメッセージ",
    "library_title": "ライブラリ", "library_header_title": "ファイル",
    "library_header_body": "共有中のもの。", "library_header_subtitles": "字幕を追加できます。",
    "library_info_items": "アイテム", "library_info_folders": "フォルダ", "library_info_size": "サイズ",
    "library_empty_title": "空", "library_empty_body": "追加してください。", "library_section_folders": "フォルダ",
    "library_section_folders_body": "共有フォルダ。", "library_empty_filter_title": "なし",
    "library_empty_filter_body": "フィルターを変更。", "library_section_files": "ファイル", "library_single_file_name": "ファイル",
    "library_selected_files_name": "選択済", "library_save_selected_title": "保存",
    "library_save_selected_body": "後で使う。", "library_share_name": "名前", "library_manage_title": "管理",
    "library_manage_body": "ファイルを整理。", "library_selection_title": "新しい選択",
    "library_selection_step_1": "1. 選択。", "library_selection_step_2": "2. 完了。",
    "library_search_label": "検索...", "library_show_title": "表示", "library_show_body": "フィルター",
    "library_category_all": "すべて", "library_category_videos": "動画", "library_category_photos": "写真",
    "library_category_music": "音楽", "library_category_files": "ファイル", "library_add_title": "追加",
    "library_add_body": "スマホから。", "library_add_files": "ファイル", "library_add_whole_folder": "フォルダ",
    "library_add_from_suggestions": "ギャラリー", "library_organize_title": "並び替え",
    "library_organize_body": "順序を選択。", "library_sort_prefix": "順序: %1$s",
    "library_clear_all_action": "すべてクリア", "plural:library_items_in_view": {"one": "1", "other": "%1$d"},
    "library_clear_all_title": "すべてクリア？", "library_clear_all_body": "リストが空になります。",
    "library_sort_newest": "新しい順", "library_sort_name": "名前", "library_sort_size": "サイズ",
    "library_cancel_selection": "キャンセル", "library_create_saved_share": "完了", "library_start_saved_share_selection": "選択",
    "library_browser_prep_title": "Webコピー", "library_browser_prep_body": "ブラウザ用の軽いファイル。",
    "library_folder_summary": "%1$d | %2$s", "library_unavailable": "利用不可", "library_direct_play": "直接再生",
    "library_subtitle": "字幕", "library_selected": "選択済", "library_tap_to_select": "タップ",
    "library_select_this_file": "はい", "library_preparing": "準備中", "library_preparing_for_browser": "キュー内",
    "library_ready": "完了", "library_ready_for_browser": "Web完了", "library_try_again": "もう一度",
    "library_try_browser_prep_again": "再試行", "library_prepare": "準備", "library_prepare_for_browser": "完了",
    "library_type_video": "動画", "library_type_photo": "写真", "library_type_music": "音楽", "library_type_file": "ファイル",
    "library_compat_ready_to_play": "完了 | %1$s", "library_compat_not_prepared": "未準備", "library_compat_queued": "キュー内",
    "library_compat_preparing": "処理中...", "library_compat_ready": "完了", "library_compat_unavailable": "非対応",
    "library_compat_message": "%1$s | %2$s", "selection_add_files_title": "選択", "selection_add_files_body": "何を共有しますか？",
    "selection_add_selected": "追加", "selection_pick_files_again": "変更", "selection_nothing_selected_title": "空",
    "selection_nothing_selected_body": "何か選んでください。", "selection_add_folder_title": "フォルダ",
    "selection_add_folder_body": "フォルダを選択。", "selection_add_folder": "完了",
    "selection_choose_another_folder": "変更", "selection_no_folder_title": "エラー",
    "selection_no_folder_body": "フォルダを選択。", "selection_selected_folder": "フォルダ", "selection_selected_item": "1",
    "selection_smart_picks_title": "日付", "selection_smart_picks_body": "準備済。",
    "selection_media_access_title": "許可", "selection_media_access_body": "許可を与えてください。",
    "selection_grant_access": "はい", "selection_loading_groups_title": "検索中...", "selection_loading_groups_body": "設定中...",
    "selection_no_groups_title": "なし", "selection_no_groups_body": "手動で追加。", "selection_refresh_groups": "更新",
    "selection_add_group": "プラス", "home_upload_request_title": "新しいファイル", "home_upload_request_single": "ファイル",
    "home_upload_request_files": "%1$d ファイル", "home_upload_request_body": "%1$s が %2$s を送信:",
    "home_upload_request_total_size": "サイズ: %1$s", "home_history_content_desc": "履歴",
    "home_settings_content_desc": "設定", "home_network_required_title": "ネットワーク",
    "home_network_required_body": "Wi-Fiまたはホットスポット。", "message_unable_add_folder": "エラー。",
    "message_saved_share_named": "保存済: '%1$s'", "message_unable_save_share": "失敗。",
    "message_saved_share_ready": "完了。", "home_all_files_access_title": "ドキュメント？",
    "home_all_files_access_body": "許可してください。", "home_all_files_access_grant": "はい",
    "home_all_files_access_media_only": "メディアのみ", "home_all_files_nudge_text": "すべてのファイル！",
    "message_unable_open_saved_share": "エラー。", "message_saved_share_removed": "削除済。",
    "message_something_went_wrong": "問題が発生。", "message_pin_on": "PINオン。", "message_pin_off": "PINオフ。",
    "message_debug_log_prepare_failed": "ログエラー。", "message_debug_log_cleared": "完了。",
    "message_debug_log_clear_failed": "エラー。", "message_file_no_longer_available": "消失。",
    "message_preparing_browser_playback": "Web %1$s。", "nearby_helper_tap_session": "タップ。",
    "nearby_helper_open_on_other_device": "開く。", "share_preset_enter_name": "名前:",
    "share_preset_add_content_first": "入れて。", "share_preset_select_file_first": "選択。",
    "share_preset_files_unavailable": "ファイルなし。", "share_preset_collection_unavailable": "なし。",
    "share_preset_restore_failed": "エラー。", "sharing_preflight_failed": "エラー: %1$s",
    "sharing_add_content_first": "ファイルを入れて。", "sharing_same_wifi_needed": "同じWi-Fi。",
    "sharing_connect_before_start": "接続して。", "sharing_server_start_failed": "エラー: %1$s",
    "sharing_blocked_by_live_screen": "画面共有をオフに。", "sharing_stopped": "停止済。",
    "sharing_device_android": "Android", "network_helper_wifi_ready": "Wi-Fi OK。",
    "network_helper_local_ready": "ローカル OK。", "network_helper_wifi_found": "IPあり。",
    "network_helper_hotspot_ready": "ホットスポット OK。", "network_helper_mobile_only": "データのみ。",
    "network_helper_local_address_ready": "IP OK。", "network_helper_connect_both": "一緒に接続。",
    "discovery_unavailable_device": "オフ。", "discovery_nsd_unavailable": "オフ。",
    "discovery_searching": "検索...", "discovery_unavailable_now": "QRのみ。",
    "discovery_start_failed": "エラー (%1$d)", "discovery_ready_to_open": "完了。",
    "browser_title": "DirectServe", "browser_subtitle": "ファイル", "browser_file_unavailable": "消失。",
    "browser_debug_unavailable": "オフ。", "browser_debug_missing_payload": "空。", "browser_pin_mismatch": "PIN間違い。",
    "browser_device_blocked": "ブロック済。", "browser_enter_pin": "PIN:",
    "browser_optimized_unavailable": "Web非対応。", "browser_video_part_preparing": "作成中...",
    "browser_video_part_unavailable": "空。", "browser_hls_not_needed": "不要。",
    "browser_hls_not_ready": "未準備。", "home_action_add_to_share_title": "追加",
    "home_action_add_to_share_subtitle": "ファイル", "home_action_files": "ファイル", "home_action_files_desc": "はい",
    "home_action_folder": "フォルダ", "home_action_folder_desc": "はい", "home_action_library": "ライブラリ",
    "home_action_library_desc": "検索", "home_button_share_all_media": "すべて", "home_button_adding_all": "追加中...",
    "home_media_server_active": "すべてオン", "home_btn_stop_media_server": "ストップ", "web_folders_title": "フォルダ",
    "web_folder_items": "%1$d", "web_btn_back_to_folders": "戻る", "web_all_media": "メディア",
    "home_nearby_title": "周辺", "home_nearby_subtitle": "デバイス。",
    "home_nearby_refresh_status": "更新", "home_network_wifi": "Wi-Fi OK", "home_network_hotspot": "ホットスポット OK",
    "home_network_local": "ローカル OK", "home_network_none": "空", "home_network_ready_desc": "準備済。",
    "home_network_none_desc": "接続が必要。", "home_nearby_optional_title": "Appは任意",
    "home_nearby_optional_desc": "Webでも可。", "home_nearby_refresh": "検索",
    "home_nearby_open_title": "Appで", "home_nearby_open_desc": "あれば。",
    "home_nearby_action_open_session": "さあ", "home_nearby_action_open": "はい", "home_nearby_device_available": "完了",
    "home_nearby_device_pin": "PIN", "web_hero_eyebrow": "DirectServe", "web_hero_title": "あなたのメディア",
    "web_hero_desc1": "動画、写真。", "web_hero_desc2": "ファイル。", "web_hero_desc3": "プライベート。",
    "web_hero_stat_shared": "実行中", "web_items": "アイテム", "web_hero_stat_ready": "完了", "web_hero_stat_access": "許可",
    "web_access_pin": "ロック済", "web_access_instant": "オープン", "web_access_pin_desc": "PINが必要",
    "web_access_instant_desc": "完了", "web_pin_entry_kicker": "PIN", "web_pin_entry_title": "PIN入力",
    "web_pin_entry_desc": "画面に表示。", "web_pin_entry_placeholder": "PIN", "web_btn_videos": "動画",
    "web_btn_download_all_files": "すべてダウンロード", "web_cat_videos": "動画", "web_cat_photos": "写真",
    "web_cat_music": "音楽", "web_cat_files": "ファイル", "web_recent_title": "新規", "web_recent_meta": "完了",
    "web_nav_home": "ホーム", "web_nav_drop_zone": "ドロップ", "web_nav_logout": "ログアウト", "web_nav_media": "メディア",
    "web_nav_files": "ファイル", "web_nav_send": "送信", "web_strip_session": "セッション", "web_strip_device": "私たち",
    "web_strip_link": "リンク", "web_security_pin": "PIN", "web_security_open": "オフ", "web_status_unknown": "?",
    "home_connected_devices": "接続済", "home_rename_device": "名前", "home_rename_device_subtitle": "%1$s • %2$s",
    "home_rename_custom_name": "新規", "home_rename_save": "完了", "home_rename_cancel": "キャンセル", "home_quick_filters": "フィルター",
    "home_quick_filter_today": "今日", "home_quick_filter_today_desc": "24時間", "home_quick_filter_week": "今週",
    "home_quick_filter_week_desc": "7日間", "home_quick_filter_month": "今月", "home_quick_filter_month_desc": "30日間",
    "home_quick_filter_custom": "時間", "home_quick_filter_custom_desc": "選択", "home_date_range_title": "日",
    "home_date_range_from": "開始", "home_date_range_start": "開始", "home_date_range_to": "終了",
    "home_date_range_end": "終了", "home_date_range_tip": "いいね。", "home_date_range_apply": "OK",
    "home_date_range_cancel": "キャンセル", "home_recent_shares": "古い", "home_section_library": "ファイル",
    "home_section_live_tools": "ツール", "home_section_network_tv": "TV", "home_section_sharing": "アクション",
    "home_section_live_features": "エクストラ", "home_feature_library": "ライブラリ", "home_feature_library_desc": "セット。",
    "home_feature_transfers": "転送", "home_feature_transfers_desc": "ダウンロード。", "home_feature_share_files": "共有",
    "home_feature_share_files_desc": "すべて。", "home_feature_receive_files": "受信",
    "home_feature_receive_files_desc": "はい。", "home_feature_play_media": "再生",
    "home_feature_play_media_desc": "Web。", "home_feature_play_media_live": "はい。", "home_feature_dlna": "DLNA",
    "home_feature_dlna_desc": "TV。", "home_feature_dlna_enabled": "オン。", "home_feature_live_screen": "画面",
    "home_feature_live_screen_desc": "ミラー。", "home_feature_quick_text": "テキスト", "home_feature_quick_text_desc": "はい。",
    "home_saved_shares": "コレクション", "home_saved_shares_save_now": "保存", "home_saved_shares_open": "開く",
    "home_saved_shares_delete": "削除", "plural:home_saved_shares_items_count": {"one": "1", "other": "%1$d"},
    "library_date_group_label": "%1$s", "web_upload_title": "アップロード", "web_upload_subtitle": "スマホへ。",
    "web_upload_prompt_title": "ファイルを", "web_upload_prompt_desktop": "ドラッグ。",
    "web_upload_prompt_mobile": "タップ。", "web_upload_button_browse": "検索",
    "web_upload_button_photos": "写真", "web_upload_button_any_file": "ファイル", "web_upload_target_kicker": "スマホ",
    "web_upload_target_status": "完了。", "web_upload_how_kicker": "はい", "web_upload_how_title": "許可",
    "web_upload_how_body": "同意が必要。", "web_action_download": "ダウンロード", "web_action_view": "見る",
    "web_photo_view": "見る", "web_btn_download_all": "すべてダウンロード", "web_btn_download_selected": "ダウンロード",
    "web_btn_download_original": "オリジナル", "web_btn_fullscreen": "フルスクリーン", "web_error_streaming_codec": "動かない。ダウンロードして。",
    "web_error_downloads_disabled": "オフ。", "web_error_video_decode": "エラー。ダウンロード。",
    "web_error_video_start": "エラー。ダウンロード。", "web_error_video_start_no_dl": "修正中...",
    "web_error_load_failed": "エラー。", "web_btn_select_files": "選択", "web_status_selection_on": "オン",
    "web_btn_select_all": "すべて", "web_btn_clear_selection": "キャンセル", "web_player_slow_start_hint": "お待ちを...",
    "web_selection_count": "%1$d", "web_library_desc_download": "見るか取るか。", "web_library_desc_browse": "すべてここに。",
    "web_btn_load_more": "もっと", "web_btn_show_all": "すべて", "web_btn_showing_all": "取得中...",
    "web_show_all_confirm": "すべて %1$d？", "web_library_showing_count": "%1$d / %2$d",
    "web_search_placeholder": "名前...", "web_library_empty": "空。", "web_upload_selection_empty": "なし。",
    "web_upload_selection_single": "%1$s", "web_upload_selection_multiple": "%1$d", "web_upload_button_send": "送信",
    "common_quick_filters": "フィルター", "common_edit_nickname": "名前", "home_quick_filters_desc": "日。",
    "home_date_range_body": "日。", "web_upload_requesting": "リクエスト中...", "web_upload_waiting": "待機中...",
    "web_upload_denied": "拒否。", "web_upload_failed_status": "エラー (%1$d)",
    "web_upload_network_error": "ネットワーク。", "web_upload_cancelled": "キャンセル済。", "web_upload_success_title": "入った",
    "web_upload_success_detail_single": "完了。", "web_upload_success_detail_multiple": "完了。",
    "web_upload_failed_title": "いいえ", "web_upload_failed_detail": "エラー。", "web_player_error_open": "失敗",
    "web_player_opening": "開始...", "web_player_ready": "準備完了", "web_player_analyzing": "確認中...",
    "web_player_finalizing": "終了...", "web_player_stalled": "停止", "web_player_starting": "さあ...",
    "web_player_wait_desc": "少々...", "web_player_ready_desc": "再生。", "web_player_analyzing_desc": "検索...",
    "web_player_finalizing_desc": "もうすぐ...", "web_player_stalled_desc": "重い。",
    "web_player_needs_prepare": "Webが必要", "web_player_needs_prepare_desc": "スマホで。",
    "web_player_starting_desc": "開始...", "web_player_try_again": "もう一度", "web_player_status_opening": "開始",
    "web_player_status_ready": "OK", "web_player_status_analyzing": "チェック", "web_player_status_finalizing": "終了",
    "web_player_status_stalled": "詰まり", "web_player_status_playing": "再生中", "web_player_progress_preparing": "待機",
    "web_player_progress_converting": "書き込み", "web_player_status_failed": "失敗", "web_player_status_stopped": "ストップ",
    "web_prepare_video": "Web", "web_progress_percent": "%1$d%%", "web_media_quick_title": "メディア",
    "web_media_quick_subtitle": "入れる。", "web_media_open_category": "%1$s", "web_media_empty": "空。",
    "web_send_files_to_device": "送信", "web_upload_in_progress": "進行中...", "web_upload_complete": "完了",
    "web_upload_failed": "失敗", "web_cancel": "キャンセル", "web_upload_preparing_transfer": "準備中...",
    "web_upload_connecting": "接続中...", "web_btn_back": "戻る", "web_status_subtitles_available": "字幕",
    "web_now_playing": "Playing", "common_resume": "再開", "web_status_init_progress": "0%",
    "common_play": "再生", "common_pause": "一時停止", "common_unit_b": "B", "common_unit_kb": "KB",
    "common_unit_mb": "MB", "common_unit_gb": "GB", "common_unit_tb": "TB", "common_unit_s": "秒",
    "common_unit_m": "分", "common_unit_h": "時", "common_byte_format_decimal": "%1$.1f %2$s",
    "common_byte_format_integer": "%1$d %2$s", "common_duration_format_m_s": "%1$d分 %2$d秒",
    "common_duration_format_h_m": "%1$d時 %2$d分", "common_duration_format_s": "%1$d秒",
    "common_duration_timestamp_m_s": "%1$d:%2$02d", "common_duration_timestamp_h_m_s": "%1$d:%2$02d:%3$02d",
    "service_file_index_pattern": "%1$s (%2$d/%3$d)", "service_upload_progress_subtext_pattern": "%1$s / %2$s",
    "help_section_media_server": "サーバー", "help_line_media_server_1": "ハブ。",
    "help_line_media_server_2": "整理。", "help_section_folders_nav": "フォルダ",
    "help_line_folders_1": "そのまま。", "help_line_folders_2": "クリーン。", "help_section_dlna_tv": "TV",
    "help_line_dlna_1": "スマート。", "help_line_dlna_2": "DirectServe。", "help_line_dlna_3": "ネットワーク。",
    "help_line_dlna_4": "VLC OK。", "help_section_search_sticky": "検索", "help_line_search_1": "速い。",
    "help_line_search_2": "上。", "settings_dlna": "DLNA TV", "settings_dlna_desc": "TV/VLC。",
    "dlna_server_name": "DirectServe", "dlna_server_name_template": "DirectServe (%1$s)",
    "web_action_download_zip": "ZIP", "web_btn_download_all_zip": "すべてZIP",
    "web_btn_download_selected_zip": "ZIP取得", "web_error_no_items_selected": "空。",
    "web_download_started_hint": "包む...", "playback_mode_direct": "Direct Play",
    "playback_mode_repackaging": "箱", "playback_mode_transcoding": "重い",
    "playback_mode_analyzing": "チェック", "compatibility_message_cached_ready": "準備済。",
    "compatibility_message_stopped": "ストップ。", "compatibility_message_validation_failed": "エラー: %1$s",
    "compatibility_message_adjusted": "完了。", "compatibility_message_optimizing": "準備中...",
    "compatibility_message_almost_ready": "すぐに...", "compatibility_message_ready": "完了。",
    "compatibility_message_analyzing": "見る...", "compatibility_message_finalizing_optimized": "最後...",
    "compatibility_message_finalizing_compatible": "最後...", "compatibility_message_optimizing_web": "Web...",
    "compatibility_message_repackaging_web": "包む...", "compatibility_message_converting_web": "変換...",
}

# KOREAN (ko)
ko_data = {
    "common_back": "뒤로", "common_cancel": "취소", "common_save": "저장", "common_delete": "삭제",
    "common_open": "열기", "common_refresh": "새로고침", "common_continue": "계속", "common_accept": "수락",
    "common_decline": "거절", "common_dismiss": "닫기", "common_remove": "제거", "common_search": "검색",
    "common_separator_pipe": " | ", "common_separator_dot": " • ", "onboarding_skip": "건너뛰기",
    "onboarding_title": "DirectServe",
    "onboarding_subtitle": "휴대폰을 로컬 허브로 만드세요.",
    "onboarding_page_1_title": "어떤 화면에서든 보기",
    "onboarding_page_1_description": "클라우드 없이 동영상과 사진을 감상하세요.",
    "onboarding_page_2_title": "모든 디바이스 호환",
    "onboarding_page_2_description": "브라우저만 있으면 됩니다.",
    "onboarding_page_3_title": "브라우저에서 접속",
    "onboarding_page_3_description": "링크나 QR 코드로 연결.",
    "onboarding_page_4_title": "양방향 공유",
    "onboarding_page_4_description": "파일을 쉽게 보내고 받으세요.",
    "onboarding_page_5_title": "인터넷 필요 없음",
    "onboarding_page_5_description": "Wi-Fi나 핫스팟으로 동작.",
    "onboarding_page_6_title": "완벽한 프라이버시",
    "onboarding_page_6_description": "파일은 휴대폰에 남습니다.",
    "onboarding_page_counter": "%1$d / %2$d", "onboarding_next": "다음", "onboarding_get_started": "시작하기",
    "settings_title": "설정", "settings_subtitle": "DirectServe 맞춤 설정",
    "settings_group_general": "일반", "settings_group_notifications": "알림", "settings_group_privacy": "프라이버시",
    "settings_group_browser": "브라우저", "settings_group_advanced": "고급", "settings_group_network": "네트워크",
    "settings_group_help": "도움말", "settings_group_debug": "디버그", "settings_language": "언어",
    "settings_theme": "테마", "settings_theme_subtitle": "디자인 변경", "settings_theme_system": "시스템",
    "settings_theme_dark": "다크", "settings_theme_light": "라이트", "settings_keep_screen_awake": "화면 켜짐 유지",
    "settings_keep_screen_awake_desc": "공유 중 화면 꺼짐 방지.",
    "settings_vibrate_on_connect": "연결 시 진동", "settings_vibrate_on_connect_desc": "누군가 연결될 때.",
    "settings_show_speed": "속도 표시", "settings_show_speed_desc": "실시간 전송 속도.",
    "settings_show_recent_shares": "최근 항목 표시", "settings_show_recent_shares_desc": "로컬 기록 저장.",
    "settings_auto_stop": "자동 중지", "settings_auto_stop_never": "안 함", "settings_auto_stop_15m": "15분",
    "settings_auto_stop_30m": "30분", "settings_auto_stop_1h": "1시간", "settings_connection_alerts": "연결 알림",
    "settings_connection_alerts_desc": "디바이스 접속 시.",
    "settings_download_alerts": "다운로드 알림", "settings_download_alerts_desc": "파일 다운로드 시.",
    "settings_upload_requests": "업로드 요청", "settings_upload_requests_desc": "파일 수신 전 확인.",
    "settings_quick_text_enabled": "빠른 텍스트", "settings_quick_text_enabled_desc": "메시지 공유.",
    "settings_quick_text_alerts": "메시지 알림", "settings_quick_text_alerts_desc": "메시지 수신 시.",
    "settings_use_pin": "PIN 사용", "settings_use_pin_desc": "보안을 위해.",
    "settings_new_pin_each_time": "매번 새 PIN", "settings_new_pin_each_time_desc": "강력한 보안.",
    "settings_pin_label": "PIN", "settings_pin_placeholder": "4-6자리", "settings_approve_file_uploads": "업로드 승인",
    "settings_approve_file_uploads_desc": "수신 전 허락.",
    "settings_approve_per_device": "디바이스별 승인", "settings_approve_per_device_desc": "한 번만 승인.",
    "settings_received_files_location": "다운로드 폴더", "settings_received_files_location_value": "다운로드",
    "settings_show_thumbnails": "썸네일 표시", "settings_show_thumbnails_desc": "미디어 미리보기.",
    "settings_large_tv_layout": "TV 레이아웃", "settings_large_tv_layout_desc": "큰 버튼.",
    "settings_highlight_downloads": "다운로드 강조", "settings_highlight_downloads_desc": "명확하게.",
    "settings_sign_out_on_stop": "중지 시 로그아웃", "settings_sign_out_on_stop_desc": "연결 해제.",
    "settings_clear_temporary_files": "임시 파일 삭제", "settings_clear_temporary_files_desc": "최적화 파일 지우기.",
    "settings_prevent_downloads": "다운로드 방지", "settings_prevent_downloads_desc": "시청만 허용.",
    "settings_auto_optimize_library": "백그라운드 최적화", "settings_auto_optimize_library_desc": "배터리 소모.",
    "settings_sharing_port": "포트", "settings_sharing_port_placeholder": "43183",
    "settings_sharing_port_help": "변경하지 마세요.",
    "settings_wifi_settings": "Wi-Fi 설정", "settings_wifi_settings_desc": "같은 네트워크에.",
    "settings_hotspot_settings": "핫스팟 설정", "settings_hotspot_settings_desc": "로컬 네트워크.",
    "settings_view_onboarding": "튜토리얼 보기", "settings_view_onboarding_desc": "다시 보기.",
    "settings_privacy_policy": "개인정보처리방침", "settings_privacy_policy_desc": "로컬 프라이버시.",
    "settings_privacy_promise": "약속", "settings_privacy_promise_desc": "안전합니다.",
    "settings_how_it_works": "사용 방법", "settings_how_it_works_desc": "도움말.",
    "settings_app_version": "버전", "settings_recent_shares_count": "컬렉션: %1$d",
    "settings_share_debug_log": "디버그 로그 전송", "settings_share_debug_log_desc": "문제 신고.",
    "settings_clear_debug_log": "로그 지우기",
    "help_title": "도움말", "help_about_title": "정보",
    "help_about_1": "브라우저로 파일 열기.",
    "help_about_2": "앱 설치 불필요.",
    "help_about_3": "인터넷, 클라우드 불필요.",
    "help_section_what_you_can_do": "할 수 있는 일", "help_section_video_playback": "비디오 재생",
    "help_section_browser_preparation": "웹 최적화", "help_section_receiving_files": "파일 수신",
    "help_section_drop_zone": "파일 전송", "help_section_multiple_devices": "여러 디바이스",
    "help_section_privacy_controls": "프라이버시", "help_section_good_to_know": "알아두기",
    "help_section_quick_flow": "빠른 시작", "help_line_share_files": "파일, 폴더 공유.",
    "help_line_open_session": "브라우저에서 접속.",
    "help_line_same_network": "같은 Wi-Fi 사용.",
    "help_line_multiple_browse": "동시 접속.",
    "help_line_video_direct": "비디오 직접 재생.",
    "help_line_video_temporary": "포맷 변환 필요할 수도.",
    "help_line_video_original": "원본은 안전.",
    "help_line_prep_optional": "최적화는 선택.",
    "help_line_prep_control": "언제든 중지.",
    "help_line_prep_batch": "휴대폰 발열 주의.",
    "help_line_receive_upload": "다른 사람이 파일 전송.",
    "help_line_receive_approval": "수신 승인.",
    "help_line_receive_history": "다운로드 폴더 저장.",
    "help_line_drop_zone": "드래그 앤 드롭.",
    "help_line_drop_zone_pick": "수동 선택.", "help_line_drop_zone_local": "100% 로컬.",
    "help_line_multi_connect": "다수 디바이스.",
    "help_line_multi_live": "화면에 표시.",
    "help_line_multi_controls": "필요시 차단.",
    "help_line_privacy_local": "계정 불필요.",
    "help_line_privacy_session": "선택한 것만 공유.",
    "help_line_privacy_controls": "완전한 제어.",
    "help_line_wifi_hotspot": "Wi-Fi 또는 핫스팟.",
    "help_line_public_wifi": "핫스팟 권장.",
    "help_line_downloads_disabled": "다운로드 차단 가능.",
    "help_line_flow_1": "1. 파일 선택.", "help_line_flow_2": "2. 세션 시작.",
    "help_line_flow_3": "3. QR 스캔.", "help_line_flow_4": "4. 시청.",
    "home_brand_title": "DirectServe", "home_brand_subtitle": "프라이빗 공유",
    "home_chip_local_session": "로컬", "home_chip_sharing": "공유 중", "home_chip_ready": "준비됨",
    "home_chip_setup_needed": "네트워크 필요", "home_live_banner": "라이브 세션",
    "home_title_live": "공유 활성", "home_title_start": "현재 공유",
    "home_body_live": "다른 디바이스가 연결 가능.", "home_body_start": "파일을 추가하세요.",
    "home_body_start_secondary": "라이브러리 사용.",
    "home_button_start_session": "시작", "home_button_open_session": "열기",
    "home_button_starting": "시작 중...", "home_button_add_media": "추가", "home_button_add_more": "더 추가",
    "home_summary_current_share": "총", "home_summary_media": "미디어", "home_summary_files": "파일",
    "home_content_filter_title": "공유 중", "home_content_filter_subtitle": "브라우저 표시",
    "home_content_filter_videos": "비디오", "home_content_filter_music": "음악", "home_content_filter_photos": "사진",
    "home_content_filter_files": "파일", "home_no_network": "Wi-Fi 없음",
    "network_setup_title": "네트워크 필요", "network_setup_body": "같은 네트워크여야 합니다.",
    "network_setup_trouble_title": "문제 있나요?",
    "network_setup_trouble_body": "핫스팟 사용.",
    "network_setup_open_wifi": "Wi-Fi", "network_setup_switch_hotspot": "핫스팟",
    "network_setup_retry": "재시도", "network_setup_footer": "빠르고 안정적.",
    "session_title": "라이브 세션", "session_stop_sharing": "중지", "session_live_now": "라이브",
    "session_live_now_subtitle": "네트워크에 보입니다.", "session_share_live": "세션 활성",
    "session_share_preparing": "준비 중...", "session_share_live_body": "QR 코드 스캔.",
    "session_qr_title": "스캔", "session_qr_body": "모든 디바이스.",
    "session_qr_preparing": "생성 중", "session_browser_prep_title": "웹 최적화",
    "session_browser_prep_active": "%1$d%% • 완료 %2$d / %3$d", "session_browser_prep_queued": "대기 %1$d",
    "session_browser_prep_ready": "%1$d 완료", "session_browser_prep_message_active": "처리 중...",
    "session_browser_prep_message_queued": "대기", "session_browser_prep_message_ready": "완료",
    "session_browser_prep_message_manual": "작업 필요",
    "session_browser_prep_manual_note": "브라우저 재생이 안될 수 있음.",
    "session_prepare_browser_files": "준비", "session_stop_browser_files": "중지",
    "session_library_refresh_title": "새로고침",
    "session_library_refresh_pending": "%1$d 파일 대기 중.",
    "session_library_refresh_up_to_date": "최신 상태.", "session_refresh_library": "지금 새로고침",
    "message_live_library_refreshed_updates": "%1$d 추가됨.",
    "message_live_library_refreshed_current": "이미 업데이트됨.",
    "message_browser_playback_queued_all": "대기열 추가.",
    "message_browser_playback_already_ready": "이미 완료.", "message_browser_playback_stopped": "중지됨.",
    "library_importing_title": "가져오는 중", "library_importing_body": "기다려 주세요...",
    "session_waiting_local_link": "네트워크...", "session_qr_content_desc": "QR 코드",
    "session_share_link": "링크", "session_share_link_body": "같은 네트워크에서.", "session_network": "네트워크",
    "session_access_pin": "접속 PIN", "session_pin_off": "끄기", "session_new_pin": "신규",
    "session_turn_pin_on": "PIN 켜기", "session_turn_pin_off": "PIN 끄기", "session_nearby_name": "이름",
    "session_what_happens_now": "상태", "session_waiting_ready": "대기 중...",
    "session_waiting_first_device": "디바이스를 기다립니다...", "session_devices_connected_now": "%1$d 연결됨.",
    "session_friendly_local_name": "로컬 이름", "session_copy_link": "복사", "session_share": "공유",
    "session_metric_devices": "디바이스", "session_metric_sent": "전송됨", "session_metric_speed": "속도",
    "session_metric_elapsed": "시간", "session_metric_remaining": "남음", "session_connected_waiting": "대기 중...",
    "session_connected_title": "연결됨", "session_connected_waiting_body": "여기에 표시됨.",
    "session_connected_count": "%1$d 활성.", "session_disconnect_all": "모두 연결 해제",
    "session_no_devices": "아직 없음.", "session_block_device": "차단",
    "session_block": "차단", "session_blocked_title": "차단됨", "session_unblock_device": "차단 해제",
    "session_unblock": "해제", "session_state_sharing_now": "활성", "session_state_preparing": "준비 중",
    "session_state_network_needed": "네트워크 필요", "session_network_hotspot": "핫스팟", "session_network_wifi": "Wi-Fi",
    "session_network_local": "로컬", "session_network_offline": "오프라인", "history_title": "기록",
    "history_tab_all": "전체", "history_tab_received": "수신됨", "history_empty_all": "비었음.",
    "history_empty_received": "비었음.", "history_sent": "송신", "history_received": "수신",
    "history_open": "열기", "history_delete": "삭제", "history_delete_desc": "기록 삭제",
    "history_date_time_format": "%1$s %2$s", "splash_title": "DirectServe", "splash_subtitle": "프라이빗 공유",
    "privacy_policy_title": "개인정보", "privacy_policy_intro": "안전합니다.",
    "privacy_policy_line_1": "가입 없음.", "privacy_policy_line_2": "클라우드 없음.",
    "privacy_policy_line_3": "로컬만.", "privacy_policy_line_4": "안전.",
    "main_service_background_protection_failed": "백그라운드 시작 실패.",
    "main_notification_permission_warning": "알림 권한 필요.",
    "main_batch_media_access_needed": "미디어 권한 필요.", "main_debug_log_subject": "디버그 로그",
    "main_debug_log_body": "전송됨.", "main_debug_log_chooser": "보내기...",
    "main_no_email_app": "메일 앱 없음.", "main_no_browser_app": "브라우저 없음.",
    "main_no_file_app": "파일 앱 없음.", "main_link_copied": "복사됨.",
    "main_link_preparing": "기다리세요...", "main_share_link_chooser": "공유...",
    "main_link_not_ready": "준비 안됨.", "main_not_sharing": "꺼짐", "service_start_failed": "실패.",
    "service_auto_stop_message": "시간 초과.", "service_upload_request_title": "수신 파일",
    "service_upload_request_text": "%1$s (%3$s -> %2$s)", "service_upload_progress_title": "받는 중 %1$s",
    "service_upload_progress_text": "%1$d%% (%2$s)", "service_upload_progress_text_unknown": "보낸 사람 %1$s",
    "service_upload_success_title": "저장됨: %1$s", "service_upload_success_text": "보낸 사람 %1$s",
    "service_upload_success_subtext": "다운로드 폴더", "service_file_count": "%1$d 파일",
    "plural:service_new_devices_connected": {"one": "디바이스 연결", "other": "%1$d 디바이스 연결"},
    "plural:service_devices_joined": {"one": "%1$s 연결.", "other": "%1$s 연결 (%2$d)."},
    "service_waiting_for_devices": "대기 중...", "plural:service_devices_connected": {"one": "1 디바이스", "other": "%1$d 디바이스"},
    "service_preparing_browser_access": "웹 준비 중...", "service_channel_requests_name": "전송",
    "service_channel_requests_desc": "다운로드", "service_channel_connections_name": "연결",
    "service_channel_connections_desc": "디바이스", "service_channel_quick_text_name": "텍스트",
    "service_channel_quick_text_desc": "메시지", "service_quick_text_title": "%1$s의 메시지",
    "library_title": "라이브러리", "library_header_title": "파일",
    "library_header_body": "공유 중인 항목.", "library_header_subtitles": "자막 추가.",
    "library_info_items": "항목", "library_info_folders": "폴더", "library_info_size": "크기",
    "library_empty_title": "비었음", "library_empty_body": "추가하세요.", "library_section_folders": "폴더",
    "library_section_folders_body": "공유 폴더.", "library_empty_filter_title": "없음",
    "library_empty_filter_body": "필터 변경.", "library_section_files": "파일", "library_single_file_name": "파일",
    "library_selected_files_name": "선택됨", "library_save_selected_title": "저장",
    "library_save_selected_body": "나중에 사용.", "library_share_name": "이름", "library_manage_title": "관리",
    "library_manage_body": "파일 관리.", "library_selection_title": "새로운 선택",
    "library_selection_step_1": "1. 선택.", "library_selection_step_2": "2. 완료.",
    "library_search_label": "검색...", "library_show_title": "표시", "library_show_body": "필터",
    "library_category_all": "전체", "library_category_videos": "비디오", "library_category_photos": "사진",
    "library_category_music": "음악", "library_category_files": "파일", "library_add_title": "추가",
    "library_add_body": "휴대폰에서.", "library_add_files": "파일", "library_add_whole_folder": "폴더",
    "library_add_from_suggestions": "갤러리", "library_organize_title": "정렬",
    "library_organize_body": "순서 선택.", "library_sort_prefix": "정렬: %1$s",
    "library_clear_all_action": "모두 지우기", "plural:library_items_in_view": {"one": "1", "other": "%1$d"},
    "library_clear_all_title": "모두 지우기?", "library_clear_all_body": "목록이 비워집니다.",
    "library_sort_newest": "최신", "library_sort_name": "이름", "library_sort_size": "크기",
    "library_cancel_selection": "취소", "library_create_saved_share": "완료", "library_start_saved_share_selection": "선택",
    "library_browser_prep_title": "웹 복사", "library_browser_prep_body": "가벼운 파일.",
    "library_folder_summary": "%1$d | %2$s", "library_unavailable": "이용 불가", "library_direct_play": "직접 재생",
    "library_subtitle": "자막", "library_selected": "선택됨", "library_tap_to_select": "탭",
    "library_select_this_file": "예", "library_preparing": "준비 중", "library_preparing_for_browser": "대기",
    "library_ready": "완료", "library_ready_for_browser": "웹 완료", "library_try_again": "다시",
    "library_try_browser_prep_again": "재시도", "library_prepare": "준비", "library_prepare_for_browser": "완료",
    "library_type_video": "비디오", "library_type_photo": "사진", "library_type_music": "음악", "library_type_file": "파일",
    "library_compat_ready_to_play": "완료 | %1$s", "library_compat_not_prepared": "미준비", "library_compat_queued": "대기",
    "library_compat_preparing": "처리 중...", "library_compat_ready": "완료", "library_compat_unavailable": "지원 안됨",
    "library_compat_message": "%1$s | %2$s", "selection_add_files_title": "선택", "selection_add_files_body": "무엇을 공유할까요?",
    "selection_add_selected": "추가", "selection_pick_files_again": "변경", "selection_nothing_selected_title": "비었음",
    "selection_nothing_selected_body": "뭔가 선택하세요.", "selection_add_folder_title": "폴더",
    "selection_add_folder_body": "폴더 선택.", "selection_add_folder": "완료",
    "selection_choose_another_folder": "변경", "selection_no_folder_title": "에러",
    "selection_no_folder_body": "폴더 선택.", "selection_selected_folder": "폴더", "selection_selected_item": "1",
    "selection_smart_picks_title": "날짜", "selection_smart_picks_body": "준비됨.",
    "selection_media_access_title": "허가", "selection_media_access_body": "권한 허용.",
    "selection_grant_access": "예", "selection_loading_groups_title": "검색 중...", "selection_loading_groups_body": "설정 중...",
    "selection_no_groups_title": "없음", "selection_no_groups_body": "수동 추가.", "selection_refresh_groups": "새로고침",
    "selection_add_group": "플러스", "home_upload_request_title": "새 파일", "home_upload_request_single": "파일",
    "home_upload_request_files": "%1$d 파일", "home_upload_request_body": "%1$s 가 %2$s 전송:",
    "home_upload_request_total_size": "크기: %1$s", "home_history_content_desc": "기록",
    "home_settings_content_desc": "설정", "home_network_required_title": "네트워크",
    "home_network_required_body": "Wi-Fi 또는 핫스팟.", "message_unable_add_folder": "에러.",
    "message_saved_share_named": "저장: '%1$s'", "message_unable_save_share": "실패.",
    "message_saved_share_ready": "완료.", "home_all_files_access_title": "문서?",
    "home_all_files_access_body": "허가.", "home_all_files_access_grant": "예",
    "home_all_files_access_media_only": "미디어만", "home_all_files_nudge_text": "모든 파일!",
    "message_unable_open_saved_share": "에러.", "message_saved_share_removed": "삭제됨.",
    "message_something_went_wrong": "문제 발생.", "message_pin_on": "PIN 온.", "message_pin_off": "PIN 오프.",
    "message_debug_log_prepare_failed": "로그 에러.", "message_debug_log_cleared": "완료.",
    "message_debug_log_clear_failed": "에러.", "message_file_no_longer_available": "소실.",
    "message_preparing_browser_playback": "웹 %1$s.", "nearby_helper_tap_session": "탭.",
    "nearby_helper_open_on_other_device": "열기.", "share_preset_enter_name": "이름:",
    "share_preset_add_content_first": "넣어.", "share_preset_select_file_first": "선택.",
    "share_preset_files_unavailable": "파일 없음.", "share_preset_collection_unavailable": "없음.",
    "share_preset_restore_failed": "에러.", "sharing_preflight_failed": "에러: %1$s",
    "sharing_add_content_first": "파일 넣어.", "sharing_same_wifi_needed": "같은 Wi-Fi.",
    "sharing_connect_before_start": "연결.", "sharing_server_start_failed": "에러: %1$s",
    "sharing_blocked_by_live_screen": "화면 공유 끄기.", "sharing_stopped": "정지됨.",
    "sharing_device_android": "Android", "network_helper_wifi_ready": "Wi-Fi OK.",
    "network_helper_local_ready": "로컬 OK.", "network_helper_wifi_found": "IP 있음.",
    "network_helper_hotspot_ready": "핫스팟 OK.", "network_helper_mobile_only": "데이터뿐.",
    "network_helper_local_address_ready": "IP OK.", "network_helper_connect_both": "같이 연결.",
    "discovery_unavailable_device": "오프.", "discovery_nsd_unavailable": "오프.",
    "discovery_searching": "검색...", "discovery_unavailable_now": "QR뿐.",
    "discovery_start_failed": "에러 (%1$d)", "discovery_ready_to_open": "완료.",
    "browser_title": "DirectServe", "browser_subtitle": "파일", "browser_file_unavailable": "소실.",
    "browser_debug_unavailable": "오프.", "browser_debug_missing_payload": "빔.", "browser_pin_mismatch": "PIN 오답.",
    "browser_device_blocked": "차단됨.", "browser_enter_pin": "PIN:",
    "browser_optimized_unavailable": "웹 아님.", "browser_video_part_preparing": "작성 중...",
    "browser_video_part_unavailable": "빔.", "browser_hls_not_needed": "불필요.",
    "browser_hls_not_ready": "미준비.", "home_action_add_to_share_title": "추가",
    "home_action_add_to_share_subtitle": "파일", "home_action_files": "파일", "home_action_files_desc": "네",
    "home_action_folder": "폴더", "home_action_folder_desc": "네", "home_action_library": "라이브러리",
    "home_action_library_desc": "검색", "home_button_share_all_media": "모두", "home_button_adding_all": "추가 중...",
    "home_media_server_active": "모두 온", "home_btn_stop_media_server": "스톱", "web_folders_title": "폴더",
    "web_folder_items": "%1$d", "web_btn_back_to_folders": "뒤로", "web_all_media": "미디어",
    "home_nearby_title": "주변", "home_nearby_subtitle": "디바이스.",
    "home_nearby_refresh_status": "새로고침", "home_network_wifi": "Wi-Fi OK", "home_network_hotspot": "핫스팟 OK",
    "home_network_local": "로컬 OK", "home_network_none": "빔", "home_network_ready_desc": "준비됨.",
    "home_network_none_desc": "연결 필요.", "home_nearby_optional_title": "App은 선택",
    "home_nearby_optional_desc": "웹 가능.", "home_nearby_refresh": "검색",
    "home_nearby_open_title": "App에서", "home_nearby_open_desc": "있으면.",
    "home_nearby_action_open_session": "자", "home_nearby_action_open": "네", "home_nearby_device_available": "완료",
    "home_nearby_device_pin": "PIN", "web_hero_eyebrow": "DirectServe", "web_hero_title": "내 미디어",
    "web_hero_desc1": "비디오, 사진.", "web_hero_desc2": "파일.", "web_hero_desc3": "프라이빗.",
    "web_hero_stat_shared": "실행 중", "web_items": "아이템", "web_hero_stat_ready": "완료", "web_hero_stat_access": "허가",
    "web_access_pin": "잠김", "web_access_instant": "오픈", "web_access_pin_desc": "PIN 필요",
    "web_access_instant_desc": "완료", "web_pin_entry_kicker": "PIN", "web_pin_entry_title": "PIN 입력",
    "web_pin_entry_desc": "화면 표시.", "web_pin_entry_placeholder": "PIN", "web_btn_videos": "비디오",
    "web_btn_download_all_files": "모두 다운", "web_cat_videos": "비디오", "web_cat_photos": "사진",
    "web_cat_music": "음악", "web_cat_files": "파일", "web_recent_title": "신규", "web_recent_meta": "완료",
    "web_nav_home": "홈", "web_nav_drop_zone": "드롭", "web_nav_logout": "로그아웃", "web_nav_media": "미디어",
    "web_nav_files": "파일", "web_nav_send": "전송", "web_strip_session": "세션", "web_strip_device": "우리",
    "web_strip_link": "링크", "web_security_pin": "PIN", "web_security_open": "오프", "web_status_unknown": "?",
    "home_connected_devices": "접속됨", "home_rename_device": "이름", "home_rename_device_subtitle": "%1$s • %2$s",
    "home_rename_custom_name": "신규", "home_rename_save": "완료", "home_rename_cancel": "취소", "home_quick_filters": "필터",
    "home_quick_filter_today": "오늘", "home_quick_filter_today_desc": "24시간", "home_quick_filter_week": "이번 주",
    "home_quick_filter_week_desc": "7일", "home_quick_filter_month": "이번 달", "home_quick_filter_month_desc": "30일",
    "home_quick_filter_custom": "시간", "home_quick_filter_custom_desc": "선택", "home_date_range_title": "일",
    "home_date_range_from": "시작", "home_date_range_start": "시작", "home_date_range_to": "끝",
    "home_date_range_end": "끝", "home_date_range_tip": "좋아요.", "home_date_range_apply": "OK",
    "home_date_range_cancel": "취소", "home_recent_shares": "오래된", "home_section_library": "파일",
    "home_section_live_tools": "툴", "home_section_network_tv": "TV", "home_section_sharing": "액션",
    "home_section_live_features": "엑스트라", "home_feature_library": "라이브러리", "home_feature_library_desc": "셋.",
    "home_feature_transfers": "전송", "home_feature_transfers_desc": "다운로드.", "home_feature_share_files": "공유",
    "home_feature_share_files_desc": "모두.", "home_feature_receive_files": "수신",
    "home_feature_receive_files_desc": "네.", "home_feature_play_media": "재생",
    "home_feature_play_media_desc": "웹.", "home_feature_play_media_live": "네.", "home_feature_dlna": "DLNA",
    "home_feature_dlna_desc": "TV.", "home_feature_dlna_enabled": "온.", "home_feature_live_screen": "화면",
    "home_feature_live_screen_desc": "미러.", "home_feature_quick_text": "텍스트", "home_feature_quick_text_desc": "네.",
    "home_saved_shares": "컬렉션", "home_saved_shares_save_now": "저장", "home_saved_shares_open": "열기",
    "home_saved_shares_delete": "삭제", "plural:home_saved_shares_items_count": {"one": "1", "other": "%1$d"},
    "library_date_group_label": "%1$s", "web_upload_title": "업로드", "web_upload_subtitle": "스마트폰으로.",
    "web_upload_prompt_title": "파일을", "web_upload_prompt_desktop": "드래그.",
    "web_upload_prompt_mobile": "탭.", "web_upload_button_browse": "검색",
    "web_upload_button_photos": "사진", "web_upload_button_any_file": "파일", "web_upload_target_kicker": "스마트폰",
    "web_upload_target_status": "완료.", "web_upload_how_kicker": "네", "web_upload_how_title": "허가",
    "web_upload_how_body": "동의 필요.", "web_action_download": "다운로드", "web_action_view": "보기",
    "web_photo_view": "보기", "web_btn_download_all": "모두 다운", "web_btn_download_selected": "다운",
    "web_btn_download_original": "원본", "web_btn_fullscreen": "전체", "web_error_streaming_codec": "안됨. 다운.",
    "web_error_downloads_disabled": "오프.", "web_error_video_decode": "에러. 다운.",
    "web_error_video_start": "에러. 다운.", "web_error_video_start_no_dl": "수정 중...",
    "web_error_load_failed": "에러.", "web_btn_select_files": "선택", "web_status_selection_on": "온",
    "web_btn_select_all": "모두", "web_btn_clear_selection": "취소", "web_player_slow_start_hint": "기다려...",
    "web_selection_count": "%1$d", "web_library_desc_download": "보거나 가져가거나.", "web_library_desc_browse": "모두 여기.",
    "web_btn_load_more": "더", "web_btn_show_all": "모두", "web_btn_showing_all": "가져오는 중...",
    "web_show_all_confirm": "모두 %1$d?", "web_library_showing_count": "%1$d / %2$d",
    "web_search_placeholder": "이름...", "web_library_empty": "비었음.", "web_upload_selection_empty": "없음.",
    "web_upload_selection_single": "%1$s", "web_upload_selection_multiple": "%1$d", "web_upload_button_send": "전송",
    "common_quick_filters": "필터", "common_edit_nickname": "이름", "home_quick_filters_desc": "일.",
    "home_date_range_body": "일.", "web_upload_requesting": "요청 중...", "web_upload_waiting": "대기 중...",
    "web_upload_denied": "거절.", "web_upload_failed_status": "에러 (%1$d)",
    "web_upload_network_error": "네트워크.", "web_upload_cancelled": "취소됨.", "web_upload_success_title": "입력",
    "web_upload_success_detail_single": "완료.", "web_upload_success_detail_multiple": "완료.",
    "web_upload_failed_title": "아니", "web_upload_failed_detail": "에러.", "web_player_error_open": "실패",
    "web_player_opening": "시작...", "web_player_ready": "완료", "web_player_analyzing": "확인 중...",
    "web_player_finalizing": "종료...", "web_player_stalled": "정지", "web_player_starting": "자...",
    "web_player_wait_desc": "잠시만...", "web_player_ready_desc": "재생.", "web_player_analyzing_desc": "검색...",
    "web_player_finalizing_desc": "곧...", "web_player_stalled_desc": "무거움.",
    "web_player_needs_prepare": "Web 필요", "web_player_needs_prepare_desc": "스마트폰에서.",
    "web_player_starting_desc": "시작...", "web_player_try_again": "다시", "web_player_status_opening": "시작",
    "web_player_status_ready": "OK", "web_player_status_analyzing": "체크", "web_player_status_finalizing": "종료",
    "web_player_status_stalled": "막힘", "web_player_status_playing": "재생 중", "web_player_progress_preparing": "대기",
    "web_player_progress_converting": "쓰기", "web_player_status_failed": "실패", "web_player_status_stopped": "스톱",
    "web_prepare_video": "Web", "web_progress_percent": "%1$d%%", "web_media_quick_title": "미디어",
    "web_media_quick_subtitle": "넣기.", "web_media_open_category": "%1$s", "web_media_empty": "비었음.",
    "web_send_files_to_device": "전송", "web_upload_in_progress": "진행 중...", "web_upload_complete": "완료",
    "web_upload_failed": "실패", "web_cancel": "취소", "web_upload_preparing_transfer": "준비 중...",
    "web_upload_connecting": "접속 중...", "web_btn_back": "뒤로", "web_status_subtitles_available": "자막",
    "web_now_playing": "Playing", "common_resume": "재개", "web_status_init_progress": "0%",
    "common_play": "재생", "common_pause": "일시 정지", "common_unit_b": "B", "common_unit_kb": "KB",
    "common_unit_mb": "MB", "common_unit_gb": "GB", "common_unit_tb": "TB", "common_unit_s": "초",
    "common_unit_m": "분", "common_unit_h": "시", "common_byte_format_decimal": "%1$.1f %2$s",
    "common_byte_format_integer": "%1$d %2$s", "common_duration_format_m_s": "%1$d분 %2$d초",
    "common_duration_format_h_m": "%1$d시 %2$d분", "common_duration_format_s": "%1$d초",
    "common_duration_timestamp_m_s": "%1$d:%2$02d", "common_duration_timestamp_h_m_s": "%1$d:%2$02d:%3$02d",
    "service_file_index_pattern": "%1$s (%2$d/%3$d)", "service_upload_progress_subtext_pattern": "%1$s / %2$s",
    "help_section_media_server": "서버", "help_line_media_server_1": "허브.",
    "help_line_media_server_2": "정리.", "help_section_folders_nav": "폴더",
    "help_line_folders_1": "그대로.", "help_line_folders_2": "클린.", "help_section_dlna_tv": "TV",
    "help_line_dlna_1": "스마트.", "help_line_dlna_2": "DirectServe.", "help_line_dlna_3": "네트워크.",
    "help_line_dlna_4": "VLC OK.", "help_section_search_sticky": "검색", "help_line_search_1": "빠름.",
    "help_line_search_2": "위.", "settings_dlna": "DLNA TV", "settings_dlna_desc": "TV/VLC.",
    "dlna_server_name": "DirectServe", "dlna_server_name_template": "DirectServe (%1$s)",
    "web_action_download_zip": "ZIP", "web_btn_download_all_zip": "모두 ZIP",
    "web_btn_download_selected_zip": "ZIP 가져오기", "web_error_no_items_selected": "비었음.",
    "web_download_started_hint": "묶는 중...", "playback_mode_direct": "Direct Play",
    "playback_mode_repackaging": "박스", "playback_mode_transcoding": "무거움",
    "playback_mode_analyzing": "체크", "compatibility_message_cached_ready": "준비 완료.",
    "compatibility_message_stopped": "스톱.", "compatibility_message_validation_failed": "에러: %1$s",
    "compatibility_message_adjusted": "완료.", "compatibility_message_optimizing": "준비 중...",
    "compatibility_message_almost_ready": "곧...", "compatibility_message_ready": "완료.",
    "compatibility_message_analyzing": "보는 중...", "compatibility_message_finalizing_optimized": "끝...",
    "compatibility_message_finalizing_compatible": "끝...", "compatibility_message_optimizing_web": "Web...",
    "compatibility_message_repackaging_web": "묶는 중...", "compatibility_message_converting_web": "변환...",
}

# Apply batch
res_dir = "core/resources/src/main/res"
rebuild_locale(res_dir, "id", id_data)
rebuild_locale(res_dir, "in", id_data)
rebuild_locale(res_dir, "ja", ja_data)
rebuild_locale(res_dir, "ko", ko_data)
