import os
import xml.etree.ElementTree as ET

def rebuild_locale(res_dir, locale_name, translation_dict):
    base_path = os.path.join(res_dir, "values", "strings.xml")
    target_dir = os.path.join(res_dir, f"values-{locale_name}")
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)
        
    target_path = os.path.join(target_dir, "strings.xml")
    tree = ET.parse(base_path)
    root = tree.getroot()
    new_root = ET.Element('resources')
    
    for child in root:
        if child.tag == 'string':
            name = child.get('name')
            translatable = child.get('translatable', 'true')
            new_node = ET.SubElement(new_root, 'string', {'name': name})
            if translatable == 'false':
                new_node.set('translatable', 'false')
                new_node.text = child.text
            else:
                val = translation_dict.get(name)
                new_node.text = val if val else child.text
        elif child.tag == 'plurals':
            name = child.get('name')
            new_node = ET.SubElement(new_root, 'plurals', {'name': name})
            plural_data = translation_dict.get(f"plural:{name}", {})
            for item in child:
                qty = item.get('quantity')
                new_item = ET.SubElement(new_node, 'item', {'quantity': qty})
                val = plural_data.get(qty)
                new_item.text = val if val else item.text
        elif child.tag == 'string-array':
            name = child.get('name')
            new_node = ET.SubElement(new_root, 'string-array', {'name': name})
            array_data = translation_dict.get(f"array:{name}", [])
            for i, item in enumerate(child):
                new_item = ET.SubElement(new_node, 'item')
                if i < len(array_data):
                    new_item.text = array_data[i]
                else:
                    new_item.text = item.text

    ET.indent(new_root, space="    ", level=0)
    rough_string = ET.tostring(new_root, encoding='utf-8').decode('utf-8')
    with open(target_path, 'w', encoding='utf-8') as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n')
        f.write(rough_string)

# RUSSIAN (ru)
ru_data = {
    "common_back": "Назад", "common_cancel": "Отмена", "common_save": "Сохранить", "common_delete": "Удалить",
    "common_open": "Открыть", "common_refresh": "Обновить", "common_continue": "Продолжить", "common_accept": "Принять",
    "common_decline": "Отклонить", "common_dismiss": "Закрыть", "common_remove": "Убрать", "common_search": "Поиск",
    "common_separator_pipe": " | ", "common_separator_dot": " • ", "onboarding_skip": "Пропустить",
    "onboarding_title": "Прямая трансляция и передача файлов",
    "onboarding_subtitle": "Превратите телефон в частный центр для ТВ, ПК, планшетов и браузеров.",
    "onboarding_page_1_title": "Смотрите на любых устройствах",
    "onboarding_page_1_description": "Открывайте видео, фото и музыку на устройствах поблизости без загрузки в облако.",
    "onboarding_page_2_title": "Работает почти на любом экране",
    "onboarding_page_2_description": "ТВ, ноутбуки, iPhone, iPad, Mac, Windows, Android — через браузер.",
    "onboarding_page_3_title": "Подключение через браузер",
    "onboarding_page_3_description": "Нужна только локальная ссылка или QR-код. Дополнительные приложения не требуются.",
    "onboarding_page_4_title": "Двусторонний обмен",
    "onboarding_page_4_description": "Отправляйте файлы, принимайте от других и собирайте данные с подключенных устройств.",
    "onboarding_page_5_title": "Интернет не нужен",
    "onboarding_page_5_description": "Всё работает через ваш Wi-Fi или точку доступа. Быстро и приватно.",
    "onboarding_page_6_title": "Конфиденциально по умолчанию",
    "onboarding_page_6_description": "Данные остаются на устройстве. Без аккаунтов, без облака.",
    "onboarding_page_counter": "%1$d из %2$d", "onboarding_next": "Далее", "onboarding_get_started": "Начать",
    "settings_title": "Настройки", "settings_subtitle": "Настройте работу DirectServe.",
    "settings_group_general": "Общие", "settings_group_notifications": "Уведомления", "settings_group_privacy": "Конфиденциальность",
    "settings_group_browser": "Браузер", "settings_group_advanced": "Дополнительно", "settings_group_network": "Сеть",
    "settings_group_help": "Помощь", "settings_group_debug": "Отладка", "settings_language": "Язык",
    "settings_theme": "Тема", "settings_theme_subtitle": "Выберите оформление", "settings_theme_system": "Системная",
    "settings_theme_dark": "Тёмная", "settings_theme_light": "Светлая", "settings_keep_screen_awake": "Не выключать экран",
    "settings_keep_screen_awake_desc": "Экран не погаснет во время раздачи.",
    "settings_vibrate_on_connect": "Вибрация при подключении", "settings_vibrate_on_connect_desc": "Короткая вибрация, когда кто-то подключается.",
    "settings_show_speed": "Показывать скорость", "settings_show_speed_desc": "Отображает скорость передачи данных.",
    "settings_show_recent_shares": "Показывать недавние", "settings_show_recent_shares_desc": "Сохраняет короткую историю на устройстве.",
    "settings_auto_stop": "Авто-остановка", "settings_auto_stop_never": "Никогда", "settings_auto_stop_15m": "15 мин",
    "settings_auto_stop_30m": "30 мин", "settings_auto_stop_1h": "1 час", "settings_connection_alerts": "Уведомления о подключении",
    "settings_connection_alerts_desc": "Сообщает, когда новое устройство присоединяется.",
    "settings_download_alerts": "Уведомления о загрузке", "settings_download_alerts_desc": "Сообщает, когда кто-то скачивает файл.",
    "settings_upload_requests": "Запросы на загрузку", "settings_upload_requests_desc": "Спрашивать разрешение перед приёмом файлов.",
    "settings_quick_text_enabled": "Быстрый текст", "settings_quick_text_enabled_desc": "Обмен короткими сообщениями и ссылками.",
    "settings_quick_text_alerts": "Уведомления о текстах", "settings_quick_text_alerts_desc": "Сообщает при получении быстрого текста.",
    "settings_use_pin": "Использовать PIN-код", "settings_use_pin_desc": "Требует код перед доступом.",
    "settings_new_pin_each_time": "Новый PIN каждый раз", "settings_new_pin_each_time_desc": "Генерирует новый код для каждой сессии.",
    "settings_pin_label": "PIN-код", "settings_pin_placeholder": "4-6 цифр", "settings_approve_file_uploads": "Одобрять загрузки",
    "settings_approve_file_uploads_desc": "Требует разрешения перед тем, как браузеры загрузят файлы.",
    "settings_approve_per_device": "Одобрять для устройства", "settings_approve_per_device_desc": "Одобрять один раз для устройства, а не для каждого файла.",
    "settings_received_files_location": "Папка загрузок", "settings_received_files_location_value": "Загрузки",
    "settings_show_thumbnails": "Показывать миниатюры", "settings_show_thumbnails_desc": "Быстрый предпросмотр для медиафайлов.",
    "settings_large_tv_layout": "Интерфейс для ТВ", "settings_large_tv_layout_desc": "Увеличивает элементы для больших экранов.",
    "settings_highlight_downloads": "Выделять загрузки", "settings_highlight_downloads_desc": "Делает кнопки скачивания более заметными.",
    "settings_sign_out_on_stop": "Отключать при остановке", "settings_sign_out_on_stop_desc": "Закрывает доступ браузерам, когда сессия окончена.",
    "settings_clear_temporary_files": "Удалять временные файлы", "settings_clear_temporary_files_desc": "Удаляет оптимизированные файлы после сессии.",
    "settings_prevent_downloads": "Запретить скачивание", "settings_prevent_downloads_desc": "Отключает кнопку скачивания в браузере.",
    "settings_auto_optimize_library": "Фоновая оптимизация", "settings_auto_optimize_library_desc": "Подготавливает видео в фоне. Тратит батарею.",
    "settings_sharing_port": "Порт сети", "settings_sharing_port_placeholder": "43183",
    "settings_sharing_port_help": "Большинству пользователей не нужно это менять.",
    "settings_wifi_settings": "Настройки Wi-Fi", "settings_wifi_settings_desc": "Убедитесь, что оба устройства в одной сети.",
    "settings_hotspot_settings": "Настройки точки доступа", "settings_hotspot_settings_desc": "Используйте точку доступа, если Wi-Fi заблокирован.",
    "settings_view_onboarding": "Смотреть обучение", "settings_view_onboarding_desc": "Повторить шаги приветствия.",
    "settings_privacy_policy": "Политика конфиденциальности", "settings_privacy_policy_desc": "Читайте о локальной конфиденциальности.",
    "settings_privacy_promise": "Наше обещание", "settings_privacy_promise_desc": "Файлы никогда не покидают ваш телефон.",
    "settings_how_it_works": "Помощь и функции", "settings_how_it_works_desc": "Узнайте о воспроизведении, подготовке и загрузках.",
    "settings_app_version": "Версия приложения", "settings_recent_shares_count": "Сохранённые недавние раздачи: %1$d",
    "settings_share_debug_log": "Поделиться логом", "settings_share_debug_log_desc": "Отправить диагностический лог по email.",
    "settings_clear_debug_log": "Очистить лог",
    "help_title": "Помощь", "help_about_title": "О DirectServe",
    "help_about_1": "DirectServe позволяет устройствам открывать файлы в браузере без аккаунтов и интернета.",
    "help_about_2": "Любое устройство с Wi-Fi и браузером может подключиться.",
    "help_about_3": "Без облака. Без аккаунтов. Без интернета.",
    "help_section_what_you_can_do": "Что можно сделать", "help_section_video_playback": "Воспроизведение видео",
    "help_section_browser_preparation": "Оптимизация для браузера", "help_section_receiving_files": "Приём файлов",
    "help_section_drop_zone": "Зона загрузки", "help_section_multiple_devices": "Несколько устройств",
    "help_section_privacy_controls": "Конфиденциальность и контроль", "help_section_good_to_know": "Полезно знать",
    "help_section_quick_flow": "Быстрый старт", "help_line_share_files": "Делитесь видео, фото, музыкой, документами и папками.",
    "help_line_open_session": "Откройте сессию в браузере (Android, iOS, ПК, ТВ).",
    "help_line_same_network": "Устройства должны быть в одной сети Wi-Fi или точке доступа.",
    "help_line_multiple_browse": "Несколько устройств могут просматривать одновременно.",
    "help_line_video_direct": "Многие видео проигрываются напрямую.",
    "help_line_video_temporary": "Некоторым видео нужна оптимизация для плавности.",
    "help_line_video_original": "Оригинал никогда не изменяется.",
    "help_line_prep_optional": "Оптимизация опциональна для совместимости.",
    "help_line_prep_control": "Вы можете начать или остановить её в любой момент.",
    "help_line_prep_batch": "Много файлов могут нагреть телефон.",
    "help_line_receive_upload": "Другие могут отправлять вам файлы.",
    "help_line_receive_approval": "При включённом одобрении вы должны принимать каждый трансфер.",
    "help_line_receive_history": "Полученные файлы сохраняются в Загрузках.",
    "help_line_drop_zone": "В веб-приложении можно перетаскивать файлы.",
    "help_line_drop_zone_pick": "Или выбирать их вручную.", "help_line_drop_zone_local": "Загрузки локальные и приватные.",
    "help_line_multi_connect": "Несколько устройств одновременно.",
    "help_line_multi_live": "На экране сессии видно, кто подключён.",
    "help_line_multi_controls": "Блокируйте устройства или используйте PIN-код.",
    "help_line_privacy_local": "Без аккаунта и облачного хранилища.",
    "help_line_privacy_session": "Доступно только то, что вы выбрали.",
    "help_line_privacy_controls": "Остановите сессию или загрузки в любой момент.",
    "help_line_wifi_hotspot": "Используйте Wi-Fi или точку доступа.",
    "help_line_public_wifi": "Публичный Wi-Fi может блокировать трафик; точка доступа лучше.",
    "help_line_downloads_disabled": "Скачивание можно отключить в настройках.",
    "help_line_flow_1": "1. Добавьте файлы или папку.", "help_line_flow_2": "2. Начните сессию.",
    "help_line_flow_3": "3. Отсканируйте QR-код или откройте ссылку.", "help_line_flow_4": "4. Изучайте и смотрите.",
    "home_brand_title": "DirectServe", "home_brand_subtitle": "Приватный обмен по Wi-Fi",
    "home_chip_local_session": "Локальная сессия", "home_chip_sharing": "В процессе", "home_chip_ready": "Готово",
    "home_chip_setup_needed": "Нужна настройка", "home_live_banner": "Активная сессия в вашей сети",
    "home_title_live": "Раздача активна", "home_title_start": "Текущая раздача",
    "home_body_live": "Устройства поблизости могут подключиться.", "home_body_start": "Добавьте файлы, чтобы начать раздачу.",
    "home_body_start_secondary": "Используйте библиотеку или выберите файлы/папки.",
    "home_button_start_session": "Начать раздачу", "home_button_open_session": "Открыть сессию",
    "home_button_starting": "Запуск...", "home_button_add_media": "Добавить файлы", "home_button_add_more": "Добавить ещё",
    "home_summary_current_share": "В раздаче", "home_summary_media": "Медиа", "home_summary_files": "Файлы",
    "home_content_filter_title": "Что раздаётся", "home_content_filter_subtitle": "Типы файлов, видимые в браузере",
    "home_content_filter_videos": "Видео", "home_content_filter_music": "Музыка", "home_content_filter_photos": "Фото",
    "home_content_filter_files": "Файлы", "home_no_network": "Wi-Fi или Точка доступа не найдены",
    "network_setup_title": "Нужна локальная сеть", "network_setup_body": "Оба устройства должны быть в одной сети.",
    "network_setup_trouble_title": "Проблемы с публичным Wi-Fi?",
    "network_setup_trouble_body": "Некоторые сети блокируют локальный трафик. Точка доступа - лучшая альтернатива.",
    "network_setup_open_wifi": "Открыть Wi-Fi", "network_setup_switch_hotspot": "Точка доступа",
    "network_setup_retry": "Повторить", "network_setup_footer": "Точка доступа идеальна в пути.",
    "session_title": "Живая сессия", "session_stop_sharing": "Остановить раздачу", "session_live_now": "В эфире",
    "session_live_now_subtitle": "Ваша сессия видна устройствам.", "session_share_live": "Активная сессия",
    "session_share_preparing": "Подготовка сессии", "session_share_live_body": "Отсканируйте QR или откройте ссылку в браузере.",
    "session_qr_title": "Сканируйте для открытия", "session_qr_body": "Для мобильных, планшетов, ПК и ТВ.",
    "session_qr_preparing": "Создание QR", "session_browser_prep_title": "Оптимизация для веб",
    "session_browser_prep_active": "%1$d%% • Готово %2$d из %3$d", "session_browser_prep_queued": "В очереди %1$d",
    "session_browser_prep_ready": "%1$d файлов готовы для веб", "session_browser_prep_message_active": "Оптимизация...",
    "session_browser_prep_message_queued": "В очереди на подготовку", "session_browser_prep_message_ready": "Готово для веб",
    "session_browser_prep_message_manual": "Нужна ручная оптимизация",
    "session_browser_prep_manual_note": "Может не воспроизводиться плавно без подготовки.",
    "session_prepare_browser_files": "Оптимизировать", "session_stop_browser_files": "Остановить",
    "session_library_refresh_title": "Обновить раздачу",
    "session_library_refresh_pending": "%1$d файлов и %2$d папок готовы к добавлению.",
    "session_library_refresh_up_to_date": "Уже актуально.", "session_refresh_library": "Обновить",
    "message_live_library_refreshed_updates": "Добавлено: %1$d файлов, %2$d папок.",
    "message_live_library_refreshed_current": "Данные уже актуальны.",
    "message_browser_playback_queued_all": "Всё в очереди на оптимизацию.", "message_browser_playback_already_ready": "Уже оптимизировано.",
    "message_browser_playback_stopped": "Оптимизация остановлена.", "library_importing_title": "Импорт",
    "library_importing_body": "Добавление файлов в раздачу...", "session_waiting_local_link": "Ожидание сети",
    "session_qr_content_desc": "QR-код сессии", "session_share_link": "Локальная ссылка",
    "session_share_link_body": "Откройте в этой же сети.", "session_network": "Сеть", "session_access_pin": "PIN-код доступа",
    "session_pin_off": "Выкл", "session_new_pin": "Новый PIN", "session_turn_pin_on": "Включить PIN",
    "session_turn_pin_off": "Выключить PIN", "session_nearby_name": "Имя хоста", "session_what_happens_now": "Статус",
    "session_waiting_ready": "Подготовка сервера...", "session_waiting_first_device": "Ожидание первого подключения...",
    "session_devices_connected_now": "Подключено устройств: %1$d.", "session_friendly_local_name": "Локальное имя",
    "session_copy_link": "Копировать", "session_share": "Поделиться", "session_metric_devices": "Устройства",
    "session_metric_sent": "Отправлено", "session_metric_speed": "Скорость", "session_metric_elapsed": "Время",
    "session_metric_remaining": "Осталось", "session_connected_waiting": "Ожидание...", "session_connected_title": "Подключенные",
    "session_connected_waiting_body": "Появятся здесь после подключения.", "session_connected_count": "Устройств активно: %1$d.",
    "session_disconnect_all": "Отключить всех", "session_no_devices": "Пока никого нет.",
    "session_block_device": "Заблокировать", "session_block": "Заблокировать", "session_blocked_title": "Заблокированные",
    "session_unblock_device": "Разблокировать", "session_unblock": "Разблокировать", "session_state_sharing_now": "В процессе",
    "session_state_preparing": "Подготовка", "session_state_network_needed": "Нет сети", "session_network_hotspot": "Точка доступа",
    "session_network_wifi": "Wi-Fi", "session_network_local": "Локально", "session_network_offline": "Офлайн",
    "history_title": "Недавняя активность", "history_tab_all": "Все", "history_tab_received": "Получено",
    "history_empty_all": "Пока нет активности.", "history_empty_received": "Нет полученных файлов.",
    "history_sent": "Отправлено", "history_received": "Получено", "history_open": "Открыть", "history_delete": "Удалить",
    "history_delete_desc": "Убрать из истории", "history_date_time_format": "%1$s в %2$s", "splash_title": "DirectServe",
    "splash_subtitle": "Приватный локальный обмен", "privacy_policy_title": "Конфиденциальность",
    "privacy_policy_intro": "Файлы остаются в вашей локальной сети. Без аккаунтов.",
    "privacy_policy_line_1": "Регистрация не нужна.", "privacy_policy_line_2": "Нет загрузки на внешние серверы.",
    "privacy_policy_line_3": "Доступ только во время активной сессии.", "privacy_policy_line_4": "Полный контроль над PIN и блокировками.",
    "main_service_background_protection_failed": "Служба не смогла запуститься в фоне.",
    "main_notification_permission_warning": "Требуется разрешение на уведомления.",
    "main_batch_media_access_needed": "Нужен доступ к медиа для Умных выборок.",
    "main_debug_log_subject": "Лог DirectServe", "main_debug_log_body": "Диагностический лог в приложении.",
    "main_debug_log_chooser": "Отправить лог", "main_no_email_app": "Приложение email не найдено.", "main_no_browser_app": "Браузер не найден.",
    "main_no_file_app": "Нет приложения для этого файла.", "main_link_copied": "Ссылка скопирована",
    "main_link_preparing": "Подготовка ссылки...", "main_share_link_chooser": "Поделиться ссылкой",
    "main_link_not_ready": "Ссылка недоступна.", "main_not_sharing": "Неактивно", "service_start_failed": "Не удалось запустить службу.",
    "service_auto_stop_message": "Остановка из-за бездействия.", "service_upload_request_title": "Входящая передача",
    "service_upload_request_text": "%1$s от %3$s к %2$s", "service_upload_progress_title": "Приём %1$s",
    "service_upload_progress_text": "%1$d%% (%2$s)", "service_upload_progress_text_unknown": "Приём от %1$s",
    "service_upload_success_title": "Сохранено: %1$s", "service_upload_success_text": "Получено от %1$s",
    "service_upload_success_subtext": "В папке Загрузки", "service_file_count": "%1$d файлов",
    "plural:service_new_devices_connected": {"one": "%1$d устройство подключилось", "other": "%1$d устройств подключилось"},
    "plural:service_devices_joined": {"one": "%1$s подключился.", "other": "%1$s подключился. Всего: %2$d."},
    "service_waiting_for_devices": "Ожидание...", "plural:service_devices_connected": {"one": "%1$d устройство", "other": "%1$d устройств"},
    "service_preparing_browser_access": "Подготовка для веб...", "service_channel_requests_name": "Передачи",
    "service_channel_requests_desc": "Запросы на файлы", "service_channel_connections_name": "Подключения",
    "service_channel_connections_desc": "Новые устройства", "service_channel_quick_text_name": "Быстрый текст",
    "service_channel_quick_text_desc": "Короткие сообщения", "service_quick_text_title": "Сообщение от %1$s",
    "library_title": "Управление раздачей", "library_header_title": "Текущий контент",
    "library_header_body": "Файлы, доступные в сессии.", "library_header_subtitles": "Добавьте субтитры .srt для плеера.",
    "library_info_items": "Элементы", "library_info_folders": "Папки", "library_info_size": "Размер", "library_empty_title": "Пусто",
    "library_empty_body": "Добавьте файлы для начала.", "library_section_folders": "Папки",
    "library_section_folders_body": "Связанные папки.", "library_empty_filter_title": "Нет результатов",
    "library_empty_filter_body": "Измените фильтр.", "library_section_files": "Файлы", "library_single_file_name": "Файл",
    "library_selected_files_name": "Выбранные", "library_save_selected_title": "Сохранить выборку",
    "library_save_selected_body": "Создать коллекцию на потом.", "library_share_name": "Имя", "library_manage_title": "Управление",
    "library_manage_body": "Добавление и удаление.", "library_selection_title": "Новая коллекция",
    "library_selection_step_1": "1. Выберите файлы.", "library_selection_step_2": "2. Создать из %1$d файлов.",
    "library_search_label": "Поиск...", "library_show_title": "Показать", "library_show_body": "Фильтр", "library_category_all": "Всё",
    "library_category_videos": "Видео", "library_category_photos": "Фото", "library_category_music": "Музыка",
    "library_category_files": "Файлы", "library_add_title": "Добавить", "library_add_body": "Просмотр локальных файлов.", "library_add_files": "Файлы",
    "library_add_whole_folder": "Папка", "library_add_from_suggestions": "Библиотека телефона", "library_organize_title": "Сортировка",
    "library_organize_body": "Сортировка и сохранение.", "library_sort_prefix": "Сортировка: %1$s", "library_clear_all_action": "Очистить всё",
    "plural:library_items_in_view": {"one": "%1$d элемент", "other": "%1$d элементов"}, "library_clear_all_title": "Очистить всё?",
    "library_clear_all_body": "Удалит всё из текущей раздачи.", "library_sort_newest": "Новые", "library_sort_name": "Имя",
    "library_sort_size": "Размер", "library_cancel_selection": "Отмена", "library_create_saved_share": "Сохранить",
    "library_start_saved_share_selection": "Выбрать", "library_browser_prep_title": "Копия для браузера",
    "library_browser_prep_body": "Создаёт лёгкую копию для браузера. Оригинал не меняется.",
    "library_folder_summary": "Файлов: %1$d | %2$s", "library_unavailable": "Недоступно", "library_direct_play": "Прямое воспроизведение",
    "library_subtitle": "Субтитры", "library_selected": "Выбрано", "library_tap_to_select": "Нажмите",
    "library_select_this_file": "Выбрать", "library_preparing": "Подготовка", "library_preparing_for_browser": "Оптимизация...",
    "library_ready": "Готово", "library_ready_for_browser": "Готово для веб", "library_try_again": "Повторить",
    "library_try_browser_prep_again": "Повторить оптимизацию", "library_prepare": "Оптимизировать", "library_prepare_for_browser": "Подготовить",
    "library_type_video": "Видео", "library_type_photo": "Фото", "library_type_music": "Музыка", "library_type_file": "Файл",
    "library_compat_ready_to_play": "Готово | %1$s", "library_compat_not_prepared": "Не оптимизировано", "library_compat_queued": "В очереди",
    "library_compat_preparing": "Подготовка", "library_compat_ready": "Готово", "library_compat_unavailable": "Не поддерживается",
    "library_compat_message": "%1$s | %2$s", "selection_add_files_title": "Выбрать файлы",
    "selection_add_files_body": "Выберите, чем хотите поделиться.", "selection_add_selected": "Добавить",
    "selection_pick_files_again": "Изменить выбор", "selection_nothing_selected_title": "Ничего не выбрано",
    "selection_nothing_selected_body": "Используйте инструмент для добавления.", "selection_add_folder_title": "Выбрать папку",
    "selection_add_folder_body": "Привязать всю папку.", "selection_add_folder": "Привязать",
    "selection_choose_another_folder": "Сменить папку", "selection_no_folder_title": "Нет папки",
    "selection_no_folder_body": "Привяжите локальные папки.", "selection_selected_folder": "Папка", "selection_selected_item": "Элемент",
    "selection_smart_picks_title": "Умные выборки", "selection_smart_picks_body": "Автоматические группы по дате.",
    "selection_media_access_title": "Требуется доступ", "selection_media_access_body": "Разрешите доступ для группировки контента.",
    "selection_grant_access": "Разрешить", "selection_loading_groups_title": "Сканирование...",
    "selection_loading_groups_body": "Организация библиотеки...", "selection_no_groups_title": "Нет групп",
    "selection_no_groups_body": "Добавьте файлы вручную.", "selection_refresh_groups": "Обновить", "selection_add_group": "Добавить",
    "home_upload_request_title": "Новая загрузка", "home_upload_request_single": "один файл",
    "home_upload_request_files": "%1$d файлов", "home_upload_request_body": "%1$s хочет отправить вам %2$s:",
    "home_upload_request_total_size": "Размер: %1$s", "home_history_content_desc": "История", "home_settings_content_desc": "Настройки",
    "home_network_required_title": "Требуется сеть", "home_network_required_body": "Используйте Wi-Fi или точку доступа.",
    "message_unable_add_folder": "Ошибка добавления папки.", "message_saved_share_named": "Сохранено как \"%1$s\".",
    "message_unable_save_share": "Ошибка при сохранении.", "message_saved_share_ready": "Коллекция готова (%1$d шт.).",
    "home_all_files_access_title": "Документы?", "home_all_files_access_body": "Разрешите полный доступ для отправки PDF и прочего.",
    "home_all_files_access_grant": "Разрешить", "home_all_files_access_media_only": "Только фото/видео",
    "home_all_files_nudge_text": "Поделитесь любым файлом с полным доступом!", "message_unable_open_saved_share": "Невозможно открыть.",
    "message_saved_share_removed": "Удалено.", "message_something_went_wrong": "Что-то пошло не так.",
    "message_pin_on": "PIN включён.", "message_pin_off": "PIN выключен.", "message_debug_log_prepare_failed": "Ошибка в логе.",
    "message_debug_log_cleared": "Лог очищен.", "message_debug_log_clear_failed": "Ошибка очистки лога.",
    "message_file_no_longer_available": "Файл не найден.", "message_preparing_browser_playback": "Оптимизация %1$s.",
    "nearby_helper_tap_session": "Нажмите, чтобы открыть в браузере.", "nearby_helper_open_on_other_device": "Откройте DirectServe на другом устройстве.",
    "share_preset_enter_name": "Введите имя.", "share_preset_add_content_first": "Сначала добавьте файлы.",
    "share_preset_select_file_first": "Выберите файлы.", "share_preset_files_unavailable": "Контент недоступен.",
    "share_preset_collection_unavailable": "Коллекция удалена.", "share_preset_restore_failed": "Ошибка восстановления.",
    "sharing_preflight_failed": "Ошибка: %1$s", "sharing_add_content_first": "Добавьте что-нибудь сначала.",
    "sharing_same_wifi_needed": "Используйте одну сеть.", "sharing_connect_before_start": "Сначала подключитесь.",
    "sharing_server_start_failed": "Ошибка сервера: %1$s", "sharing_blocked_by_live_screen": "Остановите дублирование экрана.",
    "sharing_stopped": "Раздача остановлена.", "sharing_device_android": "Android",
    "network_helper_wifi_ready": "Сеть готова. При ошибке используйте Точку доступа.", "network_helper_local_ready": "Локальная сеть ОК.",
    "network_helper_wifi_found": "IP-адрес найден.", "network_helper_hotspot_ready": "Точка доступа готова.",
    "network_helper_mobile_only": "Мобильных данных недостаточно. Нужен Wi-Fi.", "network_helper_local_address_ready": "Локальный адрес готов.",
    "network_helper_connect_both": "Нужна одна сеть для обоих.", "discovery_unavailable_device": "Поиск недоступен.",
    "discovery_nsd_unavailable": "NSD выключен.", "discovery_searching": "Поиск...", "discovery_unavailable_now": "Ошибка. Используйте QR.",
    "discovery_start_failed": "Ошибка (%1$d)", "discovery_ready_to_open": "Серверы найдены.",
    "browser_title": "DirectServe", "browser_subtitle": "Офлайн обмен", "browser_file_unavailable": "Файл недоступен.",
    "browser_debug_unavailable": "Debug выключен.", "browser_debug_missing_payload": "Нет данных.", "browser_pin_mismatch": "PIN неверный.",
    "browser_device_blocked": "Доступ заблокирован.", "browser_enter_pin": "Введите PIN.",
    "browser_optimized_unavailable": "Оптимизация недоступна.", "browser_video_part_preparing": "Подготовка куска видео...",
    "browser_video_part_unavailable": "Кусок недоступен.", "browser_hls_not_needed": "HLS не требуется.", "browser_hls_not_ready": "HLS не готов.",
    "home_action_add_to_share_title": "Добавить", "home_action_add_to_share_subtitle": "Больше контента.",
    "home_action_files": "Файлы", "home_action_files_desc": "Выбрать", "home_action_folder": "Папка",
    "home_action_folder_desc": "Привязать", "home_action_library": "Библиотека", "home_action_library_desc": "Искать",
    "home_button_share_all_media": "Добавить всё", "home_button_adding_all": "Добавление...",
    "home_media_server_active": "Всё расшарено", "home_btn_stop_media_server": "Очистить всё", "web_folders_title": "Папки",
    "web_folder_items": "Элементов: %1$d", "web_btn_back_to_folders": "Назад", "web_all_media": "Всё медиа",
    "home_nearby_title": "Сеть", "home_nearby_subtitle": "Проверка устройств в локальной сети.",
    "home_nearby_refresh_status": "Обновить", "home_network_wifi": "Wi-Fi ОК", "home_network_hotspot": "Точка доступа ОК",
    "home_network_local": "Сеть ОК", "home_network_none": "Нет сети", "home_network_ready_desc": "Устройства могут подключаться.",
    "home_network_none_desc": "Нужен один и тот же Wi-Fi.", "home_nearby_optional_title": "Приложение опционально",
    "home_nearby_optional_desc": "Нужно только для отображения хоста здесь.", "home_nearby_refresh": "Обновить",
    "home_nearby_open_title": "Открыть в приложении", "home_nearby_open_desc": "Если приложение установлено.",
    "home_nearby_action_open_session": "Войти", "home_nearby_action_open": "Открыть", "home_nearby_device_available": "Готово",
    "home_nearby_device_pin": "PIN", "web_hero_eyebrow": "DirectServe", "web_hero_title": "Медиа",
    "web_hero_desc1": "Видео, фото и музыка.", "web_hero_desc2": "Быстрая передача файлов.", "web_hero_desc3": "Локально и приватно.",
    "web_hero_stat_shared": "Активно", "web_items": "шт.", "web_hero_stat_ready": "Готово", "web_hero_stat_access": "Доступ",
    "web_access_pin": "PIN", "web_access_instant": "Открыто", "web_access_pin_desc": "Код хоста",
    "web_access_instant_desc": "Локальная сеть", "web_pin_entry_kicker": "Безопасность", "web_pin_entry_title": "Введите PIN",
    "web_pin_entry_desc": "PIN на экране хоста.", "web_pin_entry_placeholder": "PIN", "web_btn_videos": "Смотреть видео",
    "web_btn_download_all_files": "Скачать всё", "web_cat_videos": "Видео", "web_cat_photos": "Фото",
    "web_cat_music": "Музыка", "web_cat_files": "Файлы", "web_recent_title": "Сейчас", "web_recent_meta": "готово",
    "web_nav_home": "Медиа", "web_nav_drop_zone": "Отправить", "web_nav_logout": "Выйти", "web_nav_media": "Медиа",
    "web_nav_files": "Файлы", "web_nav_send": "Отправить", "web_strip_session": "Сессия", "web_strip_device": "Устройство",
    "web_strip_link": "Ссылка", "web_security_pin": "С PIN-кодом", "web_security_open": "Открыто", "web_status_unknown": "?",
    "home_connected_devices": "Подключены", "home_rename_device": "Переименовать", "home_rename_device_subtitle": "%1$s • %2$s",
    "home_rename_custom_name": "Имя", "home_rename_save": "Сохранить", "home_rename_cancel": "Отмена", "home_quick_filters": "Фильтры",
    "home_quick_filter_today": "Сегодня", "home_quick_filter_today_desc": "Файлы за сегодня", "home_quick_filter_week": "Неделя",
    "home_quick_filter_week_desc": "Последние 7 дней", "home_quick_filter_month": "Месяц", "home_quick_filter_month_desc": "Последние 30 дней",
    "home_quick_filter_custom": "Период", "home_quick_filter_custom_desc": "Выбрать даты", "home_date_range_title": "Период",
    "home_date_range_from": "С", "home_date_range_start": "Начало", "home_date_range_to": "По",
    "home_date_range_end": "Конец", "home_date_range_tip": "Фильтр по дате в библиотеке.", "home_date_range_apply": "Применить",
    "home_date_range_cancel": "Отмена", "home_recent_shares": "Недавние", "home_section_library": "Управление",
    "home_section_live_tools": "Инструменты", "home_section_network_tv": "Сеть", "home_section_sharing": "Поделиться",
    "home_section_live_features": "Функции", "home_feature_library": "Библиотека", "home_feature_library_desc": "Управление раздачей.",
    "home_feature_transfers": "Активность", "home_feature_transfers_desc": "Последние передачи.", "home_feature_share_files": "Поделиться",
    "home_feature_share_files_desc": "Выбрать контент.", "home_feature_receive_files": "Получить",
    "home_feature_receive_files_desc": "Входящие файлы.", "home_feature_play_media": "Воспроизведение",
    "home_feature_play_media_desc": "Веб-стриминг.", "home_feature_play_media_live": "Активно.", "home_feature_dlna": "DLNA",
    "home_feature_dlna_desc": "Стриминг на ТВ.", "home_feature_dlna_enabled": "DLNA ВКЛ.", "home_feature_live_screen": "Mirroring",
    "home_feature_live_screen_desc": "Трансляция экрана.", "home_feature_quick_text": "Текст", "home_feature_quick_text_desc": "Быстрые сообщения.",
    "home_saved_shares": "Коллекции", "home_saved_shares_save_now": "Сохранить", "home_saved_shares_open": "Открыть",
    "home_saved_shares_delete": "Удалить", "plural:home_saved_shares_items_count": {"one": "%1$d шт.", "other": "%1$d шт."},
    "library_date_group_label": "%1$s", "web_upload_title": "Отправить", "web_upload_subtitle": "Отправить на хост.",
    "web_upload_prompt_title": "Загрузите файлы", "web_upload_prompt_desktop": "Перетащите или выберите.",
    "web_upload_prompt_mobile": "Выберите файлы.", "web_upload_button_browse": "Обзор",
    "web_upload_button_photos": "Фото/Видео", "web_upload_button_any_file": "Файл", "web_upload_target_kicker": "Хост",
    "web_upload_target_status": "Подключён.", "web_upload_how_kicker": "Безопасность", "web_upload_how_title": "Одобрение",
    "web_upload_how_body": "Хост должен принять файл.", "web_action_download": "Скачать", "web_action_view": "Смотреть",
    "web_photo_view": "Смотреть", "web_btn_download_all": "Скачать всё", "web_btn_download_selected": "Скачать выбранное",
    "web_btn_download_original": "Оригинал", "web_btn_fullscreen": "На весь экран", "web_error_streaming_codec": "Кодек не поддерживается. Скачайте файл.",
    "web_error_downloads_disabled": "Скачивание отключено.", "web_error_video_decode": "Ошибка декодирования. Скачайте оригинал.",
    "web_error_video_start": "Ошибка при старте. Скачайте оригинал.", "web_error_video_start_no_dl": "Подготовка совместимой версии...",
    "web_error_load_failed": "Ошибка загрузки.", "web_btn_select_files": "Выбрать", "web_status_selection_on": "Выбор ВКЛ",
    "web_btn_select_all": "Всё", "web_btn_clear_selection": "Очистить", "web_player_slow_start_hint": "Может занять время.",
    "web_selection_count": "Выбрано: %1$d", "web_library_desc_download": "Просматривайте или скачивайте.",
    "web_library_desc_browse": "Просмотр контента.", "web_btn_load_more": "Ещё", "web_btn_show_all": "Всё",
    "web_btn_showing_all": "Загрузка...", "web_show_all_confirm": "Показать все %1$d?",
    "web_library_showing_count": "%1$d из %2$d", "web_search_placeholder": "Имя файла...",
    "web_library_empty": "Здесь пока пусто.", "web_upload_selection_empty": "Ничего не выбрано.",
    "web_upload_selection_single": "%1$s готов", "web_upload_selection_multiple": "Готово файлов: %1$d", "web_upload_button_send": "Отправить",
    "common_quick_filters": "Фильтры", "common_edit_nickname": "Никнейм", "home_quick_filters_desc": "По дате.",
    "home_date_range_body": "Выберите даты.", "web_upload_requesting": "Запрос разрешения...",
    "web_upload_waiting": "Ожидание хоста...", "web_upload_denied": "В отправке отказано.",
    "web_upload_failed_status": "Ошибка (%1$d)", "web_upload_network_error": "Ошибка сети.", "web_upload_cancelled": "Отменено.",
    "web_upload_success_title": "Успешно", "web_upload_success_detail_single": "Файл готов.",
    "web_upload_success_detail_multiple": "Файлы готовы.", "web_upload_failed_title": "Ошибка",
    "web_upload_failed_detail": "Отказано или ошибка.", "web_player_error_open": "Ошибка открытия",
    "web_player_opening": "Подготовка...", "web_player_ready": "Готово", "web_player_analyzing": "Анализ...",
    "web_player_finalizing": "Завершение...", "web_player_stalled": "Зависло", "web_player_starting": "Запуск...",
    "web_player_wait_desc": "Пожалуйста, подождите...", "web_player_ready_desc": "Готово к просмотру.",
    "web_player_analyzing_desc": "Проверка формата...", "web_player_finalizing_desc": "Почти готово...",
    "web_player_stalled_desc": "Слишком сложно для устройства.", "web_player_needs_prepare": "Требуется оптимизация.",
    "web_player_needs_prepare_desc": "Подготовьте для воспроизведения в браузере.", "web_player_starting_desc": "Начало...",
    "web_player_try_again": "Повторить", "web_player_status_opening": "Подготовка", "web_player_status_ready": "ОК",
    "web_player_status_analyzing": "Анализ", "web_player_status_finalizing": "Завершение", "web_player_status_stalled": "Зависло",
    "web_player_status_playing": "Играет", "web_player_progress_preparing": "Подготовка", "web_player_progress_converting": "Конвертация",
    "web_player_status_failed": "Ошибка", "web_player_status_stopped": "Остановлено", "web_prepare_video": "Подготовить",
    "web_progress_percent": "%1$d%%", "web_media_quick_title": "Медиа", "web_media_quick_subtitle": "Просмотр контента.",
    "web_media_open_category": "%1$s", "web_media_empty": "Пусто.", "web_send_files_to_device": "Отправить",
    "web_upload_in_progress": "Отправка...", "web_upload_complete": "Готово", "web_upload_failed": "Ошибка",
    "web_cancel": "Отмена", "web_upload_preparing_transfer": "Подготовка...", "web_upload_connecting": "Подключение...",
    "web_btn_back": "Назад", "web_status_subtitles_available": "Субтитры", "web_now_playing": "Сейчас играет",
    "common_resume": "Продолжить", "web_status_init_progress": "0%", "common_play": "Play", "common_pause": "Пауза",
    "common_unit_b": "Б", "common_unit_kb": "КБ", "common_unit_mb": "МБ", "common_unit_gb": "ГБ", "common_unit_tb": "ТБ",
    "common_unit_s": "с", "common_unit_m": "м", "common_unit_h": "ч", "common_byte_format_decimal": "%1$.1f %2$s",
    "common_byte_format_integer": "%1$d %2$s", "common_duration_format_m_s": "%1$dм %2$dс",
    "common_duration_format_h_m": "%1$dч %2$dм", "common_duration_format_s": "%1$dс",
    "common_duration_timestamp_m_s": "%1$d:%2$02d", "common_duration_timestamp_h_m_s": "%1$d:%2$02d:%3$02d",
    "service_file_index_pattern": "%1$s (%2$d/%3$d)", "service_upload_progress_subtext_pattern": "%1$s / %2$s",
    "help_section_media_server": "Медиасервер", "help_line_media_server_1": "Ваш телефон как сервер.",
    "help_line_media_server_2": "Самоорганизующийся.", "help_section_folders_nav": "Навигация", "help_line_folders_1": "Поиск по папкам.",
    "help_line_folders_2": "Организовано по типу.", "help_section_dlna_tv": "DLNA/ТВ", "help_line_dlna_1": "Smart TV поддерживаются.",
    "help_line_dlna_2": "Видно как DirectServe.", "help_line_dlna_3": "Сетевые настройки.", "help_line_dlna_4": "VLC/Kodi ОК.",
    "help_section_search_sticky": "Поиск", "help_line_search_1": "Мгновенный поиск.", "help_line_search_2": "Всегда сверху.",
    "settings_dlna": "DLNA", "settings_dlna_desc": "ТВ и VLC найдут хост.", "dlna_server_name": "Медиасервер DirectServe",
    "dlna_server_name_template": "DirectServe (%1$s)", "web_action_download_zip": "Скачать ZIP",
    "web_btn_download_all_zip": "Всё в ZIP", "web_btn_download_selected_zip": "Выбранное в ZIP",
    "web_error_no_items_selected": "Ничего не выбрано.", "web_download_started_hint": "Запуск загрузки...",
    "playback_mode_direct": "Direct Play", "playback_mode_repackaging": "Repackage", "playback_mode_transcoding": "Transcode",
    "playback_mode_analyzing": "Анализ", "compatibility_message_cached_ready": "Кэш готов.",
    "compatibility_message_stopped": "Остановлено.", "compatibility_message_validation_failed": "Ошибка: %1$s",
    "compatibility_message_adjusted": "Скорректировано.", "compatibility_message_optimizing": "Оптимизация...",
    "compatibility_message_almost_ready": "Почти готово...", "compatibility_message_ready": "Готово.",
    "compatibility_message_analyzing": "Анализ...", "compatibility_message_finalizing_optimized": "Завершение...",
    "compatibility_message_finalizing_compatible": "Завершение...", "compatibility_message_optimizing_web": "Оптимизация...",
    "compatibility_message_repackaging_web": "Перепаковка...", "compatibility_message_converting_web": "Конвертация...",
}

# ITALIAN (it)
it_data = {
    "common_back": "Indietro", "common_cancel": "Annulla", "common_save": "Salva", "common_delete": "Elimina",
    "common_open": "Apri", "common_refresh": "Aggiorna", "common_continue": "Continua", "common_accept": "Accetta",
    "common_decline": "Rifiuta", "common_dismiss": "Ignora", "common_remove": "Rimuovi", "common_search": "Cerca",
    "common_separator_pipe": " | ", "common_separator_dot": " • ", "onboarding_skip": "Salta",
    "onboarding_title": "Streaming diretto e condivisione file",
    "onboarding_subtitle": "Trasforma il tuo telefono in un hub privato per TV, PC e browser.",
    "onboarding_page_1_title": "Guarda subito sui tuoi dispositivi",
    "onboarding_page_1_description": "Apri video, foto e musica all'istante su altri dispositivi senza caricarli sul cloud.",
    "onboarding_page_2_title": "Funziona su quasi ogni schermo",
    "onboarding_page_2_description": "Compatibile con TV, iPhone, Android, Windows o Mac tramite browser.",
    "onboarding_page_3_title": "Accedi via browser",
    "onboarding_page_3_description": "Basta il tuo link locale o il QR code. Nessuna app richiesta sul ricevente.",
    "onboarding_page_4_title": "Condivisione bidirezionale",
    "onboarding_page_4_description": "Invia file, ricevine da altri e raccogli documenti dai dispositivi connessi.",
    "onboarding_page_5_title": "Niente Internet richiesto",
    "onboarding_page_5_description": "Tutto passa per il tuo Wi-Fi o hotspot locale. Veloce, privato e affidabile.",
    "onboarding_page_6_title": "Privacy per scelta",
    "onboarding_page_6_description": "I tuoi dati restano sul dispositivo. Niente account, niente cloud, niente accesso remoto.",
    "onboarding_page_counter": "%1$d di %2$d", "onboarding_next": "Avanti", "onboarding_get_started": "Inizia",
    "settings_title": "Impostazioni", "settings_subtitle": "Personalizza il comportamento di DirectServe.",
    "settings_group_general": "Generale", "settings_group_notifications": "Notifiche", "settings_group_privacy": "Privacy",
    "settings_group_browser": "Browser", "settings_group_advanced": "Avanzate", "settings_group_network": "Rete",
    "settings_group_help": "Aiuto", "settings_group_debug": "Debug", "settings_language": "Lingua",
    "settings_theme": "Tema", "settings_theme_subtitle": "Scegli l'aspetto dell'app", "settings_theme_system": "Sistema",
    "settings_theme_dark": "Scuro", "settings_theme_light": "Chiaro", "settings_keep_screen_awake": "Schermo sempre attivo",
    "settings_keep_screen_awake_desc": "Evita lo spegnimento durante la condivisione.",
    "settings_vibrate_on_connect": "Vibrazione alla connessione", "settings_vibrate_on_connect_desc": "Vibra quando un dispositivo si unisce.",
    "settings_show_speed": "Mostra velocità", "settings_show_speed_desc": "Mostra la velocità di trasferimento in tempo reale.",
    "settings_show_recent_shares": "Mostra attività recente", "settings_show_recent_shares_desc": "Mantiene una breve cronologia locale.",
    "settings_auto_stop": "Auto-stop", "settings_auto_stop_never": "Mai", "settings_auto_stop_15m": "15 min",
    "settings_auto_stop_30m": "30 min", "settings_auto_stop_1h": "1 ora", "settings_connection_alerts": "Avvisi di connessione",
    "settings_connection_alerts_desc": "Notifica quando qualcuno si unisce alla sessione.",
    "settings_download_alerts": "Avvisi di download", "settings_download_alerts_desc": "Notifica quando qualcuno scarica un file.",
    "settings_upload_requests": "Richieste di upload", "settings_upload_requests_desc": "Chiede conferma prima di accettare file dai browser.",
    "settings_quick_text_enabled": "Testo rapido", "settings_quick_text_enabled_desc": "Condividi messaggi brevi e link tra i dispositivi.",
    "settings_quick_text_alerts": "Avvisi testo rapido", "settings_quick_text_alerts_desc": "Notifica alla ricezione di un messaggio rapido.",
    "settings_use_pin": "Usa PIN", "settings_use_pin_desc": "Richiede un codice per accedere alla sessione.",
    "settings_new_pin_each_time": "Nuovo PIN ogni volta", "settings_new_pin_each_time_desc": "Genera un PIN diverso per ogni sessione.",
    "settings_pin_label": "PIN", "settings_pin_placeholder": "4-6 cifre", "settings_approve_file_uploads": "Approva upload",
    "settings_approve_file_uploads_desc": "Chiede il permesso prima che i browser carichino file.",
    "settings_approve_per_device": "Approva per dispositivo", "settings_approve_per_device_desc": "Approva una volta per dispositivo, non per ogni file.",
    "settings_received_files_location": "Cartella download", "settings_received_files_location_value": "Download",
    "settings_show_thumbnails": "Mostra anteprime", "settings_show_thumbnails_desc": "Anteprime rapide per i file multimediali.",
    "settings_large_tv_layout": "Layout per TV", "settings_large_tv_layout_desc": "Elementi più grandi per schermi TV.",
    "settings_highlight_downloads": "Evidenzia download", "settings_highlight_downloads_desc": "Rende i pulsanti di download più visibili.",
    "settings_sign_out_on_stop": "Disconnetti allo stop", "settings_sign_out_on_stop_desc": "Chiude l'accesso ai browser quando si ferma la condivisione.",
    "settings_clear_temporary_files": "Pulisci file temporanei", "settings_clear_temporary_files_desc": "Elimina i file ottimizzati alla fine.",
    "settings_prevent_downloads": "Impedisci download", "settings_prevent_downloads_desc": "Disattiva il tasto download nel browser.",
    "settings_auto_optimize_library": "Ottimizzazione proactiva", "settings_auto_optimize_library_desc": "Prepara i video in background. Consuma più batteria.",
    "settings_sharing_port": "Porta di condivisione", "settings_sharing_port_placeholder": "43183",
    "settings_sharing_port_help": "La maggior parte può lasciare invariato.",
    "settings_wifi_settings": "Impostazioni Wi-Fi", "settings_wifi_settings_desc": "Assicurati che i dispositivi siano sulla stessa rete.",
    "settings_hotspot_settings": "Impostazioni Hotspot", "settings_hotspot_settings_desc": "Usa l'hotspot se il Wi-Fi pubblico blocca il traffico.",
    "settings_view_onboarding": "Guida introduttiva", "settings_view_onboarding_desc": "Rivedi i passi di benvenuto.",
    "settings_privacy_policy": "Informativa sulla privacy", "settings_privacy_policy_desc": "Controlli e principi di privacy locale.",
    "settings_privacy_promise": "Promessa di privacy", "settings_privacy_promise_desc": "I tuoi file non lasciano mai il telefono.",
    "settings_how_it_works": "Aiuto e funzioni", "settings_how_it_works_desc": "Scopri di più su riproduzione, upload e controlli.",
    "settings_app_version": "Versione app", "settings_recent_shares_count": "Trasferimenti recenti salvati: %1$d",
    "settings_share_debug_log": "Condividi log di debug", "settings_share_debug_log_desc": "Invia log diagnostico via email.",
    "settings_clear_debug_log": "Cancella log di debug",
    "help_title": "Aiuto", "help_about_title": "Info su DirectServe",
    "help_about_1": "DirectServe permette ad altri dispositivi di aprire i tuoi file in un browser senza account o cloud.",
    "help_about_2": "Ogni dispositivo con Wi-Fi e browser può connettersi.",
    "help_about_3": "Niente cloud. Niente account. Niente Internet.",
    "help_section_what_you_can_do": "Cosa puoi fare", "help_section_video_playback": "Riproduzione video",
    "help_section_browser_preparation": "Ottimizzazione browser", "help_section_receiving_files": "Ricezione file",
    "help_section_drop_zone": "Upload e Drop Zone", "help_section_multiple_devices": "Più dispositivi",
    "help_section_privacy_controls": "Privacy e controllo", "help_section_good_to_know": "Informazioni utili",
    "help_section_quick_flow": "Passi rapidi", "help_line_share_files": "Condividi video, foto, musica, documenti e cartelle.",
    "help_line_open_session": "Apri la sessione su qualsiasi browser (Android, iOS, PC, TV).",
    "help_line_same_network": "Entrambi i dispositivi devono essere su Wi-Fi o hotspot.",
    "help_line_multiple_browse": "Più dispositivi possono esplorare contemporaneamente.",
    "help_line_video_direct": "La maggior parte dei video si riproduce direttamente.",
    "help_line_video_temporary": "Alcuni video richiedono una versione ottimizzata per fluidità.",
    "help_line_video_original": "Il file originale non viene mai modificato.",
    "help_line_prep_optional": "L'ottimizzazione è opzionale per migliorare la compatibilità.",
    "help_line_prep_control": "Puoi avviare o fermare l'ottimizzazione quando vuoi.",
    "help_line_prep_batch": "Trattare molti file può scaldare il dispositivo.",
    "help_line_receive_upload": "Altri possono inviarti file se lo permetti.",
    "help_line_receive_approval": "Con l'approvazione attiva, devi accettare ogni trasferimento.",
    "help_line_receive_history": "I file ricevuti finiscono nella cartella Download.",
    "help_line_drop_zone": "Dalla web app è possibile trascinare i file per inviarli.",
    "help_line_drop_zone_pick": "È possibile anche sceglierli manualmente.", "help_line_drop_zone_local": "Gli upload restano locali e privati.",
    "help_line_multi_connect": "Più persone possono connettersi insieme.",
    "help_line_multi_live": "La schermata di sessione mostra i dispositivi attivi.",
    "help_line_multi_controls": "Blocca dispositivi o usa un PIN di sicurezza.",
    "help_line_privacy_local": "Niente account o archiviazione cloud.",
    "help_line_privacy_session": "Viene condiviso solo ciò che selezioni.",
    "help_line_privacy_controls": "Ferma la condivisione o i download quando vuoi.",
    "help_line_wifi_hotspot": "Usa Wi-Fi o l'hotspot del telefono.",
    "help_line_public_wifi": "Il Wi-Fi pubblico può bloccare; l'hotspot è spesso migliore.",
    "help_line_downloads_disabled": "Puoi disattivare i download nelle impostazioni.",
    "help_line_flow_1": "1. Aggiungi file o una cartella.", "help_line_flow_2": "2. Avvia la sessione.",
    "help_line_flow_3": "3. Scansiona il QR o apri il link.", "help_line_flow_4": "4. Esplora e goditi i contenuti.",
    "home_brand_title": "DirectServe", "home_brand_subtitle": "Condivisione privata su Wi-Fi o Hotspot",
    "home_chip_local_session": "Sessione locale", "home_chip_sharing": "In condivisione", "home_chip_ready": "Pronto",
    "home_chip_setup_needed": "Config. necessaria", "home_live_banner": "Sessione attiva sulla rete locale",
    "home_title_live": "Condivisione attiva", "home_title_start": "Sessione attuale",
    "home_body_live": "I dispositivi vicini possono connettersi ora.", "home_body_start": "Aggiungi file per iniziare a condividere.",
    "home_body_start_secondary": "Usa la libreria o scegli file e cartelle.",
    "home_button_start_session": "Avvia condivisione", "home_button_open_session": "Apri sessione",
    "home_button_starting": "Avvio...", "home_button_add_media": "Aggiungi contenuti", "home_button_add_more": "Aggiungi altri",
    "home_summary_current_share": "In condivisione", "home_summary_media": "Media", "home_summary_files": "File",
    "home_content_filter_title": "Cosa condividere", "home_content_filter_subtitle": "Tipi di file visibili nel browser",
    "home_content_filter_videos": "Video", "home_content_filter_music": "Musica", "home_content_filter_photos": "Foto",
    "home_content_filter_files": "File", "home_no_network": "Nessun Wi-Fi o Hotspot rilevato",
    "network_setup_title": "Rete locale richiesta", "network_setup_body": "Assicurati che entrambi i dispositivi siano sulla stessa rete.",
    "network_setup_trouble_title": "Problemi su Wi-Fi pubblico?",
    "network_setup_trouble_body": "Alcuni Wi-Fi bloccano il traffico locale. L'hotspot è l'alternativa migliore.",
    "network_setup_open_wifi": "Apri Wi-Fi", "network_setup_switch_hotspot": "Usa Hotspot",
    "network_setup_retry": "Riprova", "network_setup_footer": "L'hotspot è ideale per quando sei in viaggio.",
    "session_title": "Sessione Live", "session_stop_sharing": "Ferma condivisione", "session_live_now": "In onda",
    "session_live_now_subtitle": "La tua sessione è visibile ai dispositivi vicini.", "session_share_live": "Condivisione attiva",
    "session_share_preparing": "Preparazione sessione", "session_share_live_body": "Scansiona il QR o apri il link in un browser.",
    "session_qr_title": "Scansiona per aprire", "session_qr_body": "Per smartphone, tablet, PC e TV.",
    "session_qr_preparing": "Generazione QR", "session_browser_prep_title": "Ottimizzazione browser",
    "session_browser_prep_active": "%1$d%% • %2$d di %3$d pronti", "session_browser_prep_queued": "%1$d in attesa",
    "session_browser_prep_ready": "%1$d file ottimizzati", "session_browser_prep_message_active": "Ottimizzazione web...",
    "session_browser_prep_message_queued": "In coda", "session_browser_prep_message_ready": "Pronto per il web",
    "session_browser_prep_message_manual": "Richiede ottimizzazione manuale",
    "session_browser_prep_manual_note": "Potrebbe non essere fluido senza preparazione.",
    "session_prepare_browser_files": "Ottimizza per web", "session_stop_browser_files": "Ferma",
    "session_library_refresh_title": "Aggiorna condivisione",
    "session_library_refresh_pending": "%1$d file e %2$d cartelle pronti per l'aggiunta.",
    "session_library_refresh_up_to_date": "Già aggiornato.", "session_refresh_library": "Aggiorna",
    "message_live_library_refreshed_updates": "%1$d file e %2$d cartelle aggiunti.",
    "message_live_library_refreshed_current": "Era già aggiornato.",
    "message_browser_playback_queued_all": "Tutti i file in coda per l'ottimizzazione.",
    "message_browser_playback_already_ready": "Già ottimizzato per il web.", "message_browser_playback_stopped": "Ottimizzazione fermata.",
    "library_importing_title": "Importazione", "library_importing_body": "Aggiunta file alla libreria condivisa...",
    "session_waiting_local_link": "Attesa rete", "session_qr_content_desc": "QR code sessione",
    "session_share_link": "Link locale", "session_share_link_body": "Apri sulla stessa rete.", "session_network": "Rete",
    "session_access_pin": "PIN di accesso", "session_pin_off": "Off", "session_new_pin": "Nuovo PIN",
    "session_turn_pin_on": "Attiva PIN", "session_turn_pin_off": "Disattiva PIN", "session_nearby_name": "Nome host",
    "session_what_happens_now": "Stato", "session_waiting_ready": "Preparazione sessione...",
    "session_waiting_first_device": "Attesa prima connessione...", "session_devices_connected_now": "%1$d dispositivo/i connesso/i.",
    "session_friendly_local_name": "Nome locale", "session_copy_link": "Copia", "session_share": "Condividi",
    "session_metric_devices": "Dispositivi", "session_metric_sent": "Inviato", "session_metric_speed": "Velocità",
    "session_metric_elapsed": "Durata", "session_metric_remaining": "Residuo", "session_connected_waiting": "In attesa...",
    "session_connected_title": "Connessi", "session_connected_waiting_body": "Appariranno qui alla connessione.",
    "session_connected_count": "%1$d dispositivo/i attivo/i.", "session_disconnect_all": "Disconnetti tutti",
    "session_no_devices": "Ancora nessuno connesso.", "session_block_device": "Blocca dispositivo",
    "session_block": "Blocca", "session_blocked_title": "Dispositivi bloccati", "session_unblock_device": "Sblocca",
    "session_unblock": "Sblocca", "session_state_sharing_now": "In condivisione", "session_state_preparing": "Preparazione",
    "session_state_network_needed": "Rete richiesta", "session_network_hotspot": "Hotspot", "session_network_wifi": "Wi-Fi",
    "session_network_local": "Locale", "session_network_offline": "Offline", "history_title": "Attività recente",
    "history_tab_all": "Cronologia", "history_tab_received": "Ricevuti", "history_empty_all": "Nessuna attività recente.",
    "history_empty_received": "Nessun file ricevuto.", "history_sent": "Inviato", "history_received": "Ricevuto",
    "history_open": "Apri", "history_delete": "Elimina", "history_delete_desc": "Rimuovi dalla cronologia",
    "history_date_time_format": "%1$s alle %2$s", "splash_title": "DirectServe", "splash_subtitle": "Condivisione locale privata",
    "privacy_policy_title": "Privacy", "privacy_policy_intro": "I tuoi file restano sulla tua rete locale. Niente account o cloud.",
    "privacy_policy_line_1": "Nessuna registrazione richiesta.", "privacy_policy_line_2": "Nessun upload su server esterni.",
    "privacy_policy_line_3": "Accesso solo durante la sessione.", "privacy_policy_line_4": "Controllo totale su PIN e blocchi.",
    "main_service_background_protection_failed": "Protezione background non avviata.",
    "main_notification_permission_warning": "Le notifiche sono necessarie per il funzionamento.",
    "main_batch_media_access_needed": "Accesso media richiesto per Smart Picks.", "main_debug_log_subject": "Log DirectServe",
    "main_debug_log_body": "Log diagnostico allegato.", "main_debug_log_chooser": "Invia log",
    "main_no_email_app": "Nessuna app email trovata.", "main_no_browser_app": "Nessun browser trovato.",
    "main_no_file_app": "Nessuna app per questo file.", "main_link_copied": "Link copiato",
    "main_link_preparing": "Preparazione link...", "main_share_link_chooser": "Condividi link",
    "main_link_not_ready": "Link non disponibile.", "main_not_sharing": "Non attivo", "service_start_failed": "Avvio servizio fallito.",
    "service_auto_stop_message": "Fermato per inattività.", "service_upload_request_title": "Trasferimento in entrata",
    "service_upload_request_text": "%1$s da %3$s a %2$s", "service_upload_progress_title": "Ricezione %1$s",
    "service_upload_progress_text": "%1$d%% (%2$s)", "service_upload_progress_text_unknown": "Ricezione da %1$s",
    "service_upload_success_title": "%1$s salvato", "service_upload_success_text": "Da %1$s",
    "service_upload_success_subtext": "In Download", "service_file_count": "%1$d file",
    "plural:service_new_devices_connected": {"one": "Dispositivo unito", "other": "%1$d dispositivi uniti"},
    "plural:service_devices_joined": {"one": "%1$s si è unito.", "other": "%1$s si è unito. %2$d attivi."},
    "service_waiting_for_devices": "In attesa...", "plural:service_devices_connected": {"one": "1 dispositivo connesso", "other": "%1$d dispositivi connessi"},
    "service_preparing_browser_access": "Preparazione web...", "service_channel_requests_name": "Trasferimenti",
    "service_channel_requests_desc": "Richieste di upload file", "service_channel_connections_name": "Connessioni",
    "service_channel_connections_desc": "Nuovi dispositivi", "service_channel_quick_text_name": "Testo rapido",
    "service_channel_quick_text_desc": "Messaggi brevi", "service_quick_text_title": "Messaggio da %1$s",
    "library_title": "Gestisci condivisione", "library_header_title": "Contenuti attuali",
    "library_header_body": "File accessibili in questa sessione.", "library_header_subtitles": "Aggiungi sottotitoli .srt per il player web.",
    "library_info_items": "Elementi", "library_info_folders": "Cartelle", "library_info_size": "Dimensione",
    "library_empty_title": "Vuoto", "library_empty_body": "Aggiungi file per iniziare.", "library_section_folders": "Cartelle",
    "library_section_folders_body": "Cartelle collegate.", "library_empty_filter_title": "Nessun risultato",
    "library_empty_filter_body": "Cambia filtro.", "library_section_files": "File", "library_single_file_name": "File",
    "library_selected_files_name": "Selezionati", "library_save_selected_title": "Salva selezione",
    "library_save_selected_body": "Crea una raccolta per dopo.", "library_share_name": "Nome", "library_manage_title": "Gestione",
    "library_manage_body": "Aggiungi o rimuovi contenuti.", "library_selection_title": "Nuova raccolta",
    "library_selection_step_1": "1. Seleziona i file.", "library_selection_step_2": "2. Crea da %1$d selezionato%2$s.",
    "library_search_label": "Cerca...", "library_show_title": "Mostra", "library_show_body": "Filtra elenco",
    "library_category_all": "Tutto", "library_category_videos": "Video", "library_category_photos": "Foto",
    "library_category_music": "Musica", "library_category_files": "File", "library_add_title": "Aggiungi",
    "library_add_body": "Sfoglia contenuti locali.", "library_add_files": "File", "library_add_whole_folder": "Cartella",
    "library_add_from_suggestions": "Libreria telefono", "library_organize_title": "Organizza",
    "library_organize_body": "Ordinamento e salvataggio.", "library_sort_prefix": "Ordina: %1$s",
    "library_clear_all_action": "Svuota tutto", "plural:library_items_in_view": {"one": "1 elemento", "other": "%1$d elementi"},
    "library_clear_all_title": "Svuota tutto?", "library_clear_all_body": "Rimuoverà tutto dalla condivisione.",
    "library_sort_newest": "Recenti", "library_sort_name": "Nome", "library_sort_size": "Dimensione",
    "library_cancel_selection": "Annulla", "library_create_saved_share": "Salva", "library_start_saved_share_selection": "Seleziona",
    "library_browser_prep_title": "Ottimizzazione browser", "library_browser_prep_body": "Crea una copia leggera per il web. L'originale non cambia.",
    "library_folder_summary": "%1$d file | %2$s", "library_unavailable": "Non disponibile", "library_direct_play": "Direct Play",
    "library_subtitle": "Sottotitolo", "library_selected": "Selezionato", "library_tap_to_select": "Tocca",
    "library_select_this_file": "Scegli", "library_preparing": "Preparazione", "library_preparing_for_browser": "Ottimizzazione...",
    "library_ready": "Pronto", "library_ready_for_browser": "Pronto per web", "library_try_again": "Riprova",
    "library_try_browser_prep_again": "Rilancia ottimizzazione", "library_prepare": "Ottimizza", "library_prepare_for_browser": "Prepara",
    "library_type_video": "Video", "library_type_photo": "Foto", "library_type_music": "Musica", "library_type_file": "File",
    "library_compat_ready_to_play": "Pronto | %1$s", "library_compat_not_prepared": "Non ottimizzato", "library_compat_queued": "In coda",
    "library_compat_preparing": "Preparazione", "library_compat_ready": "Pronto", "library_compat_unavailable": "Non supportato",
    "library_compat_message": "%1$s | %2$s", "selection_add_files_title": "Aggiungi file", "selection_add_files_body": "Scegli cosa condividere.",
    "selection_add_selected": "Aggiungi", "selection_pick_files_again": "Modifica", "selection_nothing_selected_title": "Nulla di scelto",
    "selection_nothing_selected_body": "Usa il picker per aggiungere.", "selection_add_folder_title": "Scegli cartella",
    "selection_add_folder_body": "Collega una cartella intera.", "selection_add_folder": "Collega",
    "selection_choose_another_folder": "Cambia", "selection_no_folder_title": "Nessuna cartella",
    "selection_no_folder_body": "Collega cartelle locali.", "selection_selected_folder": "Cartella", "selection_selected_item": "Item",
    "selection_smart_picks_title": "Smart Picks", "selection_smart_picks_body": "Gruppi automatici per data.",
    "selection_media_access_title": "Accesso richiesto", "selection_media_access_body": "Permetti l'accesso per raggruppare i file.",
    "selection_grant_access": "Consenti", "selection_loading_groups_title": "Ricerca...", "selection_loading_groups_body": "Organizzazione...",
    "selection_no_groups_title": "Nessun gruppo", "selection_no_groups_body": "Aggiungi manualmente.", "selection_refresh_groups": "Aggiorna",
    "selection_add_group": "Aggiungi", "home_upload_request_title": "Nuovo upload", "home_upload_request_single": "un file",
    "home_upload_request_files": "%1$d file", "home_upload_request_body": "%1$s vuole inviarti %2$s:",
    "home_upload_request_total_size": "Peso: %1$s", "home_history_content_desc": "Cronologia",
    "home_settings_content_desc": "Impostazioni", "home_network_required_title": "Rete richiesta",
    "home_network_required_body": "Usa Wi-Fi o Hotspot.", "message_unable_add_folder": "Errore cartella.",
    "message_saved_share_named": "Salvato come \"%1$s\".", "message_unable_save_share": "Errore salvataggio.",
    "message_saved_share_ready": "Raccolta pronta (%1$d items).", "home_all_files_access_title": "Documenti?",
    "home_all_files_access_body": "Permetti l'accesso totale per PDF e altro.", "home_all_files_access_grant": "Consenti",
    "home_all_files_access_media_only": "Solo foto/video", "home_all_files_nudge_text": "Condividi ogni file con l'accesso totale!",
    "message_unable_open_saved_share": "Apertura fallita.", "message_saved_share_removed": "Raccolta rimossa.",
    "message_something_went_wrong": "Errore imprevisto.", "message_pin_on": "PIN attivo.", "message_pin_off": "PIN disattivo.",
    "message_debug_log_prepare_failed": "Errore log.", "message_debug_log_cleared": "Log cancellato.",
    "message_debug_log_clear_failed": "Errore pulizia log.", "message_file_no_longer_available": "File non trovato.",
    "message_preparing_browser_playback": "Ottimizzazione di %1$s.", "nearby_helper_tap_session": "Tocca per aprire nel browser.",
    "nearby_helper_open_on_other_device": "Apri DirectServe sull'altro dispositivo.", "share_preset_enter_name": "Inserisci un nome.",
    "share_preset_add_content_first": "Aggiungi file prima.", "share_preset_select_file_first": "Seleziona file.",
    "share_preset_files_unavailable": "Contenuti non disponibili.", "share_preset_collection_unavailable": "Raccolta assente.",
    "share_preset_restore_failed": "Errore ripristino.", "sharing_preflight_failed": "Check fallito: %1$s",
    "sharing_add_content_first": "Aggiungi qualcosa prima.", "sharing_same_wifi_needed": "Usa la stessa rete.",
    "sharing_connect_before_start": "Connettiti prima di iniziare.", "sharing_server_start_failed": "Errore server: %1$s",
    "sharing_blocked_by_live_screen": "Ferma Mirroring prima.", "sharing_stopped": "Condivisione fermata.",
    "sharing_device_android": "Android", "network_helper_wifi_ready": "Rete OK. Hotspot se fallisce.",
    "network_helper_local_ready": "Rete locale OK.", "network_helper_wifi_found": "Indirizzo IP trovato.",
    "network_helper_hotspot_ready": "Hotspot pronto.", "network_helper_mobile_only": "Dati mobili non bastano. Usa Wi-Fi.",
    "network_helper_local_address_ready": "Indirizzo locale OK.", "network_helper_connect_both": "Stessa rete per entrambi.",
    "discovery_unavailable_device": "Ricerca non disponibile.", "discovery_nsd_unavailable": "NSD OFF.",
    "discovery_searching": "Ricerca...", "discovery_unavailable_now": "Errore. Usa QR.",
    "discovery_start_failed": "Errore (%1$d)", "discovery_ready_to_open": "Host trovati.",
    "browser_title": "DirectServe", "browser_subtitle": "Sharing offline", "browser_file_unavailable": "File assente.",
    "browser_debug_unavailable": "Debug OFF.", "browser_debug_missing_payload": "Dati assenti.", "browser_pin_mismatch": "PIN errato.",
    "browser_device_blocked": "Accesso bloccato.", "browser_enter_pin": "Inserisci PIN.",
    "browser_optimized_unavailable": "Ottimizzazione assente.", "browser_video_part_preparing": "Preparazione pezzo video...",
    "browser_video_part_unavailable": "Pezzo assente.", "browser_hls_not_needed": "HLS non necessario.",
    "browser_hls_not_ready": "HLS non pronto.", "home_action_add_to_share_title": "Aggiungi",
    "home_action_add_to_share_subtitle": "Più contenuti.", "home_action_files": "File", "home_action_files_desc": "Scegli",
    "home_action_folder": "Cartella", "home_action_folder_desc": "Collega", "home_action_library": "Libreria",
    "home_action_library_desc": "Cerca", "home_button_share_all_media": "Aggiungi tutto", "home_button_adding_all": "Aggiunta...",
    "home_media_server_active": "Tutto condiviso", "home_btn_stop_media_server": "Svuota tutto", "web_folders_title": "Cartelle",
    "web_folder_items": "%1$d elementi", "web_btn_back_to_folders": "Indietro", "web_all_media": "Tutti i media",
    "home_nearby_title": "Rete e dispositivi", "home_nearby_subtitle": "Controlla i dispositivi vicini.",
    "home_nearby_refresh_status": "Aggiorna", "home_network_wifi": "Wi-Fi OK", "home_network_hotspot": "Hotspot OK",
    "home_network_local": "Rete OK", "home_network_none": "No rete", "home_network_ready_desc": "Pronto per connessione.",
    "home_network_none_desc": "Stesso Wi-Fi richiesto.", "home_nearby_optional_title": "App opzionale",
    "home_nearby_optional_desc": "Serve solo per vedere l'host qui.", "home_nearby_refresh": "Cerca",
    "home_nearby_open_title": "Apri in app", "home_nearby_open_desc": "Se l'app è installata.",
    "home_nearby_action_open_session": "Entra", "home_nearby_action_open": "Apri", "home_nearby_device_available": "Pronto",
    "home_nearby_device_pin": "PIN", "web_hero_eyebrow": "DirectServe", "web_hero_title": "Media",
    "web_hero_desc1": "Video, foto e musica.", "web_hero_desc2": "Invio rapido.", "web_hero_desc3": "Locale e privato.",
    "web_hero_stat_shared": "Attivo", "web_items": "items", "web_hero_stat_ready": "Pronto", "web_hero_stat_access": "Accesso",
    "web_access_pin": "PIN", "web_access_instant": "Libero", "web_access_pin_desc": "Codice dall'host",
    "web_access_instant_desc": "Rete locale", "web_pin_entry_kicker": "Sicurezza", "web_pin_entry_title": "Inserisci PIN",
    "web_pin_entry_desc": "PIN sullo schermo host.", "web_pin_entry_placeholder": "PIN", "web_btn_videos": "Guarda video",
    "web_btn_download_all_files": "Scarica tutto", "web_cat_videos": "Video", "web_cat_photos": "Foto",
    "web_cat_music": "Musica", "web_cat_files": "File", "web_recent_title": "Ora", "web_recent_meta": "pronto",
    "web_nav_home": "Media", "web_nav_drop_zone": "Invia", "web_nav_logout": "Esci", "web_nav_media": "Media",
    "web_nav_files": "File", "web_nav_send": "Invia", "web_strip_session": "Sessione", "web_strip_device": "Dispositivo",
    "web_strip_link": "Link", "web_security_pin": "Con PIN", "web_security_open": "Aperto", "web_status_unknown": "?",
    "home_connected_devices": "Connessi", "home_rename_device": "Rinomina", "home_rename_device_subtitle": "%1$s • %2$s",
    "home_rename_custom_name": "Nome", "home_rename_save": "OK", "home_rename_cancel": "Annulla", "home_quick_filters": "Filtri",
    "home_quick_filter_today": "Oggi", "home_quick_filter_today_desc": "File di oggi", "home_quick_filter_week": "Settimana",
    "home_quick_filter_week_desc": "Ultimi 7 giorni", "home_quick_filter_month": "Mese", "home_quick_filter_month_desc": "Ultimi 30 giorni",
    "home_quick_filter_custom": "Periodo", "home_quick_filter_custom_desc": "Scegli date", "home_date_range_title": "Range",
    "home_date_range_from": "Dal", "home_date_range_start": "Inizio", "home_date_range_to": "Al",
    "home_date_range_end": "Fine", "home_date_range_tip": "Filtra per data in libreria.", "home_date_range_apply": "Applica",
    "home_date_range_cancel": "Annulla", "home_recent_shares": "Recenti", "home_section_library": "Gestione",
    "home_section_live_tools": "Strumenti", "home_section_network_tv": "Rete", "home_section_sharing": "Condividi",
    "home_section_live_features": "Funzioni", "home_feature_library": "Libreria", "home_feature_library_desc": "Gestisci condivisi.",
    "home_feature_transfers": "Attività", "home_feature_transfers_desc": "Ultimi trasferimenti.", "home_feature_share_files": "Condividi",
    "home_feature_share_files_desc": "Scegli contenuti.", "home_feature_receive_files": "Ricevi",
    "home_feature_receive_files_desc": "File in entrata.", "home_feature_play_media": "Riproduci",
    "home_feature_play_media_desc": "Streaming web.", "home_feature_play_media_live": "Attivo.", "home_feature_dlna": "DLNA",
    "home_feature_dlna_desc": "Streaming TV.", "home_feature_dlna_enabled": "DLNA ON.", "home_feature_live_screen": "Mirroring",
    "home_feature_live_screen_desc": "Schermo live.", "home_feature_quick_text": "Testo", "home_feature_quick_text_desc": "Messaggi rapidi.",
    "home_saved_shares": "Raccolte", "home_saved_shares_save_now": "Salva", "home_saved_shares_open": "Apri",
    "home_saved_shares_delete": "Elimina", "plural:home_saved_shares_items_count": {"one": "1 item", "other": "%1$d items"},
    "library_date_group_label": "%1$s", "web_upload_title": "Invia", "web_upload_subtitle": "Invia all'host.",
    "web_upload_prompt_title": "Carica i file", "web_upload_prompt_desktop": "Trascina o scegli.",
    "web_upload_prompt_mobile": "Seleziona file.", "web_upload_button_browse": "Sfoglia",
    "web_upload_button_photos": "Media", "web_upload_button_any_file": "File", "web_upload_target_kicker": "Host",
    "web_upload_target_status": "Connesso.", "web_upload_how_kicker": "Sicurezza", "web_upload_how_title": "Approvazione",
    "web_upload_how_body": "L'host deve accettare.", "web_action_download": "Laden", "web_action_view": "Vedi",
    "web_photo_view": "Vedi", "web_btn_download_all": "Scarica tutto", "web_btn_download_selected": "Scarica selezione",
    "web_btn_download_original": "Originale", "web_btn_fullscreen": "Vollbild", "web_error_streaming_codec": "Codec non supportato. Scarica.",
    "web_error_downloads_disabled": "Downloads OFF.", "web_error_video_decode": "Errore. Scarica originale.",
    "web_error_video_start": "Errore. Scarica originale.", "web_error_video_start_no_dl": "Versione compatibile...",
    "web_error_load_failed": "Errore.", "web_btn_select_files": "Scegli", "web_status_selection_on": "Selezione ON",
    "web_btn_select_all": "Tutto", "web_btn_clear_selection": "Pulisci", "web_player_slow_start_hint": "Un momento...",
    "web_selection_count": "%1$d scelti", "web_library_desc_download": "Sfoglia o scarica.", "web_library_desc_browse": "Sfoglia contenuti.",
    "web_btn_load_more": "Più", "web_btn_show_all": "Tutto", "web_btn_showing_all": "Caricamento...",
    "web_show_all_confirm": "Vedi tutti i %1$d?", "web_library_showing_count": "%1$d di %2$d",
    "web_search_placeholder": "Nome...", "web_library_empty": "Vuoto.", "web_upload_selection_empty": "Nulla scelto.",
    "web_upload_selection_single": "%1$s pronto", "web_upload_selection_multiple": "%1$d pronti", "web_upload_button_send": "Carica",
    "common_quick_filters": "Filtri", "common_edit_nickname": "Nickname", "home_quick_filters_desc": "Per data.",
    "home_date_range_body": "Scegli date.", "web_upload_requesting": "Permesso...", "web_upload_waiting": "Attesa...",
    "web_upload_denied": "Rifiutato dall'host.", "web_upload_failed_status": "Fallito (%1$d)",
    "web_upload_network_error": "Errore rete.", "web_upload_cancelled": "Annullato.", "web_upload_success_title": "OK",
    "web_upload_success_detail_single": "File pronto.", "web_upload_success_detail_multiple": "File pronti.",
    "web_upload_failed_title": "Errore", "web_upload_failed_detail": "Rifiutato o errore.", "web_player_error_open": "Fallito",
    "web_player_opening": "Prep...", "web_player_ready": "Pronto", "web_player_analyzing": "Analisi...",
    "web_player_finalizing": "Finale...", "web_player_stalled": "Bloccato", "web_player_starting": "Inizio...",
    "web_player_wait_desc": "Pazienza...", "web_player_ready_desc": "Pronto.", "web_player_analyzing_desc": "Check...",
    "web_player_finalizing_desc": "Quasi...", "web_player_stalled_desc": "Troppo complesso.",
    "web_player_needs_prepare": "Ottimizza!", "web_player_needs_prepare_desc": "Prepara ora.",
    "web_player_starting_desc": "Avvio...", "web_player_try_again": "Ancora", "web_player_status_opening": "Prep",
    "web_player_status_ready": "OK", "web_player_status_analyzing": "Analisi", "web_player_status_finalizing": "Finale",
    "web_player_status_stalled": "Stuck", "web_player_status_playing": "Playing", "web_player_progress_preparing": "Preparazione",
    "web_player_progress_converting": "Conversione", "web_player_status_failed": "Errore", "web_player_status_stopped": "Off",
    "web_prepare_video": "Prepara", "web_progress_percent": "%1$d%%", "web_media_quick_title": "Media",
    "web_media_quick_subtitle": "Sfoglia.", "web_media_open_category": "%1$s", "web_media_empty": "Vuoto.",
    "web_send_files_to_device": "Invia", "web_upload_in_progress": "Upload...", "web_upload_complete": "Pronto",
    "web_upload_failed": "Errore", "web_cancel": "Annulla", "web_upload_preparing_transfer": "Prep...",
    "web_upload_connecting": "Link...", "web_btn_back": "Indietro", "web_status_subtitles_available": "Sottotitoli",
    "web_now_playing": "In riproduzione", "common_resume": "Riprendi", "web_status_init_progress": "0%",
    "common_play": "Play", "common_pause": "Pausa", "common_unit_b": "B", "common_unit_kb": "KB",
    "common_unit_mb": "MB", "common_unit_gb": "GB", "common_unit_tb": "TB", "common_unit_s": "s",
    "common_unit_m": "m", "common_unit_h": "h", "common_byte_format_decimal": "%1$.1f %2$s",
    "common_byte_format_integer": "%1$d %2$s", "common_duration_format_m_s": "%1$dm %2$ds",
    "common_duration_format_h_m": "%1$dh %2$dm", "common_duration_format_s": "%1$ds",
    "common_duration_timestamp_m_s": "%1$d:%2$02d", "common_duration_timestamp_h_m_s": "%1$d:%2$02d:%3$02d",
    "service_file_index_pattern": "%1$s (%2$d/%3$d)", "service_upload_progress_subtext_pattern": "%1$s / %2$s",
    "help_section_media_server": "Media Server", "help_line_media_server_1": "Hub completo.",
    "help_line_media_server_2": "Auto-organizzato.", "help_section_folders_nav": "Navigazione",
    "help_line_folders_1": "Per cartelle.", "help_line_folders_2": "Ordinato.", "help_section_dlna_tv": "DLNA/TV",
    "help_line_dlna_1": "Smart TV OK.", "help_line_dlna_2": "DirectServe visibile.", "help_line_dlna_3": "Opzione rete.",
    "help_line_dlna_4": "VLC/Kodi OK.", "help_section_search_sticky": "Ricerca", "help_line_search_1": "Istante.",
    "help_line_search_2": "In alto.", "settings_dlna": "DLNA", "settings_dlna_desc": "TV/VLC trovano l'host.",
    "dlna_server_name": "Server media DirectServe", "dlna_server_name_template": "DirectServe (%1$s)",
    "web_action_download_zip": "Salva ZIP", "web_btn_download_all_zip": "Tutto ZIP",
    "web_btn_download_selected_zip": "Scegli ZIP", "web_error_no_items_selected": "Nulla scelto.",
    "web_download_started_hint": "Batch-Laden...", "playback_mode_direct": "Direct Play",
    "playback_mode_repackaging": "Repackage", "playback_mode_transcoding": "Transcode",
    "playback_mode_analyzing": "Analisi", "compatibility_message_cached_ready": "Cache pronta.",
    "compatibility_message_stopped": "Fermato.", "compatibility_message_validation_failed": "Errore: %1$s",
    "compatibility_message_adjusted": "Aggiustato.", "compatibility_message_optimizing": "Ottimizzazione...",
    "compatibility_message_almost_ready": "Quasi...", "compatibility_message_ready": "Pronto.",
    "compatibility_message_analyzing": "Analisi...", "compatibility_message_finalizing_optimized": "Finale...",
    "compatibility_message_finalizing_compatible": "Finale...", "compatibility_message_optimizing_web": "Ottimizzazione...",
    "compatibility_message_repackaging_web": "Repackage...", "compatibility_message_converting_web": "Conversione...",
}

# Apply batch
res_dir = "core/resources/src/main/res"
rebuild_locale(res_dir, "ru", ru_data)
rebuild_locale(res_dir, "it", it_data)
