import os
import xml.etree.ElementTree as ET

def rebuild_locale(res_dir, locale_name, translation_dict):
    base_path = os.path.join(res_dir, "values", "strings.xml")
    target_dir = os.path.join(res_dir, f"values-{locale_name}")
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)
        
    target_path = os.path.join(target_dir, "strings.xml")
    tree = ET.parse(base_path)
    root = tree.getroot()
    new_root = ET.Element('resources')
    
    for child in root:
        if child.tag == 'string':
            name = child.get('name')
            translatable = child.get('translatable', 'true')
            new_node = ET.SubElement(new_root, 'string', {'name': name})
            if translatable == 'false':
                new_node.set('translatable', 'false')
                new_node.text = child.text
            else:
                val = translation_dict.get(name)
                new_node.text = val if val else child.text
        elif child.tag == 'plurals':
            name = child.get('name')
            new_node = ET.SubElement(new_root, 'plurals', {'name': name})
            plural_data = translation_dict.get(f"plural:{name}", {})
            for item in child:
                qty = item.get('quantity')
                new_item = ET.SubElement(new_node, 'item', {'quantity': qty})
                val = plural_data.get(qty)
                new_item.text = val if val else item.text
        elif child.tag == 'string-array':
            name = child.get('name')
            new_node = ET.SubElement(new_root, 'string-array', {'name': name})
            array_data = translation_dict.get(f"array:{name}", [])
            for i, item in enumerate(child):
                new_item = ET.SubElement(new_node, 'item')
                if i < len(array_data):
                    new_item.text = array_data[i]
                else:
                    new_item.text = item.text

    ET.indent(new_root, space="    ", level=0)
    rough_string = ET.tostring(new_root, encoding='utf-8').decode('utf-8')
    with open(target_path, 'w', encoding='utf-8') as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n')
        f.write(rough_string)

# ARABIC (ar) - RTL
ar_data = {
    "common_back": "رجوع", "common_cancel": "إلغاء", "common_save": "حفظ", "common_delete": "حذف",
    "common_open": "فتح", "common_refresh": "تحديث", "common_continue": "متابعة", "common_accept": "قبول",
    "common_decline": "رفض", "common_dismiss": "إغلاق", "common_remove": "إزالة", "common_search": "بحث",
    "common_separator_pipe": " | ", "common_separator_dot": " • ", "onboarding_skip": "تخطي",
    "onboarding_title": "مشاركة وبث مباشر",
    "onboarding_subtitle": "حوّل هاتفك إلى خادم محلي للتلفزيون والكمبيوتر.",
    "onboarding_page_1_title": "شاهد فوراً على أجهزتك",
    "onboarding_page_1_description": "افتح الفيديو والصور على الأجهزة القريبة دون رفعها للسحابة.",
    "onboarding_page_2_title": "يعمل على أي شاشة",
    "onboarding_page_2_description": "متوافق مع أجهزة الكمبيوتر والتلفزيون والهواتف عبر المتصفح.",
    "onboarding_page_3_title": "الوصول من المتصفح",
    "onboarding_page_3_description": "لا حاجة لتطبيقات إضافية. امسح الرمز أو افتح الرابط.",
    "onboarding_page_4_title": "مشاركة ثنائية الاتجاه",
    "onboarding_page_4_description": "إرسال الملفات واستلامها بسهولة.",
    "onboarding_page_5_title": "بدون إنترنت",
    "onboarding_page_5_description": "يعمل محلياً عبر شبكة الواي فاي أو نقطة الاتصال.",
    "onboarding_page_6_title": "الخصوصية أولاً",
    "onboarding_page_6_description": "الملفات لا تترك هاتفك أبداً. لا حسابات، لا سحابة.",
    "onboarding_page_counter": "%1$d من %2$d", "onboarding_next": "التالي", "onboarding_get_started": "البدء",
    "settings_title": "الإعدادات", "settings_subtitle": "تخصيص سلوك DirectServe.",
    "settings_group_general": "عام", "settings_group_notifications": "الإشعارات", "settings_group_privacy": "الخصوصية",
    "settings_group_browser": "المتصفح", "settings_group_advanced": "متقدم", "settings_group_network": "الشبكة",
    "settings_group_help": "مساعدة", "settings_group_debug": "تطوير", "settings_language": "اللغة",
    "settings_theme": "المظهر", "settings_theme_subtitle": "تغيير شكل التطبيق", "settings_theme_system": "النظام",
    "settings_theme_dark": "داكن", "settings_theme_light": "فاتح", "settings_keep_screen_awake": "إبقاء الشاشة مضاءة",
    "settings_keep_screen_awake_desc": "يمنع إيقاف الشاشة أثناء المشاركة.",
    "settings_vibrate_on_connect": "اهتزاز عند الاتصال", "settings_vibrate_on_connect_desc": "اهتزاز قصير عندما ينضم جهاز.",
    "settings_show_speed": "عرض السرعة", "settings_show_speed_desc": "عرض سرعة النقل الحية.",
    "settings_show_recent_shares": "عرض الحديثة", "settings_show_recent_shares_desc": "حفظ سجل المشاركات محلياً.",
    "settings_auto_stop": "إيقاف تلقائي", "settings_auto_stop_never": "أبداً", "settings_auto_stop_15m": "15 دقيقة",
    "settings_auto_stop_30m": "30 دقيقة", "settings_auto_stop_1h": "ساعة واحدة", "settings_connection_alerts": "تنبيهات الاتصال",
    "settings_connection_alerts_desc": "تنبيه عند انضمام شخص.",
    "settings_download_alerts": "تنبيهات التحميل", "settings_download_alerts_desc": "تنبيه عندما يحمل شخص ملفاً.",
    "settings_upload_requests": "طلبات الرفع", "settings_upload_requests_desc": "سؤال قبل استلام الملفات.",
    "settings_quick_text_enabled": "نص سريع", "settings_quick_text_enabled_desc": "تبادل الرسائل القصيرة.",
    "settings_quick_text_alerts": "تنبيهات النص", "settings_quick_text_alerts_desc": "عند استلام رسالة.",
    "settings_use_pin": "استخدام رمز PIN", "settings_use_pin_desc": "يتطلب رمزاً قبل الوصول.",
    "settings_new_pin_each_time": "رمز PIN جديد كل مرة", "settings_new_pin_each_time_desc": "توليد رمز جديد لكل جلسة.",
    "settings_pin_label": "رمز PIN", "settings_pin_placeholder": "4-6 أرقام", "settings_approve_file_uploads": "الموافقة على الرفع",
    "settings_approve_file_uploads_desc": "يتطلب إذنًا قبل الرفع.",
    "settings_approve_per_device": "موافقة لكل جهاز", "settings_approve_per_device_desc": "موافقة مرة واحدة للجهاز.",
    "settings_received_files_location": "مجلد التنزيلات", "settings_received_files_location_value": "التنزيلات",
    "settings_show_thumbnails": "عرض المصغرات", "settings_show_thumbnails_desc": "معاينات للميديا.",
    "settings_large_tv_layout": "تخطيط التلفزيون", "settings_large_tv_layout_desc": "أزرار أكبر.",
    "settings_highlight_downloads": "إبراز التنزيلات", "settings_highlight_downloads_desc": "جعل الأزرار أوضح.",
    "settings_sign_out_on_stop": "تسجيل الخروج عند الإيقاف", "settings_sign_out_on_stop_desc": "قطع الوصول عند التوقف.",
    "settings_clear_temporary_files": "مسح الملفات المؤقتة", "settings_clear_temporary_files_desc": "حذف الفيديو المحسن.",
    "settings_prevent_downloads": "منع التنزيلات", "settings_prevent_downloads_desc": "تعطيل زر التحميل.",
    "settings_auto_optimize_library": "التحسين في الخلفية", "settings_auto_optimize_library_desc": "يستهلك البطارية بسرعة.",
    "settings_sharing_port": "المنفذ", "settings_sharing_port_placeholder": "43183",
    "settings_sharing_port_help": "لا تقم بتغييره إن لم تكن متأكداً.",
    "settings_wifi_settings": "إعدادات الواي فاي", "settings_wifi_settings_desc": "يجب أن تكون على نفس الشبكة.",
    "settings_hotspot_settings": "إعدادات نقطة الاتصال", "settings_hotspot_settings_desc": "استخدمه إذا كان الواي فاي مغلقاً.",
    "settings_view_onboarding": "عرض البرنامج التعليمي", "settings_view_onboarding_desc": "بدء خطوات الترحيب.",
    "settings_privacy_policy": "سياسة الخصوصية", "settings_privacy_policy_desc": "الخصوصية المحلية.",
    "settings_privacy_promise": "وعدنا", "settings_privacy_promise_desc": "الملفات لا تترك هاتفك.",
    "settings_how_it_works": "كيف يعمل", "settings_how_it_works_desc": "دليل المساعدة.",
    "settings_app_version": "إصدار التطبيق", "settings_recent_shares_count": "المشاركات: %1$d",
    "settings_share_debug_log": "سجل الأخطاء", "settings_share_debug_log_desc": "إرسال السجل للإبلاغ عن مشكلة.",
    "settings_clear_debug_log": "مسح السجل",
    "help_title": "مساعدة", "help_about_title": "حول DirectServe",
    "help_about_1": "يسمح للأجهزة الأخرى بفتح ملفاتك من المتصفح.",
    "help_about_2": "أي جهاز متصل بنفس الشبكة يمكنه الانضمام.",
    "help_about_3": "لا سحابة، لا حسابات، لا إنترنت.",
    "help_section_what_you_can_do": "ما يمكنك فعله", "help_section_video_playback": "تشغيل الفيديو",
    "help_section_browser_preparation": "تحسين المتصفح", "help_section_receiving_files": "استلام الملفات",
    "help_section_drop_zone": "منطقة الرفع", "help_section_multiple_devices": "أجهزة متعددة",
    "help_section_privacy_controls": "الخصوصية", "help_section_good_to_know": "من الجيد معرفته",
    "help_section_quick_flow": "بدء سريع", "help_line_share_files": "مشاركة الفيديو والصور.",
    "help_line_open_session": "الفتح في متصفح.",
    "help_line_same_network": "يجب أن تكونا على نفس الشبكة.",
    "help_line_multiple_browse": "تصفح متزامن للجميع.",
    "help_line_video_direct": "تشغيل مباشر للفيديو.",
    "help_line_video_temporary": "يتطلب التحسين أحياناً.",
    "help_line_video_original": "الملف الأصلي لا يتغير.",
    "help_line_prep_optional": "التحسين اختياري.",
    "help_line_prep_control": "يمكنك إيقافه متى شئت.",
    "help_line_prep_batch": "الملفات الكثيرة تزيد حرارة الهاتف.",
    "help_line_receive_upload": "يمكن للآخرين الإرسال إليك.",
    "help_line_receive_approval": "يجب أن توافق أولاً.",
    "help_line_receive_history": "تُحفظ في التنزيلات.",
    "help_line_drop_zone": "سحب وإفلات الملفات.",
    "help_line_drop_zone_pick": "أو اختيارها.", "help_line_drop_zone_local": "محلية 100%.",
    "help_line_multi_connect": "أجهزة متعددة معاً.",
    "help_line_multi_live": "الأجهزة تظهر على الشاشة.",
    "help_line_multi_controls": "حظر أو استخدام رمز.",
    "help_line_privacy_local": "لا حسابات.",
    "help_line_privacy_session": "فقط ما تحدده يُشارك.",
    "help_line_privacy_controls": "لديك السيطرة الكاملة.",
    "help_line_wifi_hotspot": "واي فاي أو نقطة اتصال.",
    "help_line_public_wifi": "الشبكات العامة قد تحظر النقل.",
    "help_line_downloads_disabled": "يمكن تعطيل التنزيل.",
    "help_line_flow_1": "1. إضافة ملفات.", "help_line_flow_2": "2. بدء الجلسة.",
    "help_line_flow_3": "3. مسح الرمز.", "help_line_flow_4": "4. المشاهدة.",
    "home_brand_title": "DirectServe", "home_brand_subtitle": "مشاركة خاصة",
    "home_chip_local_session": "جلسة محلية", "home_chip_sharing": "يتم المشاركة", "home_chip_ready": "جاهز",
    "home_chip_setup_needed": "الشبكة مطلوبة", "home_live_banner": "مباشر على الشبكة",
    "home_title_live": "جلسة نشطة", "home_title_start": "المشاركة الحالية",
    "home_body_live": "الأجهزة القريبة يمكنها الاتصال.", "home_body_start": "أضف ملفات للمشاركة.",
    "home_body_start_secondary": "استخدم المكتبة للإضافة.",
    "home_button_start_session": "بدء الجلسة", "home_button_open_session": "فتح",
    "home_button_starting": "جارِ البدء...", "home_button_add_media": "إضافة", "home_button_add_more": "إضافة المزيد",
    "home_summary_current_share": "المجموع", "home_summary_media": "ميديا", "home_summary_files": "ملفات",
    "home_content_filter_title": "المحتوى", "home_content_filter_subtitle": "المرئي في المتصفح",
    "home_content_filter_videos": "فيديو", "home_content_filter_music": "موسيقى", "home_content_filter_photos": "صور",
    "home_content_filter_files": "ملفات", "home_no_network": "لا يوجد واي فاي",
    "network_setup_title": "شبكة مطلوبة", "network_setup_body": "نفس الشبكة مطلوبة للاجهزة.",
    "network_setup_trouble_title": "مشكلة في الشبكة؟",
    "network_setup_trouble_body": "استخدم نقطة اتصال الهاتف.",
    "network_setup_open_wifi": "واي فاي", "network_setup_switch_hotspot": "نقطة اتصال",
    "network_setup_retry": "إعادة محاولة", "network_setup_footer": "مثالي أثناء السفر.",
    "session_title": "جلسة مباشرة", "session_stop_sharing": "إيقاف", "session_live_now": "مباشر",
    "session_live_now_subtitle": "أنت مرئي الآن على الشبكة.", "session_share_live": "المشاركة نشطة",
    "session_share_preparing": "جار التجهيز...", "session_share_live_body": "امسح الرمز أو افتح الرابط.",
    "session_qr_title": "الرمز", "session_qr_body": "للهواتف والتلفاز.",
    "session_qr_preparing": "يتم الإنشاء...", "session_browser_prep_title": "تحسين المتصفح",
    "session_browser_prep_active": "%1$d%% • جاهز %2$d من %3$d", "session_browser_prep_queued": "في الانتظار %1$d",
    "session_browser_prep_ready": "%1$d ملفات جاهزة", "session_browser_prep_message_active": "تحسين للويب...",
    "session_browser_prep_message_queued": "في الانتظار", "session_browser_prep_message_ready": "جاهز",
    "session_browser_prep_message_manual": "إجراء مطلوب",
    "session_browser_prep_manual_note": "قد لا يعمل جيداً بدون تحسين.",
    "session_prepare_browser_files": "تحسين", "session_stop_browser_files": "إيقاف",
    "session_library_refresh_title": "تحديث",
    "session_library_refresh_pending": "%1$d ملفات مضافة.",
    "session_library_refresh_up_to_date": "محدث.", "session_refresh_library": "تحديث",
    "message_live_library_refreshed_updates": "تم التحديث.",
    "message_live_library_refreshed_current": "كل شيء محدث.",
    "message_browser_playback_queued_all": "تمت إضافتها للانتظار.",
    "message_browser_playback_already_ready": "جاهزة بالفعل.", "message_browser_playback_stopped": "توقف.",
    "library_importing_title": "استيراد", "library_importing_body": "يرجى الانتظار...",
    "session_waiting_local_link": "الشبكة...", "session_qr_content_desc": "رمز QR",
    "session_share_link": "رابط", "session_share_link_body": "افتحه على نفس الشبكة.", "session_network": "الشبكة",
    "session_access_pin": "رمز الوصول", "session_pin_off": "مغلق", "session_new_pin": "رمز جديد",
    "session_turn_pin_on": "تفعيل الرمز", "session_turn_pin_off": "تعطيل الرمز", "session_nearby_name": "الاسم",
    "session_what_happens_now": "الحالة", "session_waiting_ready": "في انتظار...",
    "session_waiting_first_device": "بانتظار الجهاز الأول...", "session_devices_connected_now": "متصل الآن %1$d.",
    "session_friendly_local_name": "الاسم المحلي", "session_copy_link": "نسخ", "session_share": "مشاركة",
    "session_metric_devices": "أجهزة", "session_metric_sent": "مُرسَل", "session_metric_speed": "سرعة",
    "session_metric_elapsed": "الوقت", "session_metric_remaining": "متبقي", "session_connected_waiting": "في انتظار...",
    "session_connected_title": "الأجهزة المتصلة", "session_connected_waiting_body": "ستظهر هنا.",
    "session_connected_count": "%1$d نشط.", "session_disconnect_all": "فصل الجميع",
    "session_no_devices": "لا أحد هنا.", "session_block_device": "حظر",
    "session_block": "حظر", "session_blocked_title": "المحظورة", "session_unblock_device": "إلغاء حظر",
    "session_unblock": "إلغاء حظر", "session_state_sharing_now": "نشط", "session_state_preparing": "تجهيز",
    "session_state_network_needed": "شبكة", "session_network_hotspot": "نقطة اتصال", "session_network_wifi": "واي فاي",
    "session_network_local": "محلي", "session_network_offline": "غير متصل", "history_title": "السجل",
    "history_tab_all": "الكل", "history_tab_received": "مستلمة", "history_empty_all": "فارغ.",
    "history_empty_received": "فارغ.", "history_sent": "مُرسل", "history_received": "مُستلم",
    "history_open": "فتح", "history_delete": "حذف", "history_delete_desc": "إزالة من السجل",
    "history_date_time_format": "%1$s في %2$s", "splash_title": "DirectServe", "splash_subtitle": "مشاركة محلية خاصة",
    "privacy_policy_title": "الخصوصية", "privacy_policy_intro": "ملفاتك على جهازك فقط.",
    "privacy_policy_line_1": "لا حاجة للتسجيل.", "privacy_policy_line_2": "لا يوجد رفع للسحابة.",
    "privacy_policy_line_3": "الوصول محلي فقط.", "privacy_policy_line_4": "أنت تتحكم بالرمز.",
    "main_service_background_protection_failed": "فشل بدء الخلفية.",
    "main_notification_permission_warning": "الإشعارات مطلوبة.",
    "main_batch_media_access_needed": "الوصول للميديا مطلوب.", "main_debug_log_subject": "تقرير خطأ",
    "main_debug_log_body": "التقرير مرفق.", "main_debug_log_chooser": "إرسال عبر...",
    "main_no_email_app": "لا يوجد بريد.", "main_no_browser_app": "لا متصفح.",
    "main_no_file_app": "لا يوجد تطبيق.", "main_link_copied": "تم النسخ.",
    "main_link_preparing": "يرجى الانتظار...", "main_share_link_chooser": "مشاركة الرابط",
    "main_link_not_ready": "غير جاهز.", "main_not_sharing": "متوقف", "service_start_failed": "فشل البدء.",
    "service_auto_stop_message": "توقف لعدم النشاط.", "service_upload_request_title": "ملف وارد",
    "service_upload_request_text": "%1$s من %3$s إلى %2$s", "service_upload_progress_title": "استلام %1$s",
    "service_upload_progress_text": "%1$d%% (%2$s)", "service_upload_progress_text_unknown": "من %1$s",
    "service_upload_success_title": "تم الحفظ: %1$s", "service_upload_success_text": "من %1$s",
    "service_upload_success_subtext": "في التنزيلات", "service_file_count": "%1$d ملفات",
    "plural:service_new_devices_connected": {"one": "جهاز متصل", "other": "%1$d أجهزة متصلة"},
    "plural:service_devices_joined": {"one": "انضم %1$s.", "other": "انضم %1$s (%2$d)."},
    "service_waiting_for_devices": "في الانتظار...", "plural:service_devices_connected": {"one": "1 جهاز", "other": "%1$d أجهزة"},
    "service_preparing_browser_access": "تحضير للويب...", "service_channel_requests_name": "نقل",
    "service_channel_requests_desc": "ملفات", "service_channel_connections_name": "اتصالات",
    "service_channel_connections_desc": "أجهزة", "service_channel_quick_text_name": "نص",
    "service_channel_quick_text_desc": "رسائل", "service_quick_text_title": "رسالة من %1$s",
    "library_title": "المكتبة", "library_header_title": "المحتوى",
    "library_header_body": "الملفات المشتركة حالياً.", "library_header_subtitles": "يمكنك إضافة ترجمات.",
    "library_info_items": "ملف", "library_info_folders": "مجلد", "library_info_size": "حجم",
    "library_empty_title": "فارغ", "library_empty_body": "أضف شيئاً.", "library_section_folders": "المجلدات",
    "library_section_folders_body": "المجلدات المشتركة.", "library_empty_filter_title": "لا نتائج",
    "library_empty_filter_body": "غيّر الفلتر.", "library_section_files": "الملفات", "library_single_file_name": "ملف",
    "library_selected_files_name": "المحددة", "library_save_selected_title": "حفظ التحديد",
    "library_save_selected_body": "لوقت لاحق.", "library_share_name": "الاسم", "library_manage_title": "إدارة",
    "library_manage_body": "إضافة وإزالة.", "library_selection_title": "تحديد جديد",
    "library_selection_step_1": "1. اختر.", "library_selection_step_2": "2. تأكيد.",
    "library_search_label": "بحث...", "library_show_title": "عرض", "library_show_body": "تصفية",
    "library_category_all": "الكل", "library_category_videos": "فيديو", "library_category_photos": "صور",
    "library_category_music": "موسيقى", "library_category_files": "ملفات", "library_add_title": "إضافة",
    "library_add_body": "من الجهاز.", "library_add_files": "ملفات", "library_add_whole_folder": "مجلد",
    "library_add_from_suggestions": "معرض الصور", "library_organize_title": "ترتيب",
    "library_organize_body": "فرز.", "library_sort_prefix": "فرز: %1$s",
    "library_clear_all_action": "مسح الكل", "plural:library_items_in_view": {"one": "1", "other": "%1$d"},
    "library_clear_all_title": "مسح الكل؟", "library_clear_all_body": "يفرغ القائمة.",
    "library_sort_newest": "الأحدث", "library_sort_name": "الاسم", "library_sort_size": "الحجم",
    "library_cancel_selection": "إلغاء", "library_create_saved_share": "تم", "library_start_saved_share_selection": "اختيار",
    "library_browser_prep_title": "نسخة الويب", "library_browser_prep_body": "مُخفف للمتصفح.",
    "library_folder_summary": "%1$d | %2$s", "library_unavailable": "غير متوفر", "library_direct_play": "تشغيل مباشر",
    "library_subtitle": "ترجمة", "library_selected": "محدد", "library_tap_to_select": "اضغط",
    "library_select_this_file": "نعم", "library_preparing": "تجهيز", "library_preparing_for_browser": "في الطابور",
    "library_ready": "جاهز", "library_ready_for_browser": "جاهز للويب", "library_try_again": "إعادة",
    "library_try_browser_prep_again": "حاول مجدداً", "library_prepare": "تحضير", "library_prepare_for_browser": "تم",
    "library_type_video": "فيديو", "library_type_photo": "صورة", "library_type_music": "موسيقى", "library_type_file": "ملف",
    "library_compat_ready_to_play": "تم | %1$s", "library_compat_not_prepared": "غير جاهز", "library_compat_queued": "بالانتظار",
    "library_compat_preparing": "يُعالج...", "library_compat_ready": "تم", "library_compat_unavailable": "غير مدعوم",
    "library_compat_message": "%1$s | %2$s", "selection_add_files_title": "تحديد", "selection_add_files_body": "ماذا ستشارك؟",
    "selection_add_selected": "إضافة", "selection_pick_files_again": "تغيير", "selection_nothing_selected_title": "فارغ",
    "selection_nothing_selected_body": "اختر شيئاً.", "selection_add_folder_title": "مجلد",
    "selection_add_folder_body": "المجلد بأكمله.", "selection_add_folder": "إضافة",
    "selection_choose_another_folder": "تغيير", "selection_no_folder_title": "خطأ",
    "selection_no_folder_body": "اختر مجلد.", "selection_selected_folder": "مجلد", "selection_selected_item": "1",
    "selection_smart_picks_title": "التواريخ", "selection_smart_picks_body": "منظم.",
    "selection_media_access_title": "إذن", "selection_media_access_body": "الوصول مطلوب.",
    "selection_grant_access": "نعم", "selection_loading_groups_title": "بحث...", "selection_loading_groups_body": "تنظيم...",
    "selection_no_groups_title": "لا يوجد", "selection_no_groups_body": "أضف يدوياً.", "selection_refresh_groups": "تحديث",
    "selection_add_group": "موجب", "home_upload_request_title": "ملف جديد", "home_upload_request_single": "ملف",
    "home_upload_request_files": "%1$d ملفات", "home_upload_request_body": "%1$s يرسل %2$s:",
    "home_upload_request_total_size": "الحجم: %1$s", "home_history_content_desc": "سجل",
    "home_settings_content_desc": "إعدادات", "home_network_required_title": "شبكة",
    "home_network_required_body": "واي فاي أو نقطة اتصال.", "message_unable_add_folder": "خطأ.",
    "message_saved_share_named": "حُفظ '%1$s'.", "message_unable_save_share": "فشل.",
    "message_saved_share_ready": "جاهز.", "home_all_files_access_title": "مستندات؟",
    "home_all_files_access_body": "امنح الإذن.", "home_all_files_access_grant": "نعم",
    "home_all_files_access_media_only": "ميديا فقط", "home_all_files_nudge_text": "أي ملف!",
    "message_unable_open_saved_share": "خطأ.", "message_saved_share_removed": "حُذف.",
    "message_something_went_wrong": "حدث خطأ.", "message_pin_on": "الرمز مفعل.", "message_pin_off": "الرمز معطل.",
    "message_debug_log_prepare_failed": "خطأ بالسجل.", "message_debug_log_cleared": "تم.",
    "message_debug_log_clear_failed": "خطأ.", "message_file_no_longer_available": "غير موجود.",
    "message_preparing_browser_playback": "الويب %1$s.", "nearby_helper_tap_session": "اضغط للفتح.",
    "nearby_helper_open_on_other_device": "الفتح.", "share_preset_enter_name": "الاسم:",
    "share_preset_add_content_first": "أضف ملفات.", "share_preset_select_file_first": "اختر.",
    "share_preset_files_unavailable": "ملفات ناقصة.", "share_preset_collection_unavailable": "لا توجد.",
    "share_preset_restore_failed": "خطأ.", "sharing_preflight_failed": "خطأ: %1$s",
    "sharing_add_content_first": "أضف شيئاً.", "sharing_same_wifi_needed": "نفس الشبكة.",
    "sharing_connect_before_start": "اتصل.", "sharing_server_start_failed": "خطأ: %1$s",
    "sharing_blocked_by_live_screen": "أوقف البث.", "sharing_stopped": "متوقف.",
    "sharing_device_android": "Android", "network_helper_wifi_ready": "واي فاي تمام.",
    "network_helper_local_ready": "محلي تمام.", "network_helper_wifi_found": "IP موجود.",
    "network_helper_hotspot_ready": "نقطة تمام.", "network_helper_mobile_only": "بيانات فقط.",
    "network_helper_local_address_ready": "IP تمام.", "network_helper_connect_both": "نفس الشبكة للاجهزة.",
    "discovery_unavailable_device": "مغلق.", "discovery_nsd_unavailable": "مغلق.",
    "discovery_searching": "بحث...", "discovery_unavailable_now": "QR فقط.",
    "discovery_start_failed": "خطأ (%1$d)", "discovery_ready_to_open": "تم.",
    "browser_title": "DirectServe", "browser_subtitle": "ملفات", "browser_file_unavailable": "مفقود.",
    "browser_debug_unavailable": "مغلق.", "browser_debug_missing_payload": "لا يوجد.", "browser_pin_mismatch": "رمز خاطئ.",
    "browser_device_blocked": "محظور.", "browser_enter_pin": "الرمز:",
    "browser_optimized_unavailable": "ليس للويب.", "browser_video_part_preparing": "تجهيز...",
    "browser_video_part_unavailable": "لا يوجد.", "browser_hls_not_needed": "غير مطلوب.",
    "browser_hls_not_ready": "غير جاهز.", "home_action_add_to_share_title": "موجب",
    "home_action_add_to_share_subtitle": "إضافة", "home_action_files": "ملفات", "home_action_files_desc": "نعم",
    "home_action_folder": "مجلد", "home_action_folder_desc": "نعم", "home_action_library": "المكتبة",
    "home_action_library_desc": "بحث", "home_button_share_all_media": "الكل", "home_button_adding_all": "يُضاف...",
    "home_media_server_active": "الكل متاح", "home_btn_stop_media_server": "إيقاف", "web_folders_title": "مجلدات",
    "web_folder_items": "%1$d", "web_btn_back_to_folders": "رجوع", "web_all_media": "الميديا",
    "home_nearby_title": "حولك", "home_nearby_subtitle": "الأجهزة.",
    "home_nearby_refresh_status": "تحديث", "home_network_wifi": "واي فاي تمام", "home_network_hotspot": "نقطة تمام",
    "home_network_local": "محلي تمام", "home_network_none": "لا شيء", "home_network_ready_desc": "جاهز.",
    "home_network_none_desc": "اتصال مطلوب.", "home_nearby_optional_title": "تطبيق إضافي",
    "home_nearby_optional_desc": "ليس إلزامياً.", "home_nearby_refresh": "بحث",
    "home_nearby_open_title": "بالتطبيق", "home_nearby_open_desc": "إن وجد.",
    "home_nearby_action_open_session": "تفضل", "home_nearby_action_open": "نعم", "home_nearby_device_available": "تم",
    "home_nearby_device_pin": "الرمز", "web_hero_eyebrow": "DirectServe", "web_hero_title": "ملفاتك",
    "web_hero_desc1": "فيديو وصور.", "web_hero_desc2": "وملفات.", "web_hero_desc3": "خاص.",
    "web_hero_stat_shared": "يعمل", "web_items": "عنصر", "web_hero_stat_ready": "تم", "web_hero_stat_access": "إذن",
    "web_access_pin": "مقفل", "web_access_instant": "مفتوح", "web_access_pin_desc": "يتطلب رمز",
    "web_access_instant_desc": "تم", "web_pin_entry_kicker": "رمز", "web_pin_entry_title": "أدخل الرمز",
    "web_pin_entry_desc": "على الشاشة.", "web_pin_entry_placeholder": "الرمز", "web_btn_videos": "فيديو",
    "web_btn_download_all_files": "تحميل الكل", "web_cat_videos": "فيديو", "web_cat_photos": "صور",
    "web_cat_music": "موسيقى", "web_cat_files": "ملفات", "web_recent_title": "جديد", "web_recent_meta": "جاهز",
    "web_nav_home": "رئيسية", "web_nav_drop_zone": "إسقاط", "web_nav_logout": "خروج", "web_nav_media": "ميديا",
    "web_nav_files": "ملفات", "web_nav_send": "إرسال", "web_strip_session": "جلسة", "web_strip_device": "نحن",
    "web_strip_link": "الرابط", "web_security_pin": "رمز", "web_security_open": "بدون", "web_status_unknown": "؟",
    "home_connected_devices": "المتصلة", "home_rename_device": "اسم", "home_rename_device_subtitle": "%1$s • %2$s",
    "home_rename_custom_name": "جديد", "home_rename_save": "تم", "home_rename_cancel": "إلغاء", "home_quick_filters": "تصفية",
    "home_quick_filter_today": "اليوم", "home_quick_filter_today_desc": "24 ساعة", "home_quick_filter_week": "الأسبوع",
    "home_quick_filter_week_desc": "7 أيام", "home_quick_filter_month": "الشهر", "home_quick_filter_month_desc": "30 يوم",
    "home_quick_filter_custom": "وقت", "home_quick_filter_custom_desc": "اختيار", "home_date_range_title": "أيام",
    "home_date_range_from": "من", "home_date_range_start": "بداية", "home_date_range_to": "إلى",
    "home_date_range_end": "نهاية", "home_date_range_tip": "مفيد.", "home_date_range_apply": "تم",
    "home_date_range_cancel": "إلغاء", "home_recent_shares": "قديم", "home_section_library": "ملفات",
    "home_section_live_tools": "أدوات", "home_section_network_tv": "تلفاز", "home_section_sharing": "حدث",
    "home_section_live_features": "إضافي", "home_feature_library": "مكتبة", "home_feature_library_desc": "إدارة.",
    "home_feature_transfers": "نقل", "home_feature_transfers_desc": "تحميلات.", "home_feature_share_files": "شارك",
    "home_feature_share_files_desc": "الكل.", "home_feature_receive_files": "استلم",
    "home_feature_receive_files_desc": "نعم.", "home_feature_play_media": "شغل",
    "home_feature_play_media_desc": "ويب.", "home_feature_play_media_live": "نعم.", "home_feature_dlna": "DLNA",
    "home_feature_dlna_desc": "تلفاز.", "home_feature_dlna_enabled": "مفعل.", "home_feature_live_screen": "شاشة",
    "home_feature_live_screen_desc": "نسخ.", "home_feature_quick_text": "نص", "home_feature_quick_text_desc": "نعم.",
    "home_saved_shares": "مجموعات", "home_saved_shares_save_now": "حفظ", "home_saved_shares_open": "فتح",
    "home_saved_shares_delete": "حذف", "plural:home_saved_shares_items_count": {"one": "1", "other": "%1$d"},
    "library_date_group_label": "%1$s", "web_upload_title": "رفع", "web_upload_subtitle": "للهاتف.",
    "web_upload_prompt_title": "هات ملفات", "web_upload_prompt_desktop": "اسحب.",
    "web_upload_prompt_mobile": "اضغط.", "web_upload_button_browse": "بحث",
    "web_upload_button_photos": "صور", "web_upload_button_any_file": "ملف", "web_upload_target_kicker": "الهاتف",
    "web_upload_target_status": "تم.", "web_upload_how_kicker": "نعم", "web_upload_how_title": "موافقة",
    "web_upload_how_body": "يجب أن يوافق.", "web_action_download": "تنزيل", "web_action_view": "شاهد",
    "web_photo_view": "شاهد", "web_btn_download_all": "تنزيل", "web_btn_download_selected": "تنزيل",
    "web_btn_download_original": "عادي", "web_btn_fullscreen": "كامل", "web_error_streaming_codec": "لا يعمل. نزله.",
    "web_error_downloads_disabled": "مغلق.", "web_error_video_decode": "خطأ. نزله.",
    "web_error_video_start": "خطأ. نزله.", "web_error_video_start_no_dl": "جاري الإصلاح...",
    "web_error_load_failed": "خطأ.", "web_btn_select_files": "تحديد", "web_status_selection_on": "يعمل",
    "web_btn_select_all": "الكل", "web_btn_clear_selection": "إلغاء", "web_player_slow_start_hint": "انتظر...",
    "web_selection_count": "%1$d", "web_library_desc_download": "شاهد أو خذ.", "web_library_desc_browse": "الكل هنا.",
    "web_btn_load_more": "المزيد", "web_btn_show_all": "الكل", "web_btn_showing_all": "تحميل...",
    "web_show_all_confirm": "الكل %1$d؟", "web_library_showing_count": "%1$d / %2$d",
    "web_search_placeholder": "الاسم...", "web_library_empty": "فارغ.", "web_upload_selection_empty": "لا شيء.",
    "web_upload_selection_single": "%1$s", "web_upload_selection_multiple": "%1$d", "web_upload_button_send": "إرسال",
    "common_quick_filters": "تصفية", "common_edit_nickname": "اسم", "home_quick_filters_desc": "أيام.",
    "home_date_range_body": "أيام.", "web_upload_requesting": "يطلب...", "web_upload_waiting": "ينتظر...",
    "web_upload_denied": "لا.", "web_upload_failed_status": "خطأ (%1$d)",
    "web_upload_network_error": "شبكة.", "web_upload_cancelled": "إلغاء.", "web_upload_success_title": "دخل",
    "web_upload_success_detail_single": "تم.", "web_upload_success_detail_multiple": "تم.",
    "web_upload_failed_title": "لا", "web_upload_failed_detail": "خطأ.", "web_player_error_open": "لا يفتح",
    "web_player_opening": "يبدأ...", "web_player_ready": "تم", "web_player_analyzing": "ينظر...",
    "web_player_finalizing": "ينتهي...", "web_player_stalled": "توقف", "web_player_starting": "يلا...",
    "web_player_wait_desc": "قليلاً...", "web_player_ready_desc": "يعمل.", "web_player_analyzing_desc": "يبحث...",
    "web_player_finalizing_desc": "تقريباً...", "web_player_stalled_desc": "ثقيل.",
    "web_player_needs_prepare": "يريد ويب", "web_player_needs_prepare_desc": "بالهاتف.",
    "web_player_starting_desc": "يبدأ...", "web_player_try_again": "مجدداً", "web_player_status_opening": "بدء",
    "web_player_status_ready": "تم", "web_player_status_analyzing": "تحليل", "web_player_status_finalizing": "نهاية",
    "web_player_status_stalled": "علق", "web_player_status_playing": "شغال", "web_player_progress_preparing": "دور",
    "web_player_progress_converting": "يكتب", "web_player_status_failed": "لا", "web_player_status_stopped": "توقف",
    "web_prepare_video": "ويب", "web_progress_percent": "%1$d%%", "web_media_quick_title": "ميديا",
    "web_media_quick_subtitle": "ضع.", "web_media_open_category": "%1$s", "web_media_empty": "فارغ.",
    "web_send_files_to_device": "إرسال", "web_upload_in_progress": "يُرفع...", "web_upload_complete": "تم",
    "web_upload_failed": "لا", "web_cancel": "إلغاء", "web_upload_preparing_transfer": "تجهيز...",
    "web_upload_connecting": "اتصال...", "web_btn_back": "رجوع", "web_status_subtitles_available": "ترجمة",
    "web_now_playing": "شغال", "common_resume": "متابعة", "web_status_init_progress": "0%",
    "common_play": "تشغيل", "common_pause": "إيقاف", "common_unit_b": "B", "common_unit_kb": "KB",
    "common_unit_mb": "MB", "common_unit_gb": "GB", "common_unit_tb": "TB", "common_unit_s": "ث",
    "common_unit_m": "د", "common_unit_h": "س", "common_byte_format_decimal": "%1$.1f %2$s",
    "common_byte_format_integer": "%1$d %2$s", "common_duration_format_m_s": "%1$dد %2$dث",
    "common_duration_format_h_m": "%1$dس %2$dد", "common_duration_format_s": "%1$dث",
    "common_duration_timestamp_m_s": "%1$d:%2$02d", "common_duration_timestamp_h_m_s": "%1$d:%2$02d:%3$02d",
    "service_file_index_pattern": "%1$s (%2$d/%3$d)", "service_upload_progress_subtext_pattern": "%1$s / %2$s",
    "help_section_media_server": "خادم", "help_line_media_server_1": "سيرفر.",
    "help_line_media_server_2": "مرتب.", "help_section_folders_nav": "مجلدات",
    "help_line_folders_1": "كما هي.", "help_line_folders_2": "نظيف.", "help_section_dlna_tv": "تلفاز",
    "help_line_dlna_1": "ذكي.", "help_line_dlna_2": "DirectServe.", "help_line_dlna_3": "من الشبكة.",
    "help_line_dlna_4": "VLC تمام.", "help_section_search_sticky": "بحث", "help_line_search_1": "سريع.",
    "help_line_search_2": "فوق.", "settings_dlna": "DLNA TV", "settings_dlna_desc": "تلفاز/VLC.",
    "dlna_server_name": "DirectServe", "dlna_server_name_template": "DirectServe (%1$s)",
    "web_action_download_zip": "تنزيل ZIP", "web_btn_download_all_zip": "الكل ZIP",
    "web_btn_download_selected_zip": "تنزيل ZIP", "web_error_no_items_selected": "لا شيء.",
    "web_download_started_hint": "يضغط...", "playback_mode_direct": "مباشر",
    "playback_mode_repackaging": "علبة", "playback_mode_transcoding": "ثقيل",
    "playback_mode_analyzing": "تحليل", "compatibility_message_cached_ready": "جاهز من قبل.",
    "compatibility_message_stopped": "توقف.", "compatibility_message_validation_failed": "خطأ: %1$s",
    "compatibility_message_adjusted": "تم.", "compatibility_message_optimizing": "تجهيز...",
    "compatibility_message_almost_ready": "قريباً...", "compatibility_message_ready": "تم.",
    "compatibility_message_analyzing": "ينظر...", "compatibility_message_finalizing_optimized": "نهاية...",
    "compatibility_message_finalizing_compatible": "نهاية...", "compatibility_message_optimizing_web": "ويب...",
    "compatibility_message_repackaging_web": "تغليف...", "compatibility_message_converting_web": "تحويل...",
}

# HINDI (hi)
hi_data = {
    "common_back": "वापस", "common_cancel": "रद्द करें", "common_save": "सेव", "common_delete": "डिलीट",
    "common_open": "खोलें", "common_refresh": "रिफ्रेश", "common_continue": "जारी रखें", "common_accept": "स्वीकार करें",
    "common_decline": "अस्वीकार करें", "common_dismiss": "बंद करें", "common_remove": "हटाएं", "common_search": "खोजें",
    "common_separator_pipe": " | ", "common_separator_dot": " • ", "onboarding_skip": "स्किप",
    "onboarding_title": "DirectServe",
    "onboarding_subtitle": "अपने फ़ोन को स्थानीय हब में बदलें।",
    "onboarding_page_1_title": "सभी स्क्रीन पर देखें",
    "onboarding_page_1_description": "क्लाउड के बिना वीडियो और तस्वीरें टीवी या पीसी पर चलाएं।",
    "onboarding_page_2_title": "हर जगह काम करता है",
    "onboarding_page_2_description": "ब्राउज़र से किसी भी डिवाइस पर एक्सेस।",
    "onboarding_page_3_title": "वेबसाइट से चलाएं",
    "onboarding_page_3_description": "बस लिंक या क्यूआर (QR) कोड इस्तेमाल करें।",
    "onboarding_page_4_title": "दोनों तरफ शेयरिंग",
    "onboarding_page_4_description": "फाइल भेजें और प्राप्त करें।",
    "onboarding_page_5_title": "इंटरनेट नहीं चाहिए",
    "onboarding_page_5_description": "वाई-फाई या हॉटस्पॉट पर काम करता है।",
    "onboarding_page_6_title": "पूरी प्राइवेसी",
    "onboarding_page_6_description": "क्लाउड या अकाउंट की कोई जरूरत नहीं।",
    "onboarding_page_counter": "%1$d / %2$d", "onboarding_next": "अगला", "onboarding_get_started": "शुरू करें",
    "settings_title": "सेटिंग्स", "settings_subtitle": "अपने अनुभव को सेट करें।",
    "settings_group_general": "सामान्य", "settings_group_notifications": "सूचनाएं", "settings_group_privacy": "प्राइवेसी",
    "settings_group_browser": "ब्राउज़र", "settings_group_advanced": "एडवांस", "settings_group_network": "नेटवर्क",
    "settings_group_help": "मदद", "settings_group_debug": "डेवलपर", "settings_language": "भाषा",
    "settings_theme": "थीम", "settings_theme_subtitle": "लुक बदलें", "settings_theme_system": "सिस्टम",
    "settings_theme_dark": "डार्क", "settings_theme_light": "लाइट", "settings_keep_screen_awake": "स्क्रीन चालू रखें",
    "settings_keep_screen_awake_desc": "शेयर करते समय स्क्रीन बंद नहीं होगी।",
    "settings_vibrate_on_connect": "कनेक्ट होने पर वाइब्रेट", "settings_vibrate_on_connect_desc": "कोई जुड़े तो कंपन।",
    "settings_show_speed": "स्पीड दिखाएं", "settings_show_speed_desc": "डेटा की स्पीड।",
    "settings_show_recent_shares": "हिस्ट्री", "settings_show_recent_shares_desc": "हाल के शेयर दिखाएं।",
    "settings_auto_stop": "ऑटो-स्टॉप", "settings_auto_stop_never": "कभी नहीं", "settings_auto_stop_15m": "15 मिनट",
    "settings_auto_stop_30m": "30 मिनट", "settings_auto_stop_1h": "1 घंटा", "settings_connection_alerts": "कनेक्शन अलर्ट",
    "settings_connection_alerts_desc": "जब कोई जुड़े।",
    "settings_download_alerts": "डाउनलोड अलर्ट", "settings_download_alerts_desc": "जब कोई कुछ डाउनलोड करे।",
    "settings_upload_requests": "फाइल रिसीव", "settings_upload_requests_desc": "आने वाली फाइलें पूछें।",
    "settings_quick_text_enabled": "क्विक मैसेज", "settings_quick_text_enabled_desc": "टेक्स्ट मैसेज भेजें।",
    "settings_quick_text_alerts": "मैसेज अलर्ट", "settings_quick_text_alerts_desc": "मैसेज आने पर।",
    "settings_use_pin": "पिन इस्तेमाल करें", "settings_use_pin_desc": "पासवर्ड लगाएं।",
    "settings_new_pin_each_time": "हर बार नया पिन", "settings_new_pin_each_time_desc": "ऑटोमैटिक नया पिन।",
    "settings_pin_label": "पिन", "settings_pin_placeholder": "4-6 अंक", "settings_approve_file_uploads": "फाइलें मंजूर करें",
    "settings_approve_file_uploads_desc": "आने से पहले पूछें।",
    "settings_approve_per_device": "डिवाइस के लिए मंज़ूरी", "settings_approve_per_device_desc": "एक बार मंज़ूरी दें।",
    "settings_received_files_location": "डाउनलोड फोल्डर", "settings_received_files_location_value": "डाउनलोड",
    "settings_show_thumbnails": "फोटो दिखाएं", "settings_show_thumbnails_desc": "छोटे फोटो।",
    "settings_large_tv_layout": "टीवी लुक", "settings_large_tv_layout_desc": "बड़े बटन।",
    "settings_highlight_downloads": "डाउनलोड बटन हाईलाइट", "settings_highlight_downloads_desc": "साफ दिखने के लिए।",
    "settings_sign_out_on_stop": "लॉगआउट करें", "settings_sign_out_on_stop_desc": "स्टॉप होने पर हटा दें।",
    "settings_clear_temporary_files": "कचरा हटाएं", "settings_clear_temporary_files_desc": "वीडियो फाइल्स डिलीट।",
    "settings_prevent_downloads": "डाउनलोड बंद", "settings_prevent_downloads_desc": "केवल देखने दें।",
    "settings_auto_optimize_library": "ऑटो-रेडी", "settings_auto_optimize_library_desc": "बैटरी खर्च होगी।",
    "settings_sharing_port": "पोर्ट", "settings_sharing_port_placeholder": "43183",
    "settings_sharing_port_help": "इसे न बदलें।",
    "settings_wifi_settings": "वाई-फाई", "settings_wifi_settings_desc": "एक ही नेटवर्क पर हों।",
    "settings_hotspot_settings": "हॉटस्पॉट", "settings_hotspot_settings_desc": "अपना नेट बनाएं।",
    "settings_view_onboarding": "ट्यूटोरियल", "settings_view_onboarding_desc": "शुरुआत देखें।",
    "settings_privacy_policy": "प्राइवेसी पॉलिसी", "settings_privacy_policy_desc": "सब सुरक्षित।",
    "settings_privacy_promise": "वादा", "settings_privacy_promise_desc": "डेटा आपका है।",
    "settings_how_it_works": "कैसे काम करता है", "settings_how_it_works_desc": "मदद।",
    "settings_app_version": "वर्जन", "settings_recent_shares_count": "फाइलें: %1$d",
    "settings_share_debug_log": "लॉग भेजें", "settings_share_debug_log_desc": "गलती रिपोर्ट करें।",
    "settings_clear_debug_log": "लॉग हटाएं",
    "help_title": "मदद", "help_about_title": "बारे में",
    "help_about_1": "ब्राउज़र पर फाइलें खोलें।",
    "help_about_2": "बस वाई-फाई चाहिए।",
    "help_about_3": "इंटरनेट नहीं।",
    "help_section_what_you_can_do": "क्या कर सकते हैं", "help_section_video_playback": "वीडियो प्ले",
    "help_section_browser_preparation": "वेब ऑप्टिमाइज़", "help_section_receiving_files": "फाइल लें",
    "help_section_drop_zone": "फाइल भेजें", "help_section_multiple_devices": "कई डिवाइस",
    "help_section_privacy_controls": "प्राइवेसी", "help_section_good_to_know": "जान लें",
    "help_section_quick_flow": "शुरू करें", "help_line_share_files": "फाइलें शेयर।",
    "help_line_open_session": "ब्राउज़र में खोलें।",
    "help_line_same_network": "नेटवर्क सेम रखें।",
    "help_line_multiple_browse": "सब साथ में।",
    "help_line_video_direct": "सीधा प्ले।",
    "help_line_video_temporary": "शायद कंवर्ट करना पड़े।",
    "help_line_video_original": "ओरिजिनल सेफ।",
    "help_line_prep_optional": "कंवर्ट करना मर्जी है।",
    "help_line_prep_control": "कभी भी रोकें।",
    "help_line_prep_batch": "गर्म हो सकता है।",
    "help_line_receive_upload": "कोई भी भेज सकता है।",
    "help_line_receive_approval": "मंज़ूरी दें।",
    "help_line_receive_history": "डाउनलोड्स में मिलेगी।",
    "help_line_drop_zone": "ड्रैग एंड ड्रॉप।",
    "help_line_drop_zone_pick": "या चुनें।", "help_line_drop_zone_local": "100% लोकल।",
    "help_line_multi_connect": "बहुत लोग।",
    "help_line_multi_live": "नाम दिखेंगे।",
    "help_line_multi_controls": "ब्लॉक करें।",
    "help_line_privacy_local": "नो अकाउंट।",
    "help_line_privacy_session": "वही दिखेगा जो आप देंगे।",
    "help_line_privacy_controls": "पूरा कंट्रोल।",
    "help_line_wifi_hotspot": "वाई-फाई या हॉटस्पॉट।",
    "help_line_public_wifi": "हॉटस्पॉट बेहतर है।",
    "help_line_downloads_disabled": "डाउनलोड बंद करें।",
    "help_line_flow_1": "1. फाइलें जोड़ें।", "help_line_flow_2": "2. शुरू करें।",
    "help_line_flow_3": "3. क्यूआर स्कैन।", "help_line_flow_4": "4. देखें।",
    "home_brand_title": "DirectServe", "home_brand_subtitle": "प्राइवेट शेयरिंग",
    "home_chip_local_session": "लोकल", "home_chip_sharing": "शेयर हो रहा है", "home_chip_ready": "रेडी",
    "home_chip_setup_needed": "नेटवर्क चाहिए", "home_live_banner": "लाइव है",
    "home_title_live": "शेयरिंग चालू", "home_title_start": "करंट शेयर",
    "home_body_live": "लोग जुड़ सकते हैं।", "home_body_start": "फाइलें जोड़ें।",
    "home_body_start_secondary": "लाइब्रेरी इस्तेमाल करें।",
    "home_button_start_session": "शेयर करें", "home_button_open_session": "खोलें",
    "home_button_starting": "शुरू हो रहा है...", "home_button_add_media": "जोड़ें", "home_button_add_more": "और जोड़ें",
    "home_summary_current_share": "टोटल", "home_summary_media": "मीडिया", "home_summary_files": "फाइलें",
    "home_content_filter_title": "क्या दिखाएं", "home_content_filter_subtitle": "ब्राउज़र में",
    "home_content_filter_videos": "वीडियो", "home_content_filter_music": "गाने", "home_content_filter_photos": "फोटो",
    "home_content_filter_files": "फाइलें", "home_no_network": "वाई-फाई नहीं है",
    "network_setup_title": "नेटवर्क चाहिए", "network_setup_body": "सेम वाई-फाई।",
    "network_setup_trouble_title": "कोई दिक्कत?",
    "network_setup_trouble_body": "हॉटस्पॉट ऑन करें।",
    "network_setup_open_wifi": "वाई-फाई", "network_setup_switch_hotspot": "हॉटस्पॉट",
    "network_setup_retry": "फिर से", "network_setup_footer": "बेस्ट है।",
    "session_title": "लाइव सेशन", "session_stop_sharing": "स्टॉप", "session_live_now": "लाइव",
    "session_live_now_subtitle": "सबको दिखेगा।", "session_share_live": "चालू है",
    "session_share_preparing": "तैयार...", "session_share_live_body": "क्यूआर (QR) कोड स्कैन।",
    "session_qr_title": "स्कैन करें", "session_qr_body": "सबके लिए।",
    "session_qr_preparing": "बन रहा है", "session_browser_prep_title": "वेब तैयारी",
    "session_browser_prep_active": "%1$d%% • रेडी %2$d / %3$d", "session_browser_prep_queued": "वेटिंग %1$d",
    "session_browser_prep_ready": "%1$d रेडी", "session_browser_prep_message_active": "प्रोसेसिंग...",
    "session_browser_prep_message_queued": "वेटिंग", "session_browser_prep_message_ready": "रेडी",
    "session_browser_prep_message_manual": "ध्यान दें",
    "session_browser_prep_manual_note": "बिना तैयारी के अटकेगा।",
    "session_prepare_browser_files": "रेडी करें", "session_stop_browser_files": "स्टॉप",
    "session_library_refresh_title": "रिफ्रेश",
    "session_library_refresh_pending": "%1$d फाइलें मिलीं।",
    "session_library_refresh_up_to_date": "अप-टू-डेट है।", "session_refresh_library": "अभी",
    "message_live_library_refreshed_updates": "%1$d जुड़े।",
    "message_live_library_refreshed_current": "सब सही है।",
    "message_browser_playback_queued_all": "कतार में हैं।",
    "message_browser_playback_already_ready": "पहले से रेडी।", "message_browser_playback_stopped": "रुक गया।",
    "library_importing_title": "ला रहा है", "library_importing_body": "इंतज़ार करें...",
    "session_waiting_local_link": "नेटवर्क...", "session_qr_content_desc": "क्यूआर कोड",
    "session_share_link": "लिंक", "session_share_link_body": "सेम नेटवर्क।", "session_network": "नेटवर्क",
    "session_access_pin": "पिन", "session_pin_off": "बंद", "session_new_pin": "नया",
    "session_turn_pin_on": "ऑन", "session_turn_pin_off": "ऑफ", "session_nearby_name": "नाम",
    "session_what_happens_now": "स्टेटस", "session_waiting_ready": "इंतज़ार...",
    "session_waiting_first_device": "डिवाइस आने दें...", "session_devices_connected_now": "%1$d जुड़े।",
    "session_friendly_local_name": "लोकल नाम", "session_copy_link": "कॉपी", "session_share": "शेयर",
    "session_metric_devices": "डिवाइस", "session_metric_sent": "गया", "session_metric_speed": "स्पीड",
    "session_metric_elapsed": "समय", "session_metric_remaining": "बाकी", "session_connected_waiting": "इंतज़ार...",
    "session_connected_title": "जुड़े हुए", "session_connected_waiting_body": "यहाँ दिखेंगे।",
    "session_connected_count": "%1$d चालू।", "session_disconnect_all": "सबको हटाएं",
    "session_no_devices": "कोई नहीं।", "session_block_device": "ब्लॉक",
    "session_block": "ब्लॉक", "session_blocked_title": "ब्लॉक किए गए", "session_unblock_device": "अनब्लॉक",
    "session_unblock": "हटाएं", "session_state_sharing_now": "चालू", "session_state_preparing": "तैयार",
    "session_state_network_needed": "नेटवर्क चाहिए", "session_network_hotspot": "हॉटस्पॉट", "session_network_wifi": "वाई-फाई",
    "session_network_local": "लोकल", "session_network_offline": "ऑफ़लाइन", "history_title": "हिस्ट्री",
    "history_tab_all": "सभी", "history_tab_received": "मिले", "history_empty_all": "खाली।",
    "history_empty_received": "खाली।", "history_sent": "गए", "history_received": "मिले",
    "history_open": "खोलें", "history_delete": "हटाएं", "history_delete_desc": "क्लीन करें",
    "history_date_time_format": "%1$s - %2$s", "splash_title": "DirectServe", "splash_subtitle": "प्राइवेट शेयर",
    "privacy_policy_title": "प्राइवेसी", "privacy_policy_intro": "फाइलें आपके पास।",
    "privacy_policy_line_1": "अकाउंट नहीं चाहिए।", "privacy_policy_line_2": "क्लाउड नहीं।",
    "privacy_policy_line_3": "लोकल नेटवर्क।", "privacy_policy_line_4": "पूरा कंट्रोल।",
    "main_service_background_protection_failed": "बैकग्राउंड फेल।",
    "main_notification_permission_warning": "नोटिफिकेशन चाहिए।",
    "main_batch_media_access_needed": "मीडिया परमिशन दें।", "main_debug_log_subject": "लॉग",
    "main_debug_log_body": "अटैच है।", "main_debug_log_chooser": "भेजें...",
    "main_no_email_app": "ईमेल ऐप नहीं है।", "main_no_browser_app": "ब्राउज़र नहीं है।",
    "main_no_file_app": "ऐप नहीं है।", "main_link_copied": "कॉपी हुआ।",
    "main_link_preparing": "इंतज़ार...", "main_share_link_chooser": "शेयर...",
    "main_link_not_ready": "रेडी नहीं।", "main_not_sharing": "बंद", "service_start_failed": "शुरू नहीं हुआ।",
    "service_auto_stop_message": "टाइम खत्म।", "service_upload_request_title": "फाइल आ रही है",
    "service_upload_request_text": "%1$s (%3$s -> %2$s)", "service_upload_progress_title": "ले रहा है %1$s",
    "service_upload_progress_text": "%1$d%% (%2$s)", "service_upload_progress_text_unknown": "आ रहा है: %1$s",
    "service_upload_success_title": "सेव: %1$s", "service_upload_success_text": "भेजने वाला: %1$s",
    "service_upload_success_subtext": "डाउनलोड्स में", "service_file_count": "%1$d फाइलें",
    "plural:service_new_devices_connected": {"one": "डिवाइस जुड़ा", "other": "%1$d डिवाइस"},
    "plural:service_devices_joined": {"one": "%1$s आया।", "other": "%1$s आया (%2$d)।"},
    "service_waiting_for_devices": "इंतज़ार...", "plural:service_devices_connected": {"one": "1 डिवाइस", "other": "%1$d डिवाइस"},
    "service_preparing_browser_access": "वेब रेडी...", "service_channel_requests_name": "ट्रांसफर",
    "service_channel_requests_desc": "डाउनलोड", "service_channel_connections_name": "कनेक्शन",
    "service_channel_connections_desc": "डिवाइस", "service_channel_quick_text_name": "टेक्स्ट",
    "service_channel_quick_text_desc": "मैसेज", "service_quick_text_title": "%1$s का मैसेज",
    "library_title": "लाइब्रेरी", "library_header_title": "फाइलें",
    "library_header_body": "जो शेयर हैं।", "library_header_subtitles": "सबटाइटल्स डालें।",
    "library_info_items": "आइटम", "library_info_folders": "फोल्डर", "library_info_size": "साइज़",
    "library_empty_title": "खाली", "library_empty_body": "कुछ जोड़ें।", "library_section_folders": "फोल्डर",
    "library_section_folders_body": "शेयर किए गए फोल्डर।", "library_empty_filter_title": "कुछ नहीं",
    "library_empty_filter_body": "फिल्टर बदलें।", "library_section_files": "फाइलें", "library_single_file_name": "फाइल",
    "library_selected_files_name": "सिलेक्टेड", "library_save_selected_title": "सेव",
    "library_save_selected_body": "बाद के लिए।", "library_share_name": "नाम", "library_manage_title": "मैनेज",
    "library_manage_body": "सेट करें।", "library_selection_title": "नया",
    "library_selection_step_1": "1. चुनें।", "library_selection_step_2": "2. ओके।",
    "library_search_label": "खोजें...", "library_show_title": "दिखाएं", "library_show_body": "फिल्टर",
    "library_category_all": "सब", "library_category_videos": "वीडियो", "library_category_photos": "फोटो",
    "library_category_music": "म्यूज़िक", "library_category_files": "फाइलें", "library_add_title": "जोड़ें",
    "library_add_body": "फोन से।", "library_add_files": "फाइलें", "library_add_whole_folder": "फोल्डर",
    "library_add_from_suggestions": "गैलरी", "library_organize_title": "सॉर्ट",
    "library_organize_body": "लगाएं।", "library_sort_prefix": "क्रम: %1$s",
    "library_clear_all_action": "सब हटाएं", "plural:library_items_in_view": {"one": "1", "other": "%1$d"},
    "library_clear_all_title": "सब डिलीट?", "library_clear_all_body": "लिस्ट खाली।",
    "library_sort_newest": "नया", "library_sort_name": "नाम", "library_sort_size": "साइज़",
    "library_cancel_selection": "रद्द", "library_create_saved_share": "डन", "library_start_saved_share_selection": "सिलेक्ट",
    "library_browser_prep_title": "वेब कॉपी", "library_browser_prep_body": "ब्राउज़र के लिए हल्का।",
    "library_folder_summary": "%1$d | %2$s", "library_unavailable": "नहीं है", "library_direct_play": "डायरेक्ट प्ले",
    "library_subtitle": "सबटाइटल", "library_selected": "चुना गया", "library_tap_to_select": "टैप करें",
    "library_select_this_file": "हाँ", "library_preparing": "तैयार हो रहा है", "library_preparing_for_browser": "कतार में",
    "library_ready": "रेडी", "library_ready_for_browser": "वेब रेडी", "library_try_again": "फिर से",
    "library_try_browser_prep_again": "फिर से कोशिश", "library_prepare": "तैयार करें", "library_prepare_for_browser": "डन",
    "library_type_video": "वीडियो", "library_type_photo": "फोटो", "library_type_music": "ऑडियो", "library_type_file": "फाइल",
    "library_compat_ready_to_play": "रेडी | %1$s", "library_compat_not_prepared": "तैयार नहीं", "library_compat_queued": "कतार में",
    "library_compat_preparing": "प्रोसेसिंग...", "library_compat_ready": "रेडी", "library_compat_unavailable": "सपोर्ट नहीं",
    "library_compat_message": "%1$s | %2$s", "selection_add_files_title": "चुनें", "selection_add_files_body": "क्या शेयर करें?",
    "selection_add_selected": "जोड़ें", "selection_pick_files_again": "बदलें", "selection_nothing_selected_title": "खाली",
    "selection_nothing_selected_body": "कुछ चुनें।", "selection_add_folder_title": "फोल्डर",
    "selection_add_folder_body": "पूरा फोल्डर।", "selection_add_folder": "डन",
    "selection_choose_another_folder": "बदलें", "selection_no_folder_title": "गलती",
    "selection_no_folder_body": "चुनें।", "selection_selected_folder": "फोल्डर", "selection_selected_item": "1",
    "selection_smart_picks_title": "तारीखें", "selection_smart_picks_body": "सेट हैं।",
    "selection_media_access_title": "परमिशन", "selection_media_access_body": "अलाउ करें।",
    "selection_grant_access": "हाँ", "selection_loading_groups_title": "ढूंढ रहा है...", "selection_loading_groups_body": "सेटअप...",
    "selection_no_groups_title": "नहीं है", "selection_no_groups_body": "खुद डालें।", "selection_refresh_groups": "रिफ्रेश",
    "selection_add_group": "प्लस", "home_upload_request_title": "नयी फाइल", "home_upload_request_single": "फाइल",
    "home_upload_request_files": "%1$d फाइलें", "home_upload_request_body": "%1$s भेज रहा है %2$s:",
    "home_upload_request_total_size": "साइज़: %1$s", "home_history_content_desc": "हिस्ट्री",
    "home_settings_content_desc": "सेटिंग्स", "home_network_required_title": "नेटवर्क",
    "home_network_required_body": "वाई-फाई या हॉटस्पॉट।", "message_unable_add_folder": "एरर।",
    "message_saved_share_named": "सेव: '%1$s'", "message_unable_save_share": "फेल।",
    "message_saved_share_ready": "रेडी।", "home_all_files_access_title": "डॉक्यूमेंट?",
    "home_all_files_access_body": "परमिशन दें।", "home_all_files_access_grant": "हाँ",
    "home_all_files_access_media_only": "सिर्फ मीडिया", "home_all_files_nudge_text": "कोई भी फाइल!",
    "message_unable_open_saved_share": "एरर।", "message_saved_share_removed": "डिलीट।",
    "message_something_went_wrong": "कुछ गलत हुआ।", "message_pin_on": "पिन ऑन।", "message_pin_off": "पिन ऑफ।",
    "message_debug_log_prepare_failed": "लॉग एरर।", "message_debug_log_cleared": "डन।",
    "message_debug_log_clear_failed": "एरर।", "message_file_no_longer_available": "नहीं है।",
    "message_preparing_browser_playback": "वेब %1$s।", "nearby_helper_tap_session": "टैप करें।",
    "nearby_helper_open_on_other_device": "खोलें।", "share_preset_enter_name": "नाम दें:",
    "share_preset_add_content_first": "फाइल डालें।", "share_preset_select_file_first": "चुनें।",
    "share_preset_files_unavailable": "फाइलें नहीं हैं।", "share_preset_collection_unavailable": "नहीं है।",
    "share_preset_restore_failed": "एरर।", "sharing_preflight_failed": "एरर: %1$s",
    "sharing_add_content_first": "कुछ डालें।", "sharing_same_wifi_needed": "सेम वाई-फाई।",
    "sharing_connect_before_start": "जुड़ें।", "sharing_server_start_failed": "एरर: %1$s",
    "sharing_blocked_by_live_screen": "स्क्रीन शेयरिंग रोकें।", "sharing_stopped": "रुक गया।",
    "sharing_device_android": "Android", "network_helper_wifi_ready": "वाई-फाई ओके।",
    "network_helper_local_ready": "लोकल ओके।", "network_helper_wifi_found": "आईपी मिला।",
    "network_helper_hotspot_ready": "हॉटस्पॉट ओके।", "network_helper_mobile_only": "सिर्फ डेटा।",
    "network_helper_local_address_ready": "आईपी ओके।", "network_helper_connect_both": "साथ में जुड़ें।",
    "discovery_unavailable_device": "बंद।", "discovery_nsd_unavailable": "बंद।",
    "discovery_searching": "सर्च...", "discovery_unavailable_now": "सिर्फ क्यूआर।",
    "discovery_start_failed": "एरर (%1$d)", "discovery_ready_to_open": "डन।",
    "browser_title": "DirectServe", "browser_subtitle": "फाइलें", "browser_file_unavailable": "गायब।",
    "browser_debug_unavailable": "बंद।", "browser_debug_missing_payload": "नहीं है।", "browser_pin_mismatch": "गलत पिन।",
    "browser_device_blocked": "ब्लॉक।", "browser_enter_pin": "पिन:",
    "browser_optimized_unavailable": "वेब नहीं।", "browser_video_part_preparing": "बन रहा है...",
    "browser_video_part_unavailable": "नहीं है।", "browser_hls_not_needed": "जरूरी नहीं।",
    "browser_hls_not_ready": "रेडी नहीं।", "home_action_add_to_share_title": "प्लस",
    "home_action_add_to_share_subtitle": "जोड़ें", "home_action_files": "फाइलें", "home_action_files_desc": "हाँ",
    "home_action_folder": "फोल्डर", "home_action_folder_desc": "हाँ", "home_action_library": "लाइब्रेरी",
    "home_action_library_desc": "सर्च", "home_button_share_all_media": "सब", "home_button_adding_all": "जोड़ रहा है...",
    "home_media_server_active": "सब चालू", "home_btn_stop_media_server": "स्टॉप", "web_folders_title": "फोल्डर",
    "web_folder_items": "%1$d", "web_btn_back_to_folders": "पीछे", "web_all_media": "मीडिया",
    "home_nearby_title": "आसपास", "home_nearby_subtitle": "डिवाइस।",
    "home_nearby_refresh_status": "रिफ्रेश", "home_network_wifi": "वाई-फाई ओके", "home_network_hotspot": "हॉटस्पॉट ओके",
    "home_network_local": "लोकल ओके", "home_network_none": "कोई नहीं", "home_network_ready_desc": "रेडी।",
    "home_network_none_desc": "कनेक्शन चाहिए।", "home_nearby_optional_title": "ऐप मर्जी है",
    "home_nearby_optional_desc": "जरूरी नहीं।", "home_nearby_refresh": "ढूंढें",
    "home_nearby_open_title": "ऐप में", "home_nearby_open_desc": "अगर है।",
    "home_nearby_action_open_session": "आओ", "home_nearby_action_open": "हाँ", "home_nearby_device_available": "डन",
    "home_nearby_device_pin": "पिन", "web_hero_eyebrow": "DirectServe", "web_hero_title": "आपका मीडिया",
    "web_hero_desc1": "वीडियो, फोटो।", "web_hero_desc2": "फाइलें।", "web_hero_desc3": "प्राइवेट।",
    "web_hero_stat_shared": "चल रहा है", "web_items": "पीस", "web_hero_stat_ready": "रेडी", "web_hero_stat_access": "परमिशन",
    "web_access_pin": "लॉक", "web_access_instant": "ओपन", "web_access_pin_desc": "पिन चाहिए",
    "web_access_instant_desc": "डन", "web_pin_entry_kicker": "पिन", "web_pin_entry_title": "पिन डालें",
    "web_pin_entry_desc": "स्क्रीन पर।", "web_pin_entry_placeholder": "पिन", "web_btn_videos": "वीडियो",
    "web_btn_download_all_files": "सब डाउनलोड", "web_cat_videos": "वीडियो", "web_cat_photos": "फोटो",
    "web_cat_music": "गाने", "web_cat_files": "फाइलें", "web_recent_title": "नया", "web_recent_meta": "रेडी",
    "web_nav_home": "होम", "web_nav_drop_zone": "ड्रॉप", "web_nav_logout": "लॉगआउट", "web_nav_media": "मीडिया",
    "web_nav_files": "फाइलें", "web_nav_send": "भेजें", "web_strip_session": "सेशन", "web_strip_device": "हम",
    "web_strip_link": "लिंक", "web_security_pin": "पिन", "web_security_open": "नहीं", "web_status_unknown": "?",
    "home_connected_devices": "कनेक्टेड", "home_rename_device": "नाम", "home_rename_device_subtitle": "%1$s • %2$s",
    "home_rename_custom_name": "नया", "home_rename_save": "डन", "home_rename_cancel": "रद्द", "home_quick_filters": "फिल्टर",
    "home_quick_filter_today": "आज", "home_quick_filter_today_desc": "24 घंटे", "home_quick_filter_week": "हफ्ता",
    "home_quick_filter_week_desc": "7 दिन", "home_quick_filter_month": "महीना", "home_quick_filter_month_desc": "30 दिन",
    "home_quick_filter_custom": "टाइम", "home_quick_filter_custom_desc": "चुनें", "home_date_range_title": "दिन",
    "home_date_range_from": "से", "home_date_range_start": "शुरू", "home_date_range_to": "तक",
    "home_date_range_end": "अंत", "home_date_range_tip": "सही है।", "home_date_range_apply": "डन",
    "home_date_range_cancel": "रद्द", "home_recent_shares": "पुराने", "home_section_library": "फाइलें",
    "home_section_live_tools": "टूल्स", "home_section_network_tv": "टीवी", "home_section_sharing": "एक्शन",
    "home_section_live_features": "एक्स्ट्रा", "home_feature_library": "लाइब्रेरी", "home_feature_library_desc": "सेट।",
    "home_feature_transfers": "निकलना", "home_feature_transfers_desc": "डाउनलोड।", "home_feature_share_files": "शेयर",
    "home_feature_share_files_desc": "सब।", "home_feature_receive_files": "रिसीव",
    "home_feature_receive_files_desc": "हाँ।", "home_feature_play_media": "प्ले",
    "home_feature_play_media_desc": "वेब।", "home_feature_play_media_live": "हाँ।", "home_feature_dlna": "DLNA",
    "home_feature_dlna_desc": "टीवी।", "home_feature_dlna_enabled": "ऑन।", "home_feature_live_screen": "स्क्रीन",
    "home_feature_live_screen_desc": "मिरर।", "home_feature_quick_text": "टेक्स्ट", "home_feature_quick_text_desc": "हाँ।",
    "home_saved_shares": "कलेक्शन", "home_saved_shares_save_now": "सेव", "home_saved_shares_open": "खोलें",
    "home_saved_shares_delete": "हटाएं", "plural:home_saved_shares_items_count": {"one": "1", "other": "%1$d"},
    "library_date_group_label": "%1$s", "web_upload_title": "अपलोड", "web_upload_subtitle": "फोन पर।",
    "web_upload_prompt_title": "फाइलें दें", "web_upload_prompt_desktop": "ड्रैग।",
    "web_upload_prompt_mobile": "टैप।", "web_upload_button_browse": "ढूंढें",
    "web_upload_button_photos": "फोटो", "web_upload_button_any_file": "फाइल", "web_upload_target_kicker": "फोन",
    "web_upload_target_status": "डन।", "web_upload_how_kicker": "हाँ", "web_upload_how_title": "परमिशन",
    "web_upload_how_body": "मंज़ूरी चाहिए।", "web_action_download": "डाउनलोड", "web_action_view": "देखें",
    "web_photo_view": "देखें", "web_btn_download_all": "डाउनलोड", "web_btn_download_selected": "डाउनलोड",
    "web_btn_download_original": "नॉर्मल", "web_btn_fullscreen": "फुल", "web_error_streaming_codec": "नहीं चलेगा। डाउनलोड करें।",
    "web_error_downloads_disabled": "बंद।", "web_error_video_decode": "एरर। डाउनलोड।",
    "web_error_video_start": "एरर। डाउनलोड।", "web_error_video_start_no_dl": "फिक्स हो रहा है...",
    "web_error_load_failed": "एरर।", "web_btn_select_files": "सिलेक्ट", "web_status_selection_on": "ऑन",
    "web_btn_select_all": "सब", "web_btn_clear_selection": "रद्द", "web_player_slow_start_hint": "इंतज़ार...",
    "web_selection_count": "%1$d", "web_library_desc_download": "देखें या लें।", "web_library_desc_browse": "सब यहाँ है।",
    "web_btn_load_more": "और", "web_btn_show_all": "सब", "web_btn_showing_all": "ला रहा है...",
    "web_show_all_confirm": "सब %1$d?", "web_library_showing_count": "%1$d / %2$d",
    "web_search_placeholder": "नाम...", "web_library_empty": "खाली।", "web_upload_selection_empty": "कोई नहीं।",
    "web_upload_selection_single": "%1$s", "web_upload_selection_multiple": "%1$d", "web_upload_button_send": "भेजें",
    "common_quick_filters": "फिल्टर", "common_edit_nickname": "नाम", "home_quick_filters_desc": "दिन।",
    "home_date_range_body": "दिन।", "web_upload_requesting": "पूछ रहा है...", "web_upload_waiting": "वेट कर रहा है...",
    "web_upload_denied": "नहीं।", "web_upload_failed_status": "एरर (%1$d)",
    "web_upload_network_error": "नेटवर्क।", "web_upload_cancelled": "कैंसिल।", "web_upload_success_title": "गया",
    "web_upload_success_detail_single": "डन।", "web_upload_success_detail_multiple": "डन।",
    "web_upload_failed_title": "नहीं", "web_upload_failed_detail": "एरर।", "web_player_error_open": "नहीं खुला",
    "web_player_opening": "शुरू...", "web_player_ready": "रेडी", "web_player_analyzing": "देख रहा है...",
    "web_player_finalizing": "खत्म...", "web_player_stalled": "रुक गया", "web_player_starting": "चलो...",
    "web_player_wait_desc": "थोड़ा...", "web_player_ready_desc": "चल रहा है।", "web_player_analyzing_desc": "खोज रहा है...",
    "web_player_finalizing_desc": "लगभग...", "web_player_stalled_desc": "भारी है।",
    "web_player_needs_prepare": "वेब चाहिए", "web_player_needs_prepare_desc": "फोन में।",
    "web_player_starting_desc": "शुरू...", "web_player_try_again": "फिर से", "web_player_status_opening": "स्टार्ट",
    "web_player_status_ready": "डन", "web_player_status_analyzing": "चेक", "web_player_status_finalizing": "एंड",
    "web_player_status_stalled": "फंसा", "web_player_status_playing": "चल रहा", "web_player_progress_preparing": "वेट",
    "web_player_progress_converting": "लिख रहा", "web_player_status_failed": "नहीं", "web_player_status_stopped": "स्टॉप",
    "web_prepare_video": "वेब", "web_progress_percent": "%1$d%%", "web_media_quick_title": "मीडिया",
    "web_media_quick_subtitle": "डालें।", "web_media_open_category": "%1$s", "web_media_empty": "खाली।",
    "web_send_files_to_device": "भेजें", "web_upload_in_progress": "जा रहा है...", "web_upload_complete": "डन",
    "web_upload_failed": "नहीं", "web_cancel": "कैंसिल", "web_upload_preparing_transfer": "रेडी...",
    "web_upload_connecting": "जुड़ रहा है...", "web_btn_back": "पीछे", "web_status_subtitles_available": "सबटाइटल",
    "web_now_playing": "प्लेइंग", "common_resume": "जारी", "web_status_init_progress": "0%",
    "common_play": "प्ले", "common_pause": "पॉज़", "common_unit_b": "B", "common_unit_kb": "KB",
    "common_unit_mb": "MB", "common_unit_gb": "GB", "common_unit_tb": "TB", "common_unit_s": "s",
    "common_unit_m": "m", "common_unit_h": "h", "common_byte_format_decimal": "%1$.1f %2$s",
    "common_byte_format_integer": "%1$d %2$s", "common_duration_format_m_s": "%1$dm %2$ds",
    "common_duration_format_h_m": "%1$dh %2$dm", "common_duration_format_s": "%1$ds",
    "common_duration_timestamp_m_s": "%1$d:%2$02d", "common_duration_timestamp_h_m_s": "%1$d:%2$02d:%3$02d",
    "service_file_index_pattern": "%1$s (%2$d/%3$d)", "service_upload_progress_subtext_pattern": "%1$s / %2$s",
    "help_section_media_server": "सर्वर", "help_line_media_server_1": "हब।",
    "help_line_media_server_2": "सेट।", "help_section_folders_nav": "फोल्डर",
    "help_line_folders_1": "वैसा ही।", "help_line_folders_2": "क्लीन।", "help_section_dlna_tv": "टीवी",
    "help_line_dlna_1": "स्मार्ट।", "help_line_dlna_2": "DirectServe।", "help_line_dlna_3": "नेटवर्क से।",
    "help_line_dlna_4": "VLC ओके।", "help_section_search_sticky": "खोजें", "help_line_search_1": "तेज़।",
    "help_line_search_2": "ऊपर।", "settings_dlna": "DLNA TV", "settings_dlna_desc": "टीवी/VLC।",
    "dlna_server_name": "DirectServe", "dlna_server_name_template": "DirectServe (%1$s)",
    "web_action_download_zip": "ज़िप (ZIP)", "web_btn_download_all_zip": "सब ज़िप",
    "web_btn_download_selected_zip": "ज़िप लें", "web_error_no_items_selected": "कुछ नहीं।",
    "web_download_started_hint": "पैक कर रहा है...", "playback_mode_direct": "डायरेक्ट",
    "playback_mode_repackaging": "पैक", "playback_mode_transcoding": "भारी",
    "playback_mode_analyzing": "चेक", "compatibility_message_cached_ready": "पहले से रेडी।",
    "compatibility_message_stopped": "स्टॉप।", "compatibility_message_validation_failed": "एरर: %1$s",
    "compatibility_message_adjusted": "डन।", "compatibility_message_optimizing": "तैयार...",
    "compatibility_message_almost_ready": "जल्द...", "compatibility_message_ready": "डन।",
    "compatibility_message_analyzing": "देख रहा है...", "compatibility_message_finalizing_optimized": "एंड...",
    "compatibility_message_finalizing_compatible": "एंड...", "compatibility_message_optimizing_web": "वेब...",
    "compatibility_message_repackaging_web": "रीपैक...", "compatibility_message_converting_web": "कंवर्ट...",
}

# Apply batch
res_dir = "core/resources/src/main/res"
rebuild_locale(res_dir, "ar", ar_data)
rebuild_locale(res_dir, "hi", hi_data)
