import os
import xml.etree.ElementTree as ET

def rebuild_locale(res_dir, locale_name, translation_dict):
    base_path = os.path.join(res_dir, "values", "strings.xml")
    target_dir = os.path.join(res_dir, f"values-{locale_name}")
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)
        
    target_path = os.path.join(target_dir, "strings.xml")
    tree = ET.parse(base_path)
    root = tree.getroot()
    new_root = ET.Element('resources')
    
    for child in root:
        if child.tag == 'string':
            name = child.get('name')
            translatable = child.get('translatable', 'true')
            new_node = ET.SubElement(new_root, 'string', {'name': name})
            if translatable == 'false':
                new_node.set('translatable', 'false')
                new_node.text = child.text
            else:
                val = translation_dict.get(name)
                new_node.text = val if val else child.text
        elif child.tag == 'plurals':
            name = child.get('name')
            new_node = ET.SubElement(new_root, 'plurals', {'name': name})
            plural_data = translation_dict.get(f"plural:{name}", {})
            for item in child:
                qty = item.get('quantity')
                new_item = ET.SubElement(new_node, 'item', {'quantity': qty})
                val = plural_data.get(qty)
                new_item.text = val if val else item.text
        elif child.tag == 'string-array':
            name = child.get('name')
            new_node = ET.SubElement(new_root, 'string-array', {'name': name})
            array_data = translation_dict.get(f"array:{name}", [])
            for i, item in enumerate(child):
                new_item = ET.SubElement(new_node, 'item')
                if i < len(array_data):
                    new_item.text = array_data[i]
                else:
                    new_item.text = item.text

    ET.indent(new_root, space="    ", level=0)
    rough_string = ET.tostring(new_root, encoding='utf-8').decode('utf-8')
    with open(target_path, 'w', encoding='utf-8') as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n')
        f.write(rough_string)

# VIETNAMESE (vi)
vi_data = {
    "common_back": "Quay lại", "common_cancel": "Hủy", "common_save": "Lưu", "common_delete": "Xóa",
    "common_open": "Mở", "common_refresh": "Làm mới", "common_continue": "Tiếp tục", "common_accept": "Chấp nhận",
    "common_decline": "Từ chối", "common_dismiss": "Đóng", "common_remove": "Gỡ bỏ", "common_search": "Tìm kiếm",
    "common_separator_pipe": " | ", "common_separator_dot": " • ", "onboarding_skip": "Bỏ qua",
    "onboarding_title": "DirectServe",
    "onboarding_subtitle": "Biến điện thoại của bạn thành trung tâm chia sẻ cục bộ.",
    "onboarding_page_1_title": "Xem trên mọi màn hình",
    "onboarding_page_1_description": "Mở video và ảnh trên TV hoặc PC mà không cần đám mây.",
    "onboarding_page_2_title": "Hoạt động mọi nơi",
    "onboarding_page_2_description": "Chỉ cần trình duyệt web trên bất kỳ thiết bị nào.",
    "onboarding_page_3_title": "Truy cập từ trình duyệt",
    "onboarding_page_3_description": "Sử dụng liên kết hoặc mã QR, không cần cài app.",
    "onboarding_page_4_title": "Chia sẻ hai chiều",
    "onboarding_page_4_description": "Gửi và nhận tệp dễ dàng.",
    "onboarding_page_5_title": "Không cần Internet",
    "onboarding_page_5_description": "Hoạt động qua mạng Wi-Fi hoặc điểm phát sóng (Hotspot).",
    "onboarding_page_6_title": "Quyền riêng tư",
    "onboarding_page_6_description": "Tệp của bạn không bao giờ rời khỏi thiết bị.",
    "onboarding_page_counter": "%1$d / %2$d", "onboarding_next": "Tiếp theo", "onboarding_get_started": "Bắt đầu",
    "settings_title": "Cài đặt", "settings_subtitle": "Tùy chỉnh DirectServe.",
    "settings_group_general": "Chung", "settings_group_notifications": "Thông báo", "settings_group_privacy": "Quyền riêng tư",
    "settings_group_browser": "Trình duyệt", "settings_group_advanced": "Nâng cao", "settings_group_network": "Mạng",
    "settings_group_help": "Trợ giúp", "settings_group_debug": "Gỡ lỗi", "settings_language": "Ngôn ngữ",
    "settings_theme": "Giao diện", "settings_theme_subtitle": "Thay đổi giao diện", "settings_theme_system": "Hệ thống",
    "settings_theme_dark": "Tối", "settings_theme_light": "Sáng", "settings_keep_screen_awake": "Luôn bật màn hình",
    "settings_keep_screen_awake_desc": "Không tắt màn hình khi đang chia sẻ.",
    "settings_vibrate_on_connect": "Rung khi kết nối", "settings_vibrate_on_connect_desc": "Khi có người tham gia.",
    "settings_show_speed": "Hiển thị tốc độ", "settings_show_speed_desc": "Tốc độ truyền tải trực tiếp.",
    "settings_show_recent_shares": "Lịch sử", "settings_show_recent_shares_desc": "Lưu lịch sử chia sẻ cục bộ.",
    "settings_auto_stop": "Tự động dừng", "settings_auto_stop_never": "Không bao giờ", "settings_auto_stop_15m": "15 phút",
    "settings_auto_stop_30m": "30 phút", "settings_auto_stop_1h": "1 giờ", "settings_connection_alerts": "Cảnh báo kết nối",
    "settings_connection_alerts_desc": "Khi một thiết bị kết nối.",
    "settings_download_alerts": "Cảnh báo tải xuống", "settings_download_alerts_desc": "Khi ai đó tải tệp.",
    "settings_upload_requests": "Yêu cầu tải lên", "settings_upload_requests_desc": "Hỏi trước khi nhận tệp.",
    "settings_quick_text_enabled": "Văn bản nhanh", "settings_quick_text_enabled_desc": "Chia sẻ tin nhắn.",
    "settings_quick_text_alerts": "Cảnh báo tin nhắn", "settings_quick_text_alerts_desc": "Khi nhận được tin nhắn.",
    "settings_use_pin": "Sử dụng mã PIN", "settings_use_pin_desc": "Yêu cầu mật khẩu.",
    "settings_new_pin_each_time": "PIN mới mỗi lần", "settings_new_pin_each_time_desc": "Bảo mật cao hơn.",
    "settings_pin_label": "Mã PIN", "settings_pin_placeholder": "4-6 số", "settings_approve_file_uploads": "Phê duyệt tệp",
    "settings_approve_file_uploads_desc": "Hỏi trước khi ai đó tải lên.",
    "settings_approve_per_device": "Phê duyệt theo thiết bị", "settings_approve_per_device_desc": "Chỉ hỏi 1 lần.",
    "settings_received_files_location": "Thư mục lưu", "settings_received_files_location_value": "Tải xuống",
    "settings_show_thumbnails": "Hiển thị hình thu nhỏ", "settings_show_thumbnails_desc": "Xem trước tệp.",
    "settings_large_tv_layout": "Giao diện TV", "settings_large_tv_layout_desc": "Nút bấm lớn hơn.",
    "settings_highlight_downloads": "Nổi bật nút Tải xuống", "settings_highlight_downloads_desc": "Dễ nhìn hơn.",
    "settings_sign_out_on_stop": "Đăng xuất khi dừng", "settings_sign_out_on_stop_desc": "Ngắt truy cập.",
    "settings_clear_temporary_files": "Xóa tệp tạm thời", "settings_clear_temporary_files_desc": "Xóa video đã tối ưu.",
    "settings_prevent_downloads": "Chặn tải xuống", "settings_prevent_downloads_desc": "Chỉ cho phép xem.",
    "settings_auto_optimize_library": "Tối ưu nền", "settings_auto_optimize_library_desc": "Tốn pin.",
    "settings_sharing_port": "Cổng", "settings_sharing_port_placeholder": "43183",
    "settings_sharing_port_help": "Không thay đổi nếu không cần thiết.",
    "settings_wifi_settings": "Cài đặt Wi-Fi", "settings_wifi_settings_desc": "Cần chung mạng.",
    "settings_hotspot_settings": "Cài đặt Điểm phát sóng", "settings_hotspot_settings_desc": "Sử dụng mạng riêng.",
    "settings_view_onboarding": "Xem hướng dẫn", "settings_view_onboarding_desc": "Mở lại từ đầu.",
    "settings_privacy_policy": "Chính sách bảo mật", "settings_privacy_policy_desc": "Riêng tư 100%.",
    "settings_privacy_promise": "Cam kết", "settings_privacy_promise_desc": "Không có đám mây.",
    "settings_how_it_works": "Cách hoạt động", "settings_how_it_works_desc": "Trợ giúp.",
    "settings_app_version": "Phiên bản", "settings_recent_shares_count": "Bộ sưu tập: %1$d",
    "settings_share_debug_log": "Gửi nhật ký", "settings_share_debug_log_desc": "Báo cáo lỗi.",
    "settings_clear_debug_log": "Xóa nhật ký",
    "help_title": "Trợ giúp", "help_about_title": "Về DirectServe",
    "help_about_1": "Mở tệp trên trình duyệt.",
    "help_about_2": "Không cần cài đặt thêm.",
    "help_about_3": "Không cần internet hay đám mây.",
    "help_section_what_you_can_do": "Bạn có thể làm gì", "help_section_video_playback": "Phát video",
    "help_section_browser_preparation": "Tối ưu hóa Web", "help_section_receiving_files": "Nhận tệp",
    "help_section_drop_zone": "Khu vực chia sẻ", "help_section_multiple_devices": "Nhiều thiết bị",
    "help_section_privacy_controls": "Quyền riêng tư", "help_section_good_to_know": "Nên biết",
    "help_section_quick_flow": "Bắt đầu nhanh", "help_line_share_files": "Chia sẻ video và ảnh.",
    "help_line_open_session": "Mở trong trình duyệt.",
    "help_line_same_network": "Cần cùng chung Wi-Fi.",
    "help_line_multiple_browse": "Mọi người cùng xem.",
    "help_line_video_direct": "Video phát trực tiếp.",
    "help_line_video_temporary": "Có thể cần chuyển đổi.",
    "help_line_video_original": "Tệp gốc được giữ nguyên.",
    "help_line_prep_optional": "Tối ưu hóa là tùy chọn.",
    "help_line_prep_control": "Có thể dừng bất cứ lúc nào.",
    "help_line_prep_batch": "Điện thoại có thể bị nóng.",
    "help_line_receive_upload": "Người khác có thể gửi tệp.",
    "help_line_receive_approval": "Bạn phải duyệt trước.",
    "help_line_receive_history": "Lưu trong mục Tải xuống.",
    "help_line_drop_zone": "Kéo thả tệp dễ dàng.",
    "help_line_drop_zone_pick": "Hoặc chọn thủ công.", "help_line_drop_zone_local": "100% qua mạng cục bộ.",
    "help_line_multi_connect": "Nhiều thiết bị một lúc.",
    "help_line_multi_live": "Tên thiết bị hiển thị.",
    "help_line_multi_controls": "Có thể chặn thiết bị.",
    "help_line_privacy_local": "Không cần tài khoản.",
    "help_line_privacy_session": "Chỉ chia sẻ những gì bạn chọn.",
    "help_line_privacy_controls": "Toàn quyền kiểm soát.",
    "help_line_wifi_hotspot": "Wi-Fi hoặc Điểm phát sóng.",
    "help_line_public_wifi": "Wi-Fi công cộng có thể chặn kết nối.",
    "help_line_downloads_disabled": "Có thể tắt chức năng tải xuống.",
    "help_line_flow_1": "1. Thêm tệp.", "help_line_flow_2": "2. Bắt đầu chia sẻ.",
    "help_line_flow_3": "3. Quét mã QR.", "help_line_flow_4": "4. Thưởng thức.",
    "home_brand_title": "DirectServe", "home_brand_subtitle": "Chia sẻ riêng tư",
    "home_chip_local_session": "Cục bộ", "home_chip_sharing": "Đang chia sẻ", "home_chip_ready": "Sẵn sàng",
    "home_chip_setup_needed": "Cần mạng", "home_live_banner": "Phiên trực tiếp",
    "home_title_live": "Chia sẻ đang hoạt động", "home_title_start": "Phiên hiện tại",
    "home_body_live": "Thiết bị khác có thể tham gia.", "home_body_start": "Thêm tệp để chia sẻ.",
    "home_body_start_secondary": "Sử dụng thư viện của bạn.",
    "home_button_start_session": "Bắt đầu", "home_button_open_session": "Mở",
    "home_button_starting": "Đang bắt đầu...", "home_button_add_media": "Thêm", "home_button_add_more": "Thêm nữa",
    "home_summary_current_share": "Tổng cộng", "home_summary_media": "Phương tiện", "home_summary_files": "Tệp",
    "home_content_filter_title": "Đang chia sẻ", "home_content_filter_subtitle": "Hiển thị trên trình duyệt",
    "home_content_filter_videos": "Video", "home_content_filter_music": "Nhạc", "home_content_filter_photos": "Ảnh",
    "home_content_filter_files": "Tệp", "home_no_network": "Không có Wi-Fi",
    "network_setup_title": "Yêu cầu mạng", "network_setup_body": "Cần chung mạng Wi-Fi.",
    "network_setup_trouble_title": "Gặp vấn đề?",
    "network_setup_trouble_body": "Sử dụng Điểm phát sóng.",
    "network_setup_open_wifi": "Wi-Fi", "network_setup_switch_hotspot": "Điểm phát sóng",
    "network_setup_retry": "Thử lại", "network_setup_footer": "Nhanh và ổn định hơn.",
    "session_title": "Phiên trực tiếp", "session_stop_sharing": "Dừng", "session_live_now": "Trực tiếp",
    "session_live_now_subtitle": "Mọi người có thể thấy bạn.", "session_share_live": "Đang hoạt động",
    "session_share_preparing": "Đang chuẩn bị...", "session_share_live_body": "Quét mã QR để tham gia.",
    "session_qr_title": "Quét", "session_qr_body": "Cho điện thoại và TV.",
    "session_qr_preparing": "Đang tạo", "session_browser_prep_title": "Tối ưu hóa Web",
    "session_browser_prep_active": "%1$d%% • Xong %2$d / %3$d", "session_browser_prep_queued": "Chờ %1$d",
    "session_browser_prep_ready": "%1$d đã xong", "session_browser_prep_message_active": "Đang xử lý...",
    "session_browser_prep_message_queued": "Đang chờ", "session_browser_prep_message_ready": "Sẵn sàng",
    "session_browser_prep_message_manual": "Cần thao tác",
    "session_browser_prep_manual_note": "Video có thể không xem được trên web.",
    "session_prepare_browser_files": "Chuẩn bị", "session_stop_browser_files": "Dừng",
    "session_library_refresh_title": "Làm mới",
    "session_library_refresh_pending": "Phát hiện %1$d tệp.",
    "session_library_refresh_up_to_date": "Đã cập nhật.", "session_refresh_library": "Làm mới",
    "message_live_library_refreshed_updates": "Đã thêm %1$d tệp.",
    "message_live_library_refreshed_current": "Không có gì mới.",
    "message_browser_playback_queued_all": "Đã xếp hàng.",
    "message_browser_playback_already_ready": "Đã sẵn sàng.", "message_browser_playback_stopped": "Đã dừng.",
    "library_importing_title": "Đang nhập", "library_importing_body": "Vui lòng chờ...",
    "session_waiting_local_link": "Mạng...", "session_qr_content_desc": "Mã QR",
    "session_share_link": "Liên kết", "session_share_link_body": "Mở chung một mạng.", "session_network": "Mạng",
    "session_access_pin": "Mã PIN", "session_pin_off": "Tắt", "session_new_pin": "Mã mới",
    "session_turn_pin_on": "Bật PIN", "session_turn_pin_off": "Tắt PIN", "session_nearby_name": "Tên",
    "session_what_happens_now": "Trạng thái", "session_waiting_ready": "Đang chờ...",
    "session_waiting_first_device": "Đang chờ thiết bị...", "session_devices_connected_now": "Có %1$d thiết bị.",
    "session_friendly_local_name": "Tên hiển thị", "session_copy_link": "Sao chép", "session_share": "Chia sẻ",
    "session_metric_devices": "Thiết bị", "session_metric_sent": "Đã gửi", "session_metric_speed": "Tốc độ",
    "session_metric_elapsed": "Thời gian", "session_metric_remaining": "Còn lại", "session_connected_waiting": "Đang chờ...",
    "session_connected_title": "Đã kết nối", "session_connected_waiting_body": "Sẽ hiển thị ở đây.",
    "session_connected_count": "%1$d đang hoạt động.", "session_disconnect_all": "Ngắt kết nối tất cả",
    "session_no_devices": "Chưa có ai.", "session_block_device": "Chặn",
    "session_block": "Chặn", "session_blocked_title": "Đã chặn", "session_unblock_device": "Bỏ chặn",
    "session_unblock": "Bỏ chặn", "session_state_sharing_now": "Đang chạy", "session_state_preparing": "Đang chuẩn bị",
    "session_state_network_needed": "Cần mạng", "session_network_hotspot": "Điểm phát sóng", "session_network_wifi": "Wi-Fi",
    "session_network_local": "Cục bộ", "session_network_offline": "Ngoại tuyến", "history_title": "Lịch sử",
    "history_tab_all": "Tất cả", "history_tab_received": "Đã nhận", "history_empty_all": "Trống.",
    "history_empty_received": "Trống.", "history_sent": "Gửi", "history_received": "Nhận",
    "history_open": "Mở", "history_delete": "Xóa", "history_delete_desc": "Xóa khỏi lịch sử",
    "history_date_time_format": "%1$s lúc %2$s", "splash_title": "DirectServe", "splash_subtitle": "Chia sẻ cục bộ",
    "privacy_policy_title": "Bảo mật", "privacy_policy_intro": "Tệp luôn an toàn.",
    "privacy_policy_line_1": "Không cần đăng ký.", "privacy_policy_line_2": "Không lên đám mây.",
    "privacy_policy_line_3": "Chỉ dùng mạng nội bộ.", "privacy_policy_line_4": "Bạn kiểm soát 100%.",
    "main_service_background_protection_failed": "Lỗi chạy ngầm.",
    "main_notification_permission_warning": "Cần quyền thông báo.",
    "main_batch_media_access_needed": "Cần quyền truy cập phương tiện.", "main_debug_log_subject": "Nhật ký gỡ lỗi",
    "main_debug_log_body": "Tệp đính kèm.", "main_debug_log_chooser": "Gửi qua...",
    "main_no_email_app": "Không có ứng dụng email.", "main_no_browser_app": "Không có trình duyệt.",
    "main_no_file_app": "Không có trình quản lý tệp.", "main_link_copied": "Đã sao chép.",
    "main_link_preparing": "Vui lòng chờ...", "main_share_link_chooser": "Chia sẻ...",
    "main_link_not_ready": "Chưa sẵn sàng.", "main_not_sharing": "Đã tắt", "service_start_failed": "Lỗi bắt đầu.",
    "service_auto_stop_message": "Đã tự động dừng.", "service_upload_request_title": "Tệp mới",
    "service_upload_request_text": "%1$s (%3$s -> %2$s)", "service_upload_progress_title": "Đang nhận %1$s",
    "service_upload_progress_text": "%1$d%% (%2$s)", "service_upload_progress_text_unknown": "Từ %1$s",
    "service_upload_success_title": "Đã lưu: %1$s", "service_upload_success_text": "Từ %1$s",
    "service_upload_success_subtext": "Trong thư mục Tải xuống", "service_file_count": "%1$d tệp",
    "plural:service_new_devices_connected": {"one": "Thiết bị đã kết nối", "other": "%1$d thiết bị kết nối"},
    "plural:service_devices_joined": {"one": "%1$s đã tham gia.", "other": "%1$s tham gia (%2$d)."},
    "service_waiting_for_devices": "Đang chờ...", "plural:service_devices_connected": {"one": "1 thiết bị", "other": "%1$d thiết bị"},
    "service_preparing_browser_access": "Đang chuẩn bị web...", "service_channel_requests_name": "Truyền tải",
    "service_channel_requests_desc": "Tải xuống", "service_channel_connections_name": "Kết nối",
    "service_channel_connections_desc": "Thiết bị", "service_channel_quick_text_name": "Văn bản",
    "service_channel_quick_text_desc": "Tin nhắn", "service_quick_text_title": "Tin nhắn từ %1$s",
    "library_title": "Thư viện", "library_header_title": "Tệp",
    "library_header_body": "Các tệp đang chia sẻ.", "library_header_subtitles": "Có thể thêm phụ đề.",
    "library_info_items": "Mục", "library_info_folders": "Thư mục", "library_info_size": "Kích thước",
    "library_empty_title": "Trống", "library_empty_body": "Thêm một số tệp.", "library_section_folders": "Thư mục",
    "library_section_folders_body": "Các thư mục.", "library_empty_filter_title": "Không có",
    "library_empty_filter_body": "Thử đổi bộ lọc.", "library_section_files": "Tệp", "library_single_file_name": "Tệp",
    "library_selected_files_name": "Đã chọn", "library_save_selected_title": "Lưu",
    "library_save_selected_body": "Để dùng sau.", "library_share_name": "Tên", "library_manage_title": "Quản lý",
    "library_manage_body": "Thêm và xóa.", "library_selection_title": "Lựa chọn mới",
    "library_selection_step_1": "1. Chọn tệp.", "library_selection_step_2": "2. Xác nhận.",
    "library_search_label": "Tìm kiếm...", "library_show_title": "Hiển thị", "library_show_body": "Bộ lọc",
    "library_category_all": "Tất cả", "library_category_videos": "Video", "library_category_photos": "Ảnh",
    "library_category_music": "Nhạc", "library_category_files": "Tệp", "library_add_title": "Thêm",
    "library_add_body": "Từ điện thoại.", "library_add_files": "Tệp", "library_add_whole_folder": "Thư mục",
    "library_add_from_suggestions": "Thư viện ảnh", "library_organize_title": "Sắp xếp",
    "library_organize_body": "Thay đổi thứ tự.", "library_sort_prefix": "Sắp xếp: %1$s",
    "library_clear_all_action": "Xóa tất cả", "plural:library_items_in_view": {"one": "1", "other": "%1$d"},
    "library_clear_all_title": "Xóa tất cả?", "library_clear_all_body": "Danh sách sẽ trống.",
    "library_sort_newest": "Mới nhất", "library_sort_name": "Tên", "library_sort_size": "Kích thước",
    "library_cancel_selection": "Hủy", "library_create_saved_share": "Xong", "library_start_saved_share_selection": "Chọn",
    "library_browser_prep_title": "Bản sao cho Web", "library_browser_prep_body": "Dễ dàng cho trình duyệt.",
    "library_folder_summary": "%1$d | %2$s", "library_unavailable": "Không có", "library_direct_play": "Phát trực tiếp",
    "library_subtitle": "Phụ đề", "library_selected": "Đã chọn", "library_tap_to_select": "Chạm",
    "library_select_this_file": "Có", "library_preparing": "Đang chuẩn bị", "library_preparing_for_browser": "Đang chờ",
    "library_ready": "Sẵn sàng", "library_ready_for_browser": "Web sẵn sàng", "library_try_again": "Thử lại",
    "library_try_browser_prep_again": "Thử lại", "library_prepare": "Chuẩn bị", "library_prepare_for_browser": "Xong",
    "library_type_video": "Video", "library_type_photo": "Ảnh", "library_type_music": "Nhạc", "library_type_file": "Tệp",
    "library_compat_ready_to_play": "Xong | %1$s", "library_compat_not_prepared": "Chưa sẵn sàng", "library_compat_queued": "Đang xếp hàng",
    "library_compat_preparing": "Đang xử lý...", "library_compat_ready": "Xong", "library_compat_unavailable": "Không hỗ trợ",
    "library_compat_message": "%1$s | %2$s", "selection_add_files_title": "Chọn", "selection_add_files_body": "Chia sẻ gì?",
    "selection_add_selected": "Thêm", "selection_pick_files_again": "Thay đổi", "selection_nothing_selected_title": "Trống",
    "selection_nothing_selected_body": "Hãy chọn gì đó.", "selection_add_folder_title": "Thư mục",
    "selection_add_folder_body": "Toàn bộ thư mục.", "selection_add_folder": "Xong",
    "selection_choose_another_folder": "Thay đổi", "selection_no_folder_title": "Lỗi",
    "selection_no_folder_body": "Vui lòng chọn.", "selection_selected_folder": "Thư mục", "selection_selected_item": "1",
    "selection_smart_picks_title": "Ngày", "selection_smart_picks_body": "Đã sắp xếp.",
    "selection_media_access_title": "Cấp quyền", "selection_media_access_body": "Vui lòng cho phép.",
    "selection_grant_access": "Có", "selection_loading_groups_title": "Đang tìm...", "selection_loading_groups_body": "Chờ chút...",
    "selection_no_groups_title": "Không có", "selection_no_groups_body": "Thêm thủ công.", "selection_refresh_groups": "Làm mới",
    "selection_add_group": "Cộng", "home_upload_request_title": "Tệp mới", "home_upload_request_single": "tệp",
    "home_upload_request_files": "%1$d tệp", "home_upload_request_body": "%1$s gửi %2$s:",
    "home_upload_request_total_size": "Kích thước: %1$s", "home_history_content_desc": "Lịch sử",
    "home_settings_content_desc": "Cài đặt", "home_network_required_title": "Mạng",
    "home_network_required_body": "Wi-Fi hoặc Điểm phát sóng.", "message_unable_add_folder": "Lỗi.",
    "message_saved_share_named": "Đã lưu: '%1$s'", "message_unable_save_share": "Thất bại.",
    "message_saved_share_ready": "Sẵn sàng.", "home_all_files_access_title": "Tài liệu?",
    "home_all_files_access_body": "Vui lòng cho phép.", "home_all_files_access_grant": "Có",
    "home_all_files_access_media_only": "Chỉ phương tiện", "home_all_files_nudge_text": "Bất kỳ tệp nào!",
    "message_unable_open_saved_share": "Lỗi.", "message_saved_share_removed": "Đã xóa.",
    "message_something_went_wrong": "Đã xảy ra lỗi.", "message_pin_on": "PIN đã bật.", "message_pin_off": "PIN đã tắt.",
    "message_debug_log_prepare_failed": "Lỗi nhật ký.", "message_debug_log_cleared": "Đã xóa.",
    "message_debug_log_clear_failed": "Lỗi.", "message_file_no_longer_available": "Không tìm thấy.",
    "message_preparing_browser_playback": "Web %1$s.", "nearby_helper_tap_session": "Chạm.",
    "nearby_helper_open_on_other_device": "Mở.", "share_preset_enter_name": "Tên:",
    "share_preset_add_content_first": "Cần nội dung.", "share_preset_select_file_first": "Hãy chọn.",
    "share_preset_files_unavailable": "Thiếu tệp.", "share_preset_collection_unavailable": "Trống.",
    "share_preset_restore_failed": "Lỗi.", "sharing_preflight_failed": "Lỗi: %1$s",
    "sharing_add_content_first": "Hãy thêm gì đó.", "sharing_same_wifi_needed": "Cần chung Wi-Fi.",
    "sharing_connect_before_start": "Kết nối trước.", "sharing_server_start_failed": "Lỗi: %1$s",
    "sharing_blocked_by_live_screen": "Đang chia sẻ màn hình.", "sharing_stopped": "Đã dừng.",
    "sharing_device_android": "Android", "network_helper_wifi_ready": "Wi-Fi ổn.",
    "network_helper_local_ready": "Cục bộ ổn.", "network_helper_wifi_found": "Có IP.",
    "network_helper_hotspot_ready": "Hotspot ổn.", "network_helper_mobile_only": "Chỉ có dữ liệu.",
    "network_helper_local_address_ready": "IP ổn.", "network_helper_connect_both": "Hãy kết nối.",
    "discovery_unavailable_device": "Đã tắt.", "discovery_nsd_unavailable": "Đã tắt.",
    "discovery_searching": "Tìm kiếm...", "discovery_unavailable_now": "Chỉ dùng QR.",
    "discovery_start_failed": "Lỗi (%1$d)", "discovery_ready_to_open": "Xong.",
    "browser_title": "DirectServe", "browser_subtitle": "Tệp", "browser_file_unavailable": "Biến mất.",
    "browser_debug_unavailable": "Đã tắt.", "browser_debug_missing_payload": "Trống.", "browser_pin_mismatch": "Sai PIN.",
    "browser_device_blocked": "Bị chặn.", "browser_enter_pin": "PIN:",
    "browser_optimized_unavailable": "Không phải Web.", "browser_video_part_preparing": "Đang xử lý...",
    "browser_video_part_unavailable": "Trống.", "browser_hls_not_needed": "Không cần.",
    "browser_hls_not_ready": "Chưa xong.", "home_action_add_to_share_title": "Thêm",
    "home_action_add_to_share_subtitle": "Tệp", "home_action_files": "Tệp", "home_action_files_desc": "Có",
    "home_action_folder": "Thư mục", "home_action_folder_desc": "Có", "home_action_library": "Thư viện",
    "home_action_library_desc": "Tìm", "home_button_share_all_media": "Tất cả", "home_button_adding_all": "Đang thêm...",
    "home_media_server_active": "Tất cả bật", "home_btn_stop_media_server": "Dừng", "web_folders_title": "Thư mục",
    "web_folder_items": "%1$d", "web_btn_back_to_folders": "Trở lại", "web_all_media": "Phương tiện",
    "home_nearby_title": "Gần bạn", "home_nearby_subtitle": "Thiết bị.",
    "home_nearby_refresh_status": "Làm mới", "home_network_wifi": "Wi-Fi OK", "home_network_hotspot": "Hotspot OK",
    "home_network_local": "Cục bộ OK", "home_network_none": "Không có", "home_network_ready_desc": "Sẵn sàng.",
    "home_network_none_desc": "Cần kết nối.", "home_nearby_optional_title": "App Tùy chọn",
    "home_nearby_optional_desc": "Web cũng được.", "home_nearby_refresh": "Tìm kiếm",
    "home_nearby_open_title": "Trong App", "home_nearby_open_desc": "Nếu có.",
    "home_nearby_action_open_session": "Đi", "home_nearby_action_open": "Có", "home_nearby_device_available": "Xong",
    "home_nearby_device_pin": "PIN", "web_hero_eyebrow": "DirectServe", "web_hero_title": "Phương tiện của bạn",
    "web_hero_desc1": "Video, ảnh.", "web_hero_desc2": "Tệp.", "web_hero_desc3": "Riêng tư.",
    "web_hero_stat_shared": "Đang chạy", "web_items": "mục", "web_hero_stat_ready": "Xong", "web_hero_stat_access": "Quyền",
    "web_access_pin": "Đã khóa", "web_access_instant": "Mở", "web_access_pin_desc": "Cần PIN",
    "web_access_instant_desc": "Xong", "web_pin_entry_kicker": "PIN", "web_pin_entry_title": "Nhập mã PIN",
    "web_pin_entry_desc": "Trên màn hình.", "web_pin_entry_placeholder": "PIN", "web_btn_videos": "Video",
    "web_btn_download_all_files": "Tải tất cả", "web_cat_videos": "Video", "web_cat_photos": "Ảnh",
    "web_cat_music": "Nhạc", "web_cat_files": "Tệp", "web_recent_title": "Mới", "web_recent_meta": "Xong",
    "web_nav_home": "Nhà", "web_nav_drop_zone": "Kéo thả", "web_nav_logout": "Thoát", "web_nav_media": "Phương tiện",
    "web_nav_files": "Tệp", "web_nav_send": "Gửi", "web_strip_session": "Phiên", "web_strip_device": "Chúng tôi",
    "web_strip_link": "Link", "web_security_pin": "PIN", "web_security_open": "Tắt", "web_status_unknown": "?",
    "home_connected_devices": "Đã kết nối", "home_rename_device": "Tên", "home_rename_device_subtitle": "%1$s • %2$s",
    "home_rename_custom_name": "Mới", "home_rename_save": "Xong", "home_rename_cancel": "Hủy", "home_quick_filters": "Lọc",
    "home_quick_filter_today": "Hôm nay", "home_quick_filter_today_desc": "24h", "home_quick_filter_week": "Tuần",
    "home_quick_filter_week_desc": "7 ngày", "home_quick_filter_month": "Tháng", "home_quick_filter_month_desc": "30 ngày",
    "home_quick_filter_custom": "Lúc", "home_quick_filter_custom_desc": "Chọn", "home_date_range_title": "Ngày",
    "home_date_range_from": "Từ", "home_date_range_start": "Bắt đầu", "home_date_range_to": "Đến",
    "home_date_range_end": "Kết thúc", "home_date_range_tip": "Tốt.", "home_date_range_apply": "OK",
    "home_date_range_cancel": "Hủy", "home_recent_shares": "Cũ", "home_section_library": "Tệp",
    "home_section_live_tools": "Công cụ", "home_section_network_tv": "TV", "home_section_sharing": "Hành động",
    "home_section_live_features": "Thêm", "home_feature_library": "Thư viện", "home_feature_library_desc": "Cài.",
    "home_feature_transfers": "Truyền", "home_feature_transfers_desc": "Tải.", "home_feature_share_files": "Chia sẻ",
    "home_feature_share_files_desc": "Tất cả.", "home_feature_receive_files": "Nhận",
    "home_feature_receive_files_desc": "Có.", "home_feature_play_media": "Phát",
    "home_feature_play_media_desc": "Web.", "home_feature_play_media_live": "Có.", "home_feature_dlna": "DLNA",
    "home_feature_dlna_desc": "TV.", "home_feature_dlna_enabled": "Bật.", "home_feature_live_screen": "Màn hình",
    "home_feature_live_screen_desc": "Chiếu.", "home_feature_quick_text": "Văn bản", "home_feature_quick_text_desc": "Có.",
    "home_saved_shares": "Bộ sưu tập", "home_saved_shares_save_now": "Lưu", "home_saved_shares_open": "Mở",
    "home_saved_shares_delete": "Xóa", "plural:home_saved_shares_items_count": {"one": "1", "other": "%1$d"},
    "library_date_group_label": "%1$s", "web_upload_title": "Tải lên", "web_upload_subtitle": "Đến điện thoại.",
    "web_upload_prompt_title": "Kéo tệp vào", "web_upload_prompt_desktop": "Kéo.",
    "web_upload_prompt_mobile": "Chạm.", "web_upload_button_browse": "Tìm",
    "web_upload_button_photos": "Ảnh", "web_upload_button_any_file": "Tệp", "web_upload_target_kicker": "Điện thoại",
    "web_upload_target_status": "Xong.", "web_upload_how_kicker": "Có", "web_upload_how_title": "Quyền",
    "web_upload_how_body": "Cần đồng ý.", "web_action_download": "Tải", "web_action_view": "Xem",
    "web_photo_view": "Xem", "web_btn_download_all": "Tải tất cả", "web_btn_download_selected": "Tải",
    "web_btn_download_original": "Gốc", "web_btn_fullscreen": "Toàn màn hình", "web_error_streaming_codec": "Không chạy. Tải.",
    "web_error_downloads_disabled": "Đã tắt.", "web_error_video_decode": "Lỗi. Tải.",
    "web_error_video_start": "Lỗi. Tải.", "web_error_video_start_no_dl": "Đang sửa...",
    "web_error_load_failed": "Lỗi.", "web_btn_select_files": "Chọn", "web_status_selection_on": "Bật",
    "web_btn_select_all": "Tất cả", "web_btn_clear_selection": "Bỏ", "web_player_slow_start_hint": "Đợi xíu...",
    "web_selection_count": "%1$d", "web_library_desc_download": "Xem hoặc lấy.", "web_library_desc_browse": "Tất cả ở đây.",
    "web_btn_load_more": "Thêm", "web_btn_show_all": "Tất cả", "web_btn_showing_all": "Đang lấy...",
    "web_show_all_confirm": "Tất cả %1$d?", "web_library_showing_count": "%1$d / %2$d",
    "web_search_placeholder": "Tên...", "web_library_empty": "Trống.", "web_upload_selection_empty": "Không có.",
    "web_upload_selection_single": "%1$s", "web_upload_selection_multiple": "%1$d", "web_upload_button_send": "Gửi",
    "common_quick_filters": "Lọc", "common_edit_nickname": "Tên", "home_quick_filters_desc": "Ngày.",
    "home_date_range_body": "Ngày.", "web_upload_requesting": "Đang yêu cầu...", "web_upload_waiting": "Đang chờ...",
    "web_upload_denied": "Bị từ chối.", "web_upload_failed_status": "Lỗi (%1$d)",
    "web_upload_network_error": "Mạng.", "web_upload_cancelled": "Đã hủy.", "web_upload_success_title": "Xong",
    "web_upload_success_detail_single": "Hoàn tất.", "web_upload_success_detail_multiple": "Hoàn tất.",
    "web_upload_failed_title": "Lỗi", "web_upload_failed_detail": "Lỗi.", "web_player_error_open": "Thất bại",
    "web_player_opening": "Đang mở...", "web_player_ready": "Sẵn sàng", "web_player_analyzing": "Kiểm tra...",
    "web_player_finalizing": "Hoàn thành...", "web_player_stalled": "Tạm dừng", "web_player_starting": "Bắt đầu...",
    "web_player_wait_desc": "Chờ chút...", "web_player_ready_desc": "Chơi.", "web_player_analyzing_desc": "Đang tìm...",
    "web_player_finalizing_desc": "Sắp xong...", "web_player_stalled_desc": "Hơi nặng.",
    "web_player_needs_prepare": "Cần Web", "web_player_needs_prepare_desc": "Trên đt.",
    "web_player_starting_desc": "Đang bắt đầu...", "web_player_try_again": "Thử lại", "web_player_status_opening": "Mở",
    "web_player_status_ready": "OK", "web_player_status_analyzing": "Kiểm tra", "web_player_status_finalizing": "Xong",
    "web_player_status_stalled": "Kẹt", "web_player_status_playing": "Đang phát", "web_player_progress_preparing": "Đợi",
    "web_player_progress_converting": "Ghi", "web_player_status_failed": "Thất bại", "web_player_status_stopped": "Dừng",
    "web_prepare_video": "Web", "web_progress_percent": "%1$d%%", "web_media_quick_title": "Phương tiện",
    "web_media_quick_subtitle": "Vào.", "web_media_open_category": "%1$s", "web_media_empty": "Trống.",
    "web_send_files_to_device": "Gửi", "web_upload_in_progress": "Đang chạy...", "web_upload_complete": "Xong",
    "web_upload_failed": "Lỗi", "web_cancel": "Hủy", "web_upload_preparing_transfer": "Đang chuẩn bị...",
    "web_upload_connecting": "Đang kết nối...", "web_btn_back": "Trở lại", "web_status_subtitles_available": "Phụ đề",
    "web_now_playing": "Đang phát", "common_resume": "Tiếp", "web_status_init_progress": "0%",
    "common_play": "Phát", "common_pause": "Tạm dừng", "common_unit_b": "B", "common_unit_kb": "KB",
    "common_unit_mb": "MB", "common_unit_gb": "GB", "common_unit_tb": "TB", "common_unit_s": "s",
    "common_unit_m": "p", "common_unit_h": "g", "common_byte_format_decimal": "%1$.1f %2$s",
    "common_byte_format_integer": "%1$d %2$s", "common_duration_format_m_s": "%1$dp %2$ds",
    "common_duration_format_h_m": "%1$dg %2$dp", "common_duration_format_s": "%1$ds",
    "common_duration_timestamp_m_s": "%1$d:%2$02d", "common_duration_timestamp_h_m_s": "%1$d:%2$02d:%3$02d",
    "service_file_index_pattern": "%1$s (%2$d/%3$d)", "service_upload_progress_subtext_pattern": "%1$s / %2$s",
    "help_section_media_server": "Máy chủ", "help_line_media_server_1": "Hub.",
    "help_line_media_server_2": "Gọn gàng.", "help_section_folders_nav": "Thư mục",
    "help_line_folders_1": "Như cũ.", "help_line_folders_2": "Sạch.", "help_section_dlna_tv": "TV",
    "help_line_dlna_1": "Thông minh.", "help_line_dlna_2": "DirectServe.", "help_line_dlna_3": "Mạng.",
    "help_line_dlna_4": "VLC OK.", "help_section_search_sticky": "Tìm", "help_line_search_1": "Nhanh.",
    "help_line_search_2": "Trên.", "settings_dlna": "DLNA TV", "settings_dlna_desc": "TV/VLC.",
    "dlna_server_name": "DirectServe", "dlna_server_name_template": "DirectServe (%1$s)",
    "web_action_download_zip": "ZIP", "web_btn_download_all_zip": "Tất cả ZIP",
    "web_btn_download_selected_zip": "Tải ZIP", "web_error_no_items_selected": "Trống.",
    "web_download_started_hint": "Đang đóng gói...", "playback_mode_direct": "Direct Play",
    "playback_mode_repackaging": "Hộp", "playback_mode_transcoding": "Nặng",
    "playback_mode_analyzing": "Kiểm tra", "compatibility_message_cached_ready": "Đã sẵn sàng.",
    "compatibility_message_stopped": "Dừng.", "compatibility_message_validation_failed": "Lỗi: %1$s",
    "compatibility_message_adjusted": "Xong.", "compatibility_message_optimizing": "Đang chuẩn bị...",
    "compatibility_message_almost_ready": "Sắp...", "compatibility_message_ready": "Xong.",
    "compatibility_message_analyzing": "Đang xem...", "compatibility_message_finalizing_optimized": "Kết thúc...",
    "compatibility_message_finalizing_compatible": "Kết thúc...", "compatibility_message_optimizing_web": "Web...",
    "compatibility_message_repackaging_web": "Đóng gói...", "compatibility_message_converting_web": "Chuyển...",
}

# CHINESE SIMPLIFIED (zh-rCN)
zh_cn_data = {
    "common_back": "返回", "common_cancel": "取消", "common_save": "保存", "common_delete": "删除",
    "common_open": "打开", "common_refresh": "刷新", "common_continue": "继续", "common_accept": "接受",
    "common_decline": "拒绝", "common_dismiss": "关闭", "common_remove": "移除", "common_search": "搜索",
    "common_separator_pipe": " | ", "common_separator_dot": " • ", "onboarding_skip": "跳过",
    "onboarding_title": "DirectServe",
    "onboarding_subtitle": "将您的手机变成电视和电脑的本地控制中心。",
    "onboarding_page_1_title": "在任何屏幕上观看",
    "onboarding_page_1_description": "无需云端，在大屏幕上播放视频和照片。",
    "onboarding_page_2_title": "适用于所有设备",
    "onboarding_page_2_description": "支持电视、电脑、手机，只要有浏览器即可。",
    "onboarding_page_3_title": "从浏览器访问",
    "onboarding_page_3_description": "无需安装应用，使用链接或扫码即可。",
    "onboarding_page_4_title": "双向分享",
    "onboarding_page_4_description": "轻松发送和接收文件。",
    "onboarding_page_5_title": "无需互联网",
    "onboarding_page_5_description": "通过 Wi-Fi 或热点运行。",
    "onboarding_page_6_title": "隐私保护",
    "onboarding_page_6_description": "文件始终留在您的手机中。",
    "onboarding_page_counter": "%1$d / %2$d", "onboarding_next": "下一步", "onboarding_get_started": "开始",
    "settings_title": "设置", "settings_subtitle": "自定义 DirectServe。",
    "settings_group_general": "通用", "settings_group_notifications": "通知", "settings_group_privacy": "隐私",
    "settings_group_browser": "浏览器", "settings_group_advanced": "高级", "settings_group_network": "网络",
    "settings_group_help": "帮助", "settings_group_debug": "调试", "settings_language": "语言",
    "settings_theme": "主题", "settings_theme_subtitle": "更改外观", "settings_theme_system": "系统",
    "settings_theme_dark": "深色", "settings_theme_light": "浅色", "settings_keep_screen_awake": "保持屏幕常亮",
    "settings_keep_screen_awake_desc": "分享时防止屏幕关闭。",
    "settings_vibrate_on_connect": "连接时震动", "settings_vibrate_on_connect_desc": "有人加入时震动提示。",
    "settings_show_speed": "显示速度", "settings_show_speed_desc": "实时传输速度。",
    "settings_show_recent_shares": "显示历史记录", "settings_show_recent_shares_desc": "本地保存分享记录。",
    "settings_auto_stop": "自动停止", "settings_auto_stop_never": "从不", "settings_auto_stop_15m": "15分钟",
    "settings_auto_stop_30m": "30分钟", "settings_auto_stop_1h": "1小时", "settings_connection_alerts": "连接提醒",
    "settings_connection_alerts_desc": "设备连接时提醒。",
    "settings_download_alerts": "下载提醒", "settings_download_alerts_desc": "有人下载文件时提醒。",
    "settings_upload_requests": "上传请求", "settings_upload_requests_desc": "接收文件前询问。",
    "settings_quick_text_enabled": "快捷文本", "settings_quick_text_enabled_desc": "分享文本消息。",
    "settings_quick_text_alerts": "消息提醒", "settings_quick_text_alerts_desc": "收到消息时提醒。",
    "settings_use_pin": "使用 PIN 码", "settings_use_pin_desc": "需要密码才能访问。",
    "settings_new_pin_each_time": "每次使用新 PIN", "settings_new_pin_each_time_desc": "增强安全性。",
    "settings_pin_label": "PIN", "settings_pin_placeholder": "4-6 位数字", "settings_approve_file_uploads": "批准文件上传",
    "settings_approve_file_uploads_desc": "上传前需要同意。",
    "settings_approve_per_device": "按设备批准", "settings_approve_per_device_desc": "每台设备只需批准一次。",
    "settings_received_files_location": "接收文件夹", "settings_received_files_location_value": "下载",
    "settings_show_thumbnails": "显示缩略图", "settings_show_thumbnails_desc": "媒体预览。",
    "settings_large_tv_layout": "电视布局", "settings_large_tv_layout_desc": "更大的按钮。",
    "settings_highlight_downloads": "突出显示下载", "settings_highlight_downloads_desc": "使按钮更明显。",
    "settings_sign_out_on_stop": "停止时退出", "settings_sign_out_on_stop_desc": "断开访问。",
    "settings_clear_temporary_files": "清除临时文件", "settings_clear_temporary_files_desc": "删除优化后的视频。",
    "settings_prevent_downloads": "阻止下载", "settings_prevent_downloads_desc": "仅允许观看。",
    "settings_auto_optimize_library": "后台优化", "settings_auto_optimize_library_desc": "会消耗电池。",
    "settings_sharing_port": "端口", "settings_sharing_port_placeholder": "43183",
    "settings_sharing_port_help": "不确定请勿修改。",
    "settings_wifi_settings": "Wi-Fi 设置", "settings_wifi_settings_desc": "需要处于同一网络。",
    "settings_hotspot_settings": "热点设置", "settings_hotspot_settings_desc": "创建本地网络。",
    "settings_view_onboarding": "查看教程", "settings_view_onboarding_desc": "重新显示引导。",
    "settings_privacy_policy": "隐私政策", "settings_privacy_policy_desc": "本地隐私。",
    "settings_privacy_promise": "承诺", "settings_privacy_promise_desc": "文件永远不会上传到云端。",
    "settings_how_it_works": "工作原理", "settings_how_it_works_desc": "帮助。",
    "settings_app_version": "应用版本", "settings_recent_shares_count": "收藏夹: %1$d",
    "settings_share_debug_log": "发送日志", "settings_share_debug_log_desc": "报告问题。",
    "settings_clear_debug_log": "清除日志",
    "help_title": "帮助", "help_about_title": "关于 DirectServe",
    "help_about_1": "在浏览器中打开文件。",
    "help_about_2": "无需安装其他应用。",
    "help_about_3": "无需互联网或云端。",
    "help_section_what_you_can_do": "您可以做什么", "help_section_video_playback": "视频播放",
    "help_section_browser_preparation": "网页优化", "help_section_receiving_files": "接收文件",
    "help_section_drop_zone": "发送文件", "help_section_multiple_devices": "多台设备",
    "help_section_privacy_controls": "隐私", "help_section_good_to_know": "须知",
    "help_section_quick_flow": "快速开始", "help_line_share_files": "分享视频和照片。",
    "help_line_open_session": "在浏览器中打开。",
    "help_line_same_network": "必须在同一个 Wi-Fi 下。",
    "help_line_multiple_browse": "大家可以同时查看。",
    "help_line_video_direct": "视频直接播放。",
    "help_line_video_temporary": "有时需要转换格式。",
    "help_line_video_original": "原始文件保持不变。",
    "help_line_prep_optional": "优化是可选的。",
    "help_line_prep_control": "随时可以停止。",
    "help_line_prep_batch": "手机可能会发热。",
    "help_line_receive_upload": "其他人可以向您发送文件。",
    "help_line_receive_approval": "您必须先批准。",
    "help_line_receive_history": "保存在下载文件夹中。",
    "help_line_drop_zone": "拖拽文件。",
    "help_line_drop_zone_pick": "或手动选择。", "help_line_drop_zone_local": "100% 本地。",
    "help_line_multi_connect": "支持多设备同时连接。",
    "help_line_multi_live": "设备名称会显示在屏幕上。",
    "help_line_multi_controls": "必要时可以阻止设备。",
    "help_line_privacy_local": "不需要账号。",
    "help_line_privacy_session": "只分享您选择的内容。",
    "help_line_privacy_controls": "完全在您的控制之下。",
    "help_line_wifi_hotspot": "Wi-Fi 或热点均可。",
    "help_line_public_wifi": "公共网络可能会阻止连接。",
    "help_line_downloads_disabled": "可以关闭下载功能。",
    "help_line_flow_1": "1. 添加文件。", "help_line_flow_2": "2. 开始会话。",
    "help_line_flow_3": "3. 扫描二维码。", "help_line_flow_4": "4. 观看。",
    "home_brand_title": "DirectServe", "home_brand_subtitle": "私密分享",
    "home_chip_local_session": "本地会话", "home_chip_sharing": "正在分享", "home_chip_ready": "准备就绪",
    "home_chip_setup_needed": "需要网络", "home_live_banner": "直播会话",
    "home_title_live": "分享已开启", "home_title_start": "当前分享",
    "home_body_live": "其他设备可以连接。", "home_body_start": "添加要分享的文件。",
    "home_body_start_secondary": "使用您的媒体库。",
    "home_button_start_session": "开始", "home_button_open_session": "打开",
    "home_button_starting": "正在启动...", "home_button_add_media": "添加", "home_button_add_more": "继续添加",
    "home_summary_current_share": "总计", "home_summary_media": "媒体", "home_summary_files": "文件",
    "home_content_filter_title": "正在分享的内容", "home_content_filter_subtitle": "在浏览器中可见",
    "home_content_filter_videos": "视频", "home_content_filter_music": "音乐", "home_content_filter_photos": "照片",
    "home_content_filter_files": "文件", "home_no_network": "没有 Wi-Fi",
    "network_setup_title": "需要网络", "network_setup_body": "必须连接到同一个网络。",
    "network_setup_trouble_title": "遇到问题？",
    "network_setup_trouble_body": "使用您自己的热点。",
    "network_setup_open_wifi": "Wi-Fi", "network_setup_switch_hotspot": "热点",
    "network_setup_retry": "重试", "network_setup_footer": "速度更快，更稳定。",
    "session_title": "直播会话", "session_stop_sharing": "停止", "session_live_now": "直播",
    "session_live_now_subtitle": "您在网络上可见。", "session_share_live": "会话活跃",
    "session_share_preparing": "准备中...", "session_share_live_body": "扫描二维码加入。",
    "session_qr_title": "扫描", "session_qr_body": "适用于任何设备。",
    "session_qr_preparing": "正在生成", "session_browser_prep_title": "网页优化",
    "session_browser_prep_active": "%1$d%% • 已完成 %2$d / %3$d", "session_browser_prep_queued": "排队中 %1$d",
    "session_browser_prep_ready": "%1$d 已完成", "session_browser_prep_message_active": "处理中...",
    "session_browser_prep_message_queued": "等待中", "session_browser_prep_message_ready": "准备就绪",
    "session_browser_prep_message_manual": "需要操作",
    "session_browser_prep_manual_note": "在浏览器中可能无法正常播放。",
    "session_prepare_browser_files": "准备", "session_stop_browser_files": "停止",
    "session_library_refresh_title": "刷新",
    "session_library_refresh_pending": "%1$d 个文件等待添加。",
    "session_library_refresh_up_to_date": "已是最新。", "session_refresh_library": "立即刷新",
    "message_live_library_refreshed_updates": "已添加 %1$d 个。",
    "message_live_library_refreshed_current": "已经是最新状态。",
    "message_browser_playback_queued_all": "已加入队列。",
    "message_browser_playback_already_ready": "已经准备就绪。", "message_browser_playback_stopped": "已停止。",
    "library_importing_title": "导入中", "library_importing_body": "请稍候...",
    "session_waiting_local_link": "网络...", "session_qr_content_desc": "二维码",
    "session_share_link": "链接", "session_share_link_body": "在同一个网络下打开。", "session_network": "网络",
    "session_access_pin": "访问 PIN", "session_pin_off": "关闭", "session_new_pin": "新建",
    "session_turn_pin_on": "开启 PIN", "session_turn_pin_off": "关闭 PIN", "session_nearby_name": "名称",
    "session_what_happens_now": "状态", "session_waiting_ready": "等待中...",
    "session_waiting_first_device": "等待设备加入...", "session_devices_connected_now": "已连接 %1$d 台。",
    "session_friendly_local_name": "本地名称", "session_copy_link": "复制", "session_share": "分享",
    "session_metric_devices": "设备", "session_metric_sent": "已发送", "session_metric_speed": "速度",
    "session_metric_elapsed": "耗时", "session_metric_remaining": "剩余", "session_connected_waiting": "等待中...",
    "session_connected_title": "已连接", "session_connected_waiting_body": "将显示在这里。",
    "session_connected_count": "%1$d 台活跃。", "session_disconnect_all": "断开所有连接",
    "session_no_devices": "暂无设备。", "session_block_device": "阻止",
    "session_block": "阻止", "session_blocked_title": "已阻止", "session_unblock_device": "解除阻止",
    "session_unblock": "解除", "session_state_sharing_now": "活跃", "session_state_preparing": "准备中",
    "session_state_network_needed": "需要网络", "session_network_hotspot": "热点", "session_network_wifi": "Wi-Fi",
    "session_network_local": "本地", "session_network_offline": "离线", "history_title": "历史记录",
    "history_tab_all": "全部", "history_tab_received": "已接收", "history_empty_all": "空。",
    "history_empty_received": "空。", "history_sent": "发送", "history_received": "接收",
    "history_open": "打开", "history_delete": "删除", "history_delete_desc": "从记录中清除",
    "history_date_time_format": "%1$s %2$s", "splash_title": "DirectServe", "splash_subtitle": "私密本地分享",
    "privacy_policy_title": "隐私", "privacy_policy_intro": "您的文件安全地留在手机中。",
    "privacy_policy_line_1": "无需注册。", "privacy_policy_line_2": "没有云端。",
    "privacy_policy_line_3": "仅限本地网络。", "privacy_policy_line_4": "您掌控一切。",
    "main_service_background_protection_failed": "后台启动失败。",
    "main_notification_permission_warning": "需要通知权限。",
    "main_batch_media_access_needed": "需要媒体权限。", "main_debug_log_subject": "调试日志",
    "main_debug_log_body": "已附上。", "main_debug_log_chooser": "发送方式...",
    "main_no_email_app": "没有邮件应用。", "main_no_browser_app": "没有浏览器。",
    "main_no_file_app": "没有文件应用。", "main_link_copied": "已复制。",
    "main_link_preparing": "请稍候...", "main_share_link_chooser": "分享...",
    "main_link_not_ready": "尚未准备好。", "main_not_sharing": "已关闭", "service_start_failed": "启动失败。",
    "service_auto_stop_message": "已自动停止。", "service_upload_request_title": "收到文件",
    "service_upload_request_text": "%1$s (%3$s -> %2$s)", "service_upload_progress_title": "正在接收 %1$s",
    "service_upload_progress_text": "%1$d%% (%2$s)", "service_upload_progress_text_unknown": "来自 %1$s",
    "service_upload_success_title": "已保存: %1$s", "service_upload_success_text": "来自 %1$s",
    "service_upload_success_subtext": "保存在下载文件夹", "service_file_count": "%1$d 个文件",
    "plural:service_new_devices_connected": {"one": "设备已连接", "other": "%1$d 台设备已连接"},
    "plural:service_devices_joined": {"one": "%1$s 已加入。", "other": "%1$s 已加入 (%2$d)。"},
    "service_waiting_for_devices": "等待中...", "plural:service_devices_connected": {"one": "1 台设备", "other": "%1$d 台设备"},
    "service_preparing_browser_access": "正在准备网页版...", "service_channel_requests_name": "传输",
    "service_channel_requests_desc": "下载", "service_channel_connections_name": "连接",
    "service_channel_connections_desc": "设备", "service_channel_quick_text_name": "文本",
    "service_channel_quick_text_desc": "消息", "service_quick_text_title": "来自 %1$s 的消息",
    "library_title": "媒体库", "library_header_title": "文件",
    "library_header_body": "正在分享的内容。", "library_header_subtitles": "您可以添加字幕。",
    "library_info_items": "项目", "library_info_folders": "文件夹", "library_info_size": "大小",
    "library_empty_title": "空", "library_empty_body": "添加一些文件。", "library_section_folders": "文件夹",
    "library_section_folders_body": "分享的文件夹。", "library_empty_filter_title": "无",
    "library_empty_filter_body": "更改筛选条件。", "library_section_files": "文件", "library_single_file_name": "文件",
    "library_selected_files_name": "已选择", "library_save_selected_title": "保存",
    "library_save_selected_body": "供以后使用。", "library_share_name": "名称", "library_manage_title": "管理",
    "library_manage_body": "整理文件。", "library_selection_title": "新的选择",
    "library_selection_step_1": "1. 选择。", "library_selection_step_2": "2. 完成。",
    "library_search_label": "搜索...", "library_show_title": "显示", "library_show_body": "筛选",
    "library_category_all": "全部", "library_category_videos": "视频", "library_category_photos": "照片",
    "library_category_music": "音乐", "library_category_files": "文件", "library_add_title": "添加",
    "library_add_body": "从手机中。", "library_add_files": "文件", "library_add_whole_folder": "文件夹",
    "library_add_from_suggestions": "相册", "library_organize_title": "排序",
    "library_organize_body": "更改顺序。", "library_sort_prefix": "排序方式: %1$s",
    "library_clear_all_action": "全部清除", "plural:library_items_in_view": {"one": "1", "other": "%1$d"},
    "library_clear_all_title": "清除全部？", "library_clear_all_body": "列表将被清空。",
    "library_sort_newest": "最新", "library_sort_name": "名称", "library_sort_size": "大小",
    "library_cancel_selection": "取消", "library_create_saved_share": "完成", "library_start_saved_share_selection": "选择",
    "library_browser_prep_title": "网页副本", "library_browser_prep_body": "适合浏览器的轻量文件。",
    "library_folder_summary": "%1$d | %2$s", "library_unavailable": "不可用", "library_direct_play": "直接播放",
    "library_subtitle": "字幕", "library_selected": "已选择", "library_tap_to_select": "点击",
    "library_select_this_file": "是", "library_preparing": "准备中", "library_preparing_for_browser": "排队中",
    "library_ready": "准备就绪", "library_ready_for_browser": "网页版就绪", "library_try_again": "重试",
    "library_try_browser_prep_again": "重试", "library_prepare": "准备", "library_prepare_for_browser": "完成",
    "library_type_video": "视频", "library_type_photo": "照片", "library_type_music": "音乐", "library_type_file": "文件",
    "library_compat_ready_to_play": "完成 | %1$s", "library_compat_not_prepared": "未准备好", "library_compat_queued": "排队中",
    "library_compat_preparing": "处理中...", "library_compat_ready": "完成", "library_compat_unavailable": "不支持",
    "library_compat_message": "%1$s | %2$s", "selection_add_files_title": "选择", "selection_add_files_body": "分享什么？",
    "selection_add_selected": "添加", "selection_pick_files_again": "更改", "selection_nothing_selected_title": "空",
    "selection_nothing_selected_body": "请选择内容。", "selection_add_folder_title": "文件夹",
    "selection_add_folder_body": "选择文件夹。", "selection_add_folder": "完成",
    "selection_choose_another_folder": "更改", "selection_no_folder_title": "错误",
    "selection_no_folder_body": "请选择文件夹。", "selection_selected_folder": "文件夹", "selection_selected_item": "1",
    "selection_smart_picks_title": "日期", "selection_smart_picks_body": "已整理。",
    "selection_media_access_title": "权限", "selection_media_access_body": "请允许访问。",
    "selection_grant_access": "是", "selection_loading_groups_title": "搜索中...", "selection_loading_groups_body": "设置中...",
    "selection_no_groups_title": "无", "selection_no_groups_body": "手动添加。", "selection_refresh_groups": "刷新",
    "selection_add_group": "添加", "home_upload_request_title": "新文件", "home_upload_request_single": "文件",
    "home_upload_request_files": "%1$d 个文件", "home_upload_request_body": "%1$s 发送了 %2$s：",
    "home_upload_request_total_size": "大小: %1$s", "home_history_content_desc": "历史记录",
    "home_settings_content_desc": "设置", "home_network_required_title": "网络",
    "home_network_required_body": "Wi-Fi 或热点。", "message_unable_add_folder": "错误。",
    "message_saved_share_named": "已保存：'%1$s'", "message_unable_save_share": "失败。",
    "message_saved_share_ready": "准备就绪。", "home_all_files_access_title": "文档？",
    "home_all_files_access_body": "请允许。", "home_all_files_access_grant": "是",
    "home_all_files_access_media_only": "仅限媒体", "home_all_files_nudge_text": "任何文件！",
    "message_unable_open_saved_share": "错误。", "message_saved_share_removed": "已删除。",
    "message_something_went_wrong": "出现问题。", "message_pin_on": "PIN 已开启。", "message_pin_off": "PIN 已关闭。",
    "message_debug_log_prepare_failed": "日志错误。", "message_debug_log_cleared": "已清除。",
    "message_debug_log_clear_failed": "错误。", "message_file_no_longer_available": "找不到了。",
    "message_preparing_browser_playback": "网页版 %1$s。", "nearby_helper_tap_session": "点击。",
    "nearby_helper_open_on_other_device": "打开。", "share_preset_enter_name": "名称：",
    "share_preset_add_content_first": "请添加内容。", "share_preset_select_file_first": "请选择。",
    "share_preset_files_unavailable": "文件丢失。", "share_preset_collection_unavailable": "空。",
    "share_preset_restore_failed": "错误。", "sharing_preflight_failed": "错误: %1$s",
    "sharing_add_content_first": "添加一些文件。", "sharing_same_wifi_needed": "需要同一个 Wi-Fi。",
    "sharing_connect_before_start": "先连接网络。", "sharing_server_start_failed": "错误: %1$s",
    "sharing_blocked_by_live_screen": "关闭屏幕分享。", "sharing_stopped": "已停止。",
    "sharing_device_android": "Android", "network_helper_wifi_ready": "Wi-Fi 正常。",
    "network_helper_local_ready": "本地网络正常。", "network_helper_wifi_found": "找到 IP。",
    "network_helper_hotspot_ready": "热点正常。", "network_helper_mobile_only": "仅使用移动数据。",
    "network_helper_local_address_ready": "IP 正常。", "network_helper_connect_both": "请连接设备。",
    "discovery_unavailable_device": "已关闭。", "discovery_nsd_unavailable": "已关闭。",
    "discovery_searching": "搜索中...", "discovery_unavailable_now": "只能使用二维码。",
    "discovery_start_failed": "错误 (%1$d)", "discovery_ready_to_open": "完成。",
    "browser_title": "DirectServe", "browser_subtitle": "文件", "browser_file_unavailable": "消失了。",
    "browser_debug_unavailable": "已关闭。", "browser_debug_missing_payload": "空。", "browser_pin_mismatch": "PIN 码错误。",
    "browser_device_blocked": "已阻止。", "browser_enter_pin": "PIN 码：",
    "browser_optimized_unavailable": "不支持网页。", "browser_video_part_preparing": "制作中...",
    "browser_video_part_unavailable": "空。", "browser_hls_not_needed": "不需要。",
    "browser_hls_not_ready": "未准备好。", "home_action_add_to_share_title": "添加",
    "home_action_add_to_share_subtitle": "文件", "home_action_files": "文件", "home_action_files_desc": "是",
    "home_action_folder": "文件夹", "home_action_folder_desc": "是", "home_action_library": "媒体库",
    "home_action_library_desc": "查找", "home_button_share_all_media": "全部", "home_button_adding_all": "添加中...",
    "home_media_server_active": "全部开启", "home_btn_stop_media_server": "停止", "web_folders_title": "文件夹",
    "web_folder_items": "%1$d", "web_btn_back_to_folders": "返回", "web_all_media": "媒体",
    "home_nearby_title": "附近", "home_nearby_subtitle": "设备。",
    "home_nearby_refresh_status": "刷新", "home_network_wifi": "Wi-Fi 正常", "home_network_hotspot": "热点正常",
    "home_network_local": "本地正常", "home_network_none": "无", "home_network_ready_desc": "准备就绪。",
    "home_network_none_desc": "需要连接。", "home_nearby_optional_title": "App 是可选的",
    "home_nearby_optional_desc": "网页也可以。", "home_nearby_refresh": "搜索",
    "home_nearby_open_title": "在 App 中", "home_nearby_open_desc": "如果有的话。",
    "home_nearby_action_open_session": "走吧", "home_nearby_action_open": "是", "home_nearby_device_available": "完成",
    "home_nearby_device_pin": "PIN", "web_hero_eyebrow": "DirectServe", "web_hero_title": "您的媒体",
    "web_hero_desc1": "视频，照片。", "web_hero_desc2": "文件。", "web_hero_desc3": "私密。",
    "web_hero_stat_shared": "运行中", "web_items": "项", "web_hero_stat_ready": "完成", "web_hero_stat_access": "权限",
    "web_access_pin": "已锁定", "web_access_instant": "公开", "web_access_pin_desc": "需要 PIN",
    "web_access_instant_desc": "完成", "web_pin_entry_kicker": "PIN", "web_pin_entry_title": "输入 PIN 码",
    "web_pin_entry_desc": "在屏幕上。", "web_pin_entry_placeholder": "PIN", "web_btn_videos": "视频",
    "web_btn_download_all_files": "下载全部", "web_cat_videos": "视频", "web_cat_photos": "照片",
    "web_cat_music": "音乐", "web_cat_files": "文件", "web_recent_title": "新增", "web_recent_meta": "完成",
    "web_nav_home": "主页", "web_nav_drop_zone": "拖拽区", "web_nav_logout": "退出", "web_nav_media": "媒体",
    "web_nav_files": "文件", "web_nav_send": "发送", "web_strip_session": "会话", "web_strip_device": "我们",
    "web_strip_link": "链接", "web_security_pin": "PIN", "web_security_open": "关闭", "web_status_unknown": "?",
    "home_connected_devices": "已连接", "home_rename_device": "名称", "home_rename_device_subtitle": "%1$s • %2$s",
    "home_rename_custom_name": "新名称", "home_rename_save": "完成", "home_rename_cancel": "取消", "home_quick_filters": "筛选",
    "home_quick_filter_today": "今天", "home_quick_filter_today_desc": "24小时", "home_quick_filter_week": "本周",
    "home_quick_filter_week_desc": "7天", "home_quick_filter_month": "本月", "home_quick_filter_month_desc": "30天",
    "home_quick_filter_custom": "时间", "home_quick_filter_custom_desc": "选择", "home_date_range_title": "天",
    "home_date_range_from": "从", "home_date_range_start": "开始", "home_date_range_to": "到",
    "home_date_range_end": "结束", "home_date_range_tip": "好。", "home_date_range_apply": "确定",
    "home_date_range_cancel": "取消", "home_recent_shares": "较早", "home_section_library": "文件",
    "home_section_live_tools": "工具", "home_section_network_tv": "电视", "home_section_sharing": "操作",
    "home_section_live_features": "附加功能", "home_feature_library": "媒体库", "home_feature_library_desc": "管理。",
    "home_feature_transfers": "传输", "home_feature_transfers_desc": "下载。", "home_feature_share_files": "分享",
    "home_feature_share_files_desc": "全部。", "home_feature_receive_files": "接收",
    "home_feature_receive_files_desc": "是。", "home_feature_play_media": "播放",
    "home_feature_play_media_desc": "网页。", "home_feature_play_media_live": "是。", "home_feature_dlna": "DLNA",
    "home_feature_dlna_desc": "电视。", "home_feature_dlna_enabled": "开启。", "home_feature_live_screen": "屏幕",
    "home_feature_live_screen_desc": "镜像。", "home_feature_quick_text": "文本", "home_feature_quick_text_desc": "是。",
    "home_saved_shares": "收藏夹", "home_saved_shares_save_now": "保存", "home_saved_shares_open": "打开",
    "home_saved_shares_delete": "删除", "plural:home_saved_shares_items_count": {"one": "1", "other": "%1$d"},
    "library_date_group_label": "%1$s", "web_upload_title": "上传", "web_upload_subtitle": "到手机。",
    "web_upload_prompt_title": "放入文件", "web_upload_prompt_desktop": "拖放。",
    "web_upload_prompt_mobile": "点击。", "web_upload_button_browse": "浏览",
    "web_upload_button_photos": "照片", "web_upload_button_any_file": "文件", "web_upload_target_kicker": "手机",
    "web_upload_target_status": "完成。", "web_upload_how_kicker": "是", "web_upload_how_title": "权限",
    "web_upload_how_body": "需要同意。", "web_action_download": "下载", "web_action_view": "查看",
    "web_photo_view": "查看", "web_btn_download_all": "下载全部", "web_btn_download_selected": "下载",
    "web_btn_download_original": "原文件", "web_btn_fullscreen": "全屏", "web_error_streaming_codec": "无法播放。请下载。",
    "web_error_downloads_disabled": "已关闭。", "web_error_video_decode": "错误。请下载。",
    "web_error_video_start": "错误。请下载。", "web_error_video_start_no_dl": "修复中...",
    "web_error_load_failed": "错误。", "web_btn_select_files": "选择", "web_status_selection_on": "开启",
    "web_btn_select_all": "全部", "web_btn_clear_selection": "取消", "web_player_slow_start_hint": "稍等...",
    "web_selection_count": "%1$d", "web_library_desc_download": "观看或保存。", "web_library_desc_browse": "都在这里。",
    "web_btn_load_more": "更多", "web_btn_show_all": "全部", "web_btn_showing_all": "获取中...",
    "web_show_all_confirm": "全部 %1$d？", "web_library_showing_count": "%1$d / %2$d",
    "web_search_placeholder": "名称...", "web_library_empty": "空。", "web_upload_selection_empty": "无。",
    "web_upload_selection_single": "%1$s", "web_upload_selection_multiple": "%1$d", "web_upload_button_send": "发送",
    "common_quick_filters": "筛选", "common_edit_nickname": "名称", "home_quick_filters_desc": "天。",
    "home_date_range_body": "天。", "web_upload_requesting": "请求中...", "web_upload_waiting": "等待中...",
    "web_upload_denied": "已拒绝。", "web_upload_failed_status": "错误 (%1$d)",
    "web_upload_network_error": "网络。", "web_upload_cancelled": "已取消。", "web_upload_success_title": "上传成功",
    "web_upload_success_detail_single": "完成。", "web_upload_success_detail_multiple": "完成。",
    "web_upload_failed_title": "失败", "web_upload_failed_detail": "错误。", "web_player_error_open": "失败",
    "web_player_opening": "打开中...", "web_player_ready": "准备就绪", "web_player_analyzing": "检查中...",
    "web_player_finalizing": "完成中...", "web_player_stalled": "暂停", "web_player_starting": "开始...",
    "web_player_wait_desc": "稍等...", "web_player_ready_desc": "播放。", "web_player_analyzing_desc": "寻找中...",
    "web_player_finalizing_desc": "快好了...", "web_player_stalled_desc": "卡顿。",
    "web_player_needs_prepare": "需要网页优化", "web_player_needs_prepare_desc": "在手机上。",
    "web_player_starting_desc": "启动中...", "web_player_try_again": "重试", "web_player_status_opening": "打开",
    "web_player_status_ready": "确定", "web_player_status_analyzing": "检查", "web_player_status_finalizing": "结束",
    "web_player_status_stalled": "卡住", "web_player_status_playing": "播放中", "web_player_progress_preparing": "等待",
    "web_player_progress_converting": "写入中", "web_player_status_failed": "失败", "web_player_status_stopped": "停止",
    "web_prepare_video": "网页优化", "web_progress_percent": "%1$d%%", "web_media_quick_title": "媒体",
    "web_media_quick_subtitle": "放入。", "web_media_open_category": "%1$s", "web_media_empty": "空。",
    "web_send_files_to_device": "发送", "web_upload_in_progress": "进行中...", "web_upload_complete": "完成",
    "web_upload_failed": "失败", "web_cancel": "取消", "web_upload_preparing_transfer": "准备中...",
    "web_upload_connecting": "连接中...", "web_btn_back": "返回", "web_status_subtitles_available": "字幕",
    "web_now_playing": "播放中", "common_resume": "继续", "web_status_init_progress": "0%",
    "common_play": "播放", "common_pause": "暂停", "common_unit_b": "B", "common_unit_kb": "KB",
    "common_unit_mb": "MB", "common_unit_gb": "GB", "common_unit_tb": "TB", "common_unit_s": "秒",
    "common_unit_m": "分", "common_unit_h": "时", "common_byte_format_decimal": "%1$.1f %2$s",
    "common_byte_format_integer": "%1$d %2$s", "common_duration_format_m_s": "%1$d分 %2$d秒",
    "common_duration_format_h_m": "%1$d时 %2$d分", "common_duration_format_s": "%1$d秒",
    "common_duration_timestamp_m_s": "%1$d:%2$02d", "common_duration_timestamp_h_m_s": "%1$d:%2$02d:%3$02d",
    "service_file_index_pattern": "%1$s (%2$d/%3$d)", "service_upload_progress_subtext_pattern": "%1$s / %2$s",
    "help_section_media_server": "服务器", "help_line_media_server_1": "中心。",
    "help_line_media_server_2": "整洁。", "help_section_folders_nav": "文件夹",
    "help_line_folders_1": "原样。", "help_line_folders_2": "干净。", "help_section_dlna_tv": "电视",
    "help_line_dlna_1": "智能。", "help_line_dlna_2": "DirectServe。", "help_line_dlna_3": "网络。",
    "help_line_dlna_4": "VLC 可以。", "help_section_search_sticky": "搜索", "help_line_search_1": "快。",
    "help_line_search_2": "上方。", "settings_dlna": "DLNA 电视", "settings_dlna_desc": "电视/VLC。",
    "dlna_server_name": "DirectServe", "dlna_server_name_template": "DirectServe (%1$s)",
    "web_action_download_zip": "ZIP", "web_btn_download_all_zip": "全部打包",
    "web_btn_download_selected_zip": "打包下载", "web_error_no_items_selected": "空。",
    "web_download_started_hint": "打包中...", "playback_mode_direct": "直接播放",
    "playback_mode_repackaging": "封装", "playback_mode_transcoding": "转码",
    "playback_mode_analyzing": "分析", "compatibility_message_cached_ready": "已准备好。",
    "compatibility_message_stopped": "已停止。", "compatibility_message_validation_failed": "错误: %1$s",
    "compatibility_message_adjusted": "完成。", "compatibility_message_optimizing": "准备中...",
    "compatibility_message_almost_ready": "马上...", "compatibility_message_ready": "完成。",
    "compatibility_message_analyzing": "查看中...", "compatibility_message_finalizing_optimized": "最后...",
    "compatibility_message_finalizing_compatible": "最后...", "compatibility_message_optimizing_web": "网页...",
    "compatibility_message_repackaging_web": "封装中...", "compatibility_message_converting_web": "转换中...",
}

# CHINESE TRADITIONAL (zh-rTW)
zh_tw_data = {
    "common_back": "返回", "common_cancel": "取消", "common_save": "儲存", "common_delete": "刪除",
    "common_open": "打開", "common_refresh": "重新整理", "common_continue": "繼續", "common_accept": "接受",
    "common_decline": "拒絕", "common_dismiss": "關閉", "common_remove": "移除", "common_search": "搜尋",
    "common_separator_pipe": " | ", "common_separator_dot": " • ", "onboarding_skip": "跳過",
    "onboarding_title": "DirectServe",
    "onboarding_subtitle": "將您的手機變成電視和電腦的本地控制中心。",
    "onboarding_page_1_title": "在任何螢幕上觀看",
    "onboarding_page_1_description": "無需雲端，在大螢幕上播放影片和相片。",
    "onboarding_page_2_title": "適用於所有設備",
    "onboarding_page_2_description": "支援電視、電腦、手機，只要有瀏覽器即可。",
    "onboarding_page_3_title": "從瀏覽器存取",
    "onboarding_page_3_description": "無需安裝應用程式，使用連結或掃碼即可。",
    "onboarding_page_4_title": "雙向分享",
    "onboarding_page_4_description": "輕鬆發送和接收檔案。",
    "onboarding_page_5_title": "無需網際網路",
    "onboarding_page_5_description": "透過 Wi-Fi 或熱點運行。",
    "onboarding_page_6_title": "隱私保護",
    "onboarding_page_6_description": "檔案始終留在您的手機中。",
    "onboarding_page_counter": "%1$d / %2$d", "onboarding_next": "下一步", "onboarding_get_started": "開始",
    "settings_title": "設定", "settings_subtitle": "自訂 DirectServe。",
    "settings_group_general": "一般", "settings_group_notifications": "通知", "settings_group_privacy": "隱私",
    "settings_group_browser": "瀏覽器", "settings_group_advanced": "進階", "settings_group_network": "網路",
    "settings_group_help": "幫助", "settings_group_debug": "偵錯", "settings_language": "語言",
    "settings_theme": "主題", "settings_theme_subtitle": "更改外觀", "settings_theme_system": "系統",
    "settings_theme_dark": "深色", "settings_theme_light": "淺色", "settings_keep_screen_awake": "保持螢幕常亮",
    "settings_keep_screen_awake_desc": "分享時防止螢幕關閉。",
    "settings_vibrate_on_connect": "連線時震動", "settings_vibrate_on_connect_desc": "有人加入時震動提示。",
    "settings_show_speed": "顯示速度", "settings_show_speed_desc": "即時傳輸速度。",
    "settings_show_recent_shares": "顯示歷史記錄", "settings_show_recent_shares_desc": "本地儲存分享記錄。",
    "settings_auto_stop": "自動停止", "settings_auto_stop_never": "從不", "settings_auto_stop_15m": "15分鐘",
    "settings_auto_stop_30m": "30分鐘", "settings_auto_stop_1h": "1小時", "settings_connection_alerts": "連線提醒",
    "settings_connection_alerts_desc": "設備連線時提醒。",
    "settings_download_alerts": "下載提醒", "settings_download_alerts_desc": "有人下載檔案時提醒。",
    "settings_upload_requests": "上傳請求", "settings_upload_requests_desc": "接收檔案前詢問。",
    "settings_quick_text_enabled": "快捷文本", "settings_quick_text_enabled_desc": "分享文字訊息。",
    "settings_quick_text_alerts": "訊息提醒", "settings_quick_text_alerts_desc": "收到訊息時提醒。",
    "settings_use_pin": "使用 PIN 碼", "settings_use_pin_desc": "需要密碼才能存取。",
    "settings_new_pin_each_time": "每次使用新 PIN", "settings_new_pin_each_time_desc": "增強安全性。",
    "settings_pin_label": "PIN", "settings_pin_placeholder": "4-6 位數字", "settings_approve_file_uploads": "批准檔案上傳",
    "settings_approve_file_uploads_desc": "上傳前需要同意。",
    "settings_approve_per_device": "按設備批准", "settings_approve_per_device_desc": "每台設備只需批准一次。",
    "settings_received_files_location": "接收資料夾", "settings_received_files_location_value": "下載",
    "settings_show_thumbnails": "顯示縮圖", "settings_show_thumbnails_desc": "媒體預覽。",
    "settings_large_tv_layout": "電視佈局", "settings_large_tv_layout_desc": "更大的按鈕。",
    "settings_highlight_downloads": "突出顯示下載", "settings_highlight_downloads_desc": "使按鈕更明顯。",
    "settings_sign_out_on_stop": "停止時登出", "settings_sign_out_on_stop_desc": "斷開存取。",
    "settings_clear_temporary_files": "清除暫存檔案", "settings_clear_temporary_files_desc": "刪除優化後的影片。",
    "settings_prevent_downloads": "阻止下載", "settings_prevent_downloads_desc": "僅允許觀看。",
    "settings_auto_optimize_library": "後台優化", "settings_auto_optimize_library_desc": "會消耗電池。",
    "settings_sharing_port": "連接埠", "settings_sharing_port_placeholder": "43183",
    "settings_sharing_port_help": "不確定請勿修改。",
    "settings_wifi_settings": "Wi-Fi 設定", "settings_wifi_settings_desc": "需要處於同一網路。",
    "settings_hotspot_settings": "熱點設定", "settings_hotspot_settings_desc": "建立本地網路。",
    "settings_view_onboarding": "查看教學", "settings_view_onboarding_desc": "重新顯示引導。",
    "settings_privacy_policy": "隱私權政策", "settings_privacy_policy_desc": "本地隱私。",
    "settings_privacy_promise": "承諾", "settings_privacy_promise_desc": "檔案永遠不會上傳到雲端。",
    "settings_how_it_works": "工作原理", "settings_how_it_works_desc": "幫助。",
    "settings_app_version": "應用程式版本", "settings_recent_shares_count": "收藏夾: %1$d",
    "settings_share_debug_log": "發送日誌", "settings_share_debug_log_desc": "報告問題。",
    "settings_clear_debug_log": "清除日誌",
    "help_title": "幫助", "help_about_title": "關於 DirectServe",
    "help_about_1": "在瀏覽器中打開檔案。",
    "help_about_2": "無需安裝其他應用程式。",
    "help_about_3": "無需網際網路或雲端。",
    "help_section_what_you_can_do": "您可以做什麼", "help_section_video_playback": "影片播放",
    "help_section_browser_preparation": "網頁優化", "help_section_receiving_files": "接收檔案",
    "help_section_drop_zone": "發送檔案", "help_section_multiple_devices": "多台設備",
    "help_section_privacy_controls": "隱私", "help_section_good_to_know": "須知",
    "help_section_quick_flow": "快速開始", "help_line_share_files": "分享影片和相片。",
    "help_line_open_session": "在瀏覽器中打開。",
    "help_line_same_network": "必須在同一個 Wi-Fi 下。",
    "help_line_multiple_browse": "大家可以同時查看。",
    "help_line_video_direct": "影片直接播放。",
    "help_line_video_temporary": "有時需要轉換格式。",
    "help_line_video_original": "原始檔案保持不變。",
    "help_line_prep_optional": "優化是可選的。",
    "help_line_prep_control": "隨時可以停止。",
    "help_line_prep_batch": "手機可能會發熱。",
    "help_line_receive_upload": "其他人可以向您發送檔案。",
    "help_line_receive_approval": "您必須先批准。",
    "help_line_receive_history": "儲存在下載資料夾中。",
    "help_line_drop_zone": "拖曳檔案。",
    "help_line_drop_zone_pick": "或手動選擇。", "help_line_drop_zone_local": "100% 本地。",
    "help_line_multi_connect": "支援多設備同時連線。",
    "help_line_multi_live": "設備名稱會顯示在螢幕上。",
    "help_line_multi_controls": "必要時可以阻止設備。",
    "help_line_privacy_local": "不需要帳號。",
    "help_line_privacy_session": "只分享您選擇的內容。",
    "help_line_privacy_controls": "完全在您的控制之下。",
    "help_line_wifi_hotspot": "Wi-Fi 或熱點均可。",
    "help_line_public_wifi": "公共網路可能會阻止連線。",
    "help_line_downloads_disabled": "可以關閉下載功能。",
    "help_line_flow_1": "1. 添加檔案。", "help_line_flow_2": "2. 開始會話。",
    "help_line_flow_3": "3. 掃描二維碼。", "help_line_flow_4": "4. 觀看。",
    "home_brand_title": "DirectServe", "home_brand_subtitle": "私密分享",
    "home_chip_local_session": "本地會話", "home_chip_sharing": "正在分享", "home_chip_ready": "準備就緒",
    "home_chip_setup_needed": "需要網路", "home_live_banner": "直播會話",
    "home_title_live": "分享已開啟", "home_title_start": "目前分享",
    "home_body_live": "其他設備可以連線。", "home_body_start": "添加要分享的檔案。",
    "home_body_start_secondary": "使用您的媒體庫。",
    "home_button_start_session": "開始", "home_button_open_session": "打開",
    "home_button_starting": "正在啟動...", "home_button_add_media": "添加", "home_button_add_more": "繼續添加",
    "home_summary_current_share": "總計", "home_summary_media": "媒體", "home_summary_files": "檔案",
    "home_content_filter_title": "正在分享的內容", "home_content_filter_subtitle": "在瀏覽器中可見",
    "home_content_filter_videos": "影片", "home_content_filter_music": "音樂", "home_content_filter_photos": "相片",
    "home_content_filter_files": "檔案", "home_no_network": "沒有 Wi-Fi",
    "network_setup_title": "需要網路", "network_setup_body": "必須連接到同一個網路。",
    "network_setup_trouble_title": "遇到問題？",
    "network_setup_trouble_body": "使用您自己的熱點。",
    "network_setup_open_wifi": "Wi-Fi", "network_setup_switch_hotspot": "熱點",
    "network_setup_retry": "重試", "network_setup_footer": "速度更快，更穩定。",
    "session_title": "直播會話", "session_stop_sharing": "停止", "session_live_now": "直播",
    "session_live_now_subtitle": "您在網路上可見。", "session_share_live": "會話活躍",
    "session_share_preparing": "準備中...", "session_share_live_body": "掃描二維碼加入。",
    "session_qr_title": "掃描", "session_qr_body": "適用於任何設備。",
    "session_qr_preparing": "正在生成", "session_browser_prep_title": "網頁優化",
    "session_browser_prep_active": "%1$d%% • 已完成 %2$d / %3$d", "session_browser_prep_queued": "排隊中 %1$d",
    "session_browser_prep_ready": "%1$d 已完成", "session_browser_prep_message_active": "處理中...",
    "session_browser_prep_message_queued": "等待中", "session_browser_prep_message_ready": "準備就緒",
    "session_browser_prep_message_manual": "需要操作",
    "session_browser_prep_manual_note": "在瀏覽器中可能無法正常播放。",
    "session_prepare_browser_files": "準備", "session_stop_browser_files": "停止",
    "session_library_refresh_title": "重新整理",
    "session_library_refresh_pending": "%1$d 個檔案等待添加。",
    "session_library_refresh_up_to_date": "已是最新。", "session_refresh_library": "立即重新整理",
    "message_live_library_refreshed_updates": "已添加 %1$d 個。",
    "message_live_library_refreshed_current": "已經是最新狀態。",
    "message_browser_playback_queued_all": "已加入佇列。",
    "message_browser_playback_already_ready": "已經準備就緒。", "message_browser_playback_stopped": "已停止。",
    "library_importing_title": "導入中", "library_importing_body": "請稍候...",
    "session_waiting_local_link": "網路...", "session_qr_content_desc": "二維碼",
    "session_share_link": "連結", "session_share_link_body": "在同一個網路下打開。", "session_network": "網路",
    "session_access_pin": "存取 PIN", "session_pin_off": "關閉", "session_new_pin": "新建",
    "session_turn_pin_on": "開啟 PIN", "session_turn_pin_off": "關閉 PIN", "session_nearby_name": "名稱",
    "session_what_happens_now": "狀態", "session_waiting_ready": "等待中...",
    "session_waiting_first_device": "等待設備加入...", "session_devices_connected_now": "已連線 %1$d 台。",
    "session_friendly_local_name": "本地名稱", "session_copy_link": "複製", "session_share": "分享",
    "session_metric_devices": "設備", "session_metric_sent": "已發送", "session_metric_speed": "速度",
    "session_metric_elapsed": "耗時", "session_metric_remaining": "剩餘", "session_connected_waiting": "等待中...",
    "session_connected_title": "已連線", "session_connected_waiting_body": "將顯示在這裡。",
    "session_connected_count": "%1$d 台活躍。", "session_disconnect_all": "斷開所有連線",
    "session_no_devices": "暫無設備。", "session_block_device": "阻止",
    "session_block": "阻止", "session_blocked_title": "已阻止", "session_unblock_device": "解除阻止",
    "session_unblock": "解除", "session_state_sharing_now": "活躍", "session_state_preparing": "準備中",
    "session_state_network_needed": "需要網路", "session_network_hotspot": "熱點", "session_network_wifi": "Wi-Fi",
    "session_network_local": "本地", "session_network_offline": "離線", "history_title": "歷史記錄",
    "history_tab_all": "全部", "history_tab_received": "已接收", "history_empty_all": "空。",
    "history_empty_received": "空。", "history_sent": "發送", "history_received": "接收",
    "history_open": "打開", "history_delete": "刪除", "history_delete_desc": "從記錄中清除",
    "history_date_time_format": "%1$s %2$s", "splash_title": "DirectServe", "splash_subtitle": "私密本地分享",
    "privacy_policy_title": "隱私", "privacy_policy_intro": "您的檔案安全地留在手機中。",
    "privacy_policy_line_1": "無需註冊。", "privacy_policy_line_2": "沒有雲端。",
    "privacy_policy_line_3": "僅限本地網路。", "privacy_policy_line_4": "您掌控一切。",
    "main_service_background_protection_failed": "後台啟動失敗。",
    "main_notification_permission_warning": "需要通知權限。",
    "main_batch_media_access_needed": "需要媒體權限。", "main_debug_log_subject": "偵錯日誌",
    "main_debug_log_body": "已附上。", "main_debug_log_chooser": "發送方式...",
    "main_no_email_app": "沒有郵件應用程式。", "main_no_browser_app": "沒有瀏覽器。",
    "main_no_file_app": "沒有檔案應用程式。", "main_link_copied": "已複製。",
    "main_link_preparing": "請稍候...", "main_share_link_chooser": "分享...",
    "main_link_not_ready": "尚未準備好。", "main_not_sharing": "已關閉", "service_start_failed": "啟動失敗。",
    "service_auto_stop_message": "已自動停止。", "service_upload_request_title": "收到檔案",
    "service_upload_request_text": "%1$s (%3$s -> %2$s)", "service_upload_progress_title": "正在接收 %1$s",
    "service_upload_progress_text": "%1$d%% (%2$s)", "service_upload_progress_text_unknown": "來自 %1$s",
    "service_upload_success_title": "已儲存: %1$s", "service_upload_success_text": "來自 %1$s",
    "service_upload_success_subtext": "儲存在下載資料夾", "service_file_count": "%1$d 個檔案",
    "plural:service_new_devices_connected": {"one": "設備已連線", "other": "%1$d 台設備已連線"},
    "plural:service_devices_joined": {"one": "%1$s 已加入。", "other": "%1$s 已加入 (%2$d)。"},
    "service_waiting_for_devices": "等待中...", "plural:service_devices_connected": {"one": "1 台設備", "other": "%1$d 台設備"},
    "service_preparing_browser_access": "正在準備網頁版...", "service_channel_requests_name": "傳輸",
    "service_channel_requests_desc": "下載", "service_channel_connections_name": "連線",
    "service_channel_connections_desc": "設備", "service_channel_quick_text_name": "文本",
    "service_channel_quick_text_desc": "訊息", "service_quick_text_title": "來自 %1$s 的訊息",
    "library_title": "媒體庫", "library_header_title": "檔案",
    "library_header_body": "正在分享的內容。", "library_header_subtitles": "您可以添加字幕。",
    "library_info_items": "項目", "library_info_folders": "資料夾", "library_info_size": "大小",
    "library_empty_title": "空", "library_empty_body": "添加一些檔案。", "library_section_folders": "資料夾",
    "library_section_folders_body": "分享的資料夾。", "library_empty_filter_title": "無",
    "library_empty_filter_body": "更改篩選條件。", "library_section_files": "檔案", "library_single_file_name": "檔案",
    "library_selected_files_name": "已選擇", "library_save_selected_title": "儲存",
    "library_save_selected_body": "供以後使用。", "library_share_name": "名稱", "library_manage_title": "管理",
    "library_manage_body": "整理檔案。", "library_selection_title": "新的選擇",
    "library_selection_step_1": "1. 選擇。", "library_selection_step_2": "2. 完成。",
    "library_search_label": "搜尋...", "library_show_title": "顯示", "library_show_body": "篩選",
    "library_category_all": "全部", "library_category_videos": "影片", "library_category_photos": "相片",
    "library_category_music": "音樂", "library_category_files": "檔案", "library_add_title": "添加",
    "library_add_body": "從手機中。", "library_add_files": "檔案", "library_add_whole_folder": "資料夾",
    "library_add_from_suggestions": "相簿", "library_organize_title": "排序",
    "library_organize_body": "更改順序。", "library_sort_prefix": "排序方式: %1$s",
    "library_clear_all_action": "全部清除", "plural:library_items_in_view": {"one": "1", "other": "%1$d"},
    "library_clear_all_title": "清除全部？", "library_clear_all_body": "列表將被清空。",
    "library_sort_newest": "最新", "library_sort_name": "名稱", "library_sort_size": "大小",
    "library_cancel_selection": "取消", "library_create_saved_share": "完成", "library_start_saved_share_selection": "選擇",
    "library_browser_prep_title": "網頁副本", "library_browser_prep_body": "適合瀏覽器的輕量檔案。",
    "library_folder_summary": "%1$d | %2$s", "library_unavailable": "不可用", "library_direct_play": "直接播放",
    "library_subtitle": "字幕", "library_selected": "已選擇", "library_tap_to_select": "點擊",
    "library_select_this_file": "是", "library_preparing": "準備中", "library_preparing_for_browser": "排隊中",
    "library_ready": "準備就緒", "library_ready_for_browser": "網頁版就緒", "library_try_again": "重試",
    "library_try_browser_prep_again": "重試", "library_prepare": "準備", "library_prepare_for_browser": "完成",
    "library_type_video": "影片", "library_type_photo": "相片", "library_type_music": "音樂", "library_type_file": "檔案",
    "library_compat_ready_to_play": "完成 | %1$s", "library_compat_not_prepared": "未準備好", "library_compat_queued": "排隊中",
    "library_compat_preparing": "處理中...", "library_compat_ready": "完成", "library_compat_unavailable": "不支援",
    "library_compat_message": "%1$s | %2$s", "selection_add_files_title": "選擇", "selection_add_files_body": "分享什麼？",
    "selection_add_selected": "添加", "selection_pick_files_again": "更改", "selection_nothing_selected_title": "空",
    "selection_nothing_selected_body": "請選擇內容。", "selection_add_folder_title": "資料夾",
    "selection_add_folder_body": "選擇資料夾。", "selection_add_folder": "完成",
    "selection_choose_another_folder": "更改", "selection_no_folder_title": "錯誤",
    "selection_no_folder_body": "請選擇資料夾。", "selection_selected_folder": "資料夾", "selection_selected_item": "1",
    "selection_smart_picks_title": "日期", "selection_smart_picks_body": "已整理。",
    "selection_media_access_title": "權限", "selection_media_access_body": "請允許存取。",
    "selection_grant_access": "是", "selection_loading_groups_title": "搜尋中...", "selection_loading_groups_body": "設定中...",
    "selection_no_groups_title": "無", "selection_no_groups_body": "手動添加。", "selection_refresh_groups": "重新整理",
    "selection_add_group": "添加", "home_upload_request_title": "新檔案", "home_upload_request_single": "檔案",
    "home_upload_request_files": "%1$d 個檔案", "home_upload_request_body": "%1$s 發送了 %2$s：",
    "home_upload_request_total_size": "大小: %1$s", "home_history_content_desc": "歷史記錄",
    "home_settings_content_desc": "設定", "home_network_required_title": "網路",
    "home_network_required_body": "Wi-Fi 或熱點。", "message_unable_add_folder": "錯誤。",
    "message_saved_share_named": "已儲存：'%1$s'", "message_unable_save_share": "失敗。",
    "message_saved_share_ready": "準備就緒。", "home_all_files_access_title": "文件？",
    "home_all_files_access_body": "請允許。", "home_all_files_access_grant": "是",
    "home_all_files_access_media_only": "僅限媒體", "home_all_files_nudge_text": "任何檔案！",
    "message_unable_open_saved_share": "錯誤。", "message_saved_share_removed": "已刪除。",
    "message_something_went_wrong": "出現問題。", "message_pin_on": "PIN 已開啟。", "message_pin_off": "PIN 已關閉。",
    "message_debug_log_prepare_failed": "日誌錯誤。", "message_debug_log_cleared": "已清除。",
    "message_debug_log_clear_failed": "錯誤。", "message_file_no_longer_available": "找不到了。",
    "message_preparing_browser_playback": "網頁版 %1$s。", "nearby_helper_tap_session": "點擊。",
    "nearby_helper_open_on_other_device": "打開。", "share_preset_enter_name": "名稱：",
    "share_preset_add_content_first": "請添加內容。", "share_preset_select_file_first": "請選擇。",
    "share_preset_files_unavailable": "檔案遺失。", "share_preset_collection_unavailable": "空。",
    "share_preset_restore_failed": "錯誤。", "sharing_preflight_failed": "錯誤: %1$s",
    "sharing_add_content_first": "添加一些檔案。", "sharing_same_wifi_needed": "需要同一個 Wi-Fi。",
    "sharing_connect_before_start": "先連接網路。", "sharing_server_start_failed": "錯誤: %1$s",
    "sharing_blocked_by_live_screen": "關閉螢幕分享。", "sharing_stopped": "已停止。",
    "sharing_device_android": "Android", "network_helper_wifi_ready": "Wi-Fi 正常。",
    "network_helper_local_ready": "本地網路正常。", "network_helper_wifi_found": "找到 IP。",
    "network_helper_hotspot_ready": "熱點正常。", "network_helper_mobile_only": "僅使用行動數據。",
    "network_helper_local_address_ready": "IP 正常。", "network_helper_connect_both": "請連接設備。",
    "discovery_unavailable_device": "已關閉。", "discovery_nsd_unavailable": "已關閉。",
    "discovery_searching": "搜尋中...", "discovery_unavailable_now": "只能使用二維碼。",
    "discovery_start_failed": "錯誤 (%1$d)", "discovery_ready_to_open": "完成。",
    "browser_title": "DirectServe", "browser_subtitle": "檔案", "browser_file_unavailable": "消失了。",
    "browser_debug_unavailable": "已關閉。", "browser_debug_missing_payload": "空。", "browser_pin_mismatch": "PIN 碼錯誤。",
    "browser_device_blocked": "已阻止。", "browser_enter_pin": "PIN 碼：",
    "browser_optimized_unavailable": "不支援網頁。", "browser_video_part_preparing": "製作中...",
    "browser_video_part_unavailable": "空。", "browser_hls_not_needed": "不需要。",
    "browser_hls_not_ready": "未準備好。", "home_action_add_to_share_title": "添加",
    "home_action_add_to_share_subtitle": "檔案", "home_action_files": "檔案", "home_action_files_desc": "是",
    "home_action_folder": "資料夾", "home_action_folder_desc": "是", "home_action_library": "媒體庫",
    "home_action_library_desc": "查找", "home_button_share_all_media": "全部", "home_button_adding_all": "添加中...",
    "home_media_server_active": "全部開啟", "home_btn_stop_media_server": "停止", "web_folders_title": "資料夾",
    "web_folder_items": "%1$d", "web_btn_back_to_folders": "返回", "web_all_media": "媒體",
    "home_nearby_title": "附近", "home_nearby_subtitle": "設備。",
    "home_nearby_refresh_status": "重新整理", "home_network_wifi": "Wi-Fi 正常", "home_network_hotspot": "熱點正常",
    "home_network_local": "本地正常", "home_network_none": "無", "home_network_ready_desc": "準備就緒。",
    "home_network_none_desc": "需要連接。", "home_nearby_optional_title": "App 是可選的",
    "home_nearby_optional_desc": "網頁也可以。", "home_nearby_refresh": "搜尋",
    "home_nearby_open_title": "在 App 中", "home_nearby_open_desc": "如果有的話。",
    "home_nearby_action_open_session": "走吧", "home_nearby_action_open": "是", "home_nearby_device_available": "完成",
    "home_nearby_device_pin": "PIN", "web_hero_eyebrow": "DirectServe", "web_hero_title": "您的媒體",
    "web_hero_desc1": "影片，相片。", "web_hero_desc2": "檔案。", "web_hero_desc3": "私密。",
    "web_hero_stat_shared": "運行中", "web_items": "項", "web_hero_stat_ready": "完成", "web_hero_stat_access": "權限",
    "web_access_pin": "已鎖定", "web_access_instant": "公開", "web_access_pin_desc": "需要 PIN",
    "web_access_instant_desc": "完成", "web_pin_entry_kicker": "PIN", "web_pin_entry_title": "輸入 PIN 碼",
    "web_pin_entry_desc": "在螢幕上。", "web_pin_entry_placeholder": "PIN", "web_btn_videos": "影片",
    "web_btn_download_all_files": "下載全部", "web_cat_videos": "影片", "web_cat_photos": "相片",
    "web_cat_music": "音樂", "web_cat_files": "檔案", "web_recent_title": "新增", "web_recent_meta": "完成",
    "web_nav_home": "主頁", "web_nav_drop_zone": "拖曳區", "web_nav_logout": "退出", "web_nav_media": "媒體",
    "web_nav_files": "檔案", "web_nav_send": "發送", "web_strip_session": "會話", "web_strip_device": "我們",
    "web_strip_link": "連結", "web_security_pin": "PIN", "web_security_open": "關閉", "web_status_unknown": "?",
    "home_connected_devices": "已連線", "home_rename_device": "名稱", "home_rename_device_subtitle": "%1$s • %2$s",
    "home_rename_custom_name": "新名稱", "home_rename_save": "完成", "home_rename_cancel": "取消", "home_quick_filters": "篩選",
    "home_quick_filter_today": "今天", "home_quick_filter_today_desc": "24小時", "home_quick_filter_week": "本週",
    "home_quick_filter_week_desc": "7天", "home_quick_filter_month": "本月", "home_quick_filter_month_desc": "30天",
    "home_quick_filter_custom": "時間", "home_quick_filter_custom_desc": "選擇", "home_date_range_title": "天",
    "home_date_range_from": "從", "home_date_range_start": "開始", "home_date_range_to": "到",
    "home_date_range_end": "結束", "home_date_range_tip": "好。", "home_date_range_apply": "確定",
    "home_date_range_cancel": "取消", "home_recent_shares": "較早", "home_section_library": "檔案",
    "home_section_live_tools": "工具", "home_section_network_tv": "電視", "home_section_sharing": "操作",
    "home_section_live_features": "附加功能", "home_feature_library": "媒體庫", "home_feature_library_desc": "管理。",
    "home_feature_transfers": "傳輸", "home_feature_transfers_desc": "下載。", "home_feature_share_files": "分享",
    "home_feature_share_files_desc": "全部。", "home_feature_receive_files": "接收",
    "home_feature_receive_files_desc": "是。", "home_feature_play_media": "播放",
    "home_feature_play_media_desc": "網頁。", "home_feature_play_media_live": "是。", "home_feature_dlna": "DLNA",
    "home_feature_dlna_desc": "電視。", "home_feature_dlna_enabled": "開啟。", "home_feature_live_screen": "螢幕",
    "home_feature_live_screen_desc": "鏡像。", "home_feature_quick_text": "文本", "home_feature_quick_text_desc": "是。",
    "home_saved_shares": "收藏夾", "home_saved_shares_save_now": "儲存", "home_saved_shares_open": "打開",
    "home_saved_shares_delete": "刪除", "plural:home_saved_shares_items_count": {"one": "1", "other": "%1$d"},
    "library_date_group_label": "%1$s", "web_upload_title": "上傳", "web_upload_subtitle": "到手機。",
    "web_upload_prompt_title": "放入檔案", "web_upload_prompt_desktop": "拖放。",
    "web_upload_prompt_mobile": "點擊。", "web_upload_button_browse": "瀏覽",
    "web_upload_button_photos": "相片", "web_upload_button_any_file": "檔案", "web_upload_target_kicker": "手機",
    "web_upload_target_status": "完成。", "web_upload_how_kicker": "是", "web_upload_how_title": "權限",
    "web_upload_how_body": "需要同意。", "web_action_download": "下載", "web_action_view": "查看",
    "web_photo_view": "查看", "web_btn_download_all": "下載全部", "web_btn_download_selected": "下載",
    "web_btn_download_original": "原檔案", "web_btn_fullscreen": "全螢幕", "web_error_streaming_codec": "無法播放。請下載。",
    "web_error_downloads_disabled": "已關閉。", "web_error_video_decode": "錯誤。請下載。",
    "web_error_video_start": "錯誤。請下載。", "web_error_video_start_no_dl": "修復中...",
    "web_error_load_failed": "錯誤。", "web_btn_select_files": "選擇", "web_status_selection_on": "開啟",
    "web_btn_select_all": "全部", "web_btn_clear_selection": "取消", "web_player_slow_start_hint": "稍等...",
    "web_selection_count": "%1$d", "web_library_desc_download": "觀看或保存。", "web_library_desc_browse": "都在這裡。",
    "web_btn_load_more": "更多", "web_btn_show_all": "全部", "web_btn_showing_all": "獲取中...",
    "web_show_all_confirm": "全部 %1$d？", "web_library_showing_count": "%1$d / %2$d",
    "web_search_placeholder": "名稱...", "web_library_empty": "空。", "web_upload_selection_empty": "無。",
    "web_upload_selection_single": "%1$s", "web_upload_selection_multiple": "%1$d", "web_upload_button_send": "發送",
    "common_quick_filters": "篩選", "common_edit_nickname": "名稱", "home_quick_filters_desc": "天。",
    "home_date_range_body": "天。", "web_upload_requesting": "請求中...", "web_upload_waiting": "等待中...",
    "web_upload_denied": "已拒絕。", "web_upload_failed_status": "錯誤 (%1$d)",
    "web_upload_network_error": "網路。", "web_upload_cancelled": "已取消。", "web_upload_success_title": "上傳成功",
    "web_upload_success_detail_single": "完成。", "web_upload_success_detail_multiple": "完成。",
    "web_upload_failed_title": "失敗", "web_upload_failed_detail": "錯誤。", "web_player_error_open": "失敗",
    "web_player_opening": "打開中...", "web_player_ready": "準備就緒", "web_player_analyzing": "檢查中...",
    "web_player_finalizing": "完成中...", "web_player_stalled": "暫停", "web_player_starting": "開始...",
    "web_player_wait_desc": "稍等...", "web_player_ready_desc": "播放。", "web_player_analyzing_desc": "尋找中...",
    "web_player_finalizing_desc": "快好了...", "web_player_stalled_desc": "卡頓。",
    "web_player_needs_prepare": "需要網頁優化", "web_player_needs_prepare_desc": "在手機上。",
    "web_player_starting_desc": "啟動中...", "web_player_try_again": "重試", "web_player_status_opening": "打開",
    "web_player_status_ready": "確定", "web_player_status_analyzing": "檢查", "web_player_status_finalizing": "結束",
    "web_player_status_stalled": "卡住", "web_player_status_playing": "播放中", "web_player_progress_preparing": "等待",
    "web_player_progress_converting": "寫入中", "web_player_status_failed": "失敗", "web_player_status_stopped": "停止",
    "web_prepare_video": "網頁優化", "web_progress_percent": "%1$d%%", "web_media_quick_title": "媒體",
    "web_media_quick_subtitle": "放入。", "web_media_open_category": "%1$s", "web_media_empty": "空。",
    "web_send_files_to_device": "發送", "web_upload_in_progress": "進行中...", "web_upload_complete": "完成",
    "web_upload_failed": "失敗", "web_cancel": "取消", "web_upload_preparing_transfer": "準備中...",
    "web_upload_connecting": "連接中...", "web_btn_back": "返回", "web_status_subtitles_available": "字幕",
    "web_now_playing": "播放中", "common_resume": "繼續", "web_status_init_progress": "0%",
    "common_play": "播放", "common_pause": "暫停", "common_unit_b": "B", "common_unit_kb": "KB",
    "common_unit_mb": "MB", "common_unit_gb": "GB", "common_unit_tb": "TB", "common_unit_s": "秒",
    "common_unit_m": "分", "common_unit_h": "時", "common_byte_format_decimal": "%1$.1f %2$s",
    "common_byte_format_integer": "%1$d %2$s", "common_duration_format_m_s": "%1$d分 %2$d秒",
    "common_duration_format_h_m": "%1$d時 %2$d分", "common_duration_format_s": "%1$d秒",
    "common_duration_timestamp_m_s": "%1$d:%2$02d", "common_duration_timestamp_h_m_s": "%1$d:%2$02d:%3$02d",
    "service_file_index_pattern": "%1$s (%2$d/%3$d)", "service_upload_progress_subtext_pattern": "%1$s / %2$s",
    "help_section_media_server": "伺服器", "help_line_media_server_1": "中心。",
    "help_line_media_server_2": "整潔。", "help_section_folders_nav": "資料夾",
    "help_line_folders_1": "原樣。", "help_line_folders_2": "乾淨。", "help_section_dlna_tv": "電視",
    "help_line_dlna_1": "智能。", "help_line_dlna_2": "DirectServe。", "help_line_dlna_3": "網路。",
    "help_line_dlna_4": "VLC 可以。", "help_section_search_sticky": "搜尋", "help_line_search_1": "快。",
    "help_line_search_2": "上方。", "settings_dlna": "DLNA 電視", "settings_dlna_desc": "電視/VLC。",
    "dlna_server_name": "DirectServe", "dlna_server_name_template": "DirectServe (%1$s)",
    "web_action_download_zip": "ZIP", "web_btn_download_all_zip": "全部打包",
    "web_btn_download_selected_zip": "打包下載", "web_error_no_items_selected": "空。",
    "web_download_started_hint": "打包中...", "playback_mode_direct": "直接播放",
    "playback_mode_repackaging": "封裝", "playback_mode_transcoding": "轉碼",
    "playback_mode_analyzing": "分析", "compatibility_message_cached_ready": "已準備好。",
    "compatibility_message_stopped": "已停止。", "compatibility_message_validation_failed": "錯誤: %1$s",
    "compatibility_message_adjusted": "完成。", "compatibility_message_optimizing": "準備中...",
    "compatibility_message_almost_ready": "馬上...", "compatibility_message_ready": "完成。",
    "compatibility_message_analyzing": "查看中...", "compatibility_message_finalizing_optimized": "最後...",
    "compatibility_message_finalizing_compatible": "最後...", "compatibility_message_optimizing_web": "網頁...",
    "compatibility_message_repackaging_web": "封裝中...", "compatibility_message_converting_web": "轉換中...",
}

# Apply batch
res_dir = "core/resources/src/main/res"
rebuild_locale(res_dir, "vi", vi_data)
rebuild_locale(res_dir, "zh-rCN", zh_cn_data)
rebuild_locale(res_dir, "zh-rTW", zh_tw_data)
